### ISSUE TITLE
PublisherProvidedID not implemented?

### ISSUE THREAD

**Issue by pboisso** [xamarin/GoogleApisForiOSComponents#104]
Hi,

Trying to find out where and how we can set PublisherProvidedID and it seems like it is not implemented.  For example:

request = Request.GetDefaultRequest();
request.PublisherProvidedID = "hash_here";   //no definition for PublisherProviderID or setPublisherProviderID or anything that looks like it.

Am I missing something or is this just not implemented?

Thanks.

Patrice

**Comment by SotoiGhost** [comment]
@pboisso yes, this is implemented. The `PublisherProvidedID` property is located in the [Request][1] class but of the `Google.MobileAds.DoubleClick` namespace.

[1]: https://github.com/xamarin/GoogleApisForiOSComponents/blob/master/Google.MobileAds/source/Google.MobileAds/ApiDefinition.cs#L2512-L2514
