### ISSUE TITLE
Firebase.AdMob component not allowing project to build

### ISSUE THREAD

**Issue by odyzzey** [xamarin/GoogleApisForiOSComponents#105]
Hi, 

It looks like in the latest Firebase.AdMob version (building with latest Xcode for 64-bit iOS 11 device) does not allow projects to build. The error given is

"
Error MT5216: Native linking failed for '/Users/User/Projects/SolutionFolder/ProjectFolder/obj/iPhone/Debug/device-builds/iphone6.1-11.0/mtouch-cache/arm64/libGoogle.MobileAds.dll.dylib'. Please file a bug report at http://bugzilla.xamarin.com (MT5216)
"

After removing the component and removing references to it in my code the app functioned. Adding the component to a blank template application will cause it to no longer be able to build.

Is there anything that can be done to remedy this?

Thanks.

**Comment by SotoiGhost** [comment]
@odyzzey just to be sure, did you just reference Google.MobileAds in your code? Firebase.AdMob installed other dependencies but, does the error happen when you just write code from Google.MobileAds library?

**Comment by odyzzey** [comment]
The error happens if the component is installed on the project. The result is the same if it is installed on a project that does not reference it or use the library. For what it's worth Google.MobileAds is the one being referenced. This is on Visual Studio For Mac.

**Comment by SotoiGhost** [comment]
Seems to be a bug with Google.MobileAds and Incremental builds.

We have two workarounds here:

1. Open the project settings of your app and go to **Build**/**iOS Build** and uncheck the **Enable incremental builds** option
2. Implement Firebase with MobileAds

Hope this helps you.

I'm closing this issue now, if you still have problems with this, feel free to re-open this issue.

Best.
