### ISSUE TITLE
C++ Linking Issue

### ISSUE THREAD

**Issue by Plofstoffel** [xamarin/GoogleApisForiOSComponents#110]
Hi,

I have recently updated all my Firbase packages and now get the following error message on build.

Native linking failed, undefined Objective-C class: FIRActionCodeSettings. The symbol '_OBJC_CLASS_$_FIRActionCodeSettings' could not be found in any of the libraries or frameworks linked with your application.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	

If i compile the same source on our Mac it works, its only on my windows dev machine.

Please help!!!!

**Comment by SotoiGhost** [comment]
@Plofstoffel which component did you add to your app?

**Comment by SotoiGhost** [comment]
We have not received the requested information. If you are still experiencing this issue please provide all the requested information and re-open the issue report. Thanks!
