### ISSUE TITLE
Native linking failed, duplicate symbol '_main'.

### ISSUE THREAD

**Issue by mikewaz** [xamarin/GoogleApisForiOSComponents#111]
If I add the following string
`DatabaseReference rootNode = Database.DefaultInstance.GetRootReference ();`
in FinishedLaunching method I got 6 compile error

- linker command failed with exit code 1
- Native linking failed, duplicate symbol '_main'
- Duplicate symbol in: /Users/mary_zhiveynova/Projects/FBTest7/iOS/MTOUCH: Error MT5213: Duplicate symbol in: /Users/mary_zhiveynova/Projects/FBTest7/iOS/obj/iPhoneSimulator/Debug/device-builds/iphone10.4-11.1/mtouch-cache/leveldb-library(leveldb_main.o) (Location related to previous error)
- Duplicate symbol in: /Users/mary_zhiveynova/Projects/FBTest7/iOS/MTOUCH: Error MT5213: Duplicate symbol in: /Users/mary_zhiveynova/Projects/FBTest7/iOS/obj/iPhoneSimulator/Debug/device-builds/iphone10.4-11.1/mtouch-cache/x86_64/main.o (Location related to previous error)
- 1duplicate symbol for architecture x86_64
- Native linking failed. Please review the build log. (MT5202)

My code
```
[Register("AppDelegate")]
public partial class AppDelegate : UIApplicationDelegate
{
  public override bool FinishedLaunching(UIApplication app, NSDictionary options)
  {
    Firebase.Core.App.Configure();
    Firebase.Database.Database.DefaultInstance.PersistenceEnabled = true;
    Firebase.Database.DatabaseReference rootNode = 
    Firebase.Database.Database.DefaultInstance.GetRootReference();

    return true;
  }
}
```

What am I doing wrong?

**Comment by SotoiGhost** [comment]
@mikewaz Yes, we discover this issue like two weeks ago, this only happens in simulator AFAIK. Seems that the dependency LevelDB left their Main symbol. I'll file a bug on Firebase. The workaround for this is to change the behavior of the **Registrar** on Simulator:

1. Open your project settings
2. Go to **Build** tab
3. Select **iOS Build** option
4. Type `--registrar:static` in **Additional mtouch arguments** textbox
5. Click on **Ok**

Don't forget to add this in **Release** and **Debug** configuration of **iPhoneSimulator** platform.

**Comment by mikewaz** [comment]
@SotoiGhost Thank you!

**Comment by Shashidhar014** [comment]
@SotoiGhost Thanks, it worked for me also

**Comment by VinoliyaPrincy** [comment]
Am facing this issue still.

**Comment by EdwinOtten** [comment]
It appears that Xamarin.Firebase.iOS packages won't compile for `ARMv7s`, but does for `ARMv7` and `ARM64`. Why? I didn't figure that out yet..

@VinoliyaPrincy Try this:
1. In Visual Studio, open the project settings of your iOS project, go to `Build > iOS Build`.
2. Select Configuration `Release` and Platform `iPhone` *
3. Next to `Supported architectures` select `ARMv7 + ARM64` instead of `ARMv7 + ARMv7s + ARM64`.

\* If you also have problems in Debug, check if the `ARMv7s` is in the list for the Debug configuration.

**Comment by SotoiGhost** [comment]
@EdwinOtten Google removed the **ARMv7s** support from its libraries some time ago, that's why we don't longer support that arch neither.

**Comment by INHack20** [comment]
+1

**Comment by Nixon-Joseph** [comment]
@SotoiGhost you are my favorite person!

**Comment by jawrainey** [comment]
I ran into the same issue today, including many other link issues related to this. Would it be worthwhile to update the [documentation](https://github.com/xamarin/GoogleApisForiOSComponents/blob/master/Firebase.CrashReporting/component/GettingStarted.md) to detail this potential problem and the fix as suggested above @SotoiGhost?

**Comment by joilsonc** [comment]
1-    Open your project settings
2-    Go to Build tab
3-    Select iOS Build option
4-    Type --registrar:static in Additional mtouch arguments textbox
5-    Click on Ok

it worked fine to me. THANKS A LOT ...I saved too much time...

**Comment by Sivamuralidhar** [comment]
Thanks @SotoiGhost for providing clear steps to fix the issue. i was seeing this line of code in every site "--registrar:static" but not sure where to place.

**Comment by victorarce** [comment]
@joilsonc  thanx man, saved my life.

**Comment by dennis-kruta** [comment]
In my case, Xamarin.iOS project was successfully built for real iOS device, and was constantly failing to build for iPhone Simulator with "MT5209: Error: 1 duplicate symbol for architecture x86_64 Native linking" error.
@SotoiGhost instructions did the trick and fixed the issue! 

Thanks!!!

**Comment by crivera** [comment]
I have the same issue and tried the ''--registrar:static" trick but it didn't work. Is it ok to have other mtouch arguments there? Any other suggestions?

**Comment by sathishkumar1624** [comment]
@SotoiGhost Thank you! You save me.

**Comment by dev-aritra** [comment]
@SotoiGhost Thanks buddy.

**Comment by josueeap** [comment]
@SotoiGhost Thanks!!!!, it worked for me!!
