### ISSUE TITLE
Firebase Storage WriteToFile never completes

### ISSUE THREAD

**Issue by liao1994** [xamarin/GoogleApisForiOSComponents#115]
The eventcompletionhandler would never be called, when trying to download to a local file
`
downloadTask = pdfNode.WriteToFile(PdflocalNsUrl, (url, error) =>
                {
                    if (error != null)
                    {
                        // Uh-oh, an error occurred!
                    }
                    else
                    {
                        LoadPdf(PdflocalNsUrl);
                    }
});
`

**Comment by SotoiGhost** [comment]
@liao1994 This only happens when you try to download a local file? Can you share a test case, please? This will help to speed up the process. Thanks in advance.

**Comment by SotoiGhost** [comment]
We have not received the requested information. If you are still experiencing this issue please provide all the requested information and re-open the issue report. Thanks!
