### ISSUE TITLE
Xamarin.Google.iOS.SignIn 4.1.0 does not call ISignInUIDelegate methods

### ISSUE THREAD

**Issue by softlion** [xamarin/GoogleApisForiOSComponents#119]
Xamarin.Google.iOS.SignIn version 4.1.0 does not call ISignInUIDelegate methods when calling             SignIn.SharedInstance.SignInUser();
And it also displays a popup "app want to open "Google SignIn" ...".

Version 4.0.2.2 works fine with the same code, and displays no popup.

Maybe related to https://github.com/googlesamples/google-services/issues/336

**Comment by SotoiGhost** [comment]
Version 4.1.1 was released, can you try to see if the error is fixed? Thanks in advance!

**Comment by softlion** [comment]
FIXEd
