### ISSUE TITLE
Not able to close Interstitial ads on Iphone x

### ISSUE THREAD

**Issue by bemnet4u** [xamarin/GoogleApisForiOSComponents#121]
Looks like this is an issue with the google's admob framework nd there is already a fix out: https://groups.google.com/forum/#!category-topic/google-admob-ads-sdk/LXnPtaSYXTY
Should we expect update of this component anytime soon?

**Comment by SotoiGhost** [comment]
Google Mobile Ads/Firebase AdMob v7.27 is live now. If you are still experiencing this issue please feel free to re-open the issue report. Thanks!
