### ISSUE TITLE
Google Cast - castStyle.castViews missing

### ISSUE THREAD

**Issue by ElenaVolpi** [xamarin/GoogleApisForiOSComponents#122]
Hi,
I want to customize style of google cast controllers, in the google guide there are this few row to implement it:

GCKUIStyle *castStyle = [GCKUIStyle.sharedInstance];
castStyle.castViews.mediaControl.miniController.bodyTextColor = [UIColor red];
// Assign colors, fonts and images to other properties, as needed
[castStyle applyStyle];

I tried to do the same on xamarin but:

var castStyle = UIStyle.SharedInstance;
castStyle.?????? ( castViews is missing )
castStyle.ApplyStyle();

is there a different way to do this ?
Many thanks
Elena

**Comment by ElenaVolpi** [comment]
Hi,
I tried to download binding project and I uncomment this row:
		[Export ("castViews", ArgumentSemantic.Strong)]
		UIStyleAttributesCastViews CastViews { get; }
then I integrate the dll result in my project and I can set styles.

But, why did you comment that row ?

Thanks 
Elena

**Comment by SotoiGhost** [comment]
Hi @ElenaVolpi! 

Some versions ago, Google exposed that property, but they marked `UIStyleAttributesCastViews` symbol as **non-external**. So, in that moment, there was no way to bind that class. That's the reason we decided to comment that property.

In the end, we forgot that we commented that property. Now `UIStyleAttributesCastViews` symbol is **external** and is already bound, we just forgot to uncomment that property. Thanks for pointing that out.

Greetings,
Israel Soto.

**Comment by dationguyen** [comment]
someone has revert this change

**Comment by SotoiGhost** [comment]
@dationguyen Can you open a new issue if this is missing? So we don’t forget to check this. Thanks in advance!
