### ISSUE TITLE
firebase analytics for ios not working

### ISSUE THREAD

**Issue by Shaboo** [xamarin/GoogleApisForiOSComponents#128]
I am using the latest version, it is 4.0.5, and follow the getting started, when build the following error occured:

Configuration fails. It may be caused by an invalid GOOGLE_APP_ID in GoogleService-Info.plist or set in the customized options.

**Comment by SotoiGhost** [comment]
Hi @Shaboo!

I created a new project, tested Firebase Analytics and worked ok for me. Can you [create a new](https://console.firebase.google.com/) GoogleService-Info.plist and try again, please? Double check that the Bundle ID is the same between **Info.plist** and **GoogleService-Info.plist.**

If the issue persists, can you upload a test case? That would make things easier.

Thanks in advance!

Greetings,
Israel Soto.

**Comment by Shaboo** [comment]
I have already done that and it worked with no errors,
thanks

**Comment by SotoiGhost** [comment]
Glad to read that, closing this now. If something else happens related to this, feel free to reopen this issue.
