### ISSUE TITLE
Xamarin.Google.iOS.MobileAds - Test devices not loading test ads

### ISSUE THREAD

**Issue by sbonkosky** [xamarin/GoogleApisForiOSComponents#130]
I am not seeing the gray "Test Ad" label that should be on test ads when TestDevices is set on the Request.

From Google's documentation, test ads should display this label for devices listed in TestDevices:

[Test Ads](https://developers.google.com/admob/ios/test-ads#enable_test_devices)

My code:

```
Request request = Request.GetDefaultRequest();
request.TestDevices = new string[] { Request.SimulatorId, "xxxxxxxxxxxxxxxxxxxxxxx" }; // Where x...x is my device id
RewardBasedVideoAd.SharedInstance.Delegate = this;
RewardBasedVideoAd.SharedInstance.LoadRequest(request, AdUnitUD);
```

But once I display the ad, if Im using a real reward ad setup in my account, I see the real ad and not one with the gray "Test Ad" label that should be displayed.

**Comment by SotoiGhost** [comment]
Hi @sbonkosky! 

I tested the sample, and as you say, the **Test ad** label is not shown in `RewardBasedVideoAd` ads. However, I tested other type of ads and the label appears:

|   |    |
|--|--|
| <img src="https://user-images.githubusercontent.com/5924210/37734587-40cbbbc4-2d11-11e8-9278-cc27e1a2edae.PNG" height=400> | <img src="https://user-images.githubusercontent.com/5924210/37734588-42cc5cda-2d11-11e8-8a5c-43a133f4d98c.PNG" height=400> |

So, I decided to test the Google AdMob sample and, the first few times, the ad didn't show the label and then, suddenly, it started to show the label:

|   |    |
|--|--|
| <img src="https://user-images.githubusercontent.com/5924210/38004816-2ccb93da-31fb-11e8-80e1-210d7ff583a9.PNG" height=400> | <img src="https://user-images.githubusercontent.com/5924210/38004817-2cef480c-31fb-11e8-9c10-e756d51edc47.PNG" height=400> |

I'm not really sure if this is a bug from Google or from our end, I'll keep investigating.

Best,
Israel Soto.

**Comment by SotoiGhost** [comment]
@sbonkosky I think I found the problem, the Google sample is on v7.30.0 and our end is on v7.27.0, so, I downgraded Google sample to v7.27.0 and it shows no label:

|   |
|--|
| <img src="https://user-images.githubusercontent.com/5924210/38005334-8453ce5e-31fd-11e8-8960-8e682240a78d.PNG" height=400> |

A possible fix for this is to update Mobile Ads to most recent version. I'm not really sure if the ad showed is a test ad or not.

**Comment by newky2k** [comment]
@sbonkosky  We released the latest version of this library 4 days ago, can you check to see if this still and issue for.

**Comment by newky2k** [comment]
no response for two weeks
