### ISSUE TITLE
Firebase.CrashReporting is being deprecated please add support for Firebase.Crashlytics

### ISSUE THREAD

**Issue by NPSconsultingLLC** [xamarin/GoogleApisForiOSComponents#134]
As the title states, CrashReporting has been deprecated by Google in favor of Crashlytics (inside Firebase). Details about the change can be found here. 

https://firebase.googleblog.com/2018/03/firebase-crashlytics-graduates-from-beta.html

**Comment by Shaboo** [comment]
is the new component will support vs in windows?
@SotoiGhost

**Comment by SotoiGhost** [comment]
@Shaboo Yes, this will have Windows support.
