### ISSUE TITLE
App Freezing because of CrashReporting

### ISSUE THREAD

**Issue by wellofspirit** [xamarin/GoogleApisForiOSComponents#136]
I recently added Firebase.iOS.CrashReporting to my project.

Our app freezes on background loading process with this displayed in the application output.

> ** Unknown exception behavior: 0

My Assumption:

I think there might be an unhandled exception in background thread not being managed and triggered the CrashReporting. And the crash reporting can not handle background exceptions properly.

**Comment by SotoiGhost** [comment]
Hi @wellofspirit! Can you share a test case, please? So we can investigate further on this.

**Comment by wellofspirit** [comment]
Sorry to catch up with you so late.

What is happening is:

In our code, when we are loading up, we do some database update work in the background. I know that there will be some exceptions thrown in that progress, but we handled them properly.

Before I import Crash Reporting, it works properly, nothing breaks. However, when I import Crash Reporting. Yes, simply by importing that framework, it breaks the loading process. The application is not crashed, it is just one single prompt in debug output: **unknown exception: 0.

I hope this contains enough detail.

**Comment by SotoiGhost** [comment]
@wellofspirit I will need more details to make a further investigation, like a test case where I can reproduce the error that would be great.

**Comment by newky2k** [comment]
No further information provided
