### ISSUE TITLE
Map nuget version to Google API version

### ISSUE THREAD

**Issue by jzeferino** [xamarin/GoogleApisForiOSComponents#137]
Would be great to have some kind of map between the nuget releases and the Google API releases.

For example, I'm using the version Xamarin.Google.iOS.Core 3.0.3.3 and I want to know what version of Google API it represents.

Would be nice to have git TAGS representing it. Or at least some kind of Markdown table.

**Comment by SotoiGhost** [comment]
@jzeferino We started using tags and also we added a table on ReadMe file that says what components are deprecated and in which general version is each component. Hope this helps.

Best!
Israel Soto.
