### ISSUE TITLE
MobileVision component

### ISSUE THREAD

**Issue by Shan11812** [xamarin/GoogleApisForiOSComponents#139]
Are there any plans for releasing GoogleMobileVision for Xamarin.iOS?

I've tried creating bindings, but some dependencies have missing headers (intentional, since they are not to be used directly) so couldn't....

**Comment by GalaxiaGuy** [comment]
Not intending to hijack this thread, but is there information on what criteria a package should meet to be part of this? Or somewhere for suggestions?

I too have tried binding some Google libraries but I have never gotten very far.

**Comment by newky2k** [comment]
GoogleMobileVision is now part of ML Kit so this would need to a bigger project to bring that to xamarin.
