### ISSUE TITLE
problems upgrading xamarin.google.ios.cast package from nuget with xamarin

### ISSUE THREAD

**Issue by ivocarminati** [xamarin/GoogleApisForiOSComponents#144]
Hi all,

I'm having problems after an upgrade of "xamarin.google.ios.cast" package from version 4.0.2.1 to 4.1.0 from nuget with Xamarin.

Attached you can see the problems I see in console.
Can someone help me solving these issues?
I've tried to clean the solution, delete bin and obj folders, close and reopen the ide, ... but without success.
![schermata 2018-05-04 alle 16 42 32](https://user-images.githubusercontent.com/11219337/39637117-6463ae7e-4fc2-11e8-8f17-6e8dc29f9060.png)

Thanks in advance.
Ivo

**Comment by SotoiGhost** [comment]
Hi @ivocarminati! I tried to reproduce the issue but with no success. I created a new test app, added G.CAst v4.0.2.1, upgraded it to most recent version and everything worked as expected.

Can you, please, erase the Xamarin Build Download cache and try again? The cache is located in `~/Library/Caches/XamarinBuildDownload`. What I can see with the error showed is that XBD could not download the Google.Cast framework into the cache folder.

**Comment by newky2k** [comment]
@ivocarminati are you still having this issue?  Did you try @SotoiGhost's suggestion?

**Comment by newky2k** [comment]
no response for two weeks, closing

**Comment by softlion** [comment]
I discover what happens. It is when building with Visual Studio Windows through a remote mac machine, and there is no space left on the mac. Then the download in the cache is incomplete. But Xamarin does not detect it.
