### ISSUE TITLE
Native linking failed after update to VS 15.7.0

### ISSUE THREAD

**Issue by ozzy1873** [xamarin/GoogleApisForiOSComponents#146]
After updating Visual Studio to version 15.7.0, I get the following errors when building the ad-hoc provisioning profile:

error : Native linking failed, duplicate symbol: '_OBJC_CLASS_$_GADMediatedNativeAd'.
error : Duplicate symbol in: /Users/user.name/Library/Caches/Xamarin/mtbs/builds/MyApp.iOS/f5afeabd875dec75a403ab628fb3cc1b/obj/iPhone/Ad-Hoc/mtouch-cache/arm64/registrar.o (Location related to previous error)
error : Duplicate symbol in: /Users/user.name/Library/Caches/Xamarin/mtbs/builds/MyApp.iOS/f5afeabd875dec75a403ab628fb3cc1b/obj/iPhone/Ad-Hoc/mtouch-cache/GoogleMobileAds(flat-arm64) (Location related to previous error)
error : Native linking failed, duplicate symbol: '_OBJC_METACLASS_$_GADMediatedNativeAd'.
error : Duplicate symbol in: /Users/user.name/Library/Caches/Xamarin/mtbs/builds/MyApp.iOS/f5afeabd875dec75a403ab628fb3cc1b/obj/iPhone/Ad-Hoc/mtouch-cache/arm64/registrar.o (Location related to previous error)
error : Duplicate symbol in: /Users/user.name/Library/Caches/Xamarin/mtbs/builds/MyApp.iOS/f5afeabd875dec75a403ab628fb3cc1b/obj/iPhone/Ad-Hoc/mtouch-cache/GoogleMobileAds(flat-arm64) (Location related to previous error)
error : Native linking error: 2 duplicate symbols for architecture arm64

**Comment by SKKbySSK** [comment]
Same here. I'm using VS for Mac 7.5(build 1254)
The error doesn't come up when building an app on the iOS simulator

**Comment by jackamgine** [comment]
I got same problem from yesterday. :(

Visual Studio Community 2017 for Mac (Preview)
Version 7.6 Preview (7.6 build 711)
Runtime:
    Mono 5.12.0.226 (2018-02/9824e260f56) (64-bit)
    GTK+ 2.24.23 (Raleigh theme)
    Xamarin.Mac 4.4.0.36 (master / 0c7c49a6)
    Package version: 512000226

**Comment by SotoiGhost** [comment]
Hi guys! Thanks for letting us know this. Right now, we are working on a fix for this. Hope we can release the fix today.

**Comment by chrisfoulds** [comment]
Any news on fix? totally blocking issue for us.

**Comment by chrisfoulds** [comment]
Anyway to downgrade VS as this fix is not forthcoming and we are totally stuck without it.

**Comment by runesig** [comment]
I am also struggling with this issue...please fix soon!

**Comment by nzz1234** [comment]
We need v7.27.0.3 to this fix in VS2007 for Mac

**Comment by bartdkmediahuis** [comment]
@SotoiGhost *bump
Any news on the new nuget package ? Since our builds are blocked on this issue... thanks !

**Comment by syed-pelican** [comment]
Same here.. awaiting a NuGet package update

**Comment by ThomasDhaen** [comment]
@SotoiGhost  Status for NuGet package? This is blocking for us. Cheers!

**Comment by Macjon** [comment]
Hi, we are having the same problem. I can't run my test app on my device so we can't deploy it to the store. Please fix it ASAP. Thanks in advance.

**Comment by iodiot** [comment]
I've got the same error after upgrading Xamarin/Xcode.

**Comment by aer127** [comment]
Same error here.

**Comment by chrisfoulds** [comment]
Yes when is the fix ACTUALLY coming out @Redth @SotoiGhost

**Comment by brendanzagaeski** [comment]
Cross-referencing note for the Microsoft team

The same error message has also been reported in: <https://developercommunity.visualstudio.com/content/problem/251326/error-mt5212-native-linking-failed-duplicate-symbo.html>

**Comment by SotoiGhost** [comment]
Guys, just letting you know that Firebase AdMob/Google Mobile Ads v7.27.0.3 is now live on NuGet. A big apology for all the inconveniences that this caused.

If you have any doubt, don't hesitate to ask.

Best,
Israel Soto.

**Comment by mterwoord** [comment]
Works. Great work!

2018-05-14 23:40 GMT+02:00 Israel Soto <notifications@github.com>:

**Comment by jadenrogers** [comment]
On the latest nuget package it works when building for a real device but I still have this same issue when going to the iOS simulator.

Native linking error: 1 duplicate symbol for architecture x86_64

Anyone else having this?

**Comment by SotoiGhost** [comment]
@jadenrogers What's the name of the duplicated symbol? Maybe [this answer][1] can help you.

[1]: https://github.com/xamarin/GoogleApisForiOSComponents/issues/111#issuecomment-346887313

**Comment by jadenrogers** [comment]
Thanks @SotoiGhost that worked. I tried that when this issue first came up (which didn't help) and didn't think to give that another go with the fix!

**Comment by RushikPatel** [comment]
Hello Guys,

We are getting following errors in VS 2017 at build Xamarin cross platform app existing project.

```
> Native linking failed. Please review the build log.			
> Native linking error: 1 duplicate symbol for architecture i386			
> Native linking error: warning: ignoring file /Users/user1/Library/Caches/Xamarin/mtbs/builds/ItsLiveNow.iOS/009be1dc70d68b6f7ff589eefa4397ac/obj/iPhoneSimulator/Debug/mtouch-cache/LFLiveKit.framework/LFLiveKit, missing required architecture i386 in file /Users/user1/Library/Caches/Xamarin/mtbs/builds/ItsLiveNow.iOS/009be1dc70d68b6f7ff589eefa4397ac/obj/iPhoneSimulator/Debug/mtouch-cache/LFLiveKit.framework/LFLiveKit (2 slices)			
> Duplicate symbol in: /Users/user1/Library/Caches/Xamarin/mtbs/builds/ItsLiveNow.iOS/009be1dc70d68b6f7ff589eefa4397ac/obj/iPhoneSimulator/Debug/mtouch-cache/i386/main.o (Location related to previous error)			
> Native linking failed, duplicate symbol: '_main'.			
> Duplicate symbol in: /Users/user1/Library/Caches/Xamarin/mtbs/builds/ItsLiveNow.iOS/009be1dc70d68b6f7ff589eefa4397ac/obj/iPhoneSimulator/Debug/mtouch-cache/leveldb-library(leveldb_main.o) (Location related to previous error)			
> The "ProcessGoogleServicesJson" task was not given a value for the required parameter "ResStringsPath".			
> 
> 
```
Can you please help me to get proper solution and any regarding help links ? 

Thanks & Regards

**Comment by SotoiGhost** [comment]
@RushikPatel Can you try this [workaround][1], please, and see what happens? Thanks in advance!

[1]: https://github.com/xamarin/GoogleApisForiOSComponents/issues/111#issuecomment-346887313

**Comment by RushikPatel** [comment]
Hello @Israel Soto,

Thanks for your reply.
I resolved this error by reinstall #mono.android and #Xamarin.ios dll in assemblies dependency reference.  
I m getting following error in ios project after rebuild project.

`Can't resolve the reference 'System.Void Xamarin.Forms.Internals.ResourceLoader/ResourceLoadingQuery::.ctor()', referenced from the method 'System.Void ItsLiveNow.App::InitializeComponent()' in 'Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.`

Can u give me a solution regarding this issue?

Thanks & regards.
