### ISSUE TITLE
Unable to build externals - osx

### ISSUE THREAD

**Issue by mribbons** [xamarin/GoogleApisForiOSComponents#15]
I have set up cocoapods as per the readme:

```sh
$ sudo gem install cocoapods
..
1 gem installed
$ pod env
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : 
```

Then when I try to build:
```sh
$ sh ../build.sh --target externals
Feeds used:
  /Users/user/.local/share/NuGet/Cache
  /Users/user/.nuget/packages/
  https://api.nuget.org/v3/index.json

All packages listed in /Users/user/Documents/code/GoogleApisForiOSComponents/tools/packages.config are already installed.
Analyzing build script...
Processing build script...
Installing tools...
Unable to find version '1.1.0.29' of package 'XamarinComponent'.
Error: Failed to install tool 'XamarinComponent'.
```

**Comment by mribbons** [comment]
Hi,
It seems as though nuget.exe is required in the tools folder of the sub solution we are trying to build.

In addition, I had to use nuget 2.8.6 to avoid a timezone offset issue:
https://bugzilla.xamarin.com/show_bug.cgi?id=37970

eg
```sh
cd Google.Core
rm ./tools/nuget.exe
curl -Lsfo ./tools/nuget.exe "https://dist.nuget.org/win-x86-commandline/v2.8.6/nuget.exe"
sh ../build.sh --target externals
```

```#tools``` and ```#addin``` lines from common.cake now work, but I get a new error:

```sh
Executing task: externals
pod --no-integrate install

[!] Unknown option: `--no-integrate`
Did you mean: --no-ansi?
```

**Comment by mribbons** [comment]
The ```--no-integrate``` problem gets a mention here:
https://github.com/CocoaPods/CocoaPods/issues/5240
https://bugzilla.xamarin.com/show_bug.cgi?id=40822

**Comment by SotoiGhost** [comment]
Hi @mribbons!

We are working to fix the issue about the Timezone, we have been having some problems with NuGet, Mono and timespans and timezones.

About pods, we haven't merged the update to support Pods v1.x, I'm working on that.

If you want to see how the Podfile and Makefile look like with the update, you can visit my branch where I'm working with the update:

https://github.com/SotoiGhost/GoogleApisForiOSComponents/tree/pod-update/Google.Core/externals

Greetings,
Israel Soto.

**Comment by mribbons** [comment]
Hi @SotoiGhost, I see, thanks.

When I checkout your pod-update branch I still run into more issues, is it a work in progress?

```sh
Analyzing dependencies
[!] The dependency `Google/Core (= 2.0.4)` is not used in any concrete target.
The dependency `GoogleInterchangeUtilities (= 1.2.0)` is not used in any concrete target.
```

I have tried ```sudo gem install cocoapods -v 1.0.0``` and without the -v which defaults to 1.0.1.

**Comment by SotoiGhost** [comment]
Oh, right.

I forgot to add the *target* section. Now cocoapods state that you need to add your own target, the implicit target was removed.

You can see this on their migration guide: http://blog.cocoapods.org/CocoaPods-1.0-Migration-Guide/

> You now have to define targets. Previously there was an available implicit target.

So the podfile should be like this:

```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
install! 'cocoapods', :integrate_targets => false

target 'GoogleCore' do
	pod 'Google/Core', '2.0.4'
	pod 'GoogleInterchangeUtilities', '1.2.0'
end
```

I'll update my repo with this fix.

Israel Soto.

**Comment by mribbons** [comment]
Great, I am now able to build Google.Core :smile:

**Comment by SotoiGhost** [comment]
Cool! Glad to read that.

If you have any other doubt, let us know.

I'll close this issue.

Happy Coding!
Israel Soto.
