### ISSUE TITLE
AFter updating from v1.2.1.11 to v1.2.1.12 a receive a "is not compatible" error

### ISSUE THREAD

**Issue by rubenc57** [xamarin/GoogleApisForiOSComponents#151]
Error
"Unable to resolve dependencies. 'Xamarin.Google.iOS.Core 3.1.0.1' is not compatible with 'Xamarin.Google.iOS.InstanceID 1.2.1.12 constraint: Xamarin.Google.iOS.Core (>= 3.1.0.2)'."

**Comment by SotoiGhost** [comment]
@rubenc57 We had a slip on G.Core version on Xamarin.Google.iOS.InstanceID 1.2.1.12. G.Core was not meant to be updated. Please, downgrade to version 1.2.1.11, there is no difference between these versions.

Sorry for the inconveniences.

Best,
Israel Soto.
