### ISSUE TITLE
Can't make my ads GDPR compliant

### ISSUE THREAD

**Issue by ErwinDeGroot** [xamarin/GoogleApisForiOSComponents#153]
I'm trying to only show non-personalised-ads. For the life of me I couldn't get this to work. I can't find any documentation how to get this to work in Xamarin, which is surprising since I'm sure there are others that would like to show ads to European users.

According to Google's [webpage](https://developers.google.com/admob/android/eu-consent) I need  to do the following:
    Bundle extras = new Bundle();
    extras.putString("npa", "1");
    AdRequest request = new AdRequest.Builder()
        .addNetworkExtrasBundle(AdMobAdapter.class, extras)
        .build();

I tried to get something similar going in C#:
        Request GetRequest()
        {
            var request = Request.GetDefaultRequest();
            var extras = new Extras();
            extras.SetValueForKeyPath(FromObject(1), new NSString("npa"));
            request.RegisterAdNetworkExtras(extras);
            return request;
        }

When I run this, the 'SetValueForKeyPath' methods throws a MonoTouchException exception:
    Objective-C exception thrown. Name: NSUnkownKeyException Reason: [<GADExtras 0x1c4013c60> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key npa.

I tried using FromObject("1") and also several other 'Extras' classes (like AdNetworkExtras or even NSBundle), but none work. I would really appreciate some help here.

**Comment by SotoiGhost** [comment]
Hi @ErwinDeGroot!

According to this [section][1] in docs, you need to use `Extras.AdditionalParameters` property to set the **non-personalized ads** value. Here's an example that worked for me:

```csharp
var extras = new Extras ();
extras.AdditionalParameters = NSDictionary.FromObjectAndKey (new NSString ("1"), new NSString ("npa"));
request.RegisterAdNetworkExtras (extras);
```

If you have any doubt, don't hesitate to ask. Also, feel free to reopen the issue if something else related to this appears.

[1]: https://developers.google.com/admob/ios/eu-consent#forward_consent_to_the_google_mobile_ads_sdk

**Comment by ErwinDeGroot** [comment]
Hi Isreal,

Your code works perfectly! Thanks for the help. Much appreciated.

Erwin
