### ISSUE TITLE
Is There an ETA for the Firebase Opt-In Features?

### ISSUE THREAD

**Issue by Mr-Pearce** [xamarin/GoogleApisForiOSComponents#155]
Is There an ETA for this?

**Comment by Mr-Pearce** [comment]
Still no update ?

**Comment by SotoiGhost** [comment]
Hi @Mr-Pearce! I'm not really sure what you mean with the features you ask. Is there is a particular component that is missing?

**Comment by Mr-Pearce** [comment]
I am refering to the "**Prevent auto initialization**" aka Opt-in
like shown here [https://firebase.google.com/docs/cloud-messaging/ios/client#prevent_auto_initialization]( https://firebase.google.com/docs/cloud-messaging/ios/client#prevent_auto_initialization)

And also the "**Guides for enabling opt-in for end-user personal data processing**"
here [https://firebase.google.com/support/privacy/](https://firebase.google.com/support/privacy/)

Especially for Analytics and Cloud Messaging since the "**Xamarin.Firebase.iOS.Analytics**" package is a dependency for the "**Xamarin.Firebase.iOS.CloudMessaging**" package.

By the way: The "**Xamarin.Firebase.Messaging**"(Android) package does not have any Analytics dependency.

**Comment by SotoiGhost** [comment]
@Mr-Pearce it's coming in the next update of Firebase. I don't have an exact ETA but I think it will be released this month.

**Comment by Mr-Pearce** [comment]
Thanks for the update.
Will there be an change  of the Analytics dependency for the Cloudmessaging package?

**Comment by SotoiGhost** [comment]
@Mr-Pearce Yep, in the new version, Firebase removed the Analytics dependency on Firebase Cloud Messaging

**Comment by Mr-Pearce** [comment]
Great to hear that.

**Comment by newky2k** [comment]
@Mr-Pearce  looks like a new version of firebase was released a few days ago.  hopefully this resolves everything for you.

**Comment by Mr-Pearce** [comment]
Sorry for the delay but i cant see any Updates on the Xamarin.Firebase.iOS packages

**Comment by SotoiGhost** [comment]
@Mr-Pearce iOS now should be available. If not, please, let me know.
