### ISSUE TITLE
Analytics - kGAIUserId is not mapped in GaiConstants

### ISSUE THREAD

**Issue by eclipsed4utoo** [xamarin/GoogleApisForiOSComponents#16]
Google allows set a user ID for the tracker. This value is not in the GaiConstants class.

https://developers.google.com/analytics/devguides/collection/ios/v3/user-id

**Comment by SotoiGhost** [comment]
Hi! Yes, we noticed this a couple of days ago, we are working with an update to add some missing constants. The version with the fix will be 3.14.0.7

Meanwhile, the value of the UserId constant is "&uid" (without quotes) if you are planning to use it.

**Comment by eclipsed4utoo** [comment]
I thought the constant was "kGAIUserId". "&uid" is used in Android. Figured iOS would follow the same "kGAI-" constants that are used for the other constants.

**Comment by SotoiGhost** [comment]
Well, seems that Google changed the values because all the iOS constants values follow the "&**something**" pattern.

**Comment by SotoiGhost** [comment]
Google Analytics v3.14.0.7 was released

https://components.xamarin.com/view/googleiosanalytics

Closing this issue
