### ISSUE TITLE
Xamarin.iOS.Google.MobileAds : ads display issue

### ISSUE THREAD

**Issue by nourben** [xamarin/GoogleApisForiOSComponents#161]
Hi, 

It seems that since i updated Xamarin.iOS.Google.MobileAds to version 7.27.0.3 (because of the issue caused with Visual Studio 7.5.2 on Mac), my in-house campaign illustrated ads are not displayed on Xamarin.iOS project anymore. 

The same campaign displays without problem illustrated ads (from in-house campaign) on Android devices, but on iOS I can get only "textual" ads or random AdMob ads. It look like there is specifically a problem for in-house illustrated ads, they are not displaying on banners.

Everything works fine for other ads on Android (interstitial and banner) but for iOS only interstitial ads work.
The configuration are the same beetwen my ad units, and my campaign so the only thing i could think of is that it may be from the Xamarin.iOS.Google.MobileAds component.

-----

Just to give some background, this problem occurs on a project I recently came in and they were using other ads before (with illustrated in-house campaign too) and everything was working fine.
But in a slightly short time i had to change the AdMob account  and the Visual studio update made me update Google.MobileAds plugin.
So, there is a little chance the problem is from my admob campaigns configuration but I don't really think.

I also tried the old AdUnitId we were using before and instead of showing the old image (from the illustrated in-house campaign) it display only random AdMob ads (and in the mean time, the banner displayed the old correct image on the android project).

So.. is there someone with an updated Visual Studio, Xamarin.iOS, Xamarin.iOS.Google.MobileAds who have the same issue. Or maybe someone for whom everything works well ?

Thank in advance

> VS bug [#732439](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/732439)

**Comment by AdelaPetrut** [comment]
I am having the same issue: the add on IOS (i am using AdSize = AdSizeCons.LargeBanner) are not displayed. It works correctly on Android.
The type used on my side and still with problems is: Banner.

Is there a solution for this issue?
Thank you.

**Comment by SotoiGhost** [comment]
@nourben Are you still facing this issue?

**Comment by nourben** [comment]
Hi
Yes, i'm still facing this issue.

What kind of infos can i give you to make the problem clearer ?

**Comment by ThomasDhaen** [comment]
@nourben What I usually do, is try to reproduce it in a native Android / iOS project.
If you can reproduce it there, the problem will be in the DFP SDK, rather than the Xamarin bindings.

**Comment by nourben** [comment]
@ThomasDhaen Thanks for the advice  👍 !
@SotoiGhost I created a native iOS project and it's working well. I have my real in house ad from my campaign
I also tried to create another project (Xamarin Forms) and the in the iOS part, the banner won't display what it's suppose to show.

During my tests, I used 2 kind of ads. 
The first is a textual ad. It works well and i have no problem (in native iOS project or in Xamarin Forms).
The second is an illustred ad (with an image) and it works on the native iOS project but **not in Xamarin Forms**.

So far, from what I saw, the problem only occurs on Xamarin Forms project and only with illustrated ad (with an image).

**Comment by SotoiGhost** [comment]
@nourben is this still an issue?

**Comment by nourben** [comment]
@SotoiGhost No, it's working now.
I made a lot of changes on that project, cleaned everything, updated the plugin to the last version and changed the implementation for the plugin among other things.
Maybe it was an issue on my code, a bad implementation or something like that.
Thanks guys.

**Comment by SotoiGhost** [comment]
Glad to know that! If something else happens related to this, please, open a new issue.

Best!
