### ISSUE TITLE
Performance Monitoring Sample is not Compiling

### ISSUE THREAD

**Issue by rkszone** [xamarin/GoogleApisForiOSComponents#163]
"Downloads/GoogleApisForiOSComponents-master-2/Firebase.Core/source/Firebase.Core/CSC: Error CS1566: Error reading resource 'GoogleToolboxForMac' -- 'Could not find file "Downloads/GoogleApisForiOSComponents-master-2/Firebase.Core/externals/GoogleToolboxForMac"' (CS1566) (Firebase.Core)

Also GTMSessionFetcher, leveldb-library, nanopb, Protobuf is missing,

**Comment by SotoiGhost** [comment]
Hi @rkszone! To make the sample work, you will need to run the `sh ../build.sh -t externals` command inside of the component's folder as stated in [docs][1]. For example:

```
cd ./Firebase.PerformanceMonitoring
sh ../build.sh -t externals
```

After this, you will be able to run the sample.

If you have any doubt, don't hesitate to ask.

Best!
Israel Soto.

[1]: https://github.com/xamarin/GoogleApisForiOSComponents#working-in-visual-studio

**Comment by rkszone** [comment]
Hi Team,

This Performance Monitoring is Updated to version 2.0.1.0,  But on Nuget its showing 1.1.0.1, I tried to compile and use dll of this "Performance Monitoring" project in my App project.  But is showing below error. not able to understand what i'm doing wrong, is version 2.0.1.0 available on nuget.

clang: Error: linker command failed with exit code 1 (use -v to see invocation) (App.iOS)

Error MT5211: Native linking failed, undefined Objective-C class: FIRHTTPMetric. The symbol '_OBJC_CLASS_$_FIRHTTPMetric' could not be found in any of the libraries or frameworks linked with your application. (MT5211) (App.iOS)

Error MT5211: Native linking failed, undefined Objective-C class: FIRPerformance. The symbol '_OBJC_CLASS_$_FIRPerformance' could not be found in any of the libraries or frameworks linked with your application. (MT5211) (App.iOS)

MTOUCH: Error MT5211: Native linking failed, undefined Objective-C class: FIRTrace. The symbol '_OBJC_CLASS_$_FIRTrace' could not be found in any of the libraries or frameworks linked with your application. (MT5211) (App.iOS)

Error MT5202: Native linking failed. Please review the build log. (MT5202) (App.iOS)
