### ISSUE TITLE
Performance Monitoring updated version 2.0.1.0 Error

### ISSUE THREAD

**Issue by rkszone** [xamarin/GoogleApisForiOSComponents#164]
**Why i'm doing this as current nuget pkg is not showing rendering in firebase and no api call in network section in firebase console:**
Performance Monitoring updated version 2.0.1.0  is not available on Nuget.
So i tried compiling the project from [https://github.com/xamarin/GoogleApisForiOSComponents/tree/master/Firebase.PerformanceMonitoring](url)
and use that dll in my project but its showing compiling error as i'm using available latest nuget package of Firebase.Analytics, Firebase.Core,Firebase.InstanceID in my xamarin ios app
Below are the errors : 
1. clang: Error: linker command failed with exit code 1 (use -v to see invocation) (App.iOS)

2. Error MT5211: Native linking failed, undefined Objective-C class: FIRHTTPMetric. The symbol 'OBJC_CLASS$_FIRHTTPMetric' could not be found in any of the libraries or frameworks linked with your application. (MT5211) (App.iOS)

3. Error MT5211: Native linking failed, undefined Objective-C class: FIRPerformance. The symbol 'OBJC_CLASS$_FIRPerformance' could not be found in any of the libraries or frameworks linked with your application. (MT5211) (App.iOS)

4. MTOUCH: Error MT5211: Native linking failed, undefined Objective-C class: FIRTrace. The symbol 'OBJC_CLASS$_FIRTrace' could not be found in any of the libraries or frameworks linked with your application. (MT5211) (App.iOS)

5. Error MT5202: Native linking failed. Please review the build log. (MT5202) (App.iOS)

**Comment by victor-zuev** [comment]
Hi. Have the same issue but with Dynamic Links(

**Comment by newky2k** [comment]
@rkszone @victor-zuev  an update was pushed out 10 days ago and performance monitoring is now available https://www.nuget.org/packages/Xamarin.Firebase.iOS.PerformanceMonitoring/ and https://www.nuget.org/packages/Xamarin.Firebase.iOS.DynamicLinks

**Comment by victor-zuev** [comment]
Hi. Thanks for reply and updates

вт, 21 авг. 2018 г. в 0:11, Dave Humphreys <notifications@github.com>:
