### ISSUE TITLE
Dynamic Links not passed at first launch

### ISSUE THREAD

**Issue by victor-zuev** [xamarin/GoogleApisForiOSComponents#165]
I've integrated dynamic links for iOS as described in docs (https://firebase.google.com/docs/dynamic-links/ios/receive). Everything works as expected except the first launch of the app. This is critical for us as we rely on deeplinks to properly onboard first-time app users from our website.

Steps:
0. The app is not installed.
1. Click link  from Notes app on iPhone.
2. Link opened in Safari. The preview page appeared. Then click Open on preview page and redirected to AppStore with our app page opened
3. Build and install app on device via Visual Studio for Mac.
4. Run app and receive in openUrl method link as <bundleid>//google/link/?dismiss=1&is_weak_match=1
5. Expected result - deep link passed to the app. Actual - deep link not passed.

Conditions:
1. Language set on iPhone is English.
2. Xcode version: 9.2
3. Dynamic links diagnostic output:
---- Firebase Dynamic Links diagnostic output start ----
Firebase Dynamic Links framework version **2.3.1**
System information: OS iPhone OS, OS version 9.3.5, model iPhone
Current date 2018-07-26 09:19:10 +0000
Device locale en-US (raw en_US), timezone Europe/Kiev
Specified custom URL scheme is <bundleid> and Info.plist contains such scheme in CFBundleURLTypes key.
AppID Prefix: <prefix>, Team ID: <teamId>, AppId Prefix equal to Team ID: YES
performDiagnostic completed successfully! No errors found.
---- Firebase Dynamic Links diagnostic output end ---- 

I've reported to firebase support and they asked "Could you also try to update your Firebase SDK to the latest version?" As I can see from diagnostic log the latest version from nuget is **2.3.1** and actual for now is **3.0.1**. Note that sample project in XCode with latest Firebase/DynamicLinks framework works as expected so I rely on old Xamarin binding library version in this case.

When we can get updated version of Firebase DynamicLinks for iOS on nuget?

**Comment by newky2k** [comment]
@victor-zuev I believe a new version of Firebase for iOS is pending approval and should be available sooon
