### ISSUE TITLE
Xamarin.Auth - A way to have multiple accounts in the same app using Google Firebase

### ISSUE THREAD

**Issue by mintyfusion** [xamarin/GoogleApisForiOSComponents#168]
We are using Google Firebase Phone Authentication and would like users to connect their multiple accounts in the same app (dual SIM card scenario).

Currently, we can only have one account linked using `Auth.DefaultInstance`. I was wondering if there is a way to hold more than one verified identity?

**Comment by SotoiGhost** [comment]
Hi @mintyfusion! According to [this answer][1] on StackOverflow from a Firebase engineer it seems that is not possible. I'll share you part of the answer:

> The Firebase client SDKs (for Android, iOS and Web) are meant to be used in end-user applications. They only allow you to register a single user at once, and that user is immediately signed in.

If you want to switch between accounts, I think you should log out and login every time.

Best,
Israel Soto.

[1]: https://stackoverflow.com/a/41897642
