### ISSUE TITLE
Xamarin.iOS.Firestore: Failed to get document because the client is offline exception firestore xamarin

### ISSUE THREAD

**Issue by sonnt1012** [xamarin/GoogleApisForiOSComponents#171]
I got this error in Xamarin.iOS.Firestore 0.9.4. It happens when I try to get DocumentSnapshot from Firestore Database. Please see attached image for more detail. If anyone has solution for this errors, please help.
<img width="824" alt="screen shot 2018-08-14 at 10 01 19 am" src="https://user-images.githubusercontent.com/13852761/44069462-1dad63ee-9fa9-11e8-9b31-7406012b37a4.png">

**Comment by SotoiGhost** [comment]
This seems to be related to #173. Please, follow the instructions of #173 to see if this gets fixed. If not, please, feel free to reopen this issue.

Best,
Israel Soto.
