### ISSUE TITLE
Xamarin.iOS.Firestore : GRPC_LINUX_EPOLL is not defined when call Firestore.Create(app)

### ISSUE THREAD

**Issue by sonnt1012** [xamarin/GoogleApisForiOSComponents#173]
I got issuse on Xamarin.iOS.Firestore 0.9.4. When I called Firestore.SharedInstance, it works correctly but I want to switch database projects, I used Firestore.Create(app). This bug happened, the app crashes immediately and get a log "GRPC_LINUX_EPOLL is not defined". If anyone have solution for this issues, please help me. 

Thanks in advanced,

**Comment by SotoiGhost** [comment]
@sonnt1012 Can you, please, try upgrading the component to v0.12.5? According to this [post][1] there is a bug on gRPC dependency and Firestore v0.9.4 is using that buggy version. v0.12.5 contains the most recent version of gRPC dependency that contains that fix.

If you have any doubt, please, let me know.

Best,
Israel Soto.

[1]: https://stackoverflow.com/a/48362429/2376248

**Comment by newky2k** [comment]
no response for 20 days closing

**Comment by divyesh008** [comment]
I have use the Cloud Firestore for my Xamarin.iOS application and many time when i'm running the application it gives the same error. I'm not able to find it's solution yet.

**I have used below packages for cloud firestore:**

```
Xamarin.Firebase.iOS.CloudFirestore (version-0.13.3)
Xamarin.Firebase.iOS.Core (version-5.1.8)
Xamarin.Firebase.iOS.Storage (version-3.0.2)
```

**Comment by divyesh008** [comment]
I have use the Cloud Firestore for my Xamarin.iOS application and many time when i'm running the application it gives the same error. I'm not able to find it's solution yet.

**I have used below packages for cloud firestore:**

```
Xamarin.Firebase.iOS.CloudFirestore (version-0.13.3)
Xamarin.Firebase.iOS.Core (version-5.1.8)
Xamarin.Firebase.iOS.Storage (version-3.0.2)
```
