### ISSUE TITLE
App crash during guest mode pairing

### ISSUE THREAD

**Issue by visuall** [xamarin/GoogleApisForiOSComponents#174]
When Google Cast is used on ios in guest mode it crashes during  pairing between the app and the Chromecast device. The crash hapopens just before displaying the enter pin dialog. Info for the crash is as follows:

Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: Application tried to present modally an active controller <UIViewController: 0x108dfb990>.
Native stack trace:
	0   CoreFoundation                      0x0000000182e5eda4 <redacted> + 252
	1   libobjc.A.dylib                     0x00000001820185ec objc_exception_throw + 56
	2   UIKit                               0x000000018cc9fac8 <redacted> + 4812
	3   UIKit                               0x000000018cf184b0 <redacted> + 68
	4   UIKit                               0x000000018ca2f148 <redacted> + 104
	5   UIKit                               0x000000018cf1840c <redacted> + 212
	6   UIKit                               0x000000018cc563e4 <redacted> + 512
	7   UIKit                               0x000000018cc9e7bc <redacted> + 180
	8   UIKit                               0x000000018cc9e654 <redacted> + 160
	9   GoogleCast                          0x0000000107adf440 _Z18MakeIntervalStringi + 64152
	10  GoogleCast                          0x0000000107b405a4 _Z18MakeIntervalStringi + 461820
	11  libdispatch.dylib                   0x0000000182750aa0 <redacted> + 24
	12  libdispatch.dylib                   0x0000000182750a60 <redacted> + 16
	13  libdispatch.dylib                   0x000000018275d65c <redacted> + 1012
	14  CoreFoundation                      0x0000000182e07070 <redacted> + 12
	15  CoreFoundation                      0x0000000182e04bc8 <redacted> + 2272
	16  CoreFoundation                      0x0000000182d24da8 CFRunLoopRunSpecific + 552
	17  GraphicsServices                    0x0000000184d09020 GSEventRunModal + 100
	18  UIKit                               0x000000018cd41758 UIApplicationMain + 236
	19  PlayOnCloudiOS                      0x0000000104c82420 PlayOnCloudiOS + 43967520
	20  PlayOnCloudiOS                      0x00000001045953cc PlayOnCloudiOS + 36705228
	21  PlayOnCloudiOS                      0x000000010459528c PlayOnCloudiOS + 36704908
	22  PlayOnCloudiOS                      0x000000010239b080 PlayOnCloudiOS + 1077376
	23  PlayOnCloudiOS                      0x0000000102a12cf8 PlayOnCloudiOS + 7859448
	24  PlayOnCloudiOS                      0x0000000106f016f0 mono_pmip + 26172
	25  PlayOnCloudiOS                      0x0000000106f7fb08 mono_pmip + 543316
	26  PlayOnCloudiOS                      0x0000000106f85880 mono_pmip + 567244
	27  PlayOnCloudiOS                      0x0000000106ee41b0 WebPGetDecoderVersion + 1233668
	28  PlayOnCloudiOS                      0x000000010706fe9c xamarin_localized_string_format_9 + 27664
	29  PlayOnCloudiOS                      0x0000000102365318 PlayOnCloudiOS + 856856
	30  libdyld.dylib                       0x00000001827b5fc0 <redacted> + 4

**Comment by SotoiGhost** [comment]
Hi @visuall! Are you in a modal view when you are trying to connect to the Cast device? Also, if you can share a test case, I'd appreciate it.

**Comment by newky2k** [comment]
no response for over two weeks
