### ISSUE TITLE
Xamarin.Goolge.iOS.Signin : Not getting callback of google login in device.

### ISSUE THREAD

**Issue by krupanshu** [xamarin/GoogleApisForiOSComponents#175]
I am using nuget package 4.1.2, and I am getting error like below,

Error configuring the Google context: The operation couldn’t be completed. (com.google.greenhouse error -3.)

And not able to get login call back. Is there any solution for this?

**Comment by krupanshu** [comment]
This happens only on the device. In the simulator, it is working.

**Comment by newky2k** [comment]
@krupanshu Could you provide a small demo so that we can replicate the issue and investigate further.

Thanks

**Comment by newky2k** [comment]
no response for two weeks. closing
