### ISSUE TITLE
Xamarin.Firebase.iOS.Crashlytics.targets compilation issue when calling Fabric script

### ISSUE THREAD

**Issue by deckerst** [xamarin/GoogleApisForiOSComponents#181]
After adding the iOS Crashlytics 3.10.3 package, compilation fails when it's trying to execute the script to upload symbols (I simplified paths but they're all correct):
```
[...]/packages/Xamarin.Firebase.iOS.Crashlytics.3.10.3/build/Xamarin.Firebase.iOS.Crashlytics.targets(3,3):
Error MSB3073: The command "[...]/Library/Caches/XamarinBuildDownload/Fbrc-1.7.8/upload-symbols -gsp [...]/GoogleService-Info.plist -p ios [...].app.dSYM" exited with code 132.
```

It fails because the `Fbrc-1.7.8` folder is missing. It seems that all the items from the package targets ItemGroup are skipped, as the `FCrshlytcs-3.10.3` folder is also missing.

The ItemGroup condition is `('$(OutputType)'!='Library' OR '$(IsAppExtension)'=='True')`, which should be satisfied for a regular app project, no?

For reference, here's my VS environment:
```
=== Visual Studio Community 2017 for Mac ===

Version 7.6.3 (build 1)
Installation UUID: 593a684f-9af5-490e-ab98-0f74605c5bc7
Runtime:
	Mono 5.12.0.301 (2018-02/4fe3280bba1) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000301

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.4.1 (14161)
Build 9F2000

=== Xamarin.Mac ===

Version: 4.6.0.14 (Visual Studio Community)
Hash: 1a6e2786
Branch: 
Build date: 2018-08-28 00:12:06-0400

=== Xamarin.iOS ===

Version: 11.14.0.14 (Visual Studio Community)
Hash: 1a6e2786
Branch: HEAD
Build date: 2018-08-28 00:12:06-0400

=== Xamarin.Android ===

Version: 9.0.0.20 (Visual Studio Community)
Android SDK: /Users/thibaultdeckers/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 25.0.1

Java SDK: /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 706030001
Git revision: 18a828b090fb6d2cfb0b3576cd6d7eb764f29753
Build date: 2018-08-30 15:12:59+00
Build branch: release-7.6
Xamarin extensions: f4aee57d7b72fa4be6b6d585ac90d614f20fa426

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Internet of Things (IoT) development (Preview) 7.5.3

```

**Comment by SotoiGhost** [comment]
Hi @deckerst! Can you, please, double check that the `Xamarin.Build.Download` NuGet is referenced to your app project?

**Comment by SotoiGhost** [comment]
Np :)

Hmm... weird.

> The ItemGroup condition is ('$(OutputType)'!='Library' OR '$(IsAppExtension)'=='True'), which should be satisfied for a regular app project, no?

Yes, it should work for a regular app, which project did you create for your app?

Please, try one or all of the following suggestions:

1. Re-add the Xamarin.Build.Download NuGet package
2. Delete `[...]/Library/Caches/XamarinBuildDownload/` folder and build again.
3. Remove `bin` and `obj` folders and build again.
4. Download and try the [Crashlytics sample][1] and check if the packages were downloaded on the XBD cache folder

If none of this helps, please, try to create a test case of this so I can work on it.

Thanks in advance!
Israel Soto.

[1]: https://github.com/xamarin/GoogleApisForiOSComponents/files/2351022/firebaseioscrashlytics-3.10.3.1.zip

**Comment by deckerst** [comment]
My solution has the following projects:
- BpuCommon.Core (.NET Standard project, shared with other app)
- BpuCommon.Xamarin.Droid (X-Android project, shared with other app)
- BpuCommon.Xamarin.Forms (.NET Standard project, shared with other app)
- BpuCommon.Xamarin.iOS (X-iOS project, shared with other app)
- Hermes.Droid (deployable X-Android project)
- Hermes.Forms (.NET Standard project)
- Hermes.iOS (deployable X-iOS project)

I tried your suggestions 1~3, to no avail. I'll try the sample project and report back.

Thanks for the help.

**Comment by deckerst** [comment]
Regarding the Crashlytics sample, I tried to load the solution you linked, but the package Crashlytics 3.10.3.1 couldn't be restored (this version is not available even in prerelease). Anyway, I fetched the sample solution from the current version 3.10.3, and it successfully downloaded `Fbrc-1.7.8` and `FCrshlytcs-3.10.3` as expected.

I'll try to come up with a test case.

**Comment by deckerst** [comment]
After investigation, it seems the project structure and dependencies is critical.

"BpuCommon.Xamarin.iOS" is a "Xamarin iOS Class Library" project, and "Hermes.iOS" is a "Xamarin iOS App" project. My App project depends on the Library project. And both projects depend on the Crashlytics package.

When I remove the dependency from the Library project to the Crashlytics package the build succeeds, but with that particular dependency, the whole solution build fails as I described before, despite the fact that we're also building an App project.

For my particular case, I can work around this by removing the dependency from my common Library and duplicate some code in each app, but I think it would be nice if this kind of solution structure was handled smoothly.

**Comment by SotoiGhost** [comment]
@deckerst We decided to implement that conditional because the Firebase client SDKs (for Android, iOS, and Web) are meant to be used in end-user applications.

Anyway, you can always modify the Crashlytics `.targets` file or add your own MSBuild task that downloads the Fabric stuff.

Hope this helps.

I'm closing this right now, feel free to reopen it anytime.

Best!
Israel Soto.
