### ISSUE TITLE
Xamarin.Firebase.iOS.Crashlytics build time is taking too long

### ISSUE THREAD

**Issue by andreflourenco** [xamarin/GoogleApisForiOSComponents#183]
After adding the NuGet package Xamarin.Firebase.iOS.Crashlytics to a Xamarin iOS application the build time for the application increased significantly (from about 1 minute to 20 minutes).

By looking at the output window, It seems that what's taking so long is the upload of the DSYM file which can get quite big dependend on the application. 

If that is really the case I believe that this build task should only be enabled for Release builds. Is there a project specific way of disabling this task (for Debug builds for instance)?

**Comment by SotoiGhost** [comment]
Hi @andreflourenco! Sorry for the inconveniences that this may cause. Right now, there isn't an "easy" way to disable the MSBuild task, we will work on this to provide a handy way to disable/enable this MSBuild task.

For now, the only way to disable it is by making false the [conditional][1] of the task (by adding `'True' == 'False'` fro example) in the Crashlytics `.targets` file within the NuGet package. Notice that if you readd the package, all changes you made to this file will be lost.

If you have any other doubt, don't hesitate to ask.

Best,
Israel Soto.

[1]: https://github.com/xamarin/GoogleApisForiOSComponents/blob/master/Firebase.Crashlytics/source/Firebase.Crashlytics/Firebase.Crashlytics.targets#L45
