### ISSUE TITLE
SignInWithCustomToken method in Xamarin.Firebase.iOS.Auth give System.InvalidCastException.

### ISSUE THREAD

**Issue by munirahkamaluddin** [xamarin/GoogleApisForiOSComponents#187]
Hi, 

I trying to use SignInWithCustomToken method with the latest version of Xamarin.Firebase.iOS.Auth (v.5.0.2) with my existing code that worked well with the previous version. 
Somehow, after I update the package, it gave me this below error:

System.InvalidCastException.
Specified cast is not valid 
  at (wrapper castclass) System.Object.__castclass_with_cache(object,intptr,intptr)
  at ObjCRuntime.Runtime.ConstructNSObject[T] (System.IntPtr ptr, System.Type type, ObjCRuntime.Runtime+MissingCtorResolution missingCtorResolution) [0x00050] in <6a026a6503ca4935b5bb3ed241d053fe>:0 
  at ObjCRuntime.Runtime.GetNSObject[T] (System.IntPtr ptr) [0x000d1] in <6a026a6503ca4935b5bb3ed241d053fe>:0 
  at ObjCRuntime.Trampolines+SDAuthResultHandler.Invoke (System.IntPtr block, System.IntPtr user, System.IntPtr error) [0x00016] in <2a6853d2bb50451d907ffe64206d0142>:0 
  at (wrapper native-to-managed) ObjCRuntime.Trampolines+SDAuthResultHandler.Invoke(intptr,intptr,intptr)

I suspect the problem with the completion handler because when I set the completion handler to be null, I didn't get above error & everything is looking fine.

**Comment by newky2k** [comment]
@munirahkamaluddin  could you please provide a small sample project that demonstrates the issue.

**Comment by newky2k** [comment]
No response for over two weeks closing

**Comment by faizworks** [comment]
Hey @newky2k 

I am getting exactly same error with the latest version latest version of Xamarin.Firebase.iOS.Auth (v.5.0.4). I am using the following code in AppDelegate

```
public override bool FinishedLaunching(UIApplication app, NSDictionary options)
        {
            global::Xamarin.Forms.Forms.Init();
            LoadApplication(new App());

            Firebase.Core.App.Configure();

            var token = "{mytokenreturnedfromapiby-await FirebaseAuth.DefaultInstance.CreateCustomTokenAsync(uid)}";

            Auth.DefaultInstance.SignInWithCustomToken(token, async (User user, NSError error) =>
            {
            });

            return base.FinishedLaunching(app, options);
}
```

Using the following three packages

- Xamarin.Firebase.iOS.Auth - v5.0.4
- Xamarin.Firebase.iOS.CloudFirestore - v0.13.3
- Xamarin.Firebase.iOS.Core - v5.1.3
- Xamarin.Forms - v3.3.0.967583

**Comment by matgallacher** [comment]
I can confirm this is still an issue with a custom token as per @faizworks  sample code.

Using SignInAsync(token) from 4.4.1.1 does work but it appears to have some issues with Firestore not then being authenticated.

Can this be reopened or does a new issue need raising?

**Comment by igdit** [comment]
Bump

**Comment by igdit** [comment]
Same issue here. Which issue should I be following instead?

**Comment by matgallacher** [comment]
I've raised #213 , Sample code given in this is valid but needs a way of generating a custom token
