### ISSUE TITLE
Firebase In-App Messaging

### ISSUE THREAD

**Issue by ndhuy96** [xamarin/GoogleApisForiOSComponents#188]
Will Firebase In-App Messaging appear in next version? I really need to use this exciting service!

> VS bug [#732441](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/732441)

**Comment by SotoiGhost** [comment]
We have this component on the radar, but we don't have an ETA. If someone of the community wants to take this, community PR's are very welcome! We can help you through the process.

**Comment by amitlodha** [comment]
it will be good Firebase In-App Messaging nuget package is release

**Comment by ntrivedi23** [comment]
Looking for the component, should be release soon.

**Comment by KevinvdBurg** [comment]
Is there any progress of this component for Xamarin? I would really like to use it in my app.

**Comment by amitlodha** [comment]
@xamarin-release-manager can you take this on priority there lot of use case associated with the same

**Comment by SotoiGhost** [comment]
This is closed now as Firebase In-App Messaging has been released.

**Comment by mayhammf** [comment]
> This is closed now as Firebase In-App Messaging has been released.

@SotoiGhost Would you kindly provide the name or link of the NuGet package where the Firebase In-App Messaging is released.

I can see [this PR](https://github.com/xamarin/GooglePlayServicesComponents/pull/266) which is still pending.

/Thanks

**Comment by amitlodha** [comment]
@xamarin-release-manager can this be released for Android also

**Comment by mayhammf** [comment]
@amitlodha see this [PR](https://github.com/xamarin/GooglePlayServicesComponents/pull/266)  for it.

**Comment by mayhammf** [comment]
@amitlodha regarding iOS, were you able to to implement it successfully? I ran into this issue #398
