### ISSUE TITLE
CloudMessagingSample can't receive messages from FCM console.

### ISSUE THREAD

**Issue by TylerByte666** [xamarin/GoogleApisForiOSComponents#191]
Good day!

I have downloaded your cloud messaging sample and I was able to get it deployed on my iPhone.
When the app launches it shows the default message correctly saying "Hey! To see this sample in action, send a notification from Firebase Console".

When I do that currently I can successfully send a message from the console. But it never reaches the iPhone at all. Can you please help?

**My environment**

- I have iOS 11.4 on my iPhone7.

- I am running the latest Visual Studio and Xcode synced on my Mac.

- Here's my Debug output:

`Loaded assembly: /private/var/containers/Bundle/Application/D9DDAEEA-7853-40A1-BA1D-AB7AE3873AFA/FirebaseMessaging.app/Xamarin.iOS.dll [External]
Thread started:  #2
Loaded assembly: /private/var/containers/Bundle/Application/D9DDAEEA-7853-40A1-BA1D-AB7AE3873AFA/FirebaseMessaging.app/System.Core.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/D9DDAEEA-7853-40A1-BA1D-AB7AE3873AFA/FirebaseMessaging.app/Firebase.Core.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/D9DDAEEA-7853-40A1-BA1D-AB7AE3873AFA/FirebaseMessaging.app/Firebase.InstanceID.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/D9DDAEEA-7853-40A1-BA1D-AB7AE3873AFA/FirebaseMessaging.app/Firebase.CloudMessaging.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/D9DDAEEA-7853-40A1-BA1D-AB7AE3873AFA/FirebaseMessaging.app/System.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/D9DDAEEA-7853-40A1-BA1D-AB7AE3873AFA/FirebaseMessaging.app/System.Json.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/D9DDAEEA-7853-40A1-BA1D-AB7AE3873AFA/FirebaseMessaging.app/MonoTouch.Dialog-1.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/D9DDAEEA-7853-40A1-BA1D-AB7AE3873AFA/FirebaseMessaging.app/FirebaseMessaging.exe
2018-10-09 14:30:04.728 FirebaseMessaging[955:410533] FCM token: 
2018-10-09 14:30:07.641 FirebaseMessaging[955:410533] 
Method name: DidReceiveRegistrationToken
Information: Firebase registration token: e8pMD2seV9U:APA91bFAl30m5BcYwmXR4EWHI-fAl94HqAsiGfZz3uXtaSh375Ku1-nvCDycLiailmFgV7LVJajanzPVdc5vVSPJWTq6kVgzj-neaBw07Tfdi5WydVoBgYx1IZQJyprjvp-9D17Ht6jZ
Thread started:  #3
2018-10-09 14:30:08.458 FirebaseMessaging[955:410549] True
The app has been terminated.
The app has been terminated.
The app has been terminated.
`
The app has been terminated was from me disconnecting it from the Mac. Please help :(

**Comment by TylerByte666** [comment]
Is it perhaps because of this step that actually requires me to pay money to be a part of the Developer Program?
https://firebase.google.com/docs/cloud-messaging/ios/certs

**Comment by ndhuy96** [comment]
You have to pay money to get Auth Key in order to use this service on your iphone

**Comment by TylerByte666** [comment]
Can someone from the repro please confirm before I waste 99USD?

**Comment by SotoiGhost** [comment]
@TylerByte666 AFAIK, to use Push Notifications on iOS, you must have a developer account.

**Comment by TylerByte666** [comment]
Thank you all :)
