### ISSUE TITLE
SetUserProperty not work correctly in Xamarin iOS

### ISSUE THREAD

**Issue by MaxiTalenti** [xamarin/GoogleApisForiOSComponents#192]
Hi, the function Analytics.SetUserProperty(valor, key) in Xamarin iOS it does not work almost always. Why this happens?

I used Xamarin.Firebase.iOS.Analytics package in version 5.0.1.

**Comment by newky2k** [comment]
@MaxiTalenti could you please provide a small sample project that demonstrates the issue that you are having.

Regards

**Comment by MaxiTalenti** [comment]
`public static void UpdateInfo(Context context)
        {
            Task.Run(async () =>
            {
                try
                {
                    var value = await Services();
                    PortfolioPreferences.setConfig(FirebaseProperties.Key1, value, context);

                    SubmitInfo(context);
                }
                catch (Exception e)
                {
                    Client.Services.AppCenter.AppCrashes.CreateCrash(e);
                }
            });
        }

        public static void SubmitInfo(Context context)
        {
            FirebaseCustom.FirebaseProperty.setProperty(PortfolioPreferences.GetValue(FirebaseProperties.Key1, context).ToString(), FirebaseProperties.Key1, context);
           
        }
public static void setProperty(string valor, FirebaseProperties name, Context context)
        {
            Firebase.Analytics.FirebaseAnalytics.GetInstance(context).SetUserProperty(valor, name.ToString());
        }
    }`

**Comment by newky2k** [comment]
@MaxiTalenti  Thanks for the code.  Does it produce and error/exception or does it simply do nothing?

Regards

**Comment by MaxiTalenti** [comment]
> @MaxiTalenti Thanks for the code. Does it produce and error/exception or does it simply do nothing?
> 
> Regards

it simply does not do anything but does not record it.

**Comment by SotoiGhost** [comment]
@MaxiTalenti can you, please, try [enabling the debug mode][1] for events and see if they are reaching to Firebase console?

Thanks in advance!

[1]: https://github.com/xamarin/GoogleApisForiOSComponents/blob/master/Firebase.Analytics/component/GettingStarted.md#enabling-debug-mode

**Comment by SotoiGhost** [comment]
No response for more than fourteen days, closing. If you still have this issue, please open a new issue.
