### ISSUE TITLE
Xamarin.Firebase.iOS.Crashlytics issue when uploading symbols on macOS 10.14 Mojave

### ISSUE THREAD

**Issue by deckerst** [xamarin/GoogleApisForiOSComponents#194]
A project that used to build fine before now fails after upgrading macOS to Mojave:
`[app-path]/packages/Xamarin.Firebase.iOS.Crashlytics.3.10.3.1/build/Xamarin.Firebase.iOS.Crashlytics.targets(53,3): error MSB3073: The command "/Users/thibaultdeckers/Library/Caches/XamarinBuildDownload/Fbrc-1.7.8/upload-symbols -gsp [app-path]/iOS/GoogleService-Info.plist -p ios bin/iPhone/Release/MyApp.iOS.app.dSYM" exited with code 8.`

When running this script as a standalone command:
`error: could not complete submission of dSYM at bin/iPhone/Release/MyApp.iOS.app.dSYM: Error Domain=com.crashlytics.mac.error-domain.process-dsym Code=4 "This version of OSX is not able to perform the necessary dSYM transformations." UserInfo={NSLocalizedFailureReason=This version of OSX is not able to perform the necessary dSYM transformations.}`

It seems Fabric added support for Mojave with version 1.7.11, but Xamarin.Firebase.iOS.Crashlytics v3.10.3.1 still relies on Fabric v1.7.8. An upgrade would be much appreciated.

**Comment by newky2k** [comment]
@deckerst could you please provide a small sample project that demonstrates this issue so we can investigate further.

Regards

**Comment by MaxiTalenti** [comment]
The same happens to me.

**Comment by Redth** [comment]
Assigning this to @SotoiGhost

**Comment by allandaleho** [comment]
Hi @SotoiGhost, can we know the status for this? Are there steps we can take to temporarily fix the issue? (currently blocking my deployment and I'm not a Xamarin expert)

Thanks!

**Comment by TimA11111** [comment]
Hi @SotoiGhost, any updates on this?   It's blocking my work at the moment.   Thanks.

**Comment by psoilemezis** [comment]
Hi I have the same problem.

**Comment by Gil-Littman** [comment]
I'm still seeing this error after updating Crashlytics to 3.10.9 (and all my other packages as well). Am I missing something here?
