### ISSUE TITLE
Is there a plan to upgrade the Google Maps binding to the 2.7.0 SDK?

### ISSUE THREAD

**Issue by jstawski** [xamarin/GoogleApisForiOSComponents#195]
The [latest google](https://developers.google.com/maps/documentation/ios-sdk/releases) maps version is 2.7.0. Are there plans to upgrade the binding?

**Comment by newky2k** [comment]
@jstawski  Thanks for getting in touch.

It is on the todo list and will be upgraded in the near future.

Regards
