### ISSUE TITLE
Google Map ios's circle is smaller than Android's

### ISSUE THREAD

**Issue by WhiskyDM** [xamarin/GoogleApisForiOSComponents#197]
I draw two circles with the same radius on IOS and Android but 
the circle on IOS seems a little smaller than the cirle on Android device.
Can you tell me the reason of this issue.

**Comment by newky2k** [comment]
@WhiskyDM  that could be any number of reasons, not least the size of the devices running, default zooms on the different devices, etc.

Is it significantly different or is it marginal?   How much of an issue is this?  Can you please provide a sample project that demonstrates this so we can investigate.

Regards

**Comment by WhiskyDM** [comment]
The radius of circles are the same if both devices are IOS or both are Android.
But there is a difference in display size of circles if one device is IOS and one another is Android.
I compared the two circle's display with location on Google Map, 
it can be clearly seen with large scale, that with same center position and same radius, 
Android device's circle radius is always 0.2% bigger than that of IOS.

For example, if I set a 10km radius circle, 
the radius of Android device is displayed 20m bigger than IOS's,
and it is 200m bigger if I set 100km radius circle.
The bigger circle radius is, the more clearly I can see the difference.
![ios](https://user-images.githubusercontent.com/11819843/47690091-05e16a80-dc30-11e8-9982-f5a7a6d413be.PNG)
![android](https://user-images.githubusercontent.com/11819843/47690094-0843c480-dc30-11e8-8d82-d90cae4da07a.png)

**Comment by SotoiGhost** [comment]
@WhiskyDM Can you try reproducing this issue using native iOS and Android SDKs? We want to make sure that Xamarin is playing on this issue. 

Thanks in advance!

Best!

**Comment by Redth** [comment]
Given these are two separate platforms, I think this is beyond our control, unless you can provide us with samples on each platform (native obj-c and java) which show otherwise.  Closing for now, please open another issue if you have more info.
