### ISSUE TITLE
iOS RemoteConfig - not fetching the values - dev enabled

### ISSUE THREAD

**Issue by hitsy** [xamarin/GoogleApisForiOSComponents#198]
Hoping if anyone could assist seems like I have done everything by the book but regardless am not fetching the values - android work beautifully but not iOS - any assistance would be helpfull

**Comment by newky2k** [comment]
@hitsy Can you please provide a small sample project that demonstrates this issue.

Regards

**Comment by hitsy** [comment]
This is what i have done - sorry don't have a sample app right now... 

AppDelegate -> FinishedLaunching 
`...
 Firebase.Core.App.Configure();`

then 
`...
public async Task RCInit()
        {
            RemoteConfig.SharedInstance.Init();
            RemoteConfig.SharedInstance.ConfigSettings = new RemoteConfigSettings(true);
            SetDefaultsAsync();
            await FetchRemoteConfig();
        }`
...
`var path = NSBundle.MainBundle.PathForResource("AppConfig", "plist");
            var data = NSDictionary.FromFile(path);
`
....
`RemoteConfig.SharedInstance.SetDefaults(data);`
....
`
var status = await remoteConfig.FetchAsync();
                if (status == RemoteConfigFetchStatus.Success)
                {
                    if (RemoteConfig.SharedInstance.ActivateFetched())
                    {
                        Console.WriteLine("Config Fetched! {0} {1}", DateTime.Now.ToString("O"), RemoteConfig.SharedInstance.LastFetchTime);
                    }`
...
`public string GetValue(string key)
        {
            var value = RemoteConfig.SharedInstance[key];
            return value.StringValue;
        }`

And it always returns success - but the get value is always returning the default....

**Comment by hitsy** [comment]
> This is what i have done - sorry don't have a sample app right now...
> 
> AppDelegate -> FinishedLaunching
> `... Firebase.Core.App.Configure();`
> 
> then
> `... public async Task RCInit() { RemoteConfig.SharedInstance.Init(); RemoteConfig.SharedInstance.ConfigSettings = new RemoteConfigSettings(true); SetDefaultsAsync(); await FetchRemoteConfig(); }`
> ...
> `var path = NSBundle.MainBundle.PathForResource("AppConfig", "plist"); var data = NSDictionary.FromFile(path); `
> ....
> `RemoteConfig.SharedInstance.SetDefaults(data);`
> ....
> ` var status = await remoteConfig.FetchAsync(); if (status == RemoteConfigFetchStatus.Success) { if (RemoteConfig.SharedInstance.ActivateFetched()) { Console.WriteLine("Config Fetched! {0} {1}", DateTime.Now.ToString("O"), RemoteConfig.SharedInstance.LastFetchTime); }`
> ...
> `public string GetValue(string key) { var value = RemoteConfig.SharedInstance[key]; return value.StringValue; }`
> 
> And it always returns success - but the get value is always returning the default....

**Comment by newky2k** [comment]
@hitsy  Thank you for the info, i'll pass this on to @SotoiGhost to investigate further

Regards

**Comment by hitsy** [comment]
> @hitsy Thank you for the info, i'll pass this on to @SotoiGhost to investigate further
> 
> Regards

Any thoughts\Updates ?

**Comment by SotoiGhost** [comment]
@hitsy Testing our sample everything seems to be working ok. I'll try to replicate your scenario and see what happens.

**Comment by SotoiGhost** [comment]
@hitsy I think I found the problem. Please, remove the line `RemoteConfig.SharedInstance.Init();` and try again. This line is not necessary to make Remote Config work. The `Init` method lives inside of `NSObject` and is used to create another instance of the class but it is not necessary for this scenario.

Let me know your results.

Best!
Israel Soto.

**Comment by hitsy** [comment]
> @hitsy I think I found the problem. Please, remove the line `RemoteConfig.SharedInstance.Init();` and try again. This line is not necessary to make Remote Config work. The `Init` method lives inside of `NSObject` and is used to create another instance of the class but it is not necessary for this scenario.
> 
> Let me know your results.
> 
> Best!
> Israel Soto.

@SotoiGhost - Mate... worked like a charm. Not sure why I had called it in the first place.
Thank you
