### ISSUE TITLE
Xamarin.Google.iOS.SignIn - switching branches breaks solution

### ISSUE THREAD

**Issue by romanGarasymovych** [xamarin/GoogleApisForiOSComponents#201]
Using the Xamarin.Google.iOS.Google.SignIn v4.2.0 package works, but the project terminates after build with message "The app has been terminated." with no additional output if I switch to other branches that don't use the package. The only noticeable thing I can see is that there is a warning that Google.SignIn.framework is missing in References. However, on other branches it shouldn't be referenced at all.

The only solution I found so far is closing the solution, deleting vs, obj, and bin files, and then rebuilding the project. However, this very inconvenient. 

Anything else I can do beside adding the package to master?

> VS bug [#732195](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/732195)

**Comment by newky2k** [comment]
@romanGarasymovych  Could you please provide a simple project that demonstrates this issue.

Regards

**Comment by romanGarasymovych** [comment]
I created a sample project here - [Link]( https://github.com/romanGarasymovych/GoogleSignInPackageIssue)

I used version 4.1.1.1, however, because I was getting Native linking errors with highr ones for some reason...

**Comment by SotoiGhost** [comment]
@romanGarasymovych Can you share the steps to reproduce this issue? I tried your sample repo but with no success of failing when running the app between branches.

Here's my environment info:

```
=== Visual Studio Enterprise 2017 for Mac ===

Version 7.6.11 (build 9)
Installation UUID: 48b5fb7e-9587-45b0-b10e-58dc44b4c3fe
Runtime:
	Mono 5.12.0.309 (2018-02/39d89a335c8) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000309

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
	2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.iOS ===

Version: 12.1.0.15 (Visual Studio Enterprise)
Hash: cbfb047a
Branch: xcode10.1
Build date: 2018-10-30 22:57:23-0400

=== Build Information ===

Release ID: 706110009
Git revision: d7cd66f5e3acd3d46ba0b94a0c935378f828bde0
Build date: 2018-10-31 17:17:12+00
Build branch: release-7.6
Xamarin extensions: bc9b985bfcb480b04a208a6d4045adc443a07857

=== Operating System ===

Mac OS X 10.14.0
Darwin 18.0.0 Darwin Kernel Version 18.0.0
    Wed Aug 22 20:13:40 PDT 2018
    root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64
```

**Comment by romanGarasymovych** [comment]
I simply only have to build the branch with the package, and after switching to master, I can't build or deploy until I restart the solution.

I am developing from Windows while pairing to Mac, and when I click on Sttart Debugging, nothing happens

**Comment by SotoiGhost** [comment]
I only tested this on Mac side, I'll try this on Windows.

**Comment by SotoiGhost** [comment]
@romanGarasymovych I can confirm the issue here. This happens with other packages also, not only with Google.SignIn. One solution I have found so far is that, when the message dialog appears on VS, hit **Reload Solution** instead of **Reload**. Also, if you switch branches within VS, everything seems to work correctly. I moved this issue to the iOS Team for a further investigation.

<img width="600" src="https://user-images.githubusercontent.com/5924210/51300777-aefb5e00-19f2-11e9-8771-c4d6fd38d918.png" />

I'm closing the issue.
