### ISSUE TITLE
Not able to push custom events in Firebase Analytics

### ISSUE THREAD

**Issue by niraj-bpsoftware** [xamarin/GoogleApisForiOSComponents#206]
I am getting auto events like session_start, screen_view so my iOS App is sending events to Firebase. but not the custom events where event id is a custom value like "MyEvent1"

My environment:
Windows
Visual Studio 2017 version 15.8.9
Nuget Packages:
Xamarin.Firebase.iOS.Analytics - 5.1.4 
Xamarin.Firebase.iOS.Core - 5.1.3
Xamarin.Firebase.iOS.InstanceID - 3.2.1

I have mentioned following mlaunch and start argument in iOS project properties -> iOS Run Optionts:
--argument=-FIRAnalyticsDebugEnabled

AppDelegate.cs FinishedLaunching event override code:
```
Firebase.Analytics.Loader loader1 = new Firebase.Analytics.Loader(); 
Firebase.InstanceID.Loader loader2 = new Firebase.InstanceID.Loader(); 
Firebase.Core.App.Configure(); 
AnalyticsConfiguration.SharedInstance.SetAnalyticsCollectionEnabled(true);
return base.FinishedLaunching(app, options);
```

I have implemented following solution for Firebase Analytics:
https://stackoverflow.com/questions/48774378/firebase-analytics-in-xamarin-forms/50764452#50764452
However I am facing issues in pushing custom events to Firebase for my iOS project. Android is pushing these custom events properly.
I am adding following lines in 

First problem:
following code throws an ambiguous error.(https://forums.xamarin.com/discussion/136547/firebase-analytics-the-call-is-ambiguous-between-the-following-methods-or-properties)
```
if (parameters == null)             
{                 
    Analytics.LogEvent(eventId, null);                 
    return;             
}
```

So I tried following options:
option 1:
```
if (parameters == null)             
{                 
    Firebase.Analytics.Analytics.LogEvent(eventId, new Dictionary<object, object>());                 
    return;             
}
```

This threw an exception :
    Unhandled Exception:
    System.ArgumentException: count occurred

option 2:
```
if (parameters == null)             
{                 
    Firebase.Analytics.Analytics.LogEvent(eventId, new Dictionary<object, object>(){{"key1", "value1"}});                 
    return;             
}
```

option 3:
``` 
      var keys = new List();
       var values = new List();
        if (parameters == null)
        {
            keys.Add(new NSString("Parameter"));
            values.Add(new NSString("NONE"));
        }
        else
        {
            foreach (var item in parameters)
            {
                keys.Add(new NSString(item.Key));
                values.Add(new NSString(item.Value));
            }
        }
      var parametersDictionary =
      NSDictionary<NSString, NSObject>.FromObjectsAndKeys(values.ToArray(), keys.ToArray(), keys.Count);
      Firebase.Analytics.Analytics.LogEvent(eventId, parametersDictionary);
```

Both options 2 and 3 are not working. When I am checking debug log, I can find following

[I-ACS025018] Event not logged. Call +[FIRApp configure]: iOSAnalyticsStarted
I have attached whole log file. Can anyone please help?

THanks.
[iosFirebaseAnalyticslog.txt](https://github.com/xamarin/GoogleApisForiOSComponents/files/2637456/iosFirebaseAnalyticslog.txt)

@SotoiGhost

> VS bug [#740090](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/740090)

**Comment by niraj-bpsoftware** [comment]
Hi ,
The issue was that I was trying to log an event before Firebase Analytics was initialized.
I have fixed that issue and now it's trying to log the custom event.

However I am getting an error code type 2 (https://firebase.google.com/docs/analytics/errors) firebase event error instead of my custom event which says event name is not correct. 
Any pointer on how to provide any custom event name when there are no parameters?

My existing code:
if (parameters == null)
{
Firebase.Analytics.Analytics.LogEvent(eventId, new Dictionary<object, object>() { { "key1", "value1" } });
return;
}

Here eventId value is my custom string value.

**Comment by SotoiGhost** [comment]
@niraj-bpsoftware Actually, there is a bug on [`void LogEvent (string name, Dictionary<object, object> parameters)`][1] method where it will not handle correctly the `parameters` argument if it's empty or null. This will be fixed.

For now, if you want to log an event without parameters, please, use the `LogEvent (string name, NSDictionary<NSString, NSObject> nsParameters)` method overload as follows:

```
Analytics.LogEvent (eventId, nsParameters: null);
```

Please, let me know your results.

Best!
Israel Soto.

[1]: https://github.com/xamarin/GoogleApisForiOSComponents/blob/master/Firebase.Analytics/source/Firebase.Analytics/ApiDefinition.cs#L21

**Comment by Redth** [comment]
We are closing this issue since no response was received.  Please open a new issue referring to this one if you have more information.
