### ISSUE TITLE
Unable to get managed stack trace on Crashlytics 

### ISSUE THREAD

**Issue by gnola14** [xamarin/GoogleApisForiOSComponents#207]
Hi, 
I created a sample project on VS4M, using one of the available templates (`Multiplatform App-> Native (iOS, Android)`).
When using Crashlytics on the iOS project and simulating a crash, all I can see on Firebase's dashboard is something along these lines

```
FirebaseTest.iOS
registrar.m - Line 62
native_to_managed_trampoline_2(objc_object*, objc_selector*, _MonoMethod**, unsigned int)
```

On the `Build Output` I can see that the dSYM is being correctly uploaded

```
Target Build:
Target _FirebaseCrashlyticsUploadDSymToFirebaseOnMac:
  Task "Message"
    Uploading dSYM to Firebase using Fabric upload-symbols script located at /Users/gaston/Library/Caches/XamarinBuildDownload/Fbrc-1.7.13
  Done executing task "Message".
  Using "Exec" task from assembly "/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Tasks.dll".
  Task "Exec"
    '/Users/gaston/Library/Caches/XamarinBuildDownload/Fbrc-1.7.13/upload-symbols' -gsp '/Users/gaston/Projects/FirebaseTest/iOS/GoogleService-Info.plist' -p ios 'bin/iPhone/Debug/device-builds/iphone10.2-11.4.1/FirebaseTest.iOS.app.dSYM'
    2018-12-03 13:00:18.116 upload-symbols[24784:5138325] Successfully submitted symbols for architecture arm64 with UUID 332a2db2af6e3a3f8034f7ad9dafcdb2 in dSYM: /Users/gaston/Projects/FirebaseTest/iOS/bin/iPhone/Debug/device-builds/iphone10.2-11.4.1/FirebaseTest.iOS.app.dSYM
  Done executing task "Exec".
Target _FirebaseCrashlyticsUploadDSymToFirebaseMasterTarget:

Done building project "FirebaseTest.iOS.csproj"
```

I've also manually generated a .zip file with all the dSYM found on `bin/iPhone/Debug/device-builds/iphone10.2-11.4.1` and uploaded through the dashboard, to no avail.

Am I missing something?

> VS bug [#742854](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/742854)

**Comment by SotoiGhost** [comment]
@gnola14 If Firebase Console does not ask you for a certain dSYM, it means that it was successfully uploaded. Can you share the full stack error of what you see on Crashlytics Dashboard on Firebase Console? Thanks in advance.

**Comment by gnola14** [comment]
Sure @SotoiGhost, I've attached the full crash log. The Dashboard does mention some "Optional" dSYM's that are missing, but none of the UUID's match with the one of my app
[crash_log.txt](https://github.com/xamarin/GoogleApisForiOSComponents/files/2650331/crash_log.txt)

**Comment by SotoiGhost** [comment]
@gnola14 Is the crash a C# exception or it's happening on Objective-C side? Also, I tested our sample and it seems to be working correctly. Can you provide a test case, please?

**Comment by gnola14** [comment]
@SotoiGhost it's an unhandled C# exception, being generated on the shared project (I hard-coded throwing an `ArgumentException` on one of the screens). I'll give it another shot with a different sample project to see if I still have the same issue. I'll get back to you with a test case.

**Comment by SotoiGhost** [comment]
@gnola14 I think that Firebase does not work properly with C# exceptions as the tool was thought to symbolicate iOS side exceptions, not .Net exceptions. I'm not a dSYM expert, to be honest, so, yeah, let's give a try to see if we can achieve that Firebase can symbolicate C# exceptions. I'll wait for a test case. Thanks in advance!

**Comment by gnola14** [comment]
@SotoiGhost Sorry if I didn't come back with a test case. I believe you're right, in that Crashlytics won't be able to provide more information about a C# exception. However, I found the method [recordCustomExceptionName](https://firebase.google.com/docs/reference/ios/crashlytics/api/reference/Classes/Crashlytics#/c:objc(cs)Crashlytics(im)recordCustomExceptionName:reason:frameArray:). Far from a perfect solution, but it _might_ do the trick. Thanks for your help!

**Comment by SotoiGhost** [comment]
@gnola14 That's a good way to go, not the best due to the performance but, according to the docs, that's the way to go. Closing this issue then. If you face something else related to this, please, open a new issue.

Happy coding!
Best!
