### ISSUE TITLE
I can not access `CustomEventRequest` Gender property

### ISSUE THREAD

**Issue by c-lamont** [xamarin/GoogleApisForiOSComponents#208]
From `ICustomEventBanner` method `RequestBannerAd` passes in a `CustomEventRequest` parameter.

`public void RequestBannerAd(AdSize adSize, string serverParameter, string serverLabel, CustomEventRequest request)`

How do I access the `Gender` property as described here:

https://github.com/xamarin/GoogleApisForiOSComponents/blob/5fa20397422e08d7a8ba2c0e9b51c67d3d15af73/Google.MobileAds/source/Google.MobileAds/ApiDefinition.cs#L2070

**Comment by SotoiGhost** [comment]
@c-lamont I double checked this with Google's headers and the `Gender` and `Birthday` properties were marked as obsolete everywhere, even on the `Request` class. Until now, there is no way to access these values.

Best!

**Comment by c-lamont** [comment]
@SotoiGhost Thanks for investigating and your quick response!
