### ISSUE TITLE
[Firebase][Crashlytics] Add a flag to disable or enable the upload dSYM task to Firebase Console

### ISSUE THREAD

**Issue by SotoiGhost** [xamarin/GoogleApisForiOSComponents#210]
Right now, Crashlytics uploads the dSYM to Firebase Console every time you build your app. The time that this task take depends on your internet connection and on the app size.

We must add a flag or something so the user can decide when to upload the dSYM to Firebase Console or not.

> Reference on #183

> VS bug [#740679](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/740679)

**Comment by b12kab** [comment]
I'd also like this. That way I could have it upload the dSYM files w/o attaching a device.

**Comment by SotoiGhost** [comment]
Firebase Crashlytics v3.14.0 has been pushed. This update contains two flags that let you have more control over the upload process. For more info, here's the [readme file](https://raw.githubusercontent.com/xamarin/GoogleApisForiOSComponents/master/source/Firebase/Crashlytics/readme.txt). Best!

**Comment by b12kab** [comment]
@SotoiGhost Please reopen this. Not creating the dSym file on a emulator is (as I noted) a problem - as all I have are emulators - making this useless to myself and anyone who has a pipeline not attached to a "real" device (which I'd think is all large companies).

**Comment by SotoiGhost** [comment]
@b12kab Can you file a new issue with this info? I'll work on this in the following weeks. Thanks in advance!
