### ISSUE TITLE
SignInWithCustomToken method in Xamarin.Firebase.iOS.Auth give System.InvalidCastException.

### ISSUE THREAD

**Issue by matgallacher** [xamarin/GoogleApisForiOSComponents#213]
Re-raising this from #187.

The code below is still valid

```
public override bool FinishedLaunching(UIApplication app, NSDictionary options)
        {
            global::Xamarin.Forms.Forms.Init();
            LoadApplication(new App());

            Firebase.Core.App.Configure();

            var token = "{mytokenreturnedfromapiby-await FirebaseAuth.DefaultInstance.CreateCustomTokenAsync(uid)}";

            Auth.DefaultInstance.SignInWithCustomToken(token, async (User user, NSError error) =>
            {
            });

            return base.FinishedLaunching(app, options);
}
```

> VS bug [#742856](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/742856)

**Comment by igdit** [comment]
Having the same issue. It is definitely related to the AuthResultHandler, since passing in null works fine. In the meantime, I'm having to settle for an ugly workaround that "times out" if the auth state never changes after a set amount of time (could also leverage AddAuthStateDidChangeListener):

            Auth.DefaultInstance.SignInWithCustomToken(token, null);

            // attempt for 5 seconds before giving up
            var attempts = 50;
            while(Auth.DefaultInstance.CurrentUser == null && attempts > 0)
            {
                await Task.Delay(100);
                attempts--;
            }
            return Auth.DefaultInstance.CurrentUser;

**Comment by bazookajoey** [comment]
I can +1 this issue for me on the Auth 5.0.4 package. SignInWithCustomTokenAsync and SignInWithCustomToken both throws this exception.

My app listens for auth state changes, I validated that the state change handler is fired before crashing.
`Auth.DefaultInstance.AddAuthStateDidChangeListener((auth, user) => StateDidChange(user, handler));`

**Comment by SotoiGhost** [comment]
Thanks for the information guys! As there is a workaround now, I'll look a this, not now, but very soon. This was marked as a high priority for us.
