### ISSUE TITLE
Update Google Maps 2.7.0

### ISSUE THREAD

**Issue by Redth** [xamarin/GoogleApisForiOSComponents#214]
> VS bug [#742855](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/742855)

**Comment by pizzaeater** [comment]
Hi, I'm waiting for an update to 2.7.x too, 2.5.x is a very old version.

**Comment by SotoiGhost** [comment]
@pizzaeater We have this on our TODO list and have plans to be updated in the following weeks, but community contributions are also very welcome!

If someone wants to update just the binding project, that would be enough help for us. We can help you in the process and with the other files
