### ISSUE TITLE
[FireBase] Missing MLVision package ?

### ISSUE THREAD

**Issue by rguilluy** [xamarin/GoogleApisForiOSComponents#216]
Hi, I'd like to use FireBase sdk to process Barcodes scanning on  Xamarin.droid and Xamarin.Ios projects.
Its possible in a native way (https://firebase.google.com/docs/ml-kit/ios/read-barcodes), but I cant find any Xamarin package for this feature, are you planning to release it ?

Thanks !!

**Comment by SotoiGhost** [comment]
@rguilluy We are working on MLKit for iOS right now. You can follow the progress of it on #190. Hopefully, this will be released this week or the next one.
