### ISSUE TITLE
FCM Doesn't work on iPhone X family

### ISSUE THREAD

**Issue by arsereg** [xamarin/GoogleApisForiOSComponents#221]
It seems that FCM component is failing in the iPhone X family (X, XS, XS Max, XR) but is working with no problems on other iPhones.

I get this error:

Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: -[__NSCFString setObject:forKeyedSubscript:]: unrecognized selector sent to instance 0x282dc6280
Native stack trace:
	0   CoreFoundation                      0x00000001ea44ff68 <redacted> + 256
	1   libobjc.A.dylib                     0x00000001e964c284 objc_exception_throw + 60
	2   CoreFoundation                      0x00000001ea3650e0 <redacted> + 0
	3   CoreFoundation                      0x00000001ea4559bc <redacted> + 1416
	4   CoreFoundation                      0x00000001ea457730 _CF_forwarding_prep_0 + 96
	5   Approach.iOS                        0x0000000104d99488 -[FIRMessagingDataMessageManager parseDataMessage:] + 1104
	6   Approach.iOS                        0x0000000104d98fbc -[FIRMessagingDataMessageManager processPacket:] + 260
	7   Approach.iOS                        0x0000000104d93920 -[FIRMessagingClient connectionDidRecieveMessage:] + 84
	8   Approach.iOS                        0x0000000104d968d8 -[FIRMessagingConnection didReceiveDataMessageStanza:] + 80
	9   Approach.iOS                        0x0000000104d95860 -[FIRMessagingConnection secureSocket:didReceiveData:withTag:] + 532
	10  Approach.iOS                        0x0000000104da7b7c -[FIRMessagingSecureSocket processCurrentInputBuffer:outOffset:] + 252
	11  Approach.iOS                        0x0000000104da77f0 -[FIRMessagingSecureSocket performRead] + 1060
	12  Approach.iOS                        0x0000000104da6ef0 -[FIRMessagingSecureSocket stream:handleEvent:] + 356
	13  CoreFoundation                      0x00000001ea3f1950 <redacted> + 220
	14  CoreFoundation                      0x00000001ea3ee994 <redacted> + 212
	15  CoreFoundation                      0x00000001ea3ee78c <redacted> + 312
	16  CFNetwork                           0x00000001eab09d6c <redacted> + 68
	17  CFNetwork                           0x00000001eab0f82c <redacted> + 152
	18  CFNetwork                           0x00000001eab0b408 <redacted> + 92
	19  CoreFoundation                      0x00000001ea3e5c58 <redacted> + 1352
	20  CoreFoundation                      0x00000001ea3de6c4 <redacted> + 28
	21  CoreFoundation                      0x00000001ea3de640 <redacted> + 92
	22  CoreFoundation                      0x00000001ea3ddef8 <redacted> + 180
	23  CoreFoundation                      0x00000001ea3d8bd8 <redacted> + 1032
	24  CoreFoundation                      0x00000001ea3d84b8 CFRunLoopRunSpecific + 452
	25  GraphicsServices                    0x00000001ec68bbe8 GSEventRunModal + 104
	26  UIKitCore                           0x000000021810c1b8 UIApplicationMain + 216
	27  Approach.iOS                        0x000000010544eea8 wrapper_managed_to_native_UIKit_UIApplication_UIApplicationMain_int_string___intptr_intptr + 328
	28  Approach.iOS                        0x00000001053de4fc UIKit_UIApplication_Main_string___intptr_intptr + 44
	29  Approach.iOS                        0x00000001053de4bc UIKit_UIApplication_Main_string___string_string + 172
	30  Approach.iOS                        0x0000000104ead760 Approach_iOS_Application_Main_string__ + 128
	31  Approach.iOS                        0x0000000105322738 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 248
	32  Approach.iOS                        0x000000010697ad68 mono_jit_runtime_invoke + 904
	33  Approach.iOS                        0x00000001069fedec mono_runtime_invoke_checked + 148
	34  Approach.iOS                        0x0000000106a04cd0 mono_runtime_exec_main_checked + 120
	35  Approach.iOS                        0x000000010695b240 mono_jit_exec + 268
	36  Approach.iOS                        0x0000000106af2e2c xamarin_main + 2220
	37  Approach.iOS                        0x0000000104ea9f44 main + 96
	38  libdyld.dylib                       0x00000001e9e8d050 <redacted> + 4

**Comment by SotoiGhost** [comment]
@arsereg I tried our sample on an iPhone XS and everything seems to be working ok.

<img height="500" src="https://user-images.githubusercontent.com/5924210/51221374-d40ea480-18fe-11e9-85ed-8e8410763211.jpeg" />

Can you share a test case, please? Also, the data of the message built on Firebase Console would be helpful. Thanks in advance!

**Comment by Redth** [comment]
We are closing this issue since no response was received.  Please open a new issue referring to this one if you have more information.
