### ISSUE TITLE
Update iOS Google Mobile Ads SDK

### ISSUE THREAD

**Issue by dmanning23** [xamarin/GoogleApisForiOSComponents#222]
Currentlty the version of the Google Mobile Ads SDK used by Xamarin.Google.iOS.MobileAds is 7.32.0
The latest version is 7.37.0 and has several important bug fixes.

I get the following warning message in the console when trying to load a rewarded video:
```
<Google:HTML> You are currently using version 7.32.0 of the SDK. Please consider updating your SDK to the most recent SDK version to get the latest features and bug fixes. The latest SDK can be downloaded from https://goo.gl/UoiJ8F. A full list of release notes is available at https://developers.google.com/admob/ios/rel-notes.
```

Rewarded video is behaving very squirrelly also, with problems such as various events not being fired correctly.

Cheers!

> VS bug [#774492](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/774492)

**Comment by dhindrik** [comment]
It would be great to have this update as soon as possible because I don't get any ads because of the old version.

**Comment by SotoiGhost** [comment]
Hi guys! Sorry for the late response. There is a PR with the update but this update has a problem with the Google Mobile Ads framework. Armv7 arch does not contain some symbols that can make your app not to be able to build if you target a device that supports only armv7.

This issue has been already reported to Google [here][1]

Meanwhile, this update will be released as a beta soon.

[1]: https://groups.google.com/forum/#!searchin/google-admob-ads-sdk/missing$20symbols%7Csort:relevance/google-admob-ads-sdk/ReCFJK2nmGE/Ged1DYFrHgAJ

**Comment by thisisthekap** [comment]
As we are not supporting `armv7` devices anyways, the beta nuget would be a live saver for us.

@SotoiGhost Do you have any estimate when the beta nuget is going to be published?

**Comment by SotoiGhost** [comment]
Guys! Just letting you know that the update has been released as stable, not as a beta. In the end, we find the solution for armv7 symbols.

Happy coding!
Israel Soto.
