### ISSUE TITLE
FreshChat integration from xcode project to xamarin.iOS by bindinglibrary

### ISSUE THREAD

**Issue by mpsarannyaCharu** [xamarin/GoogleApisForiOSComponents#228]
Hi

Anyone knows why it error while binding library project.

I am getting the below error once i have added the freshChat dll on my xamarin.ios project.

Error: linker command failed with exit code 1 (use -v to see invocation) (FreshChatiOS.iOS)

Error MT5216: Native linking failed for '/Users/sarannya/Projects/FreshChatiOS/iOS/obj/iPhone/Debug/device-builds/iphone9.2-12.0/mtouch-cache/armv7/libHeltChatLib.dll.dylib'. Please file a bug report at http://bugzilla.xamarin.com (MT5216) (FreshChatiOS.iOS)

**Comment by SotoiGhost** [comment]
Hi @mpsarannyaCharu!

Can you, please, file this issue on [Xamarin Mac iOS repo][1]?

There they can give better assistance. This repo is only for Google and Firebase components issues related.

Very sorry for the inconveniences.

Greetings!
Israel Soto.

[1]: https://github.com/xamarin/xamarin-macios/issues/new
