### ISSUE TITLE
How to report System.Exception using iOS Crashlytics?

### ISSUE THREAD

**Issue by rihadavid** [xamarin/GoogleApisForiOSComponents#231]
There is `Crashlytics.SharedInstance.RecordCustomExceptionName()` and `Crashlytics.SharedInstance.RecordError()` but none of them is accepting `System.Exception`. What if I want to manually report a `System.Exception`, with the message, stacktrace etc.? Is it possible or not?

I did not find any docs for the Xamarin.iOS Crashlytics Nuget, so I'm asking here.

**Comment by SotoiGhost** [comment]
Hi @rihadavid! You'll need to wrap the exception with an `NSError` and use the `RecordError` method or by wrapping it with a `StackFrame` array and using the `RecordCustomExceptionName` method. There isn't a method that receives the exception directly and does this for you. [Here][1]'s an example of how you can use the `RecordError` method.

Hope this helps you.

Best!
Israel Soto

[1]: https://github.com/xamarin/GoogleApisForiOSComponents/blob/master/Firebase.Crashlytics/component/GettingStarted.md#log-non-fatal-exceptions

**Comment by qmark** [comment]
@SotoiGhost could you please update the link to the example? Or is there any other info how to use `System.Exception` with `RecordError`?

**Comment by SotoiGhost** [comment]
@qmark Here's the updated link to Crashlytics doc. Hope it helps you. Best!

https://github.com/xamarin/GoogleApisForiOSComponents/blob/master/docs/Firebase/Crashlytics/GettingStarted.md#log-non-fatal-exceptions

**Comment by divyesh008** [comment]
I have got this done using:
```
public static void CreateCrashReport(Exception ex, string extra = null)
{
      var crashInfo = new Dictionary<object, object>
      {
            [NSError.LocalizedDescriptionKey] = ex.Message,
            ["StackTrace"] = ex.StackTrace,
      };
      var error = new NSError(new NSString(ex.Message),
           -1001,
           NSDictionary.FromObjectsAndKeys(crashInfo.Values.ToArray(), crashInfo.Keys.ToArray(), crashInfo.Keys.Count));
           Crashlytics.SharedInstance.RecordError(error);
}
```
