### ISSUE TITLE
'Xamarin.Firebase.MLKit.Common' dependency does not exist for 'Xamarin.Firebase.iOS.MLKit'

### ISSUE THREAD

**Issue by MDThomsen** [xamarin/GoogleApisForiOSComponents#233]
Should it not be 'Xamarin.Firebase.iOS.MLKit.Common' instead of 'Xamarin.Firebase.MLKit.Common'?
https://www.nuget.org/packages/Xamarin.Firebase.iOS.MLKit/

**Comment by SotoiGhost** [comment]
@MDThomsen This is fixed in PR #229

**Comment by jessejiang0214** [comment]
@SotoiGhost  When can we get the new nuget?

**Comment by jessejiang0214** [comment]
Hi @SotoiGhost , I check out your branch and build nugets. They're build successfully, but I cannot build them in a demo project, Like I create a new empty build and use these nugets as references. It can be install, but cannot build.
