### ISSUE TITLE
Nugget Xamarin.Firebase.iOS.MLKit

### ISSUE THREAD

**Issue by lilleydn** [xamarin/GoogleApisForiOSComponents#235]
GoogleApisForiOSComponents/Firebase.MLKit/nuget/Xamarin.Firebase.iOS.MLKit.nuspec

I cannot use the nugget as it cannot resolve a dependency

        <dependency id="Xamarin.Build.Download" version="0.4.11" />
        <dependency id="Xamarin.Firebase.MLKit.Common" version="0.13.0.0" />
        <dependency id="Xamarin.Firebase.iOS.Core" version="5.1.8.0" />

It should be Xamarin.Firebase.iOS.MLKit.Common

**Comment by qprotex** [comment]
I got the same issue. There is a typo in the dependency name.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1101	Unable to find package Xamarin.Firebase.MLKit.Common. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
```

**Comment by unamed000** [comment]
I have the same issue. Do you know how can i get the version 0.13.1 ?

**Comment by SotoiGhost** [comment]
Hi guys! Just letting you know that the fix has been published.
