### ISSUE TITLE
Xamarin.Firebase.MLKit.Common cannot be built

### ISSUE THREAD

**Issue by jessejiang0214** [xamarin/GoogleApisForiOSComponents#237]
I try to use Xamarin.Firebase.iOS.MLKit, but I found the dependency issue on that nuget. Then, I just want to inst MLKit.Common first.
I can install it, but I get build error 
```
      clang : error : linker command failed with exit code 1 (use -v to see invocation)
MTOUCH : error MT5210: Native linking failed, undefined symbol: _FIRLogBasic. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _kFIRLoggerMLKit. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5201: Native linking failed. Please review the build log and the user flags provided to gcc: -ObjC -lc++ -lsqlite3 -lz -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/jesse/Documents/Project/SmartElements/SmartElements.iOS/obj/iPhoneSimulator/Debug/device-builds/iphone11.4-12.1/Entitlements.xcent
MTOUCH : error MT5202: Native linking failed. Please review the build log.
    11 Warning(s)
```

I try to follow up the solution clean cache in this issue https://github.com/xamarin/GoogleApisForiOSComponents/issues/158
It still not work.
Please help us to fix this issue. 
Thanks

**Comment by SotoiGhost** [comment]
@jessejiang0214 Just letting you know that the fix has been published.

**Comment by jessejiang0214** [comment]
@SotoiGhost  brilliant!!!, Thanks very much.
Just a quick question, do you know what time Xamarin.Firebase.ML.Vision release or pre-release? Cause we need the same solution for Android.
I create a issue for this https://github.com/xamarin/GooglePlayServicesComponents/issues/180

Would you please give me some ETA about that?
