### ISSUE TITLE
Google.MobileAds v7.38

### ISSUE THREAD

**Issue by mitian** [xamarin/GoogleApisForiOSComponents#240]
Hello,

I am trying to use Google.MobileAds v7.32 from nuget for reward videos. But so far haven't been successful in rendering ad on real device with test ad unit Id. But on simulator it's working fine. So my question over here is that would I need to update Google.MobileAd version from 7.32 to 7.38 in order to resolve this issue and when are we expecting this version to be made live from beta.

**Comment by thisisthekap** [comment]
@mitian The new nuget is available in the feed.

**Comment by SotoiGhost** [comment]
Just letting you know that the update has been released to NuGet.

Best!
Israel Soto.
