### ISSUE TITLE
Native Linking Failed

### ISSUE THREAD

**Issue by MorneZaayman** [xamarin/GoogleApisForiOSComponents#241]
Related to https://github.com/xamarin/GoogleApisForiOSComponents/issues/158

The issue is still occurring when adding ARMv7 or ARMv7s to the supported architectures.

**Comment by thisisthekap** [comment]
@MorneZaayman Have you tried to ensure proper linking as suggested in https://github.com/xamarin/GoogleApisForiOSComponents/issues/158#issuecomment-448682798?

We did so by just adding this line to our application startup:
`Console.WriteLine(Firebase.Core.Configuration.SharedInstance);`

**Comment by SotoiGhost** [comment]
In addition to what @thisisthekap said, can you share the stack trace that you get and the NuGets involved, also, a test case would be much appreciated. Thanks in advance!

**Comment by vjlomocso** [comment]
I have a similar issue with google maps.
`MTOUCH : warning MT1302: Could not extract the native library 'GoogleMaps'`

we downloaded and modified the source code directly from
https://github.com/amay077/Xamarin.Forms.GoogleMaps

We didn't package it with nuget. We included the project files in our solution

**Comment by SotoiGhost** [comment]
@vjlomocso please, double check that Xamarin.Build.Download NuGet package was restored correctly.

**Comment by vjlomocso** [comment]
@SotoiGhost Yes I did that and before that I also deleted the bin and obj directories and it didn't fix it.

Now I fixed it by creating a new project and adding all the files of the old project into the new project. Lazy fix that didn't really pinpoint the problem but it worked.

**Comment by SotoiGhost** [comment]
Closing this issue now since no response was received from the owner of the issue.

If anyone faces something related to this, please, open a new issue. Thanks in advance!

Best!
Israel Soto.
