### ISSUE TITLE
Unrecognized selector class error after updating to Xamarin.Google.iOS.Core 5.2.0

### ISSUE THREAD

**Issue by ashleypringle** [xamarin/GoogleApisForiOSComponents#245]
After updating Firebase.iOS.Core to 5.2.0 and Xamarin.Firebase.iOS.InstanceID to 3.4.0 our app began to fail to launch after building, giving this error:
```
+[FIRApp registerAsConfigurable:]: unrecognized selector sent to class 0x102f4a128
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[FIRApp registerAsConfigurable:]: unrecognized selector sent to class 0x102f4a128'
*** First throw call stack:
(0x1de5e5ea4 0x1dd7b5a50 0x1de503bbc 0x1de5eb7bc 0x1de5ed46c 0x1dd7b80c0 0x1dd7b9620 0x106252388 0x106264750 0x106263798 0x106263854 0x1062526a4 0x106257468 0x106251044)
libc++abi.dylib: terminating with uncaught exception of type NSException
Application terminated.
```
I couldn't find any instances of this error happening to anyone else and couldn't find a solution, so I reverted back to Xamarin.Firebase.iOS.Core to 5.1.8 and Xamarin.Firebase.iOS.InstanceID to 3.3.0, which  seems to have fixed the problem.

> VS bug [#801368](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/801368)

**Comment by andrew-nemtsev** [comment]
The same issue with Xamarin.Google.iOS.Core 5.2.0 this is a blocker

**Comment by SotoiGhost** [comment]
That internal method exists in v5.1.8 but not in v5.2.0, so maybe can be a cache problem. Can you remove the `bin` and `obj` folders and remove the XBD cache folder located at:

* **Mac**: _~/Library/Caches/XamarinBuildDownload_
* **Windows**: _%LocalAppData%\XamarinBuildDownloadCache_

and try again, please?

If it doesn't work, can you provide the Firebase NuGets involved in your project? Thanks in advance!

**Comment by andrew-nemtsev** [comment]
Deleted bin, obj, ~/Library/Caches/XamarinBuildDownload and result is the same: '+[FIRApp registerAsConfigurable:]: unrecognized selector sent to class 0x10751fc00'

Firebase packages used in project is:
Xamarin.Firebase.iOS.Auth.5.0.4.1
Xamarin.Firebase.iOS.Core.5.2.0
Xamarin.Firebase.iOS.InstanceID.3.4.0
Xamarin.Firebase.iOS.CloudMessaging.3.1.2
Xamarin.Firebase.iOS.Database.5.0.3
Xamarin.Firebase.iOS.Analytics.5.5.0
Xamarin.Firebase.iOS.ABTesting.2.0.0.2
Xamarin.Firebase.iOS.RemoteConfig.3.0.1

**Comment by ashleypringle** [comment]
Also deleted the bin, obj and ~/Library/Caches/XamarinBuildDownload folder, still receiving the same error.

Firebase packages:
Xamarin.Firebase.iOS.Auth.5.0.4.1
Xamarin.Firebase.iOS.Core.5.2.0
Xamarin.Firebase.iOS.InstanceID.3.4.0
Xamarin.Firebase.iOS.Analytics.5.5.0
Xamarin.Google.iOS.Core 3.1.0.1
Xamarin.Google.iOS.SignIn 4.4.0

Firebase packages after reverting packages to avoid the crash:
Xamarin.Firebase.iOS.Auth 5.0.4.1
Xamarin.Firebase.iOS.Core 5.1.8
Xamarin.Firebase.iOS.InstanceID 3.3.0
Xamarin.Firebase.iOS.Analytics 5.1.4.1
Xamarin.Google.iOS.Core 3.1.0.1
Xamarin.Google.iOS.SignIn 4.4.0

If you need any more info I'd be happy to provide it.

**Comment by SotoiGhost** [comment]
I can confirm that Auth, CloudMessaging and DynamicLinks use the missing selector internally. These components need to be updated. For now, please, downgrade to 5.1.8

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wolf81** [comment]
Same with Firebase ...

**Comment by Shaggy13spe** [comment]
This is still an issue today. Has there been any movement on this?

**Comment by apy534** [comment]
I was also facing the same issue.
I have traced the solution.
Add below lines in Info.plist file, close the solution, reopen and run again.

<key>NSAppTransportSecurity</key>  
 <dict>  
      <key>NSAllowsArbitraryLoads</key><true/>  
 </dict>

**Comment by Shaggy13spe** [comment]
> I was also facing the same issue.
> I have traced the solution.
> Add below lines in Info.plist file, close the solution, reopen and run again.
> 
> ```
> <key>NSAppTransportSecurity</key>  
>  <dict>  
>       <key>NSAllowsArbitraryLoads</key><true/>  
>  </dict>
> ```

Unfortunately, this did not work for me. Sticking with 5.1.8 for now.

**Comment by apy534** [comment]
@Shaggy13pe
If you have added plugin xamarin.firebase.ios.analytics, remove it and try again

**Comment by Shaggy13spe** [comment]
No I don’t have that. I have the Auth module, but that’s it.

**Comment by SotoiGhost** [comment]
Firebase v6.5.0 has been pushed, this update resolves missing symbols.
