### ISSUE TITLE
[Firebase.CloudMessaging] Error while reading embedded mobileprovision

### ISSUE THREAD

**Issue by ihpedn** [xamarin/GoogleApisForiOSComponents#246]
Hi,

I'm developing an app using Xamarin.Forms. 
I'm configuring the app to receive FCM Push Notifications. 

I built an .ipa with a distribution certificate and a App Store provisioning profile, and upload it to the AppStore.  Since is not published in production, I'm using the app with TestFlight and seeing the 
logs in the device with the Console tool from Xcode. Also, I've already uploaded the .p8 in firebase to send the notifications (which I'm sure is correct because the same p8 is used in other apps).

I'm getting correctly the FCM Token in the `DidReceiveRegistrationToken` function, so it seems that at least that part is working correctly. But when I send a notification with the notification composer in the Firebase console, no notification is received in the app (nor anything appears in the device console). 

When the app launches, in the console there's the following error which I suppose might have something to do with my problem:
> 5.8.0 - [Firebase/InstanceID][I-IID003014] Error while reading embedded mobileprovision Error Domain=NSCocoaErrorDomain Code=260 "The file “embedded.mobileprovision” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/var/containers/Bundle/Application/BAD7D12E-1044-4A5B-9E0C-81838615C074/MyApp.iOS.app/embedded.mobileprovision, NSUnderlyingError=0x283402df0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

That's weird. Just to be sure I changed the .ipa to .zip, unzipped it, and see the contents files. I can see all the files in the .ipa there and the embedded.mobileprovision file is there. I can even cat the file and see the entitlements and so on, or even use `security cms` tool to read it better.

I'm running out of ideas here... everything seems correctly. The file embedded.mobileprovision is in the .ipa uploaded to the AppStore (and then used in TestFlight).

Any hint?.. I double-checked everything.

Extra info:
- Using Xamarin.Firebase.iOS.CloudMessaging 3.1.2. And that's the only Nuget besides Xamarin.Forms. So it shouldn't be any dependency conflict.
- I tried deleing `bin` and `obj`
- XCode is 10.1
- Visual Studio for Mac is the latest version.
- Tried also the previous version of XAmarin.Firebase.iOS.CloudMessaging (3.0.3)

**Comment by ihpedn** [comment]
Just an update of this problem.

I wasn't receiving notifications not because of this problem (which still persist and might be reasonable to understand why because maybe is the starting point for another problem in the future).

When the app was restarted, the app could receive notifications.

So why?:
I was implementing `FinishedLaunching` in `AppDelegate.cs` as mentioned in Getting Started documentation. But I think there's a problem there... it seems that the first time since the user hasn't still granted permission for push notifications, the `RegisterForRemoteNotifications` fails.
When the app restarts and `FinishedLaunching` fires again, since the app has the permission, `RegisterForRemoteNotifications` doesn't fail.

The real solution is to do the following in the handler of  `RequestAuthorization`:
```
if(granted)
{
   DispatchQueue.MainQueue.DispatchAsync(() => UIApplication.SharedApplication.RegisterForRemoteNotifications());
}
```
Maybe it may be a good idea to update the example.

**Comment by SotoiGhost** [comment]
@ihpedn With the solution provided, was the issue fixed?

**Comment by SotoiGhost** [comment]
Closing this issue now since no response was received from the owner of the issue.

If anyone faces something related to this, please, open a new issue. Best!
