### ISSUE TITLE
Xamarin.Firebase.iOS.CloudMessaging 3.1.2 issue

### ISSUE THREAD

**Issue by VistianOpenSource** [xamarin/GoogleApisForiOSComponents#248]
There would appear to be an issue with this nuget package (or perhaps one of its dependencies).

In a brand new Visual Studio 2019 Windows RC application with a default Notification Service Extension in the same solution I've installed this nuget package against the application.

If I don't reference the NSE from the application , the application can build and deploy correctly, if however I do reference the extension, I get the following error and warning 

```
Error |   | "ditto" exited with code 1. | Vistian Push Experiment | C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets | 1624 |  
Warning |   | Could not resolve reference "C:\Users\jamie\AppData\Local\XamarinBuildDownloadCache\FInstncID-3.2.1\Frameworks\FirebaseInstanceID.framework". If this reference is required by your code, you may get compilation errors. | Vistian Push Experiment | C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets | 2010 |  
```

If i dig into the detailed build output I see this 

```
2>  /usr/bin/ditto -rsrc ../../VistianPushExperimentNSE/28a99f1d642fa3dbe8fd4bb67286f587/bin/iPhone/Debug/Vistian_Push_Experiment_NSE.appex "bin/iPhone/Debug/Vistian Push Experiment.app/PlugIns/Vistian_Push_Experiment_NSE.appex" 
2>  ditto: can't get real path for source '../../VistianPushExperimentNSE/28a99f1d642fa3dbe8fd4bb67286f587/bin/iPhone/Debug/Vistian_Push_Experiment_NSE.appex'
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(1624,3): error MSB6006: "ditto" exited with code 1.
2>  Ditto: 2019-03-04T15:01:35.5186617+00:00 - Finished
2>Done executing task "Ditto" -- FAILED.


.
.
.

2>  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2010,5): warning MSB3341: Could not resolve reference "C:\Users\jamie\AppData\Local\XamarinBuildDownloadCache\FInstncID-3.2.1\Frameworks\FirebaseInstanceID.framework". If this reference is required by your code, you may get compilation errors.
2>

```

If I try the OSX version of Visual Studio 2019 (8.0 Preview (8.0 build 1805)) i can successfully build and deploy this solution.

It should also be noted that I go for a far older version of the iOS Messaging nuget 2.8.0.1 then this too can build and deploy successfully on Windows.

> VS bug [#823852](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/823852)

**Comment by SotoiGhost** [comment]
@VistianOpenSource Can you provide a test case, please? Thanks in advance!

**Comment by VistianOpenSource** [comment]
Try this https://1drv.ms/u/s!AgLeegBmXYAqu4ZIT6XfbHZ9922PIA - brand new solution with current preview version of VS.NET 2019 and 3.1.2 version of CloudMessaging. Application won't build.

**Comment by SotoiGhost** [comment]
@VistianOpenSource for some reason I cannot work with the test case provided with VS 2017 or VS 2019. Even if I remove or add the Cloud Messaging NuGet, the IntelliSense and compiler don't detect the Firebase namespace or any change.

I created a brand new solution and replicated your test case using VS 2017 and I could repro the issue even without Cloud Messaging NuGet referenced.

I did the same with VS 2019 and the test case worked without a problem. Can you try this test case and share your results?

[NSETestWithPreview.zip](https://github.com/xamarin/GoogleApisForiOSComponents/files/2986627/NSETestWithPreview.zip)

Here's my environment info:

<details>
<summary>Environment Info</summary>

```
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.0.0 Preview 4.3
VisualStudio.16.Preview/16.0.0-pre.4.3+28714.193
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Enterprise

Mono Debugging for Visual Studio   16.0.300 (573eda3)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Xamarin   16.0.0.513 (d16-0@aebc6bdb5)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android SDK   9.2.0.5 (HEAD/292d27fa)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2018-08-rc@5ad371dab1b
    Java.Interop: xamarin/java.interop/d16-0@c987483
    LibZipSharp: grendello/LibZipSharp/master@44de300
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    MXE: xamarin/mxe/xamarin@b9cbb535
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.26.0@325e91a
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-0@0a7edd6

Xamarin.iOS and Xamarin.Mac SDK   12.6.0.23 (ad57f87)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

**Comment by VistianOpenSource** [comment]
Hi, Tried your test app. However, the main app didn't reference the notification service extension project. Once it does you then get build errors. 

2>    Bundle Id: com.companyname.NSETestWithPreview.MyNSEWithPreview
2>    App Id: 99Y7B5P2A2.com.companyname.NSETestWithPreview.MyNSEWithPreview
2>  /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/jamiemutton/Library/Caches/Xamarin/mtbs/builds/NSETestWithPreview/5e9d40081a0a8e57e822d729aa3884c8/obj/iPhone/Debug/response-file.rsp --gcc_flags=-ObjC 
2>  /usr/bin/ditto -rsrc ../../MyNSEWithPreview/e381df0d7642665f982a45864b5f6f4f/bin/iPhone/Debug/MyNSEWithPreview.appex bin/iPhone/Debug/NSETestWithPreview.app/PlugIns/MyNSEWithPreview.appex 
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(1624,3): error MSB6006: "ditto" exited with code 1.

**Comment by SotoiGhost** [comment]
@VistianOpenSource The issue happens due to a mismatch configuration between the iOS app project and the NSE project. If you have the `Enable device-specific builds` option checked in one project and disabled in the other one, the issue appears. The workaround for now is to have enabled or disabled the `Enable device-specific builds` option in all projects.

You can find this option in the properties of the project -> iOS Build

This has been escalated to the Visual Studio team.

Thanks for letting us know this!

Also, please, use the exact version of **Xamarin.Firebase.iOS.Core** specified in the **Xamarin.Firebase.iOS.CloudMessaging** NuGet, if you upgrade the **Xamarin.Firebase.iOS.Core** to most recent version, you will face a runtime error. You can learn more about this on issue #245.

Best!
Israel Soto.
