### ISSUE TITLE
Error sending push notifications Firebase.

### ISSUE THREAD

**Issue by MATAUDI** [xamarin/GoogleApisForiOSComponents#256]
Hello, good afternoon.
Develop an application so that users can receive notifications of some offer, the problem is that in "production" mode is not working, does not register to the topic, nor does it receive notificaicones if I test from firebase.
What can be the problem?, only happens to me on the platform IOS.
I Have the latest version downloaded from the plugin.
Thanks a lot.

**Comment by cerdocervecero** [comment]
i have same problem, help!

**Comment by SotoiGhost** [comment]
Hi @MATAUDI, this can happen for multiple reasons. Can you provide a test case, so, I could give you better support? Thanks in advance!

**Comment by MATAUDI** [comment]
Hi @SotoiGhost, What I do is test the app in Ad-Hoc mode with a topic and it works perfect. 
I understand that the mode "Ad-Hoc " simulates being  "Production ".
Once I upload the app in the App Store, it stops registering on the topic and does not receive notifications. Probe with send a message from the Firebase console by topic and by application and neither of the two forms works.
When I test the "Ad-Hoc " mode with the file  "Entitlements. plist " In development and register the Apns in production mode it works perfect. 
When I change the file  "Entitlements. plist " to production to upload to the App store it doesn't work anymore.
I Have the latest updates of the plugin firebase.
Thank you so Much for the help.
