### ISSUE TITLE
Google maps iOS SDK: incorrect marker rendering

### ISSUE THREAD

**Issue by Smoke1987** [xamarin/GoogleApisForiOSComponents#259]
When creating a Google Map Controller, and then when using it as a child controller, the marker is drawn incorrectly. And more specifically, then:
1) create a controller (parent)
2) this controller has a view with frame with an upper indent of 64 (any value)
`View.frame = ((0, 64), (width, height))`
3) create a controller with google maps
4) create mapview 
`mapView = new MapView(new CGRect(0, 0, parentView.Frame.Width, parentView.Frame.Height))`
5) add a controller with google maps to the parent
`parentController.AddChildViewController(googleMapsViewController)`
6) add a view of google maps to the parent controller
`parentController.Add(mapView)`
`parentView.AddConstraints(mapView.FullSizeOf(parentView))`
7) inside the controller with google maps initiate display a marker
```
var mapCenter = new CGPoint(mapView.Center.X, mapView.Center.Y);
var mapCenterCoordinate = mapView.Projection.CoordinateForPoint(mapCenter);

var googleMarker = new Marker()
            {
                Title = "title",
                Snippet = "someText",
                Position = mapCenterCoordinate,
                Icon = ...someImage,
                Tappable = true,
                Map = mapView
            };
```
8) the marker is displayed incorrectly (empirically found that the readout of the Y coordinate comes from 0 and not from 64 as expected)

When creating a mapview with a frame with an upper indent of 64, the marker is drawn correctly, but then inside the map delegate the position definition is shifted along the Y axis by the same 64 points.

**Comment by Smoke1987** [comment]
An example application that demonstrates the unexpected behavior of the marker is prepared. Thank.

**Comment by SotoiGhost** [comment]
@Smoke1987 Can you share the test case, please? Thanks in advance!

**Comment by Smoke1987** [comment]
Solved. The problem was in the marker image, which is offset in the visible part of the icon ...
