### ISSUE TITLE
Please upgrade to Google SignIn 4.0 on iOS

### ISSUE THREAD

**Issue by salqadri** [xamarin/GoogleApisForiOSComponents#26]
This component currently uses 3.0 for iOS. But 4.0 is already out. Can we please upgrade this component?

**Comment by SotoiGhost** [comment]
We are working on this. Google.SignIn depends on Google.Core but now Google.Core depends on Firebase.Analytics and Firebase.InstanceId. We are working on Firebase iOS components.

In this repo there is available an update of SignIn. You can build it by yourself for now and test it but this could not be the final version of the component. If you find anything wrong with the library, you can file an issue in my repo.

https://github.com/SotoiGhost/GoogleApisForiOSComponents/tree/firebase

Greetings,
Israel Soto.
