### ISSUE TITLE
Google Cast - castStyle.castViews missing 

### ISSUE THREAD

**Issue by dationguyen** [xamarin/GoogleApisForiOSComponents#260]
Reopen issue #122

> VS bug [#843261](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/843261)

**Comment by dationguyen** [comment]
@SotoiGhost , Is there any update on this?
i tried to uncomment and create a custom build but it cause some linker error 

 Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_GCKUIStyleAttributesCastViews", referenced from:
          objc-class-ref in registrar.o
      "_OBJC_CLASS_$_GCKUIStyleAttributesConnectionController", referenced from:
          objc-class-ref in registrar.o
      "_OBJC_CLASS_$_GCKUIStyleAttributesDeviceChooser", referenced from:
          objc-class-ref in registrar.o
      "_OBJC_CLASS_$_GCKUIStyleAttributesDeviceControl", referenced from:
          objc-class-ref in registrar.o
      "_OBJC_CLASS_$_GCKUIStyleAttributesExpandedController", referenced from:
          objc-class-ref in registrar.o
      "_OBJC_CLASS_$_GCKUIStyleAttributesGuestModePairingDialog", referenced from:
          objc-class-ref in registrar.o
      "_OBJC_CLASS_$_GCKUIStyleAttributesInstructions", referenced from:
          objc-class-ref in registrar.o
      "_OBJC_CLASS_$_GCKUIStyleAttributesMediaControl", referenced from:
          objc-class-ref in registrar.o
      "_OBJC_CLASS_$_GCKUIStyleAttributesMiniController", referenced from:
          objc-class-ref in registrar.o
      "_OBJC_CLASS_$_GCKUIStyleAttributesTrackSelector", referenced from:
          objc-class-ref in registrar.o
    ld: symbol(s) not found for architecture arm64

**Comment by SotoiGhost** [comment]
@dationguyen Google changed those symbols visibility from `external` to `private external` making impossible to us to bind these classes, this is why we commented them. I filed a bug to Google and they already changed the visibility again to `external`. The component needs an update to `4.3.5`

**Comment by dationguyen** [comment]
Cool, Thanks @SotoiGhost

**Comment by SotoiGhost** [comment]
@dationguyen Google Cast v4.4.2 is live now on NuGet. Hope this helps you. Best!
