### ISSUE TITLE
error MT5210: Native linking failed, undefined symbol

### ISSUE THREAD

**Issue by zoli13** [xamarin/GoogleApisForiOSComponents#261]
I have a Xamarin Forms (3.6.0.220655) App , which runs fine on Android + iOS both.
I wanted to add Google Ad support to it, so installed Xamarin.Firebase.iOS.AdMob 7.38 to my iOS project via nuget in VS 2019.

Then I build:

**6 Warnings:**

`warning MSB3341: Could not resolve reference "D:\Users\Zoli\AppData\Local\XamarinBuildDownloadCache\FAdM-7.38.0\Frameworks\frameworks\GoogleMobileAds.framework". If this reference is required by your code, you may get compilation errors. `

**And 1 error:**

`error XBD001: Download failed. Please download https://github.com/googleads/googleads-consent-sdk-ios/archive/v1.0.3.zip to a file called D:\Users\Zoli\AppData\Local\XamarinBuildDownloadCache\GCnsnt-1.0.3.zip.`

**See attached build_1.txt for details.**
[build_1.txt](https://github.com/xamarin/GoogleApisForiOSComponents/files/3049013/build_1.txt)

So I manually downloaded the v1.0.3.zip and copied to GCnsnt-1.0.3.zip to fix the error.
Then restart build.

And I have same 6 **warnings** (see above), and lots of linker **errors** like this:

`2>C:\Program Files (x86)\Visual Studio 2019 Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(794,3): error MT5210: Native linking failed, undefined symbol: _FIRLogBasic. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
2>C:\Program Files (x86)\Visual Studio 2019 Community\MSBuild\Xamarin`

**See attached build_2.txt for details.**
[build_2.txt](https://github.com/xamarin/GoogleApisForiOSComponents/files/3049014/build_2.txt)

I tried deleting the Mac /Users/<user>/Library/Caches/Xamarin/mtbs/build/<$PROJECT> folder.
Deleted Win /Users/<user>/Appdata/Local/XamarinBuildDownloadCache
Deleted Win /Users/<user>/.nuget/packages/xamarin.firebase.ios.* folders
Cleaned project/rebuild.

Nothing helped.

**VS2019 Windows System info:**
see System_win.txt
[System_win.txt](https://github.com/xamarin/GoogleApisForiOSComponents/files/3049016/System_win.txt)

**VS2019 System MAC:**
see System_mac.txt
[System_mac.txt](https://github.com/xamarin/GoogleApisForiOSComponents/files/3049015/System_mac.txt)

**Comment by dationguyen** [comment]
you may want to update Xamarin.Firebase.Ios.Core to 5.2.0

**Comment by zoli13** [comment]
I don't know that one, I searched for Xamarin.Firebase.iOS.AdMob in nuget, installed, it downloaded all dependency for itself ( I expect the proper ones). Then tried to compile - which failed.
Note, reading your [steps:](https://github.com/xamarin/GoogleApisForiOSComponents/blob/master/Firebase.AdMob/component/GettingStarted.md) , I did not do "Add Firebase to your app" section (ie: downloading GoogleService-Info.plist, etc). Can that be the issue? I thought it's just like any other nuget package, download and build.
I removed, installed Xamarin.Google.iOS.MobileAds - that works just as expected, right immediately without any linker errors.

**Comment by SotoiGhost** [comment]
@zoli13 The first warnings and error refer that Xamarin.Build.Download NuGet package was not restored correctly or XBD failed when downloading the bits.

The second errors are related to what you said. If you don't want to use Firebase, please, just install the MobileAds NuGet. This must be added to docs.
