### ISSUE TITLE
Incremental build breaks Analytics custom events and user properties

### ISSUE THREAD

**Issue by ngraef** [xamarin/GoogleApisForiOSComponents#263]
### Environment
- macOS 10.14.4
- Visual Studio Mac 8.0.2

### Setup
- In Visual Studio Mac, create a new solution and select iOS Single View App
- Install Xamarin.Firebase.iOS.Analytics NuGet package
- Add GoogleService-Info.plist to solution and set BuildAction to `BundleResource`
- In `AppDelegate.cs#FinishedLaunching` add:

  ```csharp
  Firebase.Core.App.Configure();
  Firebase.Analytics.Analytics.SetUserProperty("123", "my_session_id");
  ```

- In `ViewController.cs#ViewDidLoad` add:

  ```csharp
  Firebase.Analytics.Analytics.LogEvent("main_page_view", new NSDictionary<NSString, NSObject> { });
  ```

- In iOS Build options, select "Enable incremental builds"
- [Enable Firebase debug mode](https://github.com/xamarin/GoogleApisForiOSComponents/blob/master/Firebase.Analytics/component/GettingStarted.md#enabling-debug-mode)
- Build solution and run on a device

### Error
The Firebase Console DebugView shows the automatic `screen_view` event, but not the custom `my_session_id` user property or `main_page_view` event. The device logs show the following:

```
13:46:16.882154 -0500	AnalyticsDebugTest	5.16.0 - [Firebase/Core][I-COR000005] No app has been configured yet.
13:46:16.882205 -0500	AnalyticsDebugTest	5.16.0 - [Firebase/Core][I-COR000005] No app has been configured yet.
13:46:16.887838 -0500	AnalyticsDebugTest	5.16.0 - [Firebase/Analytics][I-ACS025019] User property not set. Call +[FIRApp configure]: my_session_id
13:46:16.937945 -0500	AnalyticsDebugTest	5.16.0 - [Firebase/Analytics][I-ACS025018] Event not logged. Call +[FIRApp configure]: main_page_view
13:46:16.938441 -0500	AnalyticsDebugTest	5.16.0 - [Firebase/Analytics][I-ACS023007] Analytics v.50500000 started
13:46:16.938514 -0500	AnalyticsDebugTest	5.16.0 - [Firebase/Analytics][I-ACS023008] To disable debug logging set the following application argument: -noFIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
13:46:17.043914 -0500	AnalyticsDebugTest	5.16.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
13:46:17.086182 -0500	AnalyticsDebugTest	5.16.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
```

## Workaround
- Deselect "Enable incremental builds", rebuild and run

The `my_session_id` user property and `main_page_view` event are observable in the Firebase Console DebugView, and the device logs show the following:

```
13:58:30.903740 -0500	AnalyticsDebugTest	5.16.0 - [Firebase/Analytics][I-ACS023007] Analytics v.50500000 started
13:58:30.903844 -0500	AnalyticsDebugTest	5.16.0 - [Firebase/Analytics][I-ACS023008] To disable debug logging set the following application argument: -noFIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
```

**Comment by SotoiGhost** [comment]
Is this still an issue?

**Comment by SotoiGhost** [comment]
We have not received the requested information. If you are still experiencing this issue, please, open a new issue related to this. Thanks!
