### ISSUE TITLE
UserInfo data is an empty In DidReceiveNotificationResponse ?

### ISSUE THREAD

**Issue by Nandulucky** [xamarin/GoogleApisForiOSComponents#265]
Thanks for your code but I received notifications but handling notifications means when tap the notification called "DidReceiveNotificationResponse" method I'm using below code like,
`var userInfo = response.Notification.Request.Content.UserInfo;`
But I received UserInfo as empty.

Can you please check it once 

Thanks
Nandu K

**Comment by SotoiGhost** [comment]
Is this still an issue?

**Comment by SotoiGhost** [comment]
We have not received the requested information. If you are still experiencing this issue, please, open a new issue related to this. Thanks!

**Comment by Nandulucky** [comment]
Thanks mate ... resolved my issue
