### ISSUE TITLE
Push notification issues on IOS started when GCM was switched off last week

### ISSUE THREAD

**Issue by raymondjstone** [xamarin/GoogleApisForiOSComponents#266]
We have an existing app, on the IOS only version of it push notiifcations sent by topic started to not arrive when they should. Tracing this back it seems to relate to a cross platform plugin which uses this library to subscribe to topics not ending up with the subscriptions changing at all despite making the correct calls to the subscribe method withiin FireBase.CloudMessaging. 

Can't be 100% sure but this seems to have started around the time that the GCM endpoints were due to be switched off (12th April), obviouslly this should be using FCM endpoints and was fine until that date we believe but with preinistalled apps starting to fail at the same time as new builds this seems to be the only consistent factor.

Using Xamarin 3.6 (but old installs were built on 3.4)
<package id="Xamarin.Firebase.iOS.Analytics" version="5.5.0" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.CloudMessaging" version="3.1.2" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.Core" version="5.2.0" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.InstanceID" version="3.4.0" targetFramework="xamarinios10" />

**Comment by SotoiGhost** [comment]
Is this still an issue?

**Comment by raymondjstone** [comment]
I no longer work at the place having the issue. but it was 'resolved', it was something to do with the example code setting the list of topics at the wrong point and the code needed tweaked a little to set the list of subscribed topics at a slightly different point otherwise the list internally was being set incorrectly

**Comment by SotoiGhost** [comment]
@raymondjstone Thanks for the info, since this seems to be resolved, I'm closing this now.
