### ISSUE TITLE
Framework not found FIRAnalyticsConnector

### ISSUE THREAD

**Issue by baronchng** [xamarin/GoogleApisForiOSComponents#268]
I am running Visual Studio for Mac v 8.0.4 (build 0).
When I try to build after updating Firebase Analytics to v5.5.0, it shows the error below:
It was fine when I was still using v4.0.5.

/Users/user/Projects/PewPom/PewPom.iOS/clang: Error: linker command failed with exit code 1 (use -v to see invocation) (PewPom.iOS)
/Users/user/Projects/PewPom/PewPom.iOS/error MT5209: Error: framework not found FIRAnalyticsConnector (PewPom.iOS) Native linking
/Users/user/Projects/PewPom/PewPom.iOS/MTOUCH: Error MT5201: Native linking failed. Please review the build log and the user flags provided to gcc: -ObjC -lc++ -lz -ObjC -ObjC -ObjC -lc++ -lsqlite3 -lz -ObjC -lc++ -lsqlite3 -lz -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/user/Projects/PewPom/PewPom.iOS/obj/iPhoneSimulator/Debug/device-builds/iphone11.4-12.2/Entitlements.xcent (MT5201) (PewPom.iOS)
/Users/user/Projects/PewPom/PewPom.iOS/MTOUCH: Error MT5202: Native linking failed. Please review the build log. (MT5202) (PewPom.iOS)

Can anyone help on this matter? Thanks guys!

**Comment by stepanic** [comment]
I have the same issue this is the installed on the system:

`Visual Studio Community 2019 for Mac
Version 8.1.3 (build 19)
Installation UUID: 05a355ff-ef92-4a8f-a462-4e0472190e89
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.25 (d16-0 / 50f75273)

	Package version: 518010028

Mono Framework MDK
Runtime:
	Mono 5.18.1.28 (2018-08/223ea7ef92e) (64-bit)
	Package version: 518010028

NuGet
Version: 5.0.2.5988

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.11
	2.1.9
	2.1.2
	2.1.1
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.700/Sdks
SDK Versions:
	2.1.700
	2.1.505
	2.1.302
	2.1.301
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/Current/bin/Sdks

Xamarin.Profiler
Version: 1.6.10
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 9.3.0.23 (Visual Studio Community)
Commit: HEAD/d0b48056f
Android SDK: /Users/matijastepanic/Library/Developer/Xamarin/android-sdk-mac_x86
	Supported Android versions:
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.1
SDK Build Tools Version: 29.0.0

Build Information: 
Mono: mono/mono/2018-08@3a07bd426d3
Java.Interop: xamarin/java.interop/d16-1@5ddc3e3
LibZipSharp: grendello/LibZipSharp/d16-1@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-1@acabd26

Microsoft Mobile OpenJDK
Java SDK: /Users/matijastepanic/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android Device Manager
Version: 1.2.0.44
Hash: aac645b
Branch: remotes/origin/d16-1
Build date: 2019-05-29 19:55:24 UTC

Apple Developer Tools
Xcode 10.2.1 (14490.122)
Build 10E1001

Xamarin.Mac
Version: 5.10.0.157 (Visual Studio Community)
Hash: 6bd94753
Branch: d16-1
Build date: 2019-06-12 17:28:48-0400

Xamarin.iOS
Version: 12.10.0.157 (Visual Studio Community)
Hash: 6bd94753
Branch: d16-1
Build date: 2019-06-12 17:28:47-0400

Xamarin Designer
Version: 16.1.0.467
Hash: f1657e133
Branch: remotes/origin/d16-1-new-document-model
Build date: 2019-06-18 21:57:42 UTC

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 801030019
Git revision: 2d04b0145da8aa946d2cc9898fe2a59484e4f3f4
Build date: 2019-06-26 15:34:25+00
Build branch: release-8.1
Xamarin extensions: de240bddd6d1f96bfb1e7d11ce7ac5398956fe1d

Operating System
Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
    Sun Mar 31 23:13:18 PDT 2019
    root:xnu-4903.260.74~12/RELEASE_X86_64 x86_64

Enabled user installed extensions
MFractor 3.8.9
Prism Template Studio and Developer Toolkit 2.2.0.434
`

Xcode 10.2.1

Everything works on the same other Macbook Pro Mid 2014 with the same installed versions, I do not know how to fix?
I think this is the most strange issue I have ever got with the Xamarin.

**Comment by baronchng** [comment]
I totally forgot about this issue I created. I have recently solved this issue but I couldn't find the link again. 
This is based off my memories:

1. I deleted `~/Library/Caches/XamarinBuildDownload/`. This is very likely the step that solved the above issue.
2. I also deleted obj/ and bin/ from the project folder. This step did not help me but you can try.
3. I have these in the csproj. 
  ```
<Import Project="..\packages\Xamarin.Build.Download.0.4.11\build\Xamarin.Build.Download.targets" Condition="Exists('..\packages\Xamarin.Build.Download.0.4.11\build\Xamarin.Build.Download.targets')" />
  <Import Project="..\packages\Xamarin.Firebase.iOS.Crashlytics.3.10.9\build\Xamarin.Firebase.iOS.Crashlytics.targets" Condition="Exists('..\packages\Xamarin.Firebase.iOS.Crashlytics.3.10.9\build\Xamarin.Firebase.iOS.Crashlytics.targets')" />
  <Import Project="..\packages\Xamarin.Firebase.iOS.InstanceID.3.2.1\build\Xamarin.Firebase.iOS.InstanceID.targets" Condition="Exists('..\packages\Xamarin.Firebase.iOS.InstanceID.3.2.1\build\Xamarin.Firebase.iOS.InstanceID.targets')" />
  <Import Project="..\packages\Xamarin.Firebase.iOS.Analytics.5.1.4.1\build\Xamarin.Firebase.iOS.Analytics.targets" Condition="Exists('..\packages\Xamarin.Firebase.iOS.Analytics.5.1.4.1\build\Xamarin.Firebase.iOS.Analytics.targets')" />
  <Import Project="..\packages\Xamarin.Firebase.iOS.DynamicLinks.3.0.2.1\build\Xamarin.Firebase.iOS.DynamicLinks.targets" Condition="Exists('..\packages\Xamarin.Firebase.iOS.DynamicLinks.3.0.2.1\build\Xamarin.Firebase.iOS.DynamicLinks.targets')" />
```
4. These are the packages i used
```
<package id="Xamarin.Build.Download" version="0.4.11" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.Analytics" version="5.1.4.1" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.Auth" version="5.0.4.1" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.CloudMessaging" version="3.1.2" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.Core" version="5.1.3" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.Crashlytics" version="3.10.9" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.Database" version="5.0.3" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.DynamicLinks" version="3.0.2.1" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.InstanceID" version="3.2.1" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.Storage" version="3.0.2" targetFramework="xamarinios10" />
```

Hope it helps.

**Comment by stepanic** [comment]
Thank you @baronchng but I am not able to fix this issue, I have searched through every similar issue, but still the same issue.

<img width="1340" alt="Screenshot 2019-07-02 at 21 24 55" src="https://user-images.githubusercontent.com/315282/60540647-f6ab4300-9d0f-11e9-8935-a13f0857e4e6.png">

**Comment by baronchng** [comment]
You're welcome. What versions are you using for those Firebase packages? Perhaps that could shed some light on why is that problem happening to you.

By the way, this is mine:
```
Visual Studio Community 2019 for Mac
Version 8.1.2 (build 2)
Installation UUID: 489c234d-fa58-4969-ba25-1f69cb0f8d5a
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.25 (d16-0 / 50f75273)

	Package version: 518010028

Mono Framework MDK
Runtime:
	Mono 5.18.1.28 (2018-08/223ea7ef92e) (64-bit)
	Package version: 518010028

NuGet
Version: 5.0.2.5988

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.11
	2.1.9
	2.1.8
	2.1.2
	2.1.1
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.700/Sdks
SDK Versions:
	2.1.700
	2.1.505
	2.1.504
	2.1.302
	2.1.301
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/Current/bin/Sdks

Xamarin.Profiler
Version: 1.6.10
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 9.3.0.23 (Visual Studio Community)
Commit: HEAD/d0b48056f
Android SDK: /Users/chngbaron/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 27.0.3

Build Information: 
Mono: mono/mono/2018-08@3a07bd426d3
Java.Interop: xamarin/java.interop/d16-1@5ddc3e3
LibZipSharp: grendello/LibZipSharp/d16-1@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-1@acabd26

Microsoft Mobile OpenJDK
Java SDK: /Users/chngbaron/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android Device Manager
Version: 1.2.0.44
Hash: aac645b
Branch: remotes/origin/d16-1
Build date: 2019-05-29 19:55:24 UTC

Apple Developer Tools
Xcode 10.2.1 (14490.122)
Build 10E1001

Xamarin.Mac
Version: 5.10.0.157 (Visual Studio Community)
Hash: 6bd94753
Branch: d16-1
Build date: 2019-06-12 17:28:48-0400

Xamarin.iOS
Version: 12.10.0.157 (Visual Studio Community)
Hash: 6bd94753
Branch: d16-1
Build date: 2019-06-12 17:28:47-0400

Xamarin Designer
Version: 16.1.0.467
Hash: f1657e133
Branch: remotes/origin/d16-1-new-document-model
Build date: 2019-06-18 21:57:42 UTC

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 801020002
Git revision: 5d9e30e11e16dbb655977e4f7051ffedd3de9f94
Build date: 2019-06-24 20:05:44+00
Build branch: release-8.1
Xamarin extensions: 5104b76623e0df8e5f763f87d170279c0b788e89

Operating System
Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
    Thu Apr 25 23:16:27 PDT 2019
    root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

```

**Comment by stepanic** [comment]
@baronchng thank you, I finally solved with a fresh install of Visual Studio for Mac and Xcode but the key step is to delete `~/Library/Caches/XamarinBuildDownload/` but without deleting local `bin` and `obj` when I delete them then the same issue is there.
