### ISSUE TITLE
giving monotouch error M1201 if iset "Link all assebly" in xamarin ios, tried with --register:static argument passing in all configurations

### ISSUE THREAD

**Issue by asatya001** [xamarin/GoogleApisForiOSComponents#269]
giving monotouch error M1201 if iset "Link all assebly" in xamarin ios, tried with --register:static argument passing in all configurations

**Comment by SotoiGhost** [comment]
Is this still an issue?

**Comment by asatya001** [comment]
When I removed and installed updated package , it got resolved automatically, even no need to add perams
