### ISSUE TITLE
MTOUCH : error MT2101

### ISSUE THREAD

**Issue by Manne990** [xamarin/GoogleApisForiOSComponents#270]
When I use the latest Firebase Analytics nuget for iOS I get the following error from the hosted mac agent in Azure DevOps. Any idea why?

MTOUCH : error MT2101: Can't resolve the reference 'System.Void ObjCRuntime.Runtime::ReleaseBlockOnMainThread(System.IntPtr)', referenced from the method 'System.Void ObjCRuntime.Trampolines/NIDAppVoidBoolHandler::Finalize()' in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'. [/Users/vsts/agent/2.150.3/work/1/s/WellbeingMobile.iOS/WellbeingMobile.iOS.csproj]

**Comment by Manne990** [comment]
This is the build host in Azure DevOps used that is failing. https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md#xamarin

**Comment by Manne990** [comment]
It builds on my local environment, but not in Azure DevOps on the hosted mac. If I downgrade the NuGet package to version 5.1.4.1 it builds both locally and in Azure DevOps.

**Comment by SotoiGhost** [comment]
@Manne990 Is this still an issue?

**Comment by SotoiGhost** [comment]
We have not received the requested information. If you are still experiencing this issue, please, open a new issue related to this. Thanks!
