### ISSUE TITLE
why Xamarin.Firebase.iOS.DynamicLinks has Analitycs as dependency?

### ISSUE THREAD

**Issue by rayita** [xamarin/GoogleApisForiOSComponents#272]
why Xamarin.Firebase.iOS.DynamicLinks force me to install Xamarin.Firebase.iOS.Analytics even is I don't need/use analytics at all?
Android version has not this dependency.

**Comment by SotoiGhost** [comment]
@rayita Dynamic Links had Analytics as dependency due to the version at that moment, but now, Analytics is no longer needed as a dependency as has been removed. Closing this now.
