### ISSUE TITLE
why Xamarin.Firebase.iOS.RemoteConfig has Analitycs as a dependency?

### ISSUE THREAD

**Issue by rayita** [xamarin/GoogleApisForiOSComponents#274]
why Xamarin.Firebase.iOS.RemoteConfig force me to install Xamarin.Firebase.iOS.Analytics even if I don't need/use analytics at all?
Android equivalent has not this dependency.

**Comment by SotoiGhost** [comment]
Analytics has been removed in the most recent version. Closing this now.
