### ISSUE TITLE
Could not resolve FirebaseInstanceID.framework

### ISSUE THREAD

**Issue by devRoemer** [xamarin/GoogleApisForiOSComponents#277]
I have the same warning as described here:
https://github.com/xamarin/GoogleApisForiOSComponents/issues/248

Could not resolve reference "C:\Users\myprofile\AppData\Local\XamarinBuildDownloadCache\FInstncID-3.2.1\Frameworks\FirebaseInstanceID.framework"

The cache folder looks like this:
![image](https://user-images.githubusercontent.com/41320207/58938409-0a957080-8775-11e9-936d-f4f6c167a5e0.png)

Problem is that the described solution is not applicable in my case. In the ios project i have disabled device specific builds. In my xamarin forms project i cannot disable device specific builds because it is an .NET Standard 2.0 project that is referenced in the ios project.

The .NET Standard project has no reference to firebase. The iOS project has only referenced the nuget package "Xamarin.Firebase.iOS.CloudMessaging" in version 3.1.2.

A downgrade to Version 3.0.3 does not help - warning still appears.

If i downgrade further to version 2.0.8.1 the project does not even compile. But this is not desired anyways.

Do you have any Ideas?

**Comment by SotoiGhost** [comment]
Is this still an issue?

**Comment by devRoemer** [comment]
Meanwhile we updated our project to visual studio 2019 and xamarin forms 3.6. The mentioned warning still appears with this configuration.

**Comment by SotoiGhost** [comment]
Are you able to build and test your app?

**Comment by SotoiGhost** [comment]
We have not received the requested information. If you are still experiencing this issue, please, open a new issue related to this. Thanks!
