### ISSUE TITLE
not receiving deep links with custom domain

### ISSUE THREAD

**Issue by tele-bird** [xamarin/GoogleApisForiOSComponents#280]
I'm seeing bad behavior with Xamarin.Firebase.iOS.DynamicLinks version 3.0.2.1 that doesn't happen in my Swift app that uses pod: Firebase/DynamicLinks version 4.0.0.

I test them both on my iPhone 6 running iOS 12.2.

Using deep links with Google domain works fine in all cases, but when I use a deep link using our custom domain, it fails.  Specific cases include:

1. When app is not pre-installed, OpenUrl() is invoked with this NSUrl: com.keurig.app://google/link/?dismiss=1&is_weak_match=1, and when I attempt to create a DynamicLink from it (using FromCustomSchemeUrl method), it returns a DynamicLink instance with a null Url property.

2. When app is already installed, ContinueUserActivity() is invoked with the correct userActivity.WebPageUrl, but HandleUniversalLink() returns false, so the SDK doesn't handle it.

**My example Xamarin.iOS code with this bad behavior is here:**
https://github.com/tele-bird/mobile-samples/tree/master/TaskyPortable

**My example Swift app that works fine is here:**
https://github.com/tele-bird/firestore-codelab-extended-swift

Note that these two projects use the same back end Firebase configuration, so the problem must be caused by a difference on the client -side.

**For both projects, I use the same Firebase dependencies that you can see in my code:**

- Entitlements.plist with com.apple.developer.associated-domains entry and applinks: values for both Google and custom domains included ([Xamarin.iOS](https://github.com/tele-bird/mobile-samples/blob/master/TaskyPortable/TaskyiOS/Entitlements.plist)  [Swift](https://github.com/tele-bird/firestore-codelab-extended-swift/blob/master/FriendlyEats/FriendlyEats.entitlements))
- Info.plist with FirebaseDynamicLinksCustomDomains array containing one element: our custom domain with https:// included
- Info.plist with CFBundleURLTypes ([Xamarin.iOS](https://github.com/tele-bird/mobile-samples/blob/master/TaskyPortable/TaskyiOS/Info.plist)  [Swift](https://github.com/tele-bird/firestore-codelab-extended-swift/blob/master/FriendlyEats/Info.plist))
- GoogleService-info.plist (didn't include this in the GitHub repo, but you can provide your own)

**Here are the Firebase diagnostics that appear in xCode for the Swift project:**

---- Firebase Dynamic Links diagnostic output start ----
Firebase Dynamic Links framework version 4.0.0
System information: OS iOS, OS version 12.2, model iPhone
Current date 2019-06-20 13:01:18 +0000
Device locale en-US (raw en_US), timezone America/New_York
	Specified custom URL scheme is com.keurig.app and Info.plist contains such scheme in CFBundleURLTypes key.
	AppID Prefix: 35U7W7KHB9, Team ID: 35U7W7KHB9, AppId Prefix equal to Team ID: YES
performDiagnostic completed successfully! No errors found.
---- Firebase Dynamic Links diagnostic output end ----

**Here are the Firebase diagnostics that appear in Visual Studio for the Xamarin.iOS project:**

---- Firebase Dynamic Links diagnostic output start ----
Firebase Dynamic Links framework version 3.0.1
System information: OS iOS, OS version 12.2, model iPhone
Current date 2019-06-20 13:40:44 +0000
Device locale en-US (raw en_US), timezone America/New_York
	Specified custom URL scheme is com.keurig.app and Info.plist contains such scheme in CFBundleURLTypes key.
	AppID Prefix: 35U7W7KHB9, Team ID: 35U7W7KHB9, AppId Prefix equal to Team ID: YES
performDiagnostic completed successfully! No errors found.
---- Firebase Dynamic Links diagnostic output end ----

**Comment by tele-bird** [comment]
I notice a few differences in your DynamicLinksSample:

1. You are not using a custom domain (only Google-hosted domain at fpm53.app.goo.gl), and you do not have a FirebaseDynamicLinksCustomDomains key set in your Info.plist.  Maybe you never tested this library with custom domain?

2. In Info.plist, you are using CFBundleURLTypes value of Editor, while my code uses Viewer.  I tried changing this in my Xamarin.iOS project, but it did not help.  (The Swift project works with either value.)

3. In AppDelegate.cs, you are setting Options.DefaultInstance.DeepLinkUrlScheme to your bundle ID.  I tried adding this to the Xamarin.iOS project, but it did not help.  (The Swift project works with and without this line of code, and I note that the Firebase documentation says it is only needed when using a custom URL scheme.)

4. In your GoogleService-Info.plist, you have IS_ADS_ENABLED as true, but I have false.  I understand they just changed the default, and it should not make a difference: https://stackoverflow.com/questions/52380776/ios-firebase-is-ads-enabled-flag-in-googleservice-info-plist-file


When modifying your example to support custom domains, you want to modify the code in a couple of ways (other than #1 that I noted above):

- In the OpenUrl method of AppDelegate.cs, examine the contents of the dynamicLink returned by the FromCustomSchemeUrl method.  The bad behavior I'm seeing with custom domain is that it returns a non-null dynamicLink whose URL property is null, so you'll want to check that.

- In the ContinueUserActivity method of AppDelegate.cs, check what HandleUniversalLink returns.  The bad behavior I'm seeing is that it returns false even though the userActivity.WebPageUrl value is correct.

**Comment by tele-bird** [comment]
It was suggested that the core of my issue had to do with device fingerprinting.  I upgraded the following packages in my project, but it didn't help:

Xamarin.Firebase.iOS.Core 5.1.3  ==>  5.2.0
Xamarin.Firebase.iOS.InstanceID 3.2.1  ==>  3.4.0

Does this library use device fingerprinting, or does it use the clipboard contents that are captured by Firebase?

**Comment by SotoiGhost** [comment]
Is this still an issue?

**Comment by SotoiGhost** [comment]
We have not received the requested information. If you are still experiencing this issue, please, open a new issue related to this. Thanks!
