### ISSUE TITLE
Google Places API update for Xamarin.iOS

### ISSUE THREAD

**Issue by theuchenna** [xamarin/GoogleApisForiOSComponents#284]
## Please when will the iOS update of Google Places API be published, currently my team can't work on any new map based project using Xamarin.iOS. I appreciate you for your swift response on the Android Version of this API, it really saved my team and everyone sends in their regards.

Thanks a bunch,
Am expecting to hear from you.

**Comment by SotoiGhost** [comment]
@theuchenna The [Google Places for iOS v3.0.3][1] already contains support for the new API. Hope this helps you. Best!

[1]: https://www.nuget.org/packages/Xamarin.Google.iOS.Places/3.0.3
