### ISSUE TITLE
Linking issues with Firebase Analytics and 32 bit cpu's

### ISSUE THREAD

**Issue by Owlzy** [xamarin/GoogleApisForiOSComponents#286]
We are unable to build when attempting to build for release or appstore after adding Firebase Analytics to our iOS game unless building for ARM64 only.  Funnily enough it does work on debug in the simulator though. 

--Versions--
Xamarin.Build.Download - 0.4.6
Xamarin.Firebase.iOS.Analytics - 4.0.5.1
Xamarin.Firebase.iOS.Core - 4.0.13.1
Xamarin.Firebase.iOS.InstanceID - 2.0.8

I came across this previous [resolved issue](https://github.com/xamarin/GoogleApisForiOSComponents/issues/158) and have attempted the various rollbacks suggestions, clearing bin and obj folders etc but regardless of combination of versions I am still unable to get the project to build.  (my first attempt before finding that thread I simply used the latest versions).

But so far only by removing the ARMv7 and ARMv7s from the supported architectures am I able to build successfully.

![Screenshot 2019-07-01 at 16 47 52](https://user-images.githubusercontent.com/9079651/60450905-c9cd3200-9c22-11e9-87e2-790ef0a26b09.png)

**Comment by Owlzy** [comment]
Thanks but unfortunately I have tried these steps already.   However I will give it another go using the exact combination of versions you mention and get back.

**Comment by SotoiGhost** [comment]
@Owlzy The Armv7s arch is not supported by Google, you need to remove that slice from your app. If building the app with just Armv7 and Arm64 archs doesn't work, can you provide a test case, please? Thanks in advance.

**Comment by Owlzy** [comment]
@SotoiGhost awesome thank you so much, that worked!
