### ISSUE TITLE
Firebase.Performance missing the sessions feature

### ISSUE THREAD

**Issue by MatFillion** [xamarin/GoogleApisForiOSComponents#288]
The current Xamarin binding (2.1.2.0) uses the global version 5.8.1 of Firebase Performance monitoring.

We would like to leverage the sessions feature added in version [5.11.0 (October 2018)](https://firebase.google.com/support/release-notes/ios#5.11.0).

[Here](https://firebase.googleblog.com/2018/11/firebase-performance-monitoring.html) is a more detailed explanation of the feature.

Are there any plans for a version bump? Is that something you've looked into yet?
Latest version is 6.3.0, but I suppose anything above 5.11.0 would enable that feature automatically.

So far we've had good results with the performance monitoring on iOS, we have network metrics and automatic metrics (app_start etc.) working well.

**Comment by SotoiGhost** [comment]
Firebase v6.5.0 is live now, Performance Monitoring should have the requested feature now. Closing the issue now.
