### ISSUE TITLE
No GADRequest?

### ISSUE THREAD

**Issue by jordmax12** [xamarin/GoogleApisForiOSComponents#29]
So just trying to figure out how we can set up ads for debugging simulators/devices. Before installing this SDK, I was able to achieve that by providing a GADRequest, and setting the TestDevices string array. I do not see a way to do this now with this SDK. The Request object I have doesn't seem to have any property that we can use to support this. Can someone confirm or let me know how to achieve this?

**Comment by SotoiGhost** [comment]
Hi @jordmax12,

Can you provide a test case of what you want to achieve or paste the code that it seems to be missing?

**Comment by bholmes** [comment]
I believe GADRequest is handled by the following...

https://github.com/xamarin/GoogleApisForiOSComponents/blob/45484d70cf5578041bafab59dd43bebcf11f5291/Google.MobileAds/source/Google.MobileAds/ApiDefinition.cs#L331

If no response on this thread after another week we should close.

**Comment by SotoiGhost** [comment]
Closed due no response.
