### ISSUE TITLE
Xamarin.Google.ios.MobileAds NSStringFromGADAdsize

### ISSUE THREAD

**Issue by SQUALL0224** [xamarin/GoogleApisForiOSComponents#290]
=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Basic Fault Adddress Reporting
=================================================================
Memory around native instruction pointer (0x10255866c):0x10255865c  4c 00 00 14 e0 03 14 aa 37 03 00 94 f6 03 00 aa  L.......7.......
0x10255866c  08 18 40 f9 48 0e 00 b4 00 c1 02 91 e2 03 00 32  ..@.H..........2
0x10255867c  e3 03 15 aa e1 03 13 aa c4 ff ff 97 75 0e 00 34  ............u..4
0x10255868c  61 05 80 52 e0 03 13 aa 47 86 04 94 d8 22 40 f9  a..R....G...."@.

=================================================================
	Native stacktrace:
=================================================================
	0x102512700 - /var/containers/Bundle/Application/EB6270F3-6BB6-4955-B79C-2F447DEAF9B7/DFPTest.iOS.app/DFPTest.iOS : NSStringFromGADAdSize
	0x1025087e8 - /var/containers/Bundle/Application/EB6270F3-6BB6-4955-B79C-2F447DEAF9B7/DFPTest.iOS.app/DFPTest.iOS : NSStringFromGADAdSize
	0x102517050 - /var/containers/Bundle/Application/EB6270F3-6BB6-4955-B79C-2F447DEAF9B7/DFPTest.iOS.app/DFPTest.iOS : mono_pmip
	0x1ecfa19ec - /usr/lib/system/libsystem_platform.dylib : <redacted>
	0x102558668 - /var/containers/Bundle/Application/EB6270F3-6BB6-4955-B79C-2F447DEAF9B7/DFPTest.iOS.app/DFPTest.iOS : mono_pmip
	0x10255857c - /var/containers/Bundle/Application/EB6270F3-6BB6-4955-B79C-2F447DEAF9B7/DFPTest.iOS.app/DFPTest.iOS : mono_pmip
	0x10251c4ac - /var/containers/Bundle/Application/EB6270F3-6BB6-4955-B79C-2F447DEAF9B7/DFPTest.iOS.app/DFPTest.iOS : mono_pmip
	0x10251cec4 - /var/containers/Bundle/Application/EB6270F3-6BB6-4955-B79C-2F447DEAF9B7/DFPTest.iOS.app/DFPTest.iOS : mono_pmip
	0x10251df68 - /var/containers/Bundle/Application/EB6270F3-6BB6-4955-B79C-2F447DEAF9B7/DFPTest.iOS.app/DFPTest.iOS : mono_pmip
	0x1013f145c - /var/containers/Bundle/Application/EB6270F3-6BB6-4955-B79C-2F447DEAF9B7/DFPTest.iOS.app/DFPTest.iOS : NSStringFromGADAdSize
	0x1010a47cc - /var/containers/Bundle/Application/EB6270F3-6BB6-4955-B79C-2F447DEAF9B7/DFPTest.iOS.app/DFPTest.iOS : NSStringFromGADAdSize
	0x101b6a76c - /var/containers/Bundle/Application/EB6270F3-6BB6-4955-B79C-2F447DEAF9B7/DFPTest.iOS.app/DFPTest.iOS : NSStringFromGADAdSize
	0x1013bd8b8 - /var/containers/Bundle/Application/EB6270F3-6BB6-4955-B79C-2F447DEAF9B7/DFPTest.iOS.app/DFPTest.iOS : NSStringFromGADAdSize
	0x10251a4fc - /var/containers/Bundle/Application/EB6270F3-6BB6-4955-B79C-2F447DEAF9B7/DFPTest.iOS.app/DFPTest.iOS : mono_pmip
	0x1025bd964 - /var/containers/Bundle/Application/EB6270F3-6BB6-4955-B79C-2F447DEAF9B7/DFPTest.iOS.app/DFPTest.iOS : mono_pmip
	0x1025c1278 - /var/containers/Bundle/Application/EB6270F3-6BB6-4955-B79C-2F447DEAF9B7/DFPTest.iOS.app/DFPTest.iOS : mono_pmip
	0x101070c70 - /var/containers/Bundle/Application/EB6270F3-6BB6-4955-B79C-2F447DEAF9B7/DFPTest.iOS.app/DFPTest.iOS : NSStringFromGADAdSize
	0x101070a84 - /var/containers/Bundle/Application/EB6270F3-6BB6-4955-B79C-2F447DEAF9B7/DFPTest.iOS.app/DFPTest.iOS : NSStringFromGADAdSize
	0x1ede188a4 - /System/Library/Frameworks/Foundation.framework/Foundation : __NSFireTimer
	0x1ed323650 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x1ed323380 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x1ed322bb4 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x1ed31db04 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x1ed31d0b0 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : CFRunLoopRunSpecific
	0x1ef51d79c - /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices : GSEventRunModal
	0x219b4c978 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : UIApplicationMain
	0x101ba6f24 - /var/containers/Bundle/Application/EB6270F3-6BB6-4955-B79C-2F447DEAF9B7/DFPTest.iOS.app/DFPTest.iOS : NSStringFromGADAdSize
	0x101b283bc - /var/containers/Bundle/Application/EB6270F3-6BB6-4955-B79C-2F447DEAF9B7/DFPTest.iOS.app/DFPTest.iOS : NSStringFromGADAdSize
	0x101b28344 - /var/containers/Bundle/Application/EB6270F3-6BB6-4955-B79C-2F447DEAF9B7/DFPTest.iOS.app/DFPTest.iOS : NSStringFromGADAdSize
	0x10109e4a0 - /var/containers/Bundle/Application/EB6270F3-6BB6-4955-B79C-2F447DEAF9B7/DFPTest.iOS.app/DFPTest.iOS : NSStringFromGADAdSize
	0x1013bd8b8 - /var/containers/Bundle/Application/EB6270F3-6BB6-4955-B79C-2F447DEAF9B7/DFPTest.iOS.app/DFPTest.iOS : NSStringFromGADAdSize
	0x10251a4fc - /var/containers/Bundle/Application/EB6270F3-6BB6-4955-B79C-2F447DEAF9B7/DFPTest.iOS.app/DFPTest.iOS : mono_pmip
	0x1025bd964 - /var/containers/Bundle/Application/EB6270F3-6BB6-4955-B79C-2F447DEAF9B7/DFPTest.iOS.app/DFPTest.iOS : mono_pmip
	0x1025c3b64 - /var/containers/Bundle/Application/EB6270F3-6BB6-4955-B79C-2F447DEAF9B7/DFPTest.iOS.app/DFPTest.iOS : mono_pmip
	0x1024f8e2c - /var/containers/Bundle/Application/EB6270F3-6BB6-4955-B79C-2F447DEAF9B7/DFPTest.iOS.app/DFPTest.iOS : NSStringFromGADAdSize
	0x1026b6b34 - /var/containers/Bundle/Application/EB6270F3-6BB6-4955-B79C-2F447DEAF9B7/DFPTest.iOS.app/DFPTest.iOS : _Z9__isctypeim
	0x10109e3a4 - /var/containers/Bundle/Application/EB6270F3-6BB6-4955-B79C-2F447DEAF9B7/DFPTest.iOS.app/DFPTest.iOS : NSStringFromGADAdSize
	0x1ecde28e0 - /usr/lib/system/libdyld.dylib : <redacted>

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at DFPTest.iOS.EventHandler.DFPInterstitialEventHandler:<DidReceiveAd>b__12_0 <0x000cb>
	  at Foundation.NSTimerActionDispatcher:Fire <0x0002b>
	  at System.Object:runtime_invoke_dynamic <0x000f7>
	  at <unknown> <0xffffffff>
	  at UIKit.UIApplication:UIApplicationMain <0x00007>
	  at UIKit.UIApplication:Main <0x0002b>
	  at UIKit.UIApplication:Main <0x00043>
	  at DFPTest.iOS.Application:Main <0x0007f>
	  at System.Object:runtime_invoke_dynamic <0x000f7>
=================================================================

/// Returns a NSString describing the provided GADAdSize.
GAD_EXTERN NSString *NSStringFromGADAdSize(GADAdSize size);

Is this function implemented in this project or how to fix this issue?

**Comment by emiliobongiorno** [comment]
Is anyone looking to this issue? 
My app is crashing because of this

**Comment by emiliobongiorno** [comment]
NVM.. it was crashing for a different reason... still having this warning anyway

**Comment by SotoiGhost** [comment]
Is this still an issue?

**Comment by SotoiGhost** [comment]
We have not received the requested information. If you are still experiencing this issue, please, open a new issue related to this. Thanks!
