### ISSUE TITLE
Very large .dll sizes compared to previous major version

### ISSUE THREAD

**Issue by baronchng** [xamarin/GoogleApisForiOSComponents#291]
I am curious that why the sizes increased by so much that caused my app size to double in size. For example,
version 5.0.3 - 5.15 MB
https://www.nuget.org/packages/Xamarin.Firebase.iOS.Database/

version 4.1.3.1 - 31.29 KB
https://www.nuget.org/packages/Xamarin.Firebase.iOS.Database/4.1.3.1

Is this normal or did I do something wrong?

**Comment by SotoiGhost** [comment]
Is this still an issue?

**Comment by baronchng** [comment]
The packages size are significantly smaller as compared to previous versions. I supposed that's good now.
