### ISSUE TITLE
Error downloading 'XamarinComponent.1.1.0.65' while building libs

### ISSUE THREAD

**Issue by SaintMSent** [xamarin/GoogleApisForiOSComponents#292]
Hi guys
I am trying to build samples from this repository. So I decided to build libs first

Here is the output I get

`sh build.sh --target=libs
using local cake.packages.config...
Downloading NuGet...
Feeds used:
  /Users/maksymfedoriaka/.nuget/packages/
  https://api.nuget.org/v3/index.json

Restoring NuGet package Cake.0.27.0.
Adding package 'Cake.0.27.0' to folder '/Users/maksymfedoriaka/Desktop/Projects/GoogleApisForiOSComponents/tools'
Added package 'Cake.0.27.0' to folder '/Users/maksymfedoriaka/Desktop/Projects/GoogleApisForiOSComponents/tools'
Error downloading 'XamarinComponent.1.1.0.65' from 'https://api.nuget.org/v3-flatcontainer/xamarincomponent/1.1.0.65/xamarincomponent.1.1.0.65.nupkg'.
crypt32.dll
Error downloading 'XamarinComponent.1.1.0.65' from 'https://api.nuget.org/v3-flatcontainer/xamarincomponent/1.1.0.65/xamarincomponent.1.1.0.65.nupkg'.
crypt32.dll
Install failed. Rolling back...
Error: One or more errors occurred. (Error downloading 'XamarinComponent.1.1.0.65' from 'https://api.nuget.org/v3-flatcontainer/xamarincomponent/1.1.0.65/xamarincomponent.1.1.0.65.nupkg'.)
	Error downloading 'XamarinComponent.1.1.0.65' from 'https://api.nuget.org/v3-flatcontainer/xamarincomponent/1.1.0.65/xamarincomponent.1.1.0.65.nupkg'.
`

I found this issue https://github.com/xamarin/XamarinComponents/issues/595. I tried deleting tools folder and running the command again, but result is the same. My mac is running macOS 10.14.5 and I have latest versions of Visual Studio and Xamarin installed. I also tried to build it on another machine with older OS, but result is still the same.

How can I fix this issue and build the project? Thanks

**Comment by SotoiGhost** [comment]
The [ReadMe][1] file has been updated and there's a new way to build the components. Hope this helps.

[1]: https://github.com/xamarin/GoogleApisForiOSComponents/blob/master/Readme.md
