### ISSUE TITLE
Google Cast - iOS 13 permission changes - need 4.4.4 binding project

### ISSUE THREAD

**Issue by dationguyen** [xamarin/GoogleApisForiOSComponents#295]
Hi guys,

Google has released the new API (4.4.4) that support the permission change on IOS13
https://developers.google.com/cast/docs/ios_sender/ios13_changes

I wonder, do we have any plan to update our cast library to 4.4.4 anytime soon?

Thanks and best regards,
Dat Nguyen

**Comment by hongkouHenk** [comment]
Can we expect an update for compatibility with the Cast SDK 4.4.4? I am currently experiencing the issue where the cast button does not appear on iOS13 devices as described on the Google developers page: 

"Action Required: Update to Cast SDK 4.4.4 or the cast button may not appear if the user does not grant location permission. Upgrading to Cast SDK 4.4.4 is necessary to ensure a reliable casting experience on iOS 13."

**Comment by SotoiGhost** [comment]
Guys, letting you know that Google Cast v4.4.5 has been pushed today! Hope this fixes the issue. Closing this now!
