### ISSUE TITLE
Place.Types: no associated enum value

### ISSUE THREAD

**Issue by kantan-florian** [xamarin/GoogleApisForiOSComponents#296]
Hi there,

I got this error when running the DidAutocomplete():
System.NotSupportedException: 'supermarket has no associated enum value in PlaceType on this platform.'

I cannot access the "place.Types" variable, guess the supermarket value is not included in the enums, right?

Thanks,
Florian

**Comment by SotoiGhost** [comment]
@kantan-florian The only enum that has something related to `supermarket` is `PlaceType.GroceryOrSupermarket`. IDK if this a bug in our side or Google side, can you provide a test case? Thanks in advance!

**Comment by SotoiGhost** [comment]
We have not received the requested information. If you are still experiencing this issue, please, open a new issue related to this. Thanks!
