### ISSUE TITLE
Google Cast - cannot create UICastButton

### ISSUE THREAD

**Issue by bradlak** [xamarin/GoogleApisForiOSComponents#299]
I am trying to create UICastButton instance with
`new UICastButton(new CGRect(0, 0, 24, 24));`

and get the following exception:

> {Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: *** -[__NSArrayM insertObject:atIndex:]: object cannot be nil

I am using Xamarin.Google.iOS.Cast 4.4.2 version.

It is broken library or I am doing something wrong ? Can you share with me some hints, advice or working library ?

Best Regards

**Comment by dationguyen** [comment]
You need to initialize a cast-service with recieverId first. 
GCKCastOptions options = new GCKCastOptions(new DiscoveryCriteria(recieverId));
options.PhysicalVolumeButtonsWillControlDeviceVolume = true;
GCKCastContext.SetSharedInstanceWithOptions(options);

**Comment by bradlak** [comment]
Great.  How could I miss it. 
Thank you.
