### ISSUE TITLE
Xamarin.Firebase.iOS.DynamicLink using outdated firebase-ios-sdk

### ISSUE THREAD

**Issue by thisisthekap** [xamarin/GoogleApisForiOSComponents#301]
We need the fix provided in https://github.com/firebase/firebase-ios-sdk/issues/2112. Therefore, a newer newer version of firebase-ios-sdk is required, to be able to benefit from this fix.

**Comment by SotoiGhost** [comment]
A new version of Firebase Dynamic Links for iOS (global version 6.5.0) has been pushed. This update must contain the fix. Closing this now. If you still face the issue, please, open a new issue. Best!
