### ISSUE TITLE
Xamarin Cloud Messaging intermittently not recieving notifications

### ISSUE THREAD

**Issue by Eirik-** [xamarin/GoogleApisForiOSComponents#302]
I'm using Xamarin.Firebase.iOS.CloudMessaging v3.1.2 (nuget), and intermittently I'm not recieving any notification messages on iPhones.

In my latest test, sending messages from the Firebase console:
Message 1: Recieved on iPhone and Android
Message 2 (Duplicate of 1): Only recieved on Android
Message 3 (Duplicate of 1): Only recieved on Android
Message 4 (Duplicate of 1): Only recieved on Android
Message 5 (new message): Only recieved on Android

Would be very grateful if someone could help me shed some light on this!

**Comment by Eirik-** [comment]
Downgrading 3.1.2 -> 2.0.8 appeared to have solved the problem, but this should probably be looked at. (Note: Can't be 100% sure as the error was intermittently, but I have not been able to reproduce the error after downgrading - might be coincidence, but seems unlikely. )

**Comment by SotoiGhost** [comment]
@Eirik- A new version of Cloud Messaging has been pushed, can you update and try again? Thanks in advance!

**Comment by SotoiGhost** [comment]
We have not received the requested information. If you are still experiencing this issue, please, open a new issue related to this. Thanks!
