### ISSUE TITLE
Native linking fails when Xamarin.Firebase.iOS.InstanceID added

### ISSUE THREAD

**Issue by applied-kevinsalot** [xamarin/GoogleApisForiOSComponents#303]
Starting with an empty Xamarin.Forms project, adding `Xamarin.Firebase.iOS.InstanceID` package to the iOS project causes linker errors upon build. 

I attached the full msbuild log, but here are a few of the errors. Ultimately I was trying to use the `Xamarin.Firebase.iOS.Analytics` package, but I was able to recreate with just its dependencies.

`3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(804,3): error MT5210: Native linking failed, undefined symbol: _FIRLogBasic. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(804,3): error MT5210: Native linking failed, undefined symbol: _FIRLogError. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(804,3): error MT5210: Native linking failed, undefined symbol: _FIRLogWarning. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(804,3): error MT5210: Native linking failed, undefined symbol: _GULIsLoggableLevel. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(804,3): error MT5210: Native linking failed, undefined symbol: _GULLogBasic. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(804,3): error MT5210: Native linking failed, undefined symbol: _GULLogError. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(804,3): error MT5210: Native linking failed, undefined symbol: _GULLogInfo. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.`

VS solution to repro issue: 
[App.zip](https://github.com/xamarin/GoogleApisForiOSComponents/files/3611404/App.zip)

VS About:
[VS2019_About.txt](https://github.com/xamarin/GoogleApisForiOSComponents/files/3611316/VS2019_About.txt)

MSBuild log:
[msbuild_log.txt](https://github.com/xamarin/GoogleApisForiOSComponents/files/3611317/msbuild_log.txt)

**Comment by SotoiGhost** [comment]
@applied-kevinsalot Can you update to the most recent version and try again? Thanks in advance!

**Comment by applied-kevinsalot** [comment]
@SotoiGhost Sorry for the late reply, I was unavailable last week. I upgraded to version 4.2.1 and no longer receive the above error. Thanks!
