### ISSUE TITLE
Cannot create a new a DFPRequest in Google.MobileAds, only GADRequest

### ISSUE THREAD

**Issue by avidan-chen** [xamarin/GoogleApisForiOSComponents#31]
I am trying to create an instance of DFPRequest, in order to set the customTargeting property on it (which does not exist in the base class). However, Google.MobileAds.DoubleClick.Request.GetDefaultRequest() returns the base class Google.MobileAds.Request, which is GADRequest, thus I am unable to set CustomTargeting property.

Casting Google.MobileAds.DoubleClick.Request.GetDefaultRequest() to    Google.MobileAds.DoubleClick.Request throws an exception at runtime: InvalidCastException.

Using latest version of the nuget: 7.8.1.1.

**Comment by SotoiGhost** [comment]
This is fixed in Firebase.AdMob version 7.8.1.
