### ISSUE TITLE
Updated from 2.5 to 3.1 and now missing PlacePickerViewController and others

### ISSUE THREAD

**Issue by Nerves82** [xamarin/GoogleApisForiOSComponents#310]
I updates an app I am fixing from 2.5.x up to 3.1 and many classes that where in the package are now nowhere to be found, in particular PlacePickerViewController and PlacePickerViewControllerDelegate. Where did these go? Did they get deprecated? Do I need a   second package now? How do I continue to use this?

**Comment by SotoiGhost** [comment]
According to this [Google doc][1]:

> The Place Picker was deprecated on January 29, 2019. It was turned off on July 29, 2019, and is no longer available. Continued use will result in an error message. The new SDK does not support the Place Picker.

There is no way to still continue using the `PlacePickerViewController` class.

Hope this helps you.
Best!

[1]: https://developers.google.com/places/ios-sdk/client-migration#place_picker_is_no_longer_available

**Comment by Nerves82** [comment]
Thanks for this info SotoiGhost!
