### ISSUE TITLE
Xamarin.Firebase.iOS.Crashlytics issue when uploading symbols on macOS 10.15 "Catalina"

### ISSUE THREAD

**Issue by TimA11111** [xamarin/GoogleApisForiOSComponents#312]
I've just upgraded to macOS 10.15 Catalina, and I'm now getting the following build error:

packages/Xamarin.Firebase.iOS.Crashlytics.3.10.9/build/Xamarin.Firebase.iOS.Crashlytics.targets(53,3): error MSB3073: 
The command "'/Users/timauckland2/Library/Caches/XamarinBuildDownload/Fbrc-1.7.13/upload-symbols' -gsp '/Users/timauckland2/Documents/bitbucket/navigatorapp/NavigatorApp.iOS/GoogleService-Info.plist' -p ios 'bin/iPhone/Release/NavigatorApp.iOS.app.dSYM'" exited with code 8.

This looks very similar to issue #194.

Is there a workaround for this problem?

Thanks.

**Comment by Dubnovitsky** [comment]
> Is there a workaround for this problem?

I've met the same issue. As a workaround you can just comment or delete the next line in the **Xamarin.Firebase.iOS.Crashlytics.targets** file:

`<Exec Command="'$(XamarinBuildDownloadDir)$(_FabricItemsFolder)\$(_FabricScriptName)' -gsp '$(MSBuildProjectDirectory)\GoogleService-Info.plist' -p ios '$(DeviceSpecificOutputPath)\$(AssemblyName).app.dSYM'"/>`

**Comment by MauryZ** [comment]
> > Is there a workaround for this problem?
> 
> I've met the same issue. As a workaround you can just comment or delete the next line in the **Xamarin.Firebase.iOS.Crashlytics.targets** file:
> 
> `<Exec Command="'$(XamarinBuildDownloadDir)$(_FabricItemsFolder)\$(_FabricScriptName)' -gsp '$(MSBuildProjectDirectory)\GoogleService-Info.plist' -p ios '$(DeviceSpecificOutputPath)\$(AssemblyName).app.dSYM'"/>`

For now this works for me :) Waiting for fix

**Comment by TimA11111** [comment]
@Dubnovitsky  Many thanks for the workaround, and the quick response.  Very much appreciated.  I'm able to build and test again.

**Comment by TimA11111** [comment]
Opps, sorry, didn't mean to close the issue

**Comment by Jmunozg** [comment]
I have a question, if I comment on this line to compile my project, is it possible that I do not record error events in firebase?

**Comment by MauryZ** [comment]
> I have a question, if I comment on this line to compile my project, is it possible that I do not record error events in firebase?
> 
> and this not work for me, it's compile but when I open the app, it closes.

I don't think the statistics will be saved because the configuration file is commented out.

**Comment by Dubnovitsky** [comment]
@MauryZ
> I don't think the statistics will be saved because the configuration file is commented out.

This command is just upload dSYM files to Firebase. It's required if you want to see symbolicated crash logs in Firebase console. You can comment this line, compile your application and upload dSYM files to Firebase manually.

`<Exec Command="'$(XamarinBuildDownloadDir)$(_FabricItemsFolder)\$(_FabricScriptName)' -gsp '$(MSBuildProjectDirectory)\GoogleService-Info.plist' -p ios '$(DeviceSpecificOutputPath)\$(AssemblyName).app.dSYM'"/>`


@Jmunozg
`and this not work for me, it's compile but when I open the app, it closes.`
Looks like you updated some of Firebase packages to the latest version. I had the same issue. Looks like the problem is in **Xamarin.Firebase.iOS.Core** package.

**Comment by Jmunozg** [comment]
Hello, I updated to the latest version of xamarin and the reported error was not presented to me, apparently it was corrected.

**Comment by SotoiGhost** [comment]
Firebase Crashlytics v3.14.0 has been pushed. The update was tested on Catalina with the following environment of VS4M and seems to be working without a problem:

```
=== Visual Studio Enterprise 2019 for Mac ===

Version 8.3.3 (build 8)
Installation UUID: c9917c0f-497a-43df-8b9a-ac88fafafded
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 604000208

=== Mono Framework MDK ===

Runtime:
	Mono 6.4.0.208 (2019-06/07c23f2ca43) (64-bit)
	Package version: 604000208

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.0.100/Sdks
SDK Versions:
	3.0.100
	2.1.504
	2.1.301
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0
	2.1.13
	2.1.8
	2.1.1
	2.0.5
	2.0.0
	1.1.1
	1.0.4

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.1 (15405)
Build 11A1027

=== Xamarin.iOS ===

Version: 13.4.0.2 (Visual Studio Enterprise)
Hash: e37549bc
Branch: xcode11.1
Build date: 2019-10-07 22:43:23-0400

=== Build Information ===

Release ID: 803030008
Git revision: fb0d3af49f0ea88661a4f469b9dfd1018dc099cd
Build date: 2019-10-10 10:53:35+00
Build branch: release-8.3
Xamarin extensions: 3f8e699ba26ed5f69b7a6466ba679f4a328fadb4

=== Operating System ===

Mac OS X 10.15.0
Darwin 19.0.0 Darwin Kernel Version 19.0.0
    Wed Sep 25 20:18:50 PDT 2019
    root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64
```

Also, this update contains two flags that let you have more control over the upload process. For more info, here's the [readme file](https://raw.githubusercontent.com/xamarin/GoogleApisForiOSComponents/master/source/Firebase/Crashlytics/readme.txt). Best!
