### ISSUE TITLE
Can't build app with latest Google Mobile Ads SDK

### ISSUE THREAD

**Issue by tipa** [xamarin/GoogleApisForiOSComponents#318]
Using Xamarin.Google.iOS.MobileAds Nuget package v7.47.0, I am unable to build my app:
![image](https://user-images.githubusercontent.com/2863198/66699220-0f4ed000-ece5-11e9-8ffd-321f8ec63cdc.png)

Only after manually adding these Nuget packages, the app builds successfully:
`Xamarin.Firebase.iOS.Core`
`Xamarin.Build.Download`

It would be great if that wouldn't be needed.
Example project: [AdTest.zip](https://github.com/xamarin/GoogleApisForiOSComponents/files/3720464/AdTest.zip)

**Comment by motoko89** [comment]
Thanks @tipa for the tip. Wasted so much time on this

**Comment by SotoiGhost** [comment]
This seems to be a bug with VS4M and NuGet. NuGet dependencies are being downloaded but are not being referenced in the csproj. I'll file a bug about this.

**Comment by SotoiGhost** [comment]
This seems to be an issue with NuGet in general, not just with this package. Filed a [bug in NuGet][1] about this. The workaround of this issue is to add package dependencies explicitly as you did.

[1]: https://github.com/NuGet/Home/issues/8694

**Comment by markerpen** [comment]
I'm getting the following error when trying to build with v7.47.0:

`MTOUCH: Error MT1303: Could not decompress the native framework 'Protobuf.framework' from '<project>/src/obj/iPhoneSimulator/Debug/device-builds/iphone12.1-13.2/mtouch-cache/Protobuf.framework.zip'. Please review the build log for more information from the native 'unzip' command. (MT1303)`

I've removed the two NuGet packages (Firebase.Core and MobileAds), saved the two DLLs to a folder, then added those DLLs as references in VS4M. Still getting the same error. Downgrading MobileAds to 7.38 fixes the issue.

I'm running the latest version of VS4M, Xcode 11. Anyone have any ideas? You've mentioned adding package dependencies explicitly - is this different from what I'm doing? If so, what are the steps?

**Comment by SotoiGhost** [comment]
@markerpen Which NuGet do you have in your project? AFAIK, Firebase AdMob does not reference Protobuf somehow.

**Comment by tipa** [comment]
Any updates on this?

**Comment by SotoiGhost** [comment]
@tipa An update was released that contains a possible fix for this. Please, update and try again. Thanks in advance!

**Comment by tipa** [comment]
Looks like the issue is fixed now, thanks a lot!!

**Comment by tipa** [comment]
Was cheering too soon. Creating app bundle works when doing locally, but fails in Azure Pipelines all of the sudden...
```
_CompileToNative:
  /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/runner/runners/2.164.7/work/1/s/atomicclock/AtomicClock.iOS/obj/iPhone/Release/response-file.rsp --xml=/Users/runner/runners/2.164.7/work/1/s/atomicclock/AtomicClock.iOS/LinkDescription.xml "--gcc_flags=-ObjC -ObjC -lc++ -lsqlite3 -lz -ObjC -lz -lsqlite3" 
MTOUCH : error MT2101: Can't resolve the reference 'ObjCRuntime.TrampolineBlockBase', referenced from the method 'System.Void Google.MobileAds.NativeCustomTemplateAd::PerformClickOnAssetWithKey(System.String,System.Action)' in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'. [/Users/runner/runners/2.164.7/work/1/s/atomicclock/AtomicClock.iOS/AtomicClock.iOS.csproj]
Done Building Project "/Users/runner/runners/2.164.7/work/1/s/atomicclock/AtomicClock.iOS/AtomicClock.iOS.csproj" (default targets) -- FAILED.

Build FAILED.

"/Users/runner/runners/2.164.7/work/1/s/atomicclock/AtomicClock.iOS/AtomicClock.iOS.csproj" (default target) (1) ->
(_CoreCompileInterfaceDefinitions target) -> 
  Main.storyboard : ibtool warning : Automatically Adjusts Font requires using a Dynamic Type text style [/Users/runner/runners/2.164.7/work/1/s/atomicclock/AtomicClock.iOS/AtomicClock.iOS.csproj]


"/Users/runner/runners/2.164.7/work/1/s/atomicclock/AtomicClock.iOS/AtomicClock.iOS.csproj" (default target) (1) ->
(_CompileToNative target) -> 
  MTOUCH : error MT2101: Can't resolve the reference 'ObjCRuntime.TrampolineBlockBase', referenced from the method 'System.Void Google.MobileAds.NativeCustomTemplateAd::PerformClickOnAssetWithKey(System.String,System.Action)' in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'. [/Users/runner/runners/2.164.7/work/1/s/atomicclock/AtomicClock.iOS/AtomicClock.iOS.csproj]

    1 Warning(s)
    1 Error(s)

```

**Comment by tipa** [comment]
Seems like after updating Mono to 6.6.0 in the build script fixed the issue. Was using 6.4.0 before
