### ISSUE TITLE
Analytics 6.0.4 Linking Failing - Missing Framework FirebaseAnalytics

### ISSUE THREAD

**Issue by lukeacl** [xamarin/GoogleApisForiOSComponents#325]
Xamarin.Firebase.iOS.Analytics 6.0.4 is failing to link in a Xamarin.Forms project due to missing framework FirebaseAnalytics.

**Other Packages**

> Xamarin.Firebase.iOS.CloudMessaging 4.1.1.1
Newtonsoft.Json 12.0.2
sqlite-net-pcl 1.6.292
Xamarin.Essentials 1.2.0
Xamarin.Forms 4.2.0.709249

**Build Output**

> ld : warning : directory not found for option '-FFAnlytcs-6.0.4/Frameworks'
ld : warning : directory not found for option '-FFAnlytcs-6.0.4/Frameworks'
ld : warning : directory not found for option '-FFAnlytcs-6.0.4/Frameworks'
MTOUCH : warning MT5215: References to 'System' might require additional -framework=XXX or -lXXX instructions to the native linker
clang : error : linker command failed with exit code 1 (use -v to see invocation)
error MT5209 : Native linking error : warning: directory not found for option '-FFAnlytcs-6.0.4/Frameworks'
error MT5209 : Native linking error : warning: directory not found for option '-FFAnlytcs-6.0.4/Frameworks'
error MT5209 : Native linking error : warning: directory not found for option '-FFAnlytcs-6.0.4/Frameworks'
error MT5209 : Native linking error : framework not found FirebaseAnalytics

Have been unable to find a workaround for this.

**Comment by SotoiGhost** [comment]
@lukeacl Please follow [these steps][1] and let me know your results. Thanks in advance!

[1]: https://github.com/xamarin/GoogleApisForiOSComponents/issues/324#issuecomment-545725609

**Comment by SotoiGhost** [comment]
@lukeacl Sorry, I referenced to the wrong comment. Please follow [this workaround][1] and let me know your results.

[1]: https://github.com/xamarin/GoogleApisForiOSComponents/issues/318#issuecomment-543372514

**Comment by lukeacl** [comment]
@SotoiGhost That worked! Manually adding the deps required fixed the issue. Thanks for your help.

**Comment by SotoiGhost** [comment]
Glad to know that it worked! 

Linking this issue to [NuGet issue][1], just for the records.

[1]: https://github.com/NuGet/Home/issues/8694

**Comment by twannie83** [comment]
> @SotoiGhost That worked! Manually adding the deps required fixed the issue. Thanks for your help.

@SotoiGhost How to add Manually the deps? I put in my Main projectfile. But does not work
![image](https://user-images.githubusercontent.com/25795066/68890385-06578100-071f-11ea-98f1-eb9ddd20f359.png)

**Comment by SotoiGhost** [comment]
@twannie83 If you add them by hand into your `.csproj`, try restoring NuGet packages of the solution. If that does not work, please, use the NuGet manager to add them.

**Comment by SotoiGhost** [comment]
@twannie83 That error usually appears when Xamarin.Build.Download was not restored correctly or when frameworks bits weren't downloaded correctly.

My suggestion is to clean XBD and nuget caches, delete bin and obj folder and try again.

**Comment by Lapinou42** [comment]
Thank you so much @SotoiGhost  and @lukeacl ! That's working for me too :)

**Comment by twannie83** [comment]
> @twannie83 That error usually appears when Xamarin.Build.Download was not restored correctly or when frameworks bits weren't downloaded correctly.
> 
> My suggestion is to clean XBD and nuget caches, delete bin and obj folder and try again.

@SotoiGhost I fixed the problem! Had to downgrade Xamarin.Firebase.iOS.Analytics to lower version. Thanx for support!
