### ISSUE TITLE
Specified cast is not valid error while using "SignInWithCredential".

### ISSUE THREAD

**Issue by remeesms** [xamarin/GoogleApisForiOSComponents#326]
While using  "SignInWithCredential" the app is crashing with "Specified cast is not valid " error. 
Its happening after updating the firebase auth to version="6.2.1". Previously The "SignInAndRetrieveDataWithCredential" was working perfect.

Firebase versions using:
```
  <package id="Xamarin.Firebase.iOS.Analytics" version="5.1.4.1" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.Auth" version="6.2.1" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.CloudMessaging" version="4.1.1.1" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.Core" version="6.1.0" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.Database" version="6.0.0" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.InstanceID" version="4.2.1" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.Storage" version="3.4.0" targetFramework="xamarinios10" />
```

Code Sample:
```
var credendtials = PhoneAuthProvider.DefaultInstance.GetCredential(verificationId, verificationCode);
Auth.DefaultInstance.SignInWithCredential(credential: credendtials, (task, error) =>
            {
                if (error != null)
                {                  
                    tcsPhone.SetResult(false);
                }
                else
                {
                    tcsPhone.SetResult(true);
                }

            });
```
Stack Trace error:

>  at (wrapper castclass) System.Object.__castclass_with_cache(object,intptr,intptr)\n  at ObjCRuntime.Runtime.ConstructNSObject[T] (System.IntPtr ptr, System.Type type, ObjCRuntime.Runtime+MissingCtorResolution missingCtorResolution) [0x00050] in <d5ac8b1069644e148a96bf0a4b22f2fd>:0 \n  at ObjCRuntime.Runtime.GetNSObject[T] (System.IntPtr ptr) [0x000d1] in <d5ac8b1069644e148a96bf0a4b22f2fd>:0 \n  at ObjCRuntime.Trampolines+SDAuthResultHandler.Invoke (System.IntPtr block, System.IntPtr user, System.IntPtr error) [0x00016] in <d7f3560f732b4e54aa3981a41bb500be>:0 \n  at (wrapper native-to-managed) ObjCRuntime.Trampolines+SDAuthResultHandler.Invoke(intptr,intptr,intptr)\n  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)\n  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.4.0.2/src/Xamarin.iOS/UIKit/UIApplication.cs:86 \n  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.4.0.2/src/Xamarin.iOS/UIKit/UIApplication.cs:65 \n  at Myapp.Touch.Application.Main (System.String[] args) [0x00001] in /Users/developeradmin/Myapp/Alpha8/Mobile/Sources/Myapp.Touch/Main.cs:9

**Comment by remeesms** [comment]
Any update on this?

**Comment by TonyPovey** [comment]
I'm also experiencing this same issue, although the login actually completes and if I restart the app then I'm logged in.

**Comment by remeesms** [comment]
@TonyPovey Yeah same behaviour here.

**Comment by SotoiGhost** [comment]
Guys, letting you know that a fix of this is in progress. Hope it will be released this week.

**Comment by remeesms** [comment]
Now it doesn't show this error but there is no return from `SignInWithCredential`. Is there any change need in the implementation?

**Comment by SotoiGhost** [comment]
@remeesms Nothing changed, we just changed the callback parameter type. If it seems to be failing, please, file a new issue describing the problem. Also, it would be great if you can provide a test case. Thanks in advance!

**Comment by remeesms** [comment]
@SotoiGhost Filed a new issue here #337. Please have a look.
