### ISSUE TITLE
CloudMessagingSample: AppDelegate.cs is ShowMessage() called?

### ISSUE THREAD

**Issue by TylerByte666** [xamarin/GoogleApisForiOSComponents#327]
Hi guys I noticed within the AppDelegate.cs file in your Cloud Messaging Sample there is this function:

`ShowMessage(string title, string message, UIViewController fromViewController, Action actionForOk = null)`

But it does not look like it is ever called. Is there something that I missing or must we call it ourselves?
If we should call it ourselves, the most appropriate place to place it will be?

There is also a ` // TODO: Handle data of notification` is that done via the `HandleMessage()` function?

**Comment by SotoiGhost** [comment]
@TylerByte666 The `ShowMessage` method is called in the [`UserInfoViewController.cs`][1] file.
This method is for displaying information only.

And, IIRC, `HandleMessage ()` handles the incoming notification data. I can't recall if we were going to add something else to the sample.

Hope this helps you. Best!

[1]: https://github.com/xamarin/GoogleApisForiOSComponents/blob/master/samples/Firebase/CloudMessaging/CloudMessagingSample/UserInfoViewController.cs#L21

**Comment by TylerByte666** [comment]
Thanks.
