### ISSUE TITLE
No nuget for Firebase Cloud Functions

### ISSUE THREAD

**Issue by chrisfoulds** [xamarin/GoogleApisForiOSComponents#329]
https://firebase.google.com/docs/functions

Workaround is http requests, but it's not ideal.

**Comment by SotoiGhost** [comment]
We have this component on the radar, but we don't have an ETA. If someone of the community wants to take this, community PR's are very welcome! We can help you through the process.

**Comment by robinryf** [comment]
If this is still up for grabs I looked at it yesterday and have a PR open towards this issue.
https://github.com/xamarin/GoogleApisForiOSComponents/pull/387
Please have a look and provide me with feedback/reviews.

**Comment by SotoiGhost** [comment]
This is closed now as Firebase Cloud Functions has been released.

**Comment by endarea** [comment]
@chrisfoulds Did you manage to make it work using http requests? I'm at a loss understanding what headers and other things I need to set up (I always get a 500 status now)
