### ISSUE TITLE
Interstitial ads working on simulator but getting "Request Error: No ad to show." on device

### ISSUE THREAD

**Issue by strillo** [xamarin/GoogleApisForiOSComponents#33]
I'm integrating v.7.8.1.1 of the AdMob component into a Xamarin.iOS app.

I can successfully load both interstitial test and live adverts in the simulator, however keep getting a "no ads to show" error when trying the app on a real device (iPhone 6, iOS 9.3.4).

Code is:
    adInterstitial = new Interstitial("ca-app-pub-3940256099942544/4411468910"); // Google Test
    Request req = Request.GetDefaultRequest();
    req.TestDevices = new[] { Request.SimulatorId, "fd73cdb1b60c42764e99d86dbabc840e" };
    adInterstitial.LoadRequest(req);  

Which on the device returns:
"Error Domain=com.google.ads Code=1 "Request Error: No ad to show." UserInfo={NSLocalizedDescription=Request Error: No ad to show., NSLocalizedFailureReason=Request Error: No ad to show.}"

NSAppTransportSecurity is specified correctly and I got the device ID from the application log, but I always get the same response, even regardless of whether I specify the Test Devices or not.

Any ideas?

**Comment by modplug** [comment]
I just upgraded to 7.8.1.1 and I'm getting the same error. Any suggestions?

**Comment by wangshouye** [comment]
I'm getting the same error too,  Any suggestions?

**Comment by vivekvish27** [comment]
I am also facing same issue on iPhone 7 and later devices.

**Comment by SotoiGhost** [comment]
Is someone still facing this issue? I have just tested this on iPhone 7 with Google Interstitial Test ID and threw me  this message:

> <Google> Cannot find an ad network adapter with the name(s): com.google.DummyAdapter. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.

But I used my own Interstitial ID and everything worked as expected.

**Comment by SotoiGhost** [comment]
We have not received the requested information. If you are still experiencing this issue please provide all the requested information and re-open the issue report. Thanks!
