### ISSUE TITLE
ISignInUIDelegate does not exist in version 5.0.1 of Xamarin.Google.iOS.SignIn

### ISSUE THREAD

**Issue by ashleypringle** [xamarin/GoogleApisForiOSComponents#330]
I have Google sign in implemented in a Xamarin Forms iOS project and in order to implement the GoogleSignIn button I have a custom page renderer that implements the ISignInUIDelegate and ISignInDelegate interfaces and assigns SignIn.SharedInstance.Delegate and UIDelegate, as per these instructions: https://github.com/xamarin/GoogleApisForiOSComponents/blob/master/docs/Google/SignIn/GettingStarted.md

As of version 5.0.1, ISignInUIDelegate and SharedInstance.UIDelegate both don't exist and tapping the GoogleSignInButton without assigning them gives this error:

> Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: presentingViewController must be set.
> Native stack trace:
> 	0   CoreFoundation                      0x00000001a6dba9a0 DA838E75-6B30-360E-9661-C4800A7E1BF6 + 1227168
> 	1   libobjc.A.dylib                     0x00000001a6ae30a4 objc_exception_throw + 56
> 	2   CoreFoundation                      0x00000001a6cb0054 DA838E75-6B30-360E-9661-C4800A7E1BF6 + 135252
> 	3   App.iOS                       0x0000000100f1588c -[GIDSignIn assertValidPresentingViewController] + 72
> 	4   App.iOS                       0x0000000100f131f0 -[GIDSignIn signInWithOptions:] + 132
> 	5   App.iOS                       0x0000000100f16a84 -[GIDSignInButton pressed] + 264
> 	6   UIKitCore                           0x00000001aadc9a44 82C949DD-37F6-35F7-B3EF-62BA342F6BF5 + 10426948
> 	7   UIKitCore                           0x00000001aa80d6d0 82C949DD-37F6-35F7-B3EF-62BA342F6BF5 + 4413136
> 	8   UIKitCore                           0x00000001aa80da34 82C949DD-37F6-35F7-B3EF-62BA342F6BF5 + 4414004
> 	9   UIKitCore                           0x00000001aa80ca50 82C949DD-37F6-35F7-B3EF-62BA342F6BF5 + 4409936
> 	10  UIKitCore                           0x00000001aae02d68 82C949DD-37F6-35F7-B3EF-62BA342F6BF5 + 10661224
> 	11  UIKitCore                           0x00000001aae040a8 82C949DD-37F6-35F7-B3EF-62BA342F6BF5 + 10666152
> 	12  UIKitCore                           0x00000001aade0ae8 82C949DD-37F6-35F7-B3EF-62BA342F6BF5 + 10521320
> 	13  UIKit                               0x00000001daa4cfa8 F390E4E0-0FDB-3CEB-B409-E51BBF8C291D + 126888
> 	14  UIKitCore                           0x00000001aae5823c 82C949DD-37F6-35F7-B3EF-62BA342F6BF5 + 11010620
> 	15  UIKitCore                           0x00000001aae5a798 82C949DD-37F6-35F7-B3EF-62BA342F6BF5 + 11020184
> 	16  UIKitCore                           0x00000001aae5360c 82C949DD-37F6-35F7-B3EF-62BA342F6BF5 + 10991116
> 	17  CoreFoundation                      0x00000001a6d387e0 DA838E75-6B30-360E-9661-C4800A7E1BF6 + 694240
> 	18  CoreFoundation                      0x00000001a6d38738 DA838E75-6B30-360E-9661-C4800A7E1BF6 + 694072
> 	19  CoreFoundation                      0x00000001a6d37ed0 DA838E75-6B30-360E-9661-C4800A7E1BF6 + 691920
> 	20  CoreFoundation                      0x00000001a6d3301c DA838E75-6B30-360E-9661-C4800A7E1BF6 + 671772
> 	21  CoreFoundation                      0x00000001a6d328bc CFRunLoopRunSpecific + 464
> 	22  GraphicsServices                    0x00000001b0b9e328 GSEventRunModal + 104
> 	23  UIKitCore                           0x00000001aadc86d4 UIApplicationMain + 1936
> 	24  App.iOS                       0x0000000101fcd800 wrapper_managed_to_native_UIKit_UIApplication_UIApplicationMain_int_string___intptr_intptr + 352
> 	25  App.iOS                       0x0000000101f2496c UIKit_UIApplication_Main_string___intptr_intptr + 44
> 	26  App.iOS                       0x0000000101f248f4 UIKit_UIApplication_Main_string___string_string + 68
> 	27  App.iOS                       0x0000000100f609c0 App_iOS_Application_Main_string__ + 128
> 	28  App.iOS                       0x0000000101300954 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 260
> 	29  App.iOS                       0x00000001036508cc mono_jit_runtime_invoke + 1100
> 	30  App.iOS                       0x000000010370d314 mono_runtime_invoke_checked + 148
> 	31  App.iOS                       0x00000001037135dc mono_runtime_exec_main_checked + 120
> 	32  App.iOS                       0x000000010362ebbc mono_jit_exec + 376
> 	33  App.iOS                       0x000000010381b0fc xamarin_main + 2176
> 	34  App.iOS                       0x0000000100f5bc14 main + 84
> 	35  libdyld.dylib                       0x00000001a6bbd460 E1637502-BFCB-3BBC-B3E1-CCF78617E0E4 + 5216

Is this is a bug? If not, is there a new method for implementing GoogleSignInButton?

Thanks.

**Comment by natsoragge** [comment]
Try to replace
            `SignIn.SharedInstance.UIDelegate = this;`

for 
            `SignIn.SharedInstance.PresentingViewController = this;`

This solved the `NSInvalidArgumentException ` error for me

**Comment by ashleypringle** [comment]
@natsoragge @SotoiGhost Thanks for the info, I made those changes and the plugin is working again!
