### ISSUE TITLE
Xamarin.Google.iOS.SignIn: Login not working on iOS 13.x after update to version 5.0.1

### ISSUE THREAD

**Issue by natsoragge** [xamarin/GoogleApisForiOSComponents#331]
After updating the Xamarin.Google.iOS.SignIn package to version 5.0.1, SignInUser stopped working. I'm getting the following NSError with DidSignIn:

> The operation couldn’t be completed. (org.openid.appauth.general error -3.)

The alert that asks the user to allow the app to use google.com ("App Wants to Use google.com to Sign in") shows briefly and then it hides by itself and I get the error. The NSError Code is -1 (unknown error). What am I possibly doing wrong?

**Comment by SotoiGhost** [comment]
@natsoragge are you still facing this issue?

**Comment by natsoragge** [comment]
Yes, I am. I had to downgrade to version 4.0.0, in which the login is working fine. The older version is hanging on SignInUserSilently, but that's a minor problem for me compared to the SignInUser bug.

**Comment by SotoiGhost** [comment]
Can you provide a test case, please? I have tested our sample and seems to be working. Thanks in advance!

**Comment by purplerockcvd** [comment]
I have the exact same problem as @natsoragge. I am calling SignIn from a class that is not a view controller. Version 5 eliminated ISignInUIDelegate so it has obviously changed with respect to running outside a view controller. The documentation has not been updated for this scenario. Can you provide guidance to replace the obsolete documentation? Thanks.

**Comment by SotoiGhost** [comment]
@purplerockcvd Now you need to tell G.SignIn who's your VC from the login process should be presented.

Here are the [changes][1] that I made to our sample to make it work.

Also, here's the [official migration][2] guide to v5.x from Google. We just need to replace some lines to keep things working. Hope this helps you! Best!

[1]: https://github.com/xamarin/GoogleApisForiOSComponents/commit/c913e3b899f2805ecbbe78e0de45296a84febe9c#diff-1e697c9ada0e4d4a24dfe92a6cdbe8ca
[2]: https://developers.google.com/identity/sign-in/ios/quick-migration-guide#migrating_from_versions_prior_to_v500

**Comment by purplerockcvd** [comment]
Thanks, @SotoiGhost. I had looked at the sample, but seeing the changes help me focus on what mattered. Since I am using SignIn outside a view controller, I thought I would describe what I did just in case it might help someone else.
As in the old GettingStarted file, I was defining SignIn.SharedInstance.UIDelegate and Delegate. Obviously UIDelegate needed to be removed as it doesn't exist anymore. I also had to delete Delegate = this. I also had to assign PresentingViewController and SignIn as in the sample since they appear to be taking the place of the two delegates and DidSignIn. With this, DidSignIn will get called as before. Obviously you could put your callback code right in the SignedIn lambda.
`



        public void Login()
        {
            if(UIApplication.SharedApplication != null)
            {
                var window = UIApplication.SharedApplication.KeyWindow;
                var vc = window.RootViewController;
                while (vc.PresentedViewController != null)
                {
                    vc = vc.PresentedViewController;
                }
                _viewController = vc;

                SignIn.SharedInstance.PresentingViewController = _viewController;
                SignIn.SharedInstance.SignedIn += (sender, e) =>
                {
                    DidSignIn(null, e.User, e.Error);
                };
                SignIn.SharedInstance.SignInUser();
            }
        }

`

**Comment by luizvnegrini** [comment]
Same error here!

**Comment by SotoiGhost** [comment]
Is this still an issue?

**Comment by SotoiGhost** [comment]
We have not received the requested information. If you are still experiencing this issue, please, open a new issue related to this. Thanks!

**Comment by stanleywailers** [comment]
@purplerockcvd  Thanks 
this work for me SignIn.SharedInstance.PresentingViewController = _viewController;
