### ISSUE TITLE
Xamarin.Firebase.iOS.Crashlytics 3.14.0 build problem

### ISSUE THREAD

**Issue by chenjeff622** [xamarin/GoogleApisForiOSComponents#334]
2>  /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/jeff/Library/Caches/Xamarin/mtbs/builds/********.iOS/2c8dc4dacec13b39898d21f3e9cd21e3/obj/iPhone/Release/response-file.rsp "--gcc_flags=-ObjC -lc++ -lz -ObjC" 
2>G:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(842,3): error : warning: directory not found for option '-FFCrshlytcs-3.14.0/iOS'
2>G:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(842,3): error : warning: directory not found for option '-FFbrc-1.10.2/iOS'
2>G:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(842,3): error : framework not found Crashlytics
2>G:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(842,3): warning MT5215: References to 'System' might require additional -framework=XXX or -lXXX instructions to the native linker
2>G:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(842,3): error MT5201: Native linking failed. Please review the build log and the user flags provided to gcc: -ObjC -lc++ -lz -ObjC
2>G:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(842,3): error MT5202: Native linking failed. Please review the build log.
2>G:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(842,3): warning : directory not found for option '-FFCrshlytcs-3.14.0/iOS'
2>G:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(842,3): warning : directory not found for option '-FFbrc-1.10.2/iOS'
2>G:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(842,3): error : linker command failed with exit code 1 (use -v to see invocation)

**### do i miss something?**

**Comment by SotoiGhost** [comment]
@chenjeff622 Can you add `Xamarin.Build.Download` NuGet to your project and try again? There's an [issue][1] right now with NuGet where it doesn't load the .props and .targets files of a Nuget's dependency. The workaround of this is to add NuGet's dependencies explicitly to your project.

Please, let me know your results.

[1]: https://github.com/NuGet/Home/issues/8694

**Comment by SotoiGhost** [comment]
We have not received the requested information. If you are still experiencing this issue, please, open a new issue related to this. Thanks!
