### ISSUE TITLE
Xamarin.Firebase.IOS.CloudMessaging not working in background

### ISSUE THREAD

**Issue by andreybutko** [xamarin/GoogleApisForiOSComponents#335]
Hi, I've integrated your Xamarin.Firebase.IOS.CloudMessaging 4.1.1.1 and it works well but only when the app is running. When app in background - notifications not receiving, and if open app - notification showed. 
This is Xamarin.Forms (4.3.0.908675) project
Maybe I missed something, could you help me with it? I've done everything line in your sample, only 
HandleMessage looks like this

     void HandleMessage(NSDictionary message)
        {
                var apsDictionary = message["notification"] as NSDictionary;

                string title = apsDictionary["title"].ToString();
                string body = apsDictionary["body"].ToString();

                var notification = new UILocalNotification
                {
                    FireDate = NSDate.FromTimeIntervalSinceNow(5),
                    AlertAction = title,
                    AlertBody = body,
                    ApplicationIconBadgeNumber = 1,
                    SoundName = UILocalNotification.DefaultSoundName
                };

                UIApplication.SharedApplication.ScheduleLocalNotification(notification);
        }

Thank you in advance!

**Comment by SotoiGhost** [comment]
@andreybutko Can you provide a test case, please? I have tested our sample and background notifications seem to be working. Also, double-check that you have granted permission to the app to receive notifications.

**Comment by andreybutko** [comment]
@SotoiGhost in Info.plist I've checked Background Modes (Remote-Notifications). All settings the same as in the sample. I will try to create a test case and send you it. Also, I think it's better to have not only code of some part but a whole solution, then I could run it without any additional actions and make sure it works. Could you send the whole solution which you tested? Thank you in advance!

**Comment by andreybutko** [comment]
@SotoiGhost I've sent you invite to repo, there are test case.

**Comment by SotoiGhost** [comment]
@andreybutko If you want to test our sample, clone the repo and do the following steps:

1. Install the prerequisites specified in the [Readme.md][1] file
2. Run `dotnet cake -t=externals -names=Firebase.CloudMessaging` in the root folder
3. Open the solution, select `CloudMessagingSample` and run the sample.

I'll check your test case in a bit.

[1]: https://github.com/xamarin/GoogleApisForiOSComponents/blob/master/Readme.md#prerequisites

**Comment by SotoiGhost** [comment]
@andreybutko I cannot run your test case. I'm getting the following error message:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Xamarin.Forms.Xaml.XamlParseException: No embeddedresource found for OpenTempMobile.Core.FormsApp
  at Xamarin.Forms.Xaml.XamlLoader.Load (System.Object view, System.Type callingType) [0x00012] in D:\a\1\s\Xamarin.Forms.Xaml\XamlLoader.cs:70
  at Xamarin.Forms.Xaml.Extensions.LoadFromXaml[TXaml] (TXaml view, System.Type callingType) [0x00000] in <259f52496377443d865b8c8369a28aab>:0
  at OpenTempMobile.Core.FormsApp.InitializeComponent () [0x00001] in /Users/israelsoto/GitHub/andreybutko/firebasePushes/OpenTempMobile/OpenTempMobile/OpenTemp.Core/obj/Debug/netstandard2.0/FormsApp.xaml.g.cs:21
  at OpenTempMobile.Core.FormsApp..ctor () [0x00008] in /Users/israelsoto/GitHub/andreybutko/firebasePushes/OpenTempMobile/OpenTempMobile/OpenTemp.Core/FormsApp.xaml.cs:12
  at at (wrapper managed-to-native) System.Reflection.RuntimeConstructorInfo.InternalInvoke(System.Reflection.RuntimeConstructorInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00005] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:936
  --- End of inner exception stack trace ---
  at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00018] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:944
  at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic, System.Boolean wrapExceptions) [0x00095] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/mcs/class/corlib/ReferenceSources/RuntimeType.cs:185
  at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean wrapExceptions, System.Boolean skipCheckThis, System.Boolean fillCache) [0x00009] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/mcs/class/corlib/ReferenceSources/RuntimeType.cs:155
  at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Boolean wrapExceptions, System.Threading.StackCrawlMark& stackMark) [0x00027] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/mcs/class/referencesource/mscorlib/system/rttype.cs:5736
  at System.Activator.CreateInstance[T] () [0x00015] in <0e400f473a3e4716a829e46ba2f1f0d6>:0
  at MvvmCross.Forms.Platforms.Ios.Core.MvxFormsIosSetup`2[TApplication,TFormsApplication].CreateFormsApplication () [0x00000] in <68932d1f86744f858420e223858895e6>:0
  at MvvmCross.Forms.Platforms.Ios.Core.MvxFormsIosSetup.get_FormsApplication () [0x00014] in C:\projects\mvvmcross\MvvmCross.Forms\Platforms\Ios\Core\MvxFormsIosSetup.cs:59
  at MvvmCross.Forms.Platforms.Ios.Core.MvxFormsIosSetup.CreateViewPresenter () [0x00000] in C:\projects\mvvmcross\MvvmCross.Forms\Platforms\Ios\Core\MvxFormsIosSetup.cs:80
  at MvvmCross.Platforms.Ios.Core.MvxIosSetup.get_Presenter () [0x00000] in C:\projects\mvvmcross\MvvmCross\Platforms\Ios\Core\MvxIosSetup.cs:97
  at MvvmCross.Platforms.Ios.Core.MvxIosSetup.RegisterPresenter () [0x00000] in C:\projects\mvvmcross\MvvmCross\Platforms\Ios\Core\MvxIosSetup.cs:109
  at MvvmCross.Platforms.Ios.Core.MvxIosSetup.InitializePlatformServices () [0x00006] in C:\projects\mvvmcross\MvvmCross\Platforms\Ios\Core\MvxIosSetup.cs:73
  at MvvmCross.Core.MvxSetup.InitializePrimary () [0x00052] in C:\projects\mvvmcross\MvvmCross\Core\MvxSetup.cs:74
  at MvvmCross.Core.MvxSetupSingleton.StartSetupInitialization () [0x0000a] in C:\projects\mvvmcross\MvvmCross\Core\MvxSetupSingleton.cs:181
  at MvvmCross.Core.MvxSetupSingleton.EnsureInitialized () [0x00017] in C:\projects\mvvmcross\MvvmCross\Core\MvxSetupSingleton.cs:102
  at MvvmCross.Forms.Platforms.Ios.Core.MvxFormsApplicationDelegate.FinishedLaunching (UIKit.UIApplication uiApplication, Foundation.NSDictionary launchOptions) [0x00029] in C:\projects\mvvmcross\MvvmCross.Forms\Platforms\Ios\Core\MvxFormsApplicationDelegate.cs:29
  at OpenTemp.iOS.AppDelegate.FinishedLaunching (UIKit.UIApplication app, Foundation.NSDictionary options) [0x0002a] in /Users/israelsoto/GitHub/andreybutko/firebasePushes/OpenTempMobile/OpenTempMobile.iOS/AppDelegate.cs:30
  at at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.6.0.12/src/Xamarin.iOS/UIKit/UIApplication.cs:86
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.6.0.12/src/Xamarin.iOS/UIKit/UIApplication.cs:65
  at OpenTemp.iOS.Application.Main (System.String[] args) [0x00001] in /Users/israelsoto/GitHub/andreybutko/firebasePushes/OpenTempMobile/OpenTempMobile.iOS/Main.cs:9
```

**Comment by andreybutko** [comment]
@SotoiGhost Yeah, I've forgot to say that I can't give you access to firebase messaging account, so you should use your, I don't know how to do it in another way, tell me if you know.

**Comment by SotoiGhost** [comment]
@andreybutko Seems that `DidReceiveNotificationResponse` method is the one who is catching all the notifications in the foreground and background. Do you have any logic there?

**Comment by andreybutko** [comment]
@SotoiGhost I have completionHandler(); there and nothing else.

**Comment by SotoiGhost** [comment]
@andreybutko Please, delete that method and try again.

**Comment by andreybutko** [comment]
@SotoiGhost tried, but nothing

**Comment by Alexander-Alekseev** [comment]
Hi @SotoiGhost,

I've added Xamarin.Firebase.iOS.CloudMessaging 4.1.1.1 to my project today and I faced with the same problem: if app is in foreground the messages are being received by the app, if app is in background (just in background, even not force closed) then app doesn't receive messages. Once I open my app (make it foreground again) then messages are being received again.

`public override void DidReceiveRemoteNotification(UIApplication application, NSDictionary userInfo, Action<UIBackgroundFetchResult> completionHandler)` - this method is not called ever.

`[Export("messaging:didReceiveMessage:")]
        public void DidReceiveMessage(Messaging messaging, RemoteMessage remoteMessage)` - this method is called once app is in foreground.

I've done all things according to https://github.com/xamarin/GoogleApisForiOSComponents/blob/master/docs/Firebase/CloudMessaging/GettingStarted.md#setting-up-a-firebase-cloud-messaging-client-app-on-ios, except this one:

> 3. Open GoogleService-Info.plist file and change IS_GCM_ENABLED value to Yes.

I see no reason why I have to change file generated by Firebase, I have never did this in my Objective-C iOS apps and push notifications worked very well.

I understand that test project will be welcome, but I have a big one under NDA here... What else could be helpful for you? 

---

Not 100% sure that the following bug is related, but anyway: one month ago I faced with the similar problem in my Android app (https://github.com/xamarin/GooglePlayServicesComponents/issues/273): push notifications work both in foreground and in background, but app has never receive them when app is unloaded (force closed). So, maybe this problem is not in Android/iOS components but much deeper in Xamarin itself? Just a thought...

**Comment by nguyenminh92** [comment]
I am also receiving the same issue as well. When app is open, notification comes through DidReceiveMessage method. However if app is in background or off, notification does not come.

**Comment by Alexander-Alekseev** [comment]
@nguyenminh92,

You can use this (though there are several ways to do it):
1) Select GoogleService-Info.plist.
2) RMB -> Open With... -> Generic PList Editor.
3) Change value at the 'Value' column for desired 'Property' (or create one if needed).
![image](https://user-images.githubusercontent.com/32123066/69696322-6a4f5180-10f0-11ea-81bc-8a20fbaf63d8.png)

**Comment by yceron** [comment]
I'm experiencing the same issue. Any updates?

**Comment by yceron** [comment]
I was able to solve my issue.

Since this wasn’t working, I was going to implement Microsoft App Center Push and I saw something on their documentation that I hadn’t seen on the Firebase documentation and it’s that you need to enable push notifications on the application on the **Entitlements.plist**.

In my case, I also hadn’t enabled Push Notifications for the app identifier on the Apple Developer Portal. After making both these changes and creating a provisioning profile for the app id of my app (not a wildcard provisioning profile) I was able to receive notifications on my phone.
I hope this can help others with the same problem.

**Comment by nguyenminh92** [comment]
@yceron Just wanted to confirm. My case was indeed the missing APNS certification for the Identifier. Thanks for helping me solve this issue!

**Comment by Alexander-Alekseev** [comment]
You guys didn't have APNS certificate but still were able to receive push notifications when app is in foreground? This is very strange and definitely not my case.

**Comment by Alexander-Alekseev** [comment]
@SotoiGhost, hi, any updates here?

**Comment by SotoiGhost** [comment]
@andreybutko Playing with your test case, removing the `WillPresentNotification` and `DidReceiveNotificationResponse` made the trick to make it work.

**Comment by Alexander-Alekseev** [comment]
@SotoiGhost,
I don't have WillPresentNotification and DidReceiveNotificationResponse methods at all, but my app receives pushes only in foreground.

**Comment by SotoiGhost** [comment]
@Alexander-Alekseev can you provide a test case, please?  Thanks in advance!

**Comment by Alexander-Alekseev** [comment]
@SotoiGhost,

[Here ](https://gist.github.com/Alexander-Alekseev/d1567ebd5ead2b781bd5a9d294c1d344 )is my AppDelegate.cs. Could it be helpful for you?

**Comment by SotoiGhost** [comment]
@Alexander-Alekseev Sorry for the very late response…

I tested your `AppDelegate.cs` with just the logic of Firebase Cloud Messaging and everything seems to be working ok. My suggestion is to remove other components one by one, to see which ones are in conflict.

**Comment by SotoiGhost** [comment]
We have not received the requested information. If you are still experiencing this issue, please, open a new issue related to this. Thanks!

**Comment by dbarbary** [comment]
Hello, I've already posted this in the [Xamarin Forms](https://forums.xamarin.com/discussion/comment/412686/#Comment_412686) as well, but I think its a bit stale over there. So, I'll hope to get answers here too. 

I've seem to find my self in a rut. I cannot seem to receive a push message on an iOS device.
I feel like I've followed all available docs on the topic, which seem to be referencing older versions of the firebase package.

Is anyone using Xamarin.Firebase.iOS.CloudMessaging 4.3.0 ? I

Any help is appreciated.

I've confirmed that messages are being sent, just not received. and I do get a token form FCM service.

Xamarin Packages installed in VS2019 Solution
![image](https://user-images.githubusercontent.com/22451511/82933257-e400b480-9f46-11ea-8aad-a4744b700b96.png)

The AppDelegate file

``` C#
using System;
using System.Collections.Generic;
using System.Linq;
using Rg.Plugins.Popup.Extensions;
using Foundation;
using UIKit;
using Newtonsoft.Json.Linq;
using UserNotifications;
using Firebase.CloudMessaging;
using Firebase.Core;
using Badge.Plugin;
using Xamarin.Forms;

namespace Solution.iOS
{

[Register("AppDelegate")]
public partial class AppDelegate : global::Xamarin.Forms.Platform.iOS.FormsApplicationDelegate, IUNUserNotificationCenterDelegate, IMessagingDelegate 
{

    public override bool FinishedLaunching(UIApplication app, NSDictionary options)
    {
        Rg.Plugins.Popup.Popup.Init();
        global::Xamarin.Forms.Forms.Init();
        LoadApplication(new App(BuildConfig));


        if (UIDevice.CurrentDevice.CheckSystemVersion(10, 0))
        {
            // For iOS 10 display notification (sent via APNS)
            UNUserNotificationCenter.Current.Delegate = this;

            var authOptions = UNAuthorizationOptions.Alert | UNAuthorizationOptions.Badge | UNAuthorizationOptions.Sound;
            UNUserNotificationCenter.Current.RequestAuthorization(authOptions, (granted, error) =>
            {
                Console.WriteLine(granted);
            });

            // For iOS 10 display notification (sent via APNS)
            UNUserNotificationCenter.Current.Delegate = this;

        }
        else
        {
            // iOS 9 or before

            var settings = UIUserNotificationSettings.GetSettingsForTypes(UIUserNotificationType.Alert | UIUserNotificationType.Badge | UIUserNotificationType.Sound, new NSSet());
            UIApplication.SharedApplication.RegisterUserNotificationSettings(settings);
        }

        UIApplication.SharedApplication.RegisterForRemoteNotifications();

        // Firebase component initialize

        Firebase.Core.App.Configure();
        Messaging.SharedInstance.Delegate = this;

        Firebase.InstanceID.InstanceId.Notifications.ObserveTokenRefresh((sender, e) =>
        {
            Firebase.InstanceID.InstanceId.SharedInstance.GetInstanceId((result, error) =>
            {
                if (error == null)
                {
                    string token = result.Token;
                    Console.WriteLine("Got a notification token: " + token);

                }
                else
                {
                    Console.WriteLine("couldn't get Firebase Token: " + error);
                }
            });

            connectFCM();
        });
        return base.FinishedLaunching(app, options);
    }

    public override void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken)
    {
        Messaging.SharedInstance.ApnsToken = deviceToken;

    // Seems that there is no equivalent to SetApnsToken in the new version
        //Firebase.InstanceID.InstanceId.SharedInstance.SetApnsToken(deviceToken, Firebase.InstanceID.ApnsTokenType.Unknown);

    }

    public override void OnActivated(UIApplication uiApplication)
    {
        global::Xamarin.Forms.Forms.Init();

        base.OnActivated(uiApplication);
    }

    public override void DidEnterBackground(UIApplication uiApplication)
    {

    }


    public override void DidReceiveRemoteNotification(UIApplication application, NSDictionary userInfo, Action<UIBackgroundFetchResult> completionHandler)
    {

        Messaging.SharedInstance.AppDidReceiveMessage(userInfo);

        // Generate custom event
        NSString[] keys = { new NSString("Event_type") };
        NSObject[] values = { new NSString("Recieve_Notification") };
        var parameters = NSDictionary<NSString, NSObject>.FromObjectsAndKeys(keys, values, keys.Length);

        // Send custom event
        Firebase.Analytics.Analytics.LogEvent("CustomEvent", parameters);

        if (application.ApplicationState == UIApplicationState.Active)
        {
            System.Diagnostics.Debug.WriteLine(userInfo);
            var aps_d = userInfo["aps"] as NSDictionary;
            var alert_d = aps_d["alert"] as NSDictionary;
            var body = alert_d["body"] as NSString;
            var title = alert_d["title"] as NSString;
            var category_d = aps_d["category"] as NSDictionary;
        }
    }


    // iOS 10, fire when recieve notification foreground
    [Export("userNotificationCenter:willPresentNotification:withCompletionHandler:")]
    public void WillPresentNotification(UNUserNotificationCenter center, UNNotification notification, Action<UNNotificationPresentationOptions> completionHandler)
    {
        var title = notification.Request.Content.Title;
        var body = notification.Request.Content.Body;
        var view = notification.Request.Content.CategoryIdentifier;

        debugAlert("Notification: "+title, body);

    }

    public void ApplicationReceivedRemoteMessage(RemoteMessage remoteMessage)
    {
        System.Diagnostics.Debug.WriteLine(remoteMessage.AppData);
        var title = remoteMessage.AppData.ValueForKey(new NSString("title"));
        var text = remoteMessage.AppData.ValueForKey(new NSString("text"));
        debugAlert("" + title, "" + text);
    }

    [Export("userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:")]
    public void DidReceiveNotificationResponse(UNUserNotificationCenter center, UNNotificationResponse response, Action completionHandler)
    {
        System.Diagnostics.Debug.WriteLine(response.Notification); // this is used when app is in background and comes to foreground

        var title = response.Notification.Request.Content.Title;
        var body = response.Notification.Request.Content.Body;

        var redirectView = "NotificationsListView";

            if (redirectView != null || redirectView != "")
            {
                App.loadView(redirectView);

            }
    }




    private void connectFCM()
    {
        // In the older version the code below was required, now I don know if in the new version the code below has a
    // replacement or not, but I can only assume the ".Connect" is the missing piece to this.
        //Messaging.SharedInstance.Connect((error) =>
        //{
        //    if (error == null)
        //    {
        //        // Messaging.SharedInstance.Subscribe("/topics/all");
        //    }
        //    System.Diagnostics.Debug.WriteLine(error != null ? "error occured" : "connect success");
        //});
    }

    private void debugAlert(string title, string message)
    {

        App.notificationCountToTakeAction = +1;
        App.notificationMessages.Add(message);
        var alert = new UIAlertView(title ?? "Title", message ?? "Message", null, "OK", null);
        alert.Show();

    }

    //[Export("messaging:didRefreshRegistrationToken")]
    public void DidRefreshRegistrationToken(Messaging messaging, string fcmToken)
    {
        // Obsolete interface
        Console.WriteLine(messaging.FcmToken +" | "+fcmToken);
    }

    [Export("messaging:didReceiveRegistrationToken:")]
    public void DidReceiveRegistrationToken(Messaging messaging, string fcmToken)
    {
        App.AppRegistrationToken = fcmToken.ToString();
        App.AppRegistrationTokens[0] = App.AppRegistrationToken;
        var data = DependencyService.Get<IAccessTokenFile>().LoadText("DeviceToken");
        if (data != null)
        {
            if (data[0] != "")
            {
                DependencyService.Get<IAccessTokenFile>().DeleteData("DeviceToken");
                DependencyService.Get<IAccessTokenFile>().CreateLogin("DeviceToken", App.AppRegistrationTokens);
            }
            else
            {
                DependencyService.Get<IAccessTokenFile>().CreateLogin("DeviceToken", App.AppRegistrationTokens);
            }
        }
        else
        {
            DependencyService.Get<IAccessTokenFile>().CreateLogin("DeviceToken", App.AppRegistrationTokens);
        }
        App.CheckDeviceForNotificationRegistration();
    }
}
}
```
Can anyone see why the code will not receive the message?

**Comment by ali-alhuwswe** [comment]
> Hello, I've already posted this in the [Xamarin Forms](https://forums.xamarin.com/discussion/comment/412686/#Comment_412686) as well, but I think its a bit stale over there. So, I'll hope to get answers here too.
> 
> I've seem to find my self in a rut. I cannot seem to receive a push message on an iOS device.
> I feel like I've followed all available docs on the topic, which seem to be referencing older versions of the firebase package.
> 
> Is anyone using Xamarin.Firebase.iOS.CloudMessaging 4.3.0 ? I
> 
> Any help is appreciated.
> 
> I've confirmed that messages are being sent, just not received. and I do get a token form FCM service.
> 
> Xamarin Packages installed in VS2019 Solution
> ![image](https://user-images.githubusercontent.com/22451511/82933257-e400b480-9f46-11ea-8aad-a4744b700b96.png)
> 
> The AppDelegate file
> 
> ```cs
> using System;
> using System.Collections.Generic;
> using System.Linq;
> using Rg.Plugins.Popup.Extensions;
> using Foundation;
> using UIKit;
> using Newtonsoft.Json.Linq;
> using UserNotifications;
> using Firebase.CloudMessaging;
> using Firebase.Core;
> using Badge.Plugin;
> using Xamarin.Forms;
> 
> namespace Solution.iOS
> {
> 
> [Register("AppDelegate")]
> public partial class AppDelegate : global::Xamarin.Forms.Platform.iOS.FormsApplicationDelegate, IUNUserNotificationCenterDelegate, IMessagingDelegate 
> {
> 
>     public override bool FinishedLaunching(UIApplication app, NSDictionary options)
>     {
>         Rg.Plugins.Popup.Popup.Init();
>         global::Xamarin.Forms.Forms.Init();
>         LoadApplication(new App(BuildConfig));
> 
> 
>         if (UIDevice.CurrentDevice.CheckSystemVersion(10, 0))
>         {
>             // For iOS 10 display notification (sent via APNS)
>             UNUserNotificationCenter.Current.Delegate = this;
> 
>             var authOptions = UNAuthorizationOptions.Alert | UNAuthorizationOptions.Badge | UNAuthorizationOptions.Sound;
>             UNUserNotificationCenter.Current.RequestAuthorization(authOptions, (granted, error) =>
>             {
>                 Console.WriteLine(granted);
>             });
> 
>             // For iOS 10 display notification (sent via APNS)
>             UNUserNotificationCenter.Current.Delegate = this;
> 
>         }
>         else
>         {
>             // iOS 9 or before
> 
>             var settings = UIUserNotificationSettings.GetSettingsForTypes(UIUserNotificationType.Alert | UIUserNotificationType.Badge | UIUserNotificationType.Sound, new NSSet());
>             UIApplication.SharedApplication.RegisterUserNotificationSettings(settings);
>         }
> 
>         UIApplication.SharedApplication.RegisterForRemoteNotifications();
> 
>         // Firebase component initialize
> 
>         Firebase.Core.App.Configure();
>         Messaging.SharedInstance.Delegate = this;
> 
>         Firebase.InstanceID.InstanceId.Notifications.ObserveTokenRefresh((sender, e) =>
>         {
>             Firebase.InstanceID.InstanceId.SharedInstance.GetInstanceId((result, error) =>
>             {
>                 if (error == null)
>                 {
>                     string token = result.Token;
>                     Console.WriteLine("Got a notification token: " + token);
> 
>                 }
>                 else
>                 {
>                     Console.WriteLine("couldn't get Firebase Token: " + error);
>                 }
>             });
> 
>             connectFCM();
>         });
>         return base.FinishedLaunching(app, options);
>     }
> 
>     public override void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken)
>     {
>         Messaging.SharedInstance.ApnsToken = deviceToken;
> 
>     // Seems that there is no equivalent to SetApnsToken in the new version
>         //Firebase.InstanceID.InstanceId.SharedInstance.SetApnsToken(deviceToken, Firebase.InstanceID.ApnsTokenType.Unknown);
> 
>     }
> 
>     public override void OnActivated(UIApplication uiApplication)
>     {
>         global::Xamarin.Forms.Forms.Init();
> 
>         base.OnActivated(uiApplication);
>     }
> 
>     public override void DidEnterBackground(UIApplication uiApplication)
>     {
> 
>     }
> 
> 
>     public override void DidReceiveRemoteNotification(UIApplication application, NSDictionary userInfo, Action<UIBackgroundFetchResult> completionHandler)
>     {
> 
>         Messaging.SharedInstance.AppDidReceiveMessage(userInfo);
> 
>         // Generate custom event
>         NSString[] keys = { new NSString("Event_type") };
>         NSObject[] values = { new NSString("Recieve_Notification") };
>         var parameters = NSDictionary<NSString, NSObject>.FromObjectsAndKeys(keys, values, keys.Length);
> 
>         // Send custom event
>         Firebase.Analytics.Analytics.LogEvent("CustomEvent", parameters);
> 
>         if (application.ApplicationState == UIApplicationState.Active)
>         {
>             System.Diagnostics.Debug.WriteLine(userInfo);
>             var aps_d = userInfo["aps"] as NSDictionary;
>             var alert_d = aps_d["alert"] as NSDictionary;
>             var body = alert_d["body"] as NSString;
>             var title = alert_d["title"] as NSString;
>             var category_d = aps_d["category"] as NSDictionary;
>         }
>     }
> 
> 
>     // iOS 10, fire when recieve notification foreground
>     [Export("userNotificationCenter:willPresentNotification:withCompletionHandler:")]
>     public void WillPresentNotification(UNUserNotificationCenter center, UNNotification notification, Action<UNNotificationPresentationOptions> completionHandler)
>     {
>         var title = notification.Request.Content.Title;
>         var body = notification.Request.Content.Body;
>         var view = notification.Request.Content.CategoryIdentifier;
> 
>         debugAlert("Notification: "+title, body);
> 
>     }
> 
>     public void ApplicationReceivedRemoteMessage(RemoteMessage remoteMessage)
>     {
>         System.Diagnostics.Debug.WriteLine(remoteMessage.AppData);
>         var title = remoteMessage.AppData.ValueForKey(new NSString("title"));
>         var text = remoteMessage.AppData.ValueForKey(new NSString("text"));
>         debugAlert("" + title, "" + text);
>     }
> 
>     [Export("userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:")]
>     public void DidReceiveNotificationResponse(UNUserNotificationCenter center, UNNotificationResponse response, Action completionHandler)
>     {
>         System.Diagnostics.Debug.WriteLine(response.Notification); // this is used when app is in background and comes to foreground
> 
>         var title = response.Notification.Request.Content.Title;
>         var body = response.Notification.Request.Content.Body;
> 
>         var redirectView = "NotificationsListView";
> 
>             if (redirectView != null || redirectView != "")
>             {
>                 App.loadView(redirectView);
> 
>             }
>     }
> 
> 
> 
> 
>     private void connectFCM()
>     {
>         // In the older version the code below was required, now I don know if in the new version the code below has a
>     // replacement or not, but I can only assume the ".Connect" is the missing piece to this.
>         //Messaging.SharedInstance.Connect((error) =>
>         //{
>         //    if (error == null)
>         //    {
>         //        // Messaging.SharedInstance.Subscribe("/topics/all");
>         //    }
>         //    System.Diagnostics.Debug.WriteLine(error != null ? "error occured" : "connect success");
>         //});
>     }
> 
>     private void debugAlert(string title, string message)
>     {
> 
>         App.notificationCountToTakeAction = +1;
>         App.notificationMessages.Add(message);
>         var alert = new UIAlertView(title ?? "Title", message ?? "Message", null, "OK", null);
>         alert.Show();
> 
>     }
> 
>     //[Export("messaging:didRefreshRegistrationToken")]
>     public void DidRefreshRegistrationToken(Messaging messaging, string fcmToken)
>     {
>         // Obsolete interface
>         Console.WriteLine(messaging.FcmToken +" | "+fcmToken);
>     }
> 
>     [Export("messaging:didReceiveRegistrationToken:")]
>     public void DidReceiveRegistrationToken(Messaging messaging, string fcmToken)
>     {
>         App.AppRegistrationToken = fcmToken.ToString();
>         App.AppRegistrationTokens[0] = App.AppRegistrationToken;
>         var data = DependencyService.Get<IAccessTokenFile>().LoadText("DeviceToken");
>         if (data != null)
>         {
>             if (data[0] != "")
>             {
>                 DependencyService.Get<IAccessTokenFile>().DeleteData("DeviceToken");
>                 DependencyService.Get<IAccessTokenFile>().CreateLogin("DeviceToken", App.AppRegistrationTokens);
>             }
>             else
>             {
>                 DependencyService.Get<IAccessTokenFile>().CreateLogin("DeviceToken", App.AppRegistrationTokens);
>             }
>         }
>         else
>         {
>             DependencyService.Get<IAccessTokenFile>().CreateLogin("DeviceToken", App.AppRegistrationTokens);
>         }
>         App.CheckDeviceForNotificationRegistration();
>     }
> }
> }
> ```
> 
> Can anyone see why the code will not receive the message?


Did anyone find a solution i have everything here the same

**Comment by dbarbary** [comment]
Effectively some of my packages were out of date, updated various packages and I think most importantly be sure to enable push notifications in the Entitlements

![image](https://user-images.githubusercontent.com/22451511/87470415-f65bae00-c5d9-11ea-8f48-20c103d0865b.png)

**Comment by ali-alhuwswe** [comment]
> Effectively some of my packages were out of date, updated various packages and I think most importantly be sure to enable push notifications in the Entitlements
> 
> ![image](https://user-images.githubusercontent.com/22451511/87470415-f65bae00-c5d9-11ea-8f48-20c103d0865b.png)

I copied your code and now it working thanks

**Comment by dbarbary** [comment]
> copied your code

Haha, sometimes that's all it takes. =)
