### ISSUE TITLE
Xamarin.VS 4.2.0.628 Beta - Shows "Incomplete" and crashes on load

### ISSUE THREAD

**Issue by aherrick** [xamarin/GoogleApisForiOSComponents#34]
Using the latest Xamarin beta for VS + iOS 10 crashes when attempting to run solution.

![9-5-2016 5-39-57 pm](https://cloud.githubusercontent.com/assets/586671/18257333/d21f1b30-738f-11e6-8ec0-69a1b18be347.png)

**Comment by SotoiGhost** [comment]
Are you still facing this bug?

**Comment by aherrick** [comment]
I don't believe so!
