### ISSUE TITLE
Getting "ITMS-90809: Deprecated API Usage" from testflight while uploading the app.

### ISSUE THREAD

**Issue by remeesms** [xamarin/GoogleApisForiOSComponents#341]
While uploading my app to testflight I am getting the below error.

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs

I don't have any UIWebView Usage in my app, But when I search in my code I found there are reference in Firebase Auth Nuget, It seems firebase has fixed the issue but why still the reference there in Nuget Package. I found some reference as shown below.

```
Frameworks/FirebaseAuth.framework/Headers/FIRAuth.h (423, 39):            SFSafariViewController or UIWebview failed.
Frameworks/FirebaseAuth.framework/Headers/FIRAuth.h (426, 39):            SFSafariViewController or UIWebview.
Frameworks/FirebaseAuth.framework/Headers/FIRAuthErrors.h (302, 77):    /** Indicates that a network request within a SFSafariViewController or UIWebview failed.
Frameworks/FirebaseAuth.framework/Headers/FIRAuthErrors.h (306, 86):    /** Indicates that an internal error occurred within a SFSafariViewController or UIWebview.
Frameworks/FirebaseAuth.framework/Headers/FIRAuth.h (423, 39):            SFSafariViewController or UIWebview failed.
FirebaseAuth.framework/Headers/FIRAuth.h (426, 39):            SFSafariViewController or UIWebview.
```

By the way I am using the latest version of Firebase Auth. The firebase versions i am using given below.
```
<package id="Xamarin.Firebase.iOS.Analytics" version="5.1.4.1" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.Auth" version="6.2.1.1" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.CloudMessaging" version="4.1.1.1" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.Core" version="6.1.0" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.Database" version="6.0.0" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.InstanceID" version="4.2.1" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.Storage" version="3.4.0" targetFramework="xamarinios10" />
```

**Comment by remeesms** [comment]
@SotoiGhost Can you please give an update on this?

**Comment by remeesms** [comment]
@Redth @SotoiGhost  Any Update guys?

**Comment by Redth** [comment]
Looks like Firebase.Auth is using UIWebView?...  We'll have to check which one and if there's an update that addresses it, however in the meantime, I don't believe that should cause a rejection yet.  Also, are you using Xamarin.Forms? That would likely trigger the same warning.

**Comment by remeesms** [comment]
Not xamarin forums i am using Xamarin.IOS. I talk with the firebase team and they removed the UIWebView references from "Version 6.8.1 - September 10, 2019". I talk with apple support team and they said the app will stop submission of apps which have "UIWebView" reference. This is the email i got from appstore team

> Dear Developer,
> 
> We identified one or more issues with a recent delivery for your app, "Myapp Beta" 1.0.5 (2015). Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> 
> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
> 
> After you’ve corrected the issues, you can upload a new binary to App Store Connect.
> 
> Best regards,
> 
> The App Store Team

**Comment by Redth** [comment]
@sotoighost is off this week but he can have a look next week once he is back.

**Comment by remeesms** [comment]
@Redth  Ok,Thanks for the update.

**Comment by remeesms** [comment]
@Redth, @SotoiGhost Can anyone started looking in to this issue? Please give an update on this, Waiting for a release in app store.

**Comment by Redth** [comment]
Yes, @SotoiGhost is going to start looking at this very soon.  As far as I know Apple has not released any dates at which they intend to start enforcing this, and for now it's just a warning.  You can still release to the store with the warning.  The warning is relatively new, and while we understand there is definitely a sense of urgency around this matter, there is nothing that indicates it will be enforced in the immediate future.  In any case, this is definitely high on our list right now.

**Comment by remeesms** [comment]
Any Update on this guys?

**Comment by Redth** [comment]
Just an update from Apple's side: https://developer.apple.com/news/?id=12232019b

Apple will not reject app submissions for a bit yet.  The dates are:
 - No *new* apps will be accepted using UIWebView as of April 2020
 - No *updates* to existing apps will be accepted using UIWebView as of December 2020

This should put everyone a little bit more at ease.  We will be prioritizing this update work appropriately (it already _is_ a priority) and you should have an updated release in plenty of time to test before these dates.

**Comment by lilleydnSub** [comment]
Could be the same error but in ML Kit ?
https://github.com/xamarin/GoogleApisForiOSComponents/issues/369

**Comment by SotoiGhost** [comment]
@remeesms Firebase Auth v6.4.2 (a.k.a v6.15.0) has been released. This should contain the fix for the issue mentioned above. If something happens, please, let us know. Best!

**Comment by remeesms** [comment]
Let me update and check this.
