### ISSUE TITLE
Update bindings for Google Sign-In SDK to version 5.0.2 or higher

### ISSUE THREAD

**Issue by Stasan** [xamarin/GoogleApisForiOSComponents#346]
It is required to update Xamarin bindings for Google Sign-In SDK to use the latest version of a native SDK.
It is important to use the latest version to get fix related to the detecting of the user cancellation of the sign-in process. See the following issue for more details about this problem https://github.com/googlesamples/google-services/issues/426

**Comment by SotoiGhost** [comment]
Hi @Stasan! Letting you know that Google Sign-In for iOS v5.0.2 has been released! If you still face something related to this. Please, let us know! Best!
