### ISSUE TITLE
iOS Performance SDK: "Crashed: PHTFlatFilePhenotype", PHTHeterodyneSyncer

### ISSUE THREAD

**Issue by alexshikov** [xamarin/GoogleApisForiOSComponents#353]
We experience lots of crashes on iPhone 5 devices using Performance SDK 3.1.1.

The original issue is fixed in iOS Firebase SDK 6.9.0: https://github.com/firebase/firebase-ios-sdk/issues/3851

**Comment by SotoiGhost** [comment]
Hi @alexshikov! Letting you know that Firebase Performance Monitoring v3.1.9 (a.k.a 6.15.0) has been released! Hope this helps you! If something related to this happens, please, let us know. Best!
