### ISSUE TITLE
Cloud Firestore throws FIRFirestoreErrorDomain Code=14 “Failed to get document because the client is offline.”?

### ISSUE THREAD

**Issue by divyesh008** [xamarin/GoogleApisForiOSComponents#358]
I have use the Cloud Firestore for my Xamarin.iOS application and many time when i'm running the application it gives the same error. I'm not able to find it's solution yet.

**I have used below packages for cloud firestore:**

```
Xamarin.Firebase.iOS.CloudFirestore (version-0.13.3)
Xamarin.Firebase.iOS.Core (version-5.1.8)
Xamarin.Firebase.iOS.Storage (version-3.0.2)
```

![client is offline error](https://user-images.githubusercontent.com/10617244/73059391-a5d18680-3ebb-11ea-8a98-4f53360e3bb8.png)

**Also sometimes it throws cannot access closed stream error:**

![PF_Object disposed exception](https://user-images.githubusercontent.com/10617244/73059512-e29d7d80-3ebb-11ea-9f9b-b7a6f417436d.png)

**Comment by SotoiGhost** [comment]
Hi @divyesh008 Can you share us a test case with the issue, please? Thanks in advance!

**Comment by Redth** [comment]
We are closing this issue since no response was received.  Please open a new issue referring to this one if you have more information.
