### ISSUE TITLE
Can I make the sample below with Xamarin.iOS?

### ISSUE THREAD

**Issue by pulmuone** [xamarin/GoogleApisForiOSComponents#359]
Can I make the sample below with Xamarin.iOS?

https://developer.apple.com/documentation/vision/reading_phone_numbers_in_real_time

**Comment by SotoiGhost** [comment]
Hi @pulmuone! AFAIK, yes, the iOS team has bound Vision framework classes under `Vision` namespace. Hope this helps you.
