### ISSUE TITLE
Unable to log custom messages attached to Crashlytics on iOS

### ISSUE THREAD

**Issue by alexshikov** [xamarin/GoogleApisForiOSComponents#360]
According to the official documentation, it should be possible log custom message that will be attached to crash reports:
https://firebase.google.com/docs/crashlytics/customize-crash-reports#add_custom_log_messages

It actually did work previously using unofficial Fabric bindings. For example, that method worked and we saw message both in Fabric and Firebase consoles (before migration to Firebase libraries):
https://github.com/drungrin/Fabric.Sdk.Xamarin/blob/master/Sources/CrashlyticsKit.Touch/Crashlytics.cs#L94

Also, a similar method for Android actually works as expected `Crashlytics.Crashlytics.Log`

But the one available for iOS does not: `Crashlytics.SharedInstance.LogEvent`

We actually pretty much relied on this method and now all the important data missed for the new crash reports.

I assume that the proper method is simply missing.
But maybe we miss something? Is there anything we can try instead?

Note: 
The deprecation attribute method states that instead of `Crashlytics.LogEvent` an `Answers. LogCustomEvent` should be used. But this is not the same. We need to attach logs to crash reports only.

**Comment by alexshikov** [comment]
@SotoiGhost any news on this? This is a very important feature for precise crash details investigation. We're literally stuck with some issues on our iOS app, because we can't see additional traces.

Maybe you have an idea on how we can work-around it?

**Comment by SotoiGhost** [comment]
Hi @alexshikov! Sorry for the very late response.

I think you are looking for [`Crashlytics.Logging.Log`][1] and [`Crashlytics.Logging.NSLog`][2] methods. These are the bound methods for `CLSLog` and `CLSNSLog`. Also, we provided two extra methods [`LogCallerInformation`][3] and [`NSLogCallerInformation`][4] that includes some extra information by default to your log. It will have the following structure:

```
[path/to/Foo.cs]: [FooClassName].[MemberName] line [LineNumber] $ [Your log message]"
```

Hope this helps you!

Best!

[1]: https://github.com/xamarin/GoogleApisForiOSComponents/blob/master/source/Firebase/Crashlytics/Extensions.cs#L23
[2]: https://github.com/xamarin/GoogleApisForiOSComponents/blob/master/source/Firebase/Crashlytics/Extensions.cs#L38
[3]: https://github.com/xamarin/GoogleApisForiOSComponents/blob/master/source/Firebase/Crashlytics/Extensions.cs#L30
[4]: https://github.com/xamarin/GoogleApisForiOSComponents/blob/master/source/Firebase/Crashlytics/Extensions.cs#L46

**Comment by alexshikov** [comment]
@SotoiGhost wow! Thank you! Seems like these are the ones we are looking, indeed! :)
