### ISSUE TITLE
Xamarin.Google.iOS.MobileAds: UserRewarded event is not firing

### ISSUE THREAD

**Issue by dmanning23** [xamarin/GoogleApisForiOSComponents#363]
In the Xamarin.Google.iOS.MobileAds nuget package, the UserRewarded event is not firing after the use watches a rewarded video.

The event not firing is:
RewardBasedVideoAd.SharedInstance.UserRewarded

**Comment by SotoiGhost** [comment]
Hi @dmanning23! Xamarin.Google.iOS.MobileAds v7.53.1 has been release. Can you update and try again, please? Let us know your results. Best!

**Comment by dmanning23** [comment]
Thank you, confirmed that the latest build is firing the correct events.

Cheers!
