### ISSUE TITLE
Xamarin.Firebase.iOS.MLKit unable to build with iPhoneSimulator

### ISSUE THREAD

**Issue by dzeping96** [xamarin/GoogleApisForiOSComponents#367]
Hi,

As mentioned in subject, I installed Xamarin.Firebase.iOS.MLKit NuGet package, after that I try to build/debug with iPhoneSimulator, but it keeps showing message regarding Native linking failed.

![image](https://user-images.githubusercontent.com/23049317/74401468-4a603c00-4e5c-11ea-88ca-131e346bcb02.png)

But it is working completely fine if I build/debug with an actual device, may I know is MLKit have a limitation on simulator or it is a real issue regarding this?

I tried clean the folder XamarinBuildDownloadCache, but it doesn't help too.

**Details Information:**
• Xamarin.Firebase.iOS.MLKit - 0.13.0.2
• Xamarin.Firebase.iOS.MLKit.Common - 0.13.0.1
• Xamarin.Build.Download - 0.4.11 (As mentioned in [https://github.com/xamarin/GoogleApisForiOSComponents/issues/283](https://github.com/xamarin/GoogleApisForiOSComponents/issues/283))

Thank you!

**Comment by SotoiGhost** [comment]
@dzeping96 could you update to most recent version and try again?

**Comment by Redth** [comment]
We are closing this issue since no response was received.  Please open a new issue referring to this one if you have more information.
