### ISSUE TITLE
Includes Deprecated API UIWebView In Firebase ML

### ISSUE THREAD

**Issue by lilleydnSub** [xamarin/GoogleApisForiOSComponents#369]
Using MLKit it includes the API UIWebView, Which is a warning but in April  2020 Apple will stop accepting submissions with UIWebVew for new Apps. Existing Apps will stop accepting in December 2020  

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

Sample
[TestMLUpgrade.zip](https://github.com/xamarin/GoogleApisForiOSComponents/files/4214024/TestMLUpgrade.zip)

I cannot find any usage in the Headers but doing strings on file i can see it.

```
Davids-Mac-mini:TestML.app davidlilley$ pwd
/Users/xxx/Projects/TestMLUpgrade/TestML/bin/iPhone/Release/TestML.app

Davids-Mac-mini:TestML.app xx$ strings TestML | grep UIWebView
UIWebViewDelegate
c20@0:4@"UIWebView"8@"NSURLRequest"12i16
v12@0:4@"UIWebView"8
v16@0:4@"UIWebView"8@"NSError"12
@"UIWebView"
UIWebViewDelegate
B40@0:8@"UIWebView"16@"NSURLRequest"24q32
v24@0:8@"UIWebView"16
v32@0:8@"UIWebView"16@"NSError"24
@"UIWebView"

```

**Comment by lilleydnSub** [comment]
Could be the same error ? but in Firebase Auth
https://github.com/xamarin/GoogleApisForiOSComponents/issues/341

**Comment by SotoiGhost** [comment]
We are working in an update that contains this fix.
