### ISSUE TITLE
Couldn't cast the m3u8 video

### ISSUE THREAD

**Issue by basakserit** [xamarin/GoogleApisForiOSComponents#370]
I tried with the SDK 4.4.5 and 4.4.5.1 but could not cast the m3u8 formatted videos. We have this issue for a couple of days.

**Comment by SotoiGhost** [comment]
Hi @basakserit! Google Cast v4.4.6 has been released. Can you update and try again? Thanks in advance!

**Comment by onurhazar** [comment]
Hi @SotoiGhost We are having the same issue :/ I updated 4.4.6 and got build errors. I also updated Firebase iOS packages to latest version. 

![image](https://user-images.githubusercontent.com/5585009/75225152-17526c80-57bb-11ea-90a7-b44dbaa8ecd4.png)

Here is the error log:

> MTOUCH : warning MT5215: References to 'System' might require additional -framework=XXX or -lXXX instructions to the native linker
> MTOUCH : error MT5210: Native linking failed, undefined symbol: _APMAnalyticsConfiguration. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
> MTOUCH : error MT5210: Native linking failed, undefined symbol: _APMAppMeasurementOriginFirebase. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
> MTOUCH : error MT5210: Native linking failed, undefined symbol: _APMIsAnalyticsCollectionDeactivated. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
> MTOUCH : error MT5210: Native linking failed, undefined symbol: _APMIsAnalyticsCollectionEnabled. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
> MTOUCH : error MT5210: Native linking failed, undefined symbol: _APMMonitorLogTagOptionKey. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
> MTOUCH : error MT5210: Native linking failed, undefined symbol: _APMSafelistedEventsOptionKey. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
> MTOUCH : error MT5201: Native linking failed. Please review the build log and the user flags provided to gcc: -ObjC -lc++ -lsqlite3 -lz -lc++ -ObjC -lc++ -lsqlite3 -lz
> MTOUCH : error MT5202: Native linking failed. Please review the build log.
> clang : error : linker command failed with exit code 1 (use -v to see invocation)
>     65 Warning(s)
>     9 Error(s)
![errorlog](https://user-images.githubusercontent.com/5585009/75225108-fd188e80-57ba-11ea-8ebe-662433d5c681.png)

I also looked the firmware of our google cast devices:

![image](https://user-images.githubusercontent.com/5585009/75225215-3ea93980-57bb-11ea-833c-5413dbf55eaf.png)

Here is my environment:

> === Visual Studio Community 2019 for Mac ===
> 
> Version 8.4.5 (build 19)
> Installation UUID: cc984542-ac33-4954-87ba-2acd694f678c
> 	GTK+ 2.24.23 (Raleigh theme)
> 	Xamarin.Mac 5.16.1.25 (issue-7441-d16-3-vsmac / 881172e73)
> 
> 	Package version: 606000155
> 
> === Mono Framework MDK ===
> 
> Runtime:
> 	Mono 6.6.0.155 (2019-08/296a9afdb24) (64-bit)
> 	Package version: 606000155
> 
> === Roslyn (Language Service) ===
> 
> 3.4.0-beta4-19562-05+ff930dec4565e2bc424ad3bf3e22ecb20542c87d
> 
> === NuGet ===
> 
> Version: 5.3.0.6192
> 
> === .NET Core SDK ===
> 
> SDK: /usr/local/share/dotnet/sdk/3.1.101/Sdks
> SDK Versions:
> 	3.1.101
> 	3.1.100
> 	3.0.101
> 	3.0.100
> MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/msbuild/Current/bin/Sdks
> 
> === .NET Core Runtime ===
> 
> Runtime: /usr/local/share/dotnet/dotnet
> Runtime Versions:
> 	3.1.1
> 	3.1.0
> 	3.0.1
> 	3.0.0
> 	2.1.15
> 	2.1.14
> 	2.1.13
> 
> === Xamarin.Profiler ===
> 
> Version: 1.6.13.11
> Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler
> 
> === Updater ===
> 
> Version: 11
> 
> === Xamarin.Android ===
> 
> Version: 10.1.3.7 (Visual Studio Community)
> Commit: xamarin-android/d16-4/d66aed0
> Android SDK: /Users/onur.hazar/Library/Developer/Xamarin/android-sdk-macosx
> 	Supported Android versions:
> 		8.1 (API level 27)
> 
> SDK Tools Version: 26.1.1
> SDK Platform Tools Version: 29.0.5
> SDK Build Tools Version: 29.0.2
> 
> Build Information: 
> Mono: fd9f379
> Java.Interop: xamarin/java.interop/d16-4@c4e569f
> ProGuard: xamarin/proguard/master@905836d
> SQLite: xamarin/sqlite/3.28.0@46204c4
> Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b
> 
> === Microsoft Mobile OpenJDK ===
> 
> Java SDK: /Users/onur.hazar/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
> 1.8.0-25
> Android Designer EPL code available here:
> https://github.com/xamarin/AndroidDesigner.EPL
> 
> === Android SDK Manager ===
> 
> Version: 16.4.0.10
> Hash: 2c49a7d
> Branch: remotes/origin/d16-4
> Build date: 2020-01-30 10:22:44 UTC
> 
> === Android Device Manager ===
> 
> Version: 16.4.0.30
> Hash: f9172e2
> Branch: remotes/origin/d16-4
> Build date: 2020-01-30 10:23:04 UTC
> 
> === Xamarin Designer ===
> 
> Version: 16.4.0.479
> Hash: 074544417
> Branch: remotes/origin/d16-4
> Build date: 2020-01-22 22:50:22 UTC
> 
> === Apple Developer Tools ===
> 
> Xcode 11.3.1 (15715)
> Build 11C504
> 
> === Xamarin.Mac ===
> 
> Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.
> 
> === Xamarin.iOS ===
> 
> Version: 13.10.0.17 (Visual Studio Community)
> Hash: 5f802ef53
> Branch: xcode11.3
> Build date: 2020-01-07 11:53:06-0500
> 
> === Xamarin Inspector ===
> 
> Version: 1.4.3
> Hash: db27525
> Branch: 1.4-release
> Build date: Mon, 09 Jul 2018 21:20:18 GMT
> Client compatibility: 1
> 
> === Build Information ===
> 
> Release ID: 804050019
> Git revision: 5b9e12b8142016693a4b0f0bdac84ffac1d84c28
> Build date: 2020-02-07 12:51:25+00
> Build branch: release-8.4
> Xamarin extensions: 5b9e12b8142016693a4b0f0bdac84ffac1d84c28
> 
> === Operating System ===
> 
> Mac OS X 10.14.6
> Darwin 18.7.0 Darwin Kernel Version 18.7.0
>     Tue Aug 20 16:57:14 PDT 2019
>     root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

**Comment by onurhazar** [comment]
> I tried with the SDK 4.4.5 and 4.4.5.1 but could not cast the m3u8 formatted videos. We have this issue for a couple of days.

@basakserit 
I got this log while trying to cast (casting failed);

> Remote Player Status: Buffering
> GOOGLE CAST:-[GCKMediaControlChannel didReceiveTextMessage:] Received unexpected error: INVALID_REQUEST
> GOOGLE CAST:-[GCKMediaQueue request:didFailWithError:] error fetching queue item IDs: Error Domain=com.google.cast.GCKError Code=4 "Invalid request" UserInfo={gck_error_reason=INVALID_MEDIA_SESSION_ID, NSLocalizedDescription=Invalid request, gck_custom_data=INVALID_MEDIA_SESSION_ID}

**Comment by basakserit** [comment]
> Hi @basakserit! Google Cast v4.4.6 has been released. Can you update and try again? Thanks in advance!

I'm having the same problems with @onurhazar. We have the same build errors, unfortunately.

**Comment by SotoiGhost** [comment]
Guys, can you share a test case, please? Thanks in advance! Also, could you cast HLS videos before v4.4.5?

**Comment by SotoiGhost** [comment]
Guys, can you share a test case, please? Thanks in advance! Also, could you cast HLS videos before v4.4.5?

**Comment by basakserit** [comment]
> Guys, can you share a test case, please? Thanks in advance! Also, could you cast HLS videos before v4.4.5?

Yes, we could cast HLS videos in v4.5.5 before, but suddenly it's broken. I can share the video link and the m3u8 file.

HLS link: https://player.vimeo.com/external/78730857.m3u8?s=937769b820b77cff3d0286e526a56226121831e5

HLS file: 
[master.m3u8.zip](https://github.com/xamarin/GoogleApisForiOSComponents/files/4254307/master.m3u8.zip)

**Comment by SotoiGhost** [comment]
@basakserit @onurhazar I have tested the url shared and yes, I can reproduce the error mentioned above but I have tested with others HLS videos and everything seems working ok. I'm wondering if the video is corrupted somehow, do you have a way to check that?

I share you [the video list][1] that I have tested with no problems.

[1]: https://github.com/xamarin/GoogleApisForiOSComponents/files/4268155/Videos.json.zip

**Comment by basakserit** [comment]
Our issue is fixed, we also got in contact with the video platform we're using which is Vimeo. It could be related to that platform because as you said it works for the other HLS videos. Thank you @SotoiGhost
