### ISSUE TITLE
dyld: Library not loaded: @rpath/protobuf.framework/protobuf

### ISSUE THREAD

**Issue by stepheaw** [xamarin/GoogleApisForiOSComponents#373]
After upgrading my nuget packages to Xamarin.Firebase.Auth 6.4.2, I am seeing a runtime error similar to [#322](https://github.com/xamarin/GoogleApisForiOSComponents/issues/322) 
I am using Xamarin.Firebase.iOS.CloudMessaging 4.1.1.1 

I get the error on app launch
`dyld: dependent dylib '@rpath/Protobuf.framework/Protobuf' not found for '/private/var/containers/Bundle/Application/9C77982B-C2D2-448B-8482-B012516643F4/myAppiOS.app/Frameworks/FirebaseMessaging.framework/FirebaseMessaging', tried but didn't find: '/private/var/containers/Bundle/Application/9C77982B-C2D2-448B-8482-B012516643F4/myAppiOS.app/Frameworks/Protobuf.framework/Protobuf' '/private/var/containers/Bundle/Application/9C77982B-C2D2-448B-8482-B012516643F4/myAppiOS.app/Frameworks/FirebaseMessaging.framework/Frameworks/Protobuf.framework/Protobuf' '/private/var/containers/Bundle/Application/9C77982B-C2D2-448B-8482-B012516643F4/myAppiOS.app/Frameworks/Protobuf.framework/Protobuf' '@rpath/Protobuf.framework/Protobuf' '/System/Library/Frameworks/Protobuf.framework/Protobuf'`

Prior to upgrading, I was using these versions:
**Xamarin.Firebase.iOS.Core 6.1.0
Xamarin.Firebase.iOS.Auth 6.2.1.1**
Xamarin.Firebase.iOS.CloudMessaging 4.1.1.1 
Xamarin.Firebase.iOS.InstanceID 4.2.1
Xamarin.Firebase.iOS.Database 6.0.0

After upgrading nuget packages I am using 
**Xamarin.Firebase.iOS.Core 6.6.0
Xamarin.Firebase.iOS.Auth 6.4.2**
Xamarin.Firebase.iOS.CloudMessaging 4.1.1.1 
Xamarin.Firebase.iOS.InstanceID 4.2.1
Xamarin.Firebase.iOS.Database 6.0.0

Is there anything wrong with my current configuration?

**Comment by SotoiGhost** [comment]
Hi @stepheaw! Sorry for the inconveniences that this can cause. Please, downgrade your NuGets by now, Cloud Messaging cannot work with most recent packages yet. We are working on an update to fix this. Best!

**Comment by matibak** [comment]
Who can benefit from the newest packages?

**Comment by Kingram91** [comment]
Any update on this?

My current Load-out is: 
<img width="273" alt="Screen Shot 2020-03-27 at 11 01 55 AM" src="https://user-images.githubusercontent.com/7969188/77769778-abae2a00-701a-11ea-926d-b75b9ceda3bd.png">

CRASH LOG: `Incident Identifier: 1172084D-9A5A-44A6-87B9-424C64775EBB
CrashReporter Key:   1d72313b9cb9d41b394f2e2cfb0d10fc521eb3d5
Hardware Model:      iPhone12,1
Process:            [REDACTED]
Path:                [REDACTED]
Identifier:          [REDACTED]
Version:             1.0 (1.0)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           [REDACTED]


Date/Time:           2020-03-26 17:15:42.8941 -0400
Launch Time:         2020-03-26 17:15:42.8879 -0400
OS Version:          iPhone OS 13.2 (17B84)
Release Type:        User
Baseband Version:    1.02.14
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, dependent dylib '@rpath/protobuf.framework/protobuf' not found for '/private/var/containers/Bundle/Application/[REDACTED]', tried but didn't find: '/private/var/containers/Bundle/Application/[REDACTED]/Frameworks/protobuf.framework/protobuf' '@rpath/protobuf.framework/protobuf' '/System/Library/Frameworks/protobuf.framework/protobuf'
Highlighted by Thread:  0`


Also, hope y'all are staying safe from COVID-19.

**Comment by MaxSmile** [comment]
Anybody can share versions of Nugets which works for sure?

**Comment by vhugogarcia** [comment]
I am having the same question @MaxSmile asked above.

**Comment by vhugogarcia** [comment]
It appears a PR is ready for final review which includes a fix for this issue, so we may get the fix soon 🙏
