### ISSUE TITLE
Using Xamarin.Firebase.iOS.Analytics in my app causes the App Store to reject app due to non-public API

### ISSUE THREAD

**Issue by christopherspence** [xamarin/GoogleApisForiOSComponents#374]
I have the Xamarin package Xamarin.Firebase.iOS.Analytics in my iOS app, and for some reason today I'm getting the following error when trying to submit my app to the app store

`ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/FirebaseCoreDiagnostics.framework/FirebaseCoreDiagnostics: initWithFileName:. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/`

Upgrading from 6.0.4.1 to 6.2.1 doesn't make a difference. Obviously I'm not calling that method in my code, my only references to Firebase are the following

AppDelegate.cs

```
public override bool FinishedLaunching(UIApplication app, NSDictionary options)
{
       // ...
       Firebase.Core.App.Configure();
       // ...
}
```
 and in my FirebaseEventService.cs class

```
[assembly: Dependency(typeof(FirebaseEventService))]
namespace Flikshop.iOS.Services
{
    public class FirebaseEventService : IFirebaseEventService
    {
        public void SendEvent(string eventId, IDictionary<string, string> parameters)
        {
            var keys = new List<NSString>();
            var values = new List<NSString>();
            foreach (var item in parameters)
            {
                keys.Add(new NSString(item.Key));
                values.Add(new NSString(item.Value));
            }

            var parametersDictionary = NSDictionary<NSString, NSObject>.FromObjectsAndKeys(values.ToArray(), keys.ToArray(), keys.Count);
           // HERE 
           Analytics.LogEvent(eventId, parametersDictionary);
        }
    }
}
```

**Comment by SotoiGhost** [comment]
Hi @christopherspence! Sorry for the inconveniences that this can cause. I have looked over Firebase dependencies and it seems `GoogleUtilities` framework is the guilty guy that is using that method name.
I have built the most recent version (6.5.1) of `GoogleUtilities` and the method is still there.

You can verify this by running the following command on [GoogleUtilities.framework][1]. You must have the following output:

```
nm -Umo path/to/GoogleUtilities.framework/GoogleUtilities | grep initWithFileName
GoogleUtilities: 0000000000004c8f (__TEXT,__text) non-external -[GULHeartbeatDateStorage initWithFileName:]
```

Please, file a bug on [Firebase iOS GitHub repo][2] about this.

Thanks in advance!

[1]: https://github.com/xamarin/GoogleApisForiOSComponents/files/4252479/GoogleUtilities.framework.zip
[2]: https://github.com/firebase/firebase-ios-sdk/issues/new?template=bug_report.md

**Comment by christopherspence** [comment]
thanks @SotoiGhost. I filed a bug in their repo https://github.com/firebase/firebase-ios-sdk/issues/4971

**Comment by SotoiGhost** [comment]
Thanks @christopherspence! I'll be pending about Google's resolution

**Comment by SotoiGhost** [comment]
@christopherspence So Firebase suggested that you need to appeal their rejection, seems reasonable for me as I find their rejection somewhat exaggerated. If Apple doesn't change their mind (I hope they will), tell Firebase so they can change that method name.

I'm closing this issue now but if you face something related to this, feel free to leave a comment.

Best!

**Comment by sschmidTU** [comment]
Our app was still rejected due do this today.
In [the issue at Firebase](https://github.com/firebase/firebase-ios-sdk/issues/4971), a Firebase team member [basically said it's not their problem, you should appeal to Apple, and there should be more SDKs out there that use such method names that match private apple names](https://github.com/firebase/firebase-ios-sdk/issues/4971).
It would be great if there was a better solution than [filing an Appeal to the Apple App Review Team](https://developer.apple.com/contact/app-store/?topic=appeal).

**Comment by jairzjunior** [comment]
Our app was rejected with the same error today.
We use **Xamarin.Firebase.iOS.CloudMessaging (4.3.0)** that is the latest version.

Apple said this:

> ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/FirebaseCoreDiagnostics.framework/FirebaseCoreDiagnostics: initWithFileName:. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

**Comment by maxmanager** [comment]
someone can help us?

**Comment by i-omar** [comment]
my app was rejected with the same error today also :
ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/FirebaseCore.framework/FirebaseCore: initWithFileName:,The app references non-public selectors in Frameworks/FirebaseCoreDiagnostics.framework/FirebaseCoreDiagnostics: initWithFileName:. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

**Comment by lukaszwro** [comment]
Same for me, just as @jairzjunior : We use Xamarin.Firebase.iOS.CloudMessaging (4.3.0) that is the latest version.

ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/FirebaseCore.framework/FirebaseCore: initWithFileName:,The app references non-public selectors in Frameworks/FirebaseCoreDiagnostics.framework/FirebaseCoreDiagnostics: initWithFileName:. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/
