### ISSUE TITLE
Dynamic links 4.0.1.1 still referencing UIWebView

### ISSUE THREAD

**Issue by davebarnesy** [xamarin/GoogleApisForiOSComponents#375]
I'm getting this warning when submitting my apps to Apple:

 ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs starting from April 2020 . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

If I remove my reference to Xamarin.Firebase.iOS.DynamicLinks I don't get the warning any more.

If I run this command: strings events.app | grep UIWebView

I get this output only when the dynamic links reference is in place:
UIWebViewDelegate
B40@0:8@"UIWebView"16@"NSURLRequest"24q32
v24@0:8@"UIWebView"16
v32@0:8@"UIWebView"16@"NSError"24
@"UIWebView"

This is getting urgent because Apple say the deadline for new apps is 'april': https://developer.apple.com/news/?id=12232019b

Thanks!

**Comment by PawKanarek** [comment]
Any update on this?

**Comment by davebarnesy** [comment]
Any updates?

**Comment by georgethms10** [comment]
@SotoiGhost The latest version of firebase dynamic deeplink is 4.0.1.1 the version 6.21.0 is not available for Xamarin forms. We need to submit an app to appstore, Can you please expedite this request and help us deploy the app to appstore. We are frequently getting the UIWebView issue when releasing the application.
