### ISSUE TITLE
Failed to resolve "ObjCRuntime.TrampolineBlockBase" reference from "Xamarin.iOS

### ISSUE THREAD

**Issue by Owlzy** [xamarin/GoogleApisForiOSComponents#377]
Hi,

So recently I had to recreate our Xamarin iOS project, and now firebase has broken.  We previously had some issues getting setup before, and it was a bit of an odd series of steps, so rather than try and replicate those steps (and use very old version of the plugin) it'd be nice to get setup properly so we can lock down our plugin version.

Currently I'm trying the latest version of Firebase Analytics (6.2.1) with Xamarin build (0.9.0) I get the following compile time error:

MTOUCH: Error MT2002: Failed to resolve "ObjCRuntime.TrampolineBlockBase" reference from "Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065" (MT2002) 

Any help much appreciated

**Comment by SotoiGhost** [comment]
Hi @Owlzy! Sorry for the inconveniences that this may cause. Can you share a test case of this, please? Also, can you share you environment info? Thanks in advance!

**Comment by Owlzy** [comment]
Hi @SotoiGhost , thanks for the prompt response!

In terms of a test case, I don't have any specific code I can share, but I am using MonoGame, so a blank MonoGame iOS template will fail when adding the firebase analytics plugin and dependencies.

Oddly I just found out I get a different error if a try a blank Xamarin project or a new MonoGame ios project.  In that case I get a whole load of linker errors as below:

`/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/playerthree/Desktop/PJMasksMonoLatest/dev/MonoEngine.Shared/test/obj/iPhone/Debug/response-file.rsp "--gcc_flags=-ObjC -lc++ -lsqlite3 -lz -ObjC -lc++ -lsqlite3 -lz"
Process exited with code 1, command:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -F /Users/playerthree/Library/Caches/XamarinBuildDownload/GAppM-6.2.1/Frameworks -framework GoogleAppMeasurement -framework Security -framework StoreKit -framework SystemConfiguration -framework UIKit -F /Users/playerthree/Library/Caches/XamarinBuildDownload/FAnlytcs-6.2.1/Frameworks -framework FirebaseAnalytics -framework AddressBook -framework AdSupport -framework CoreGraphics -F /Users/playerthree/Library/Caches/XamarinBuildDownload/FAnlytcs-6.2.1/Frameworks -framework FIRAnalyticsConnector -framework OpenGLES -framework MediaPlayer -framework GameController -framework CoreMotion -framework CoreMedia -framework QuartzCore -framework Foundation -framework AVFoundation -weak_framework CFNetwork -Xlinker -rpath -Xlinker @executable_path/Frameworks /Users/playerthree/Desktop/PJMasksMonoLatest/dev/MonoEngine.Shared/test/obj/iPhone/Debug/mtouch-cache/arm64/registrar.o /Users/playerthree/Desktop/PJMasksMonoLatest/dev/MonoEngine.Shared/test/obj/iPhone/Debug/mtouch-cache/arm64/main.o /Users/playerthree/Desktop/PJMasksMonoLatest/dev/MonoEngine.Shared/test/obj/iPhone/Debug/mtouch-cache/arm64/test.exe.o /Users/playerthree/Desktop/PJMasksMonoLatest/dev/MonoEngine.Shared/test/obj/iPhone/Debug/mtouch-cache/arm64/mscorlib.dll.o /Users/playerthree/Desktop/PJMasksMonoLatest/dev/MonoEngine.Shared/test/obj/iPhone/Debug/mtouch-cache/arm64/Xamarin.iOS.dll.o /Users/playerthree/Desktop/PJMasksMonoLatest/dev/MonoEngine.Shared/test/obj/iPhone/Debug/mtouch-cache/arm64/System.dll.o /Users/playerthree/Desktop/PJMasksMonoLatest/dev/MonoEngine.Shared/test/obj/iPhone/Debug/mtouch-cache/arm64/System.Core.dll.o /Users/playerthree/Desktop/PJMasksMonoLatest/dev/MonoEngine.Shared/test/obj/iPhone/Debug/mtouch-cache/arm64/MonoGame.Framework.dll.o /Users/playerthree/Desktop/PJMasksMonoLatest/dev/MonoEngine.Shared/test/obj/iPhone/Debug/mtouch-cache/arm64/System.Runtime.Serialization.dll.o /Library/Frameworks/Xamarin.iOS.framework/Versions/12.8.0.2/SDKs/MonoTouch.iphoneos.sdk/usr/lib/libmonosgen-2.0.a /Library/Frameworks/Xamarin.iOS.framework/Versions/12.8.0.2/SDKs/MonoTouch.iphoneos.sdk/usr/lib/libxamarin-debug.a -force_load /Library/Frameworks/Xamarin.iOS.framework/Versions/12.8.0.2/SDKs/MonoTouch.iphoneos.sdk/usr/lib/libapp.a -Wl,-pie -arch arm64 -miphoneos-version-min=11.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk -lz -liconv -o /Users/playerthree/Desktop/PJMasksMonoLatest/dev/MonoEngine.Shared/test/bin/iPhone/Debug/test.app/test -ObjC -lc++ -lsqlite3 -lz -ObjC -lc++ -lsqlite3 -lz -u _xamarin_find_protocol_wrapper_type -u _xamarin_release_block_on_main_thread -u _xamarin_get_block_descriptor -u _UIApplicationMain -u _mono_pmip
Undefined symbols for architecture arm64:
"_GULIsLoggableLevel", referenced from:
-[APMMonitor isLoggableLevel:] in GoogleAppMeasurement(APMMonitor_6fd5817ff749ff75b699098c72b12b0c.o)
"_GULLogBasic", referenced from:
-[APMASLLogger logMessage:logTag:messageCode:withLogLevel:] in GoogleAppMeasurement(APMASLLogger_cbca7aa31a2d8520e23d674de1044fb2.o)
"_GULLogError", referenced from:
+[APMAnalytics startWithAppID:origin:options:] in GoogleAppMeasurement(APMAnalytics_cb405cb8c995318bf496bd8f1041864f.o)
-[APMUserDefaults synchronize] in GoogleAppMeasurement(APMUserDefaults_f3b7c90f8714bc43c03de1e2759173f3.o)
"_GULLogInfo", referenced from:
___44+[UIViewController(APMScreenClassName) load]_block_invoke in GoogleAppMeasurement(UIViewController+APMScreenClassName_a2846f57c82bf63eac9b7186ed63bc4e.o)
"_GULLogWarning", referenced from:
+[APMMeasurement sharedInstance] in GoogleAppMeasurement(APMMeasurement_0b66c1c0500f6cd21583c995be8b6345.o)
-[APMUserDefaults objectForKey:] in GoogleAppMeasurement(APMUserDefaults_f3b7c90f8714bc43c03de1e2759173f3.o)
-[APMUserDefaults setObject:forKey:] in GoogleAppMeasurement(APMUserDefaults_f3b7c90f8714bc43c03de1e2759173f3.o)
-[APMUserDefaults synchronize] in GoogleAppMeasurement(APMUserDefaults_f3b7c90f8714bc43c03de1e2759173f3.o)
___44+[UIViewController(APMScreenClassName) load]_block_invoke in GoogleAppMeasurement(UIViewController+APMScreenClassName_a2846f57c82bf63eac9b7186ed63bc4e.o)
"_GULSetLoggerLevel", referenced from:
-[APMMonitor setDebugModeEnabled:] in GoogleAppMeasurement(APMMonitor_6fd5817ff749ff75b699098c72b12b0c.o)
-[APMMonitor setVerboseLoggingEnabled:] in GoogleAppMeasurement(APMMonitor_6fd5817ff749ff75b699098c72b12b0c.o)
"_OBJC_CLASS_$_FIRApp", referenced from:
objc-class-ref in FirebaseAnalytics(FIRAnalytics_bb540b7bc432fd4c54bf2d7f57c43305.o)
objc-class-ref in FIRAnalyticsConnector(FIRAnalyticsConnector_8094107d82c527bf23f93e98c9db96d1.o)
"_OBJC_CLASS_$_FIRComponent", referenced from:
objc-class-ref in FIRAnalyticsConnector(FIRAnalyticsConnector_8094107d82c527bf23f93e98c9db96d1.o)
"_OBJC_CLASS_$_FIROptions", referenced from:
objc-class-ref in FirebaseAnalytics(FIRAnalytics_bb540b7bc432fd4c54bf2d7f57c43305.o)
"_OBJC_CLASS_$_GULAppDelegateSwizzler", referenced from:
objc-class-ref in GoogleAppMeasurement(APMAnalytics_cb405cb8c995318bf496bd8f1041864f.o)
"_OBJC_CLASS_$_GULMutableDictionary", referenced from:
objc-class-ref in GoogleAppMeasurement(APMRemoteConfig_dd50b6066134949d54e0a07fc2f093d3.o)
"_OBJC_CLASS_$_GULNetwork", referenced from:
objc-class-ref in GoogleAppMeasurement(APMAnalytics_cb405cb8c995318bf496bd8f1041864f.o)
objc-class-ref in GoogleAppMeasurement(APMMeasurement_0b66c1c0500f6cd21583c995be8b6345.o)
objc-class-ref in GoogleAppMeasurement(APMAppDelegateInterceptor_031b50c8e373144a2623079a0c5ffce5.o)
"_OBJC_CLASS_$_GULSwizzler", referenced from:
objc-class-ref in GoogleAppMeasurement(UIViewController+APMScreenClassName_a2846f57c82bf63eac9b7186ed63bc4e.o)
"_kFIRLoggerAnalytics", referenced from:
+[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics(FIRAnalytics_bb540b7bc432fd4c54bf2d7f57c43305.o)
"_kGULNetworkHTTPStatusCodeCannotAcceptTraffic", referenced from:
-[APMMeasurement networkUploadCompletionHandlerWithResponse : error : ] in GoogleAppMeasurement(APMMeasurement_0b66c1c0500f6cd21583c995be8b6345.o)
-[APMMeasurement networkRemoteConfigFetchCompletionHandler:data:error:] in GoogleAppMeasurement(APMMeasurement_0b66c1c0500f6cd21583c995be8b6345.o)
"_kGULNetworkHTTPStatusCodeNotFound", referenced from:
-[APMMeasurement networkRemoteConfigFetchCompletionHandler:data:error:] in GoogleAppMeasurement(APMMeasurement_0b66c1c0500f6cd21583c995be8b6345.o)
"_kGULNetworkHTTPStatusCodeNotModified", referenced from:
___41-[APMMeasurement requestDeferredDeepLink]_block_invoke in GoogleAppMeasurement(APMMeasurement_0b66c1c0500f6cd21583c995be8b6345.o)
-[APMMeasurement networkRemoteConfigFetchCompletionHandler:data:error:] in GoogleAppMeasurement(APMMeasurement_0b66c1c0500f6cd21583c995be8b6345.o)
"_kGULNetworkHTTPStatusCodeUnavailable", referenced from:
-[APMMeasurement networkUploadCompletionHandlerWithResponse : error : ] in GoogleAppMeasurement(APMMeasurement_0b66c1c0500f6cd21583c995be8b6345.o)
-[APMMeasurement networkRemoteConfigFetchCompletionHandler:data:error:] in GoogleAppMeasurement(APMMeasurement_0b66c1c0500f6cd21583c995be8b6345.o)
"_kGULNetworkHTTPStatusNoContent", referenced from:
___41-[APMMeasurement requestDeferredDeepLink]_block_invoke in GoogleAppMeasurement(APMMeasurement_0b66c1c0500f6cd21583c995be8b6345.o)
-[APMMeasurement networkUploadCompletionHandlerWithResponse : error : ] in GoogleAppMeasurement(APMMeasurement_0b66c1c0500f6cd21583c995be8b6345.o)
-[APMMeasurement networkRemoteConfigFetchCompletionHandler:data:error:] in GoogleAppMeasurement(APMMeasurement_0b66c1c0500f6cd21583c995be8b6345.o)
"_kGULNetworkHTTPStatusOK", referenced from:
___41-[APMMeasurement requestDeferredDeepLink]_block_invoke in GoogleAppMeasurement(APMMeasurement_0b66c1c0500f6cd21583c995be8b6345.o)
-[APMMeasurement networkUploadCompletionHandlerWithResponse : error : ] in GoogleAppMeasurement(APMMeasurement_0b66c1c0500f6cd21583c995be8b6345.o)
-[APMMeasurement networkRemoteConfigFetchCompletionHandler:data:error:] in GoogleAppMeasurement(APMMeasurement_0b66c1c0500f6cd21583c995be8b6345.o)
"_pb_decode", referenced from:
_apmpb_decode_audience in GoogleAppMeasurement(apmpb_audience_decoder_f4d2e8b560033daca9c357dbcadfd588.o)
_apmpb_decode_audience_leaf_filter_result in GoogleAppMeasurement(apmpb_audience_leaf_filter_result_decoder_82efa7dc2bb57446d94e09cb58b2587e.o)
_apmpb_decode_dynamic_filter_result_timestamp in GoogleAppMeasurement(apmpb_dynamic_filter_result_timestamp_decoder_96f8296287e26831849230760558b7af.o)
_apmpb_decode_event in GoogleAppMeasurement(apmpb_event_decoder_b1c882ff87f23f955547997b6ab9a965.o)
_apmpb_decode_event_config in GoogleAppMeasurement(apmpb_event_config_decoder_289a623c49642c9e10b34cd87f3f8dea.o)
_apmpb_decode_event_filter in GoogleAppMeasurement(apmpb_event_filter_decoder_308e53a35aa9dca5fcc72ef55a755a60.o)
_apmpb_decode_event_param in GoogleAppMeasurement(apmpb_event_param_decoder_2f46248c02c7c7a88d2262fe7e7c8755.o)
...
"_pb_decode_varint", referenced from:
_nano_decode_repeated_uint64 in GoogleAppMeasurement(decoder_common_414b064523ce827aa89b68ab22420e68.o)
"_pb_encode", referenced from:
_nano_two_pass_encoding in GoogleAppMeasurement(encoder_common_ca04c029591a223a2b5ce203f193bf6c.o)
"_pb_encode_string", referenced from:
_nano_encode_string in GoogleAppMeasurement(encoder_common_ca04c029591a223a2b5ce203f193bf6c.o)
"_pb_encode_submessage", referenced from:
_apmpb_encode_repeated_audience in GoogleAppMeasurement(apmpb_audience_encoder_0aa9ffd714f4587c1b3b583bca075eca.o)
_apmpb_encode_repeated_audience_leaf_filter_result in GoogleAppMeasurement(apmpb_audience_leaf_filter_result_encoder_8e129fd470d4fdf99b0de262c90c7d16.o)
_apmpb_encode_repeated_dynamic_filter_result_timestamp in GoogleAppMeasurement(apmpb_dynamic_filter_result_timestamp_encoder_a49b222a4369ca61c373ed2d12d1d46a.o)
_apmpb_encode_repeated_event in GoogleAppMeasurement(apmpb_event_encoder_88485ea66c35b7ddeef5208923172c2a.o)
_apmpb_encode_repeated_event_config in GoogleAppMeasurement(apmpb_event_config_encoder_7b6ec28ce7046b462c415b527d703665.o)
_apmpb_encode_repeated_event_filter in GoogleAppMeasurement(apmpb_event_filter_encoder_68c5a0f88563eac48e69dd8621c4b01c.o)
_apmpb_encode_repeated_event_param in GoogleAppMeasurement(apmpb_event_param_encoder_b2ac0b7f2488621fc8d579c07baaa1de.o)
...
"_pb_encode_tag_for_field", referenced from:
_apmpb_encode_repeated_audience in GoogleAppMeasurement(apmpb_audience_encoder_0aa9ffd714f4587c1b3b583bca075eca.o)
_apmpb_encode_repeated_audience_leaf_filter_result in GoogleAppMeasurement(apmpb_audience_leaf_filter_result_encoder_8e129fd470d4fdf99b0de262c90c7d16.o)
_apmpb_encode_repeated_dynamic_filter_result_timestamp in GoogleAppMeasurement(apmpb_dynamic_filter_result_timestamp_encoder_a49b222a4369ca61c373ed2d12d1d46a.o)
_apmpb_encode_repeated_event in GoogleAppMeasurement(apmpb_event_encoder_88485ea66c35b7ddeef5208923172c2a.o)
_apmpb_encode_repeated_event_config in GoogleAppMeasurement(apmpb_event_config_encoder_7b6ec28ce7046b462c415b527d703665.o)
_apmpb_encode_repeated_event_filter in GoogleAppMeasurement(apmpb_event_filter_encoder_68c5a0f88563eac48e69dd8621c4b01c.o)
_apmpb_encode_repeated_event_param in GoogleAppMeasurement(apmpb_event_param_encoder_b2ac0b7f2488621fc8d579c07baaa1de.o)
...
"_pb_encode_varint", referenced from:
_nano_encode_repeated_uint64 in GoogleAppMeasurement(encoder_common_ca04c029591a223a2b5ce203f193bf6c.o)
"_pb_istream_from_buffer", referenced from:
_apmpb_decode_audience in GoogleAppMeasurement(apmpb_audience_decoder_f4d2e8b560033daca9c357dbcadfd588.o)
_apmpb_decode_audience_leaf_filter_result in GoogleAppMeasurement(apmpb_audience_leaf_filter_result_decoder_82efa7dc2bb57446d94e09cb58b2587e.o)
_apmpb_decode_dynamic_filter_result_timestamp in GoogleAppMeasurement(apmpb_dynamic_filter_result_timestamp_decoder_96f8296287e26831849230760558b7af.o)
_apmpb_decode_event in GoogleAppMeasurement(apmpb_event_decoder_b1c882ff87f23f955547997b6ab9a965.o)
_apmpb_decode_event_config in GoogleAppMeasurement(apmpb_event_config_decoder_289a623c49642c9e10b34cd87f3f8dea.o)
_apmpb_decode_event_filter in GoogleAppMeasurement(apmpb_event_filter_decoder_308e53a35aa9dca5fcc72ef55a755a60.o)
_apmpb_decode_event_param in GoogleAppMeasurement(apmpb_event_param_decoder_2f46248c02c7c7a88d2262fe7e7c8755.o)
...
"_pb_ostream_from_buffer", referenced from:
_nano_two_pass_encoding in GoogleAppMeasurement(encoder_common_ca04c029591a223a2b5ce203f193bf6c.o)
"_pb_read", referenced from:
_apmpb_decode_repeated_audience in GoogleAppMeasurement(apmpb_audience_decoder_f4d2e8b560033daca9c357dbcadfd588.o)
_apmpb_decode_repeated_audience_leaf_filter_result in GoogleAppMeasurement(apmpb_audience_leaf_filter_result_decoder_82efa7dc2bb57446d94e09cb58b2587e.o)
_apmpb_decode_repeated_dynamic_filter_result_timestamp in GoogleAppMeasurement(apmpb_dynamic_filter_result_timestamp_decoder_96f8296287e26831849230760558b7af.o)
_apmpb_decode_repeated_event in GoogleAppMeasurement(apmpb_event_decoder_b1c882ff87f23f955547997b6ab9a965.o)
_apmpb_decode_repeated_event_config in GoogleAppMeasurement(apmpb_event_config_decoder_289a623c49642c9e10b34cd87f3f8dea.o)
_apmpb_decode_repeated_event_filter in GoogleAppMeasurement(apmpb_event_filter_decoder_308e53a35aa9dca5fcc72ef55a755a60.o)
_apmpb_decode_repeated_event_param in GoogleAppMeasurement(apmpb_event_param_decoder_2f46248c02c7c7a88d2262fe7e7c8755.o)
...
ld: symbol(s) not found for architecture arm64
clang : error : linker command failed with exit code 1 (use -v to see invocation)

MTOUCH : error MT5210: Native linking failed, undefined symbol: _GULIsLoggableLevel. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _GULLogBasic. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _GULLogError. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _GULLogInfo. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _GULLogWarning. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _GULSetLoggerLevel. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: FIRApp. The symbol '_OBJC_CLASS_$_FIRApp' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: FIRComponent. The symbol '_OBJC_CLASS_$_FIRComponent' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: FIROptions. The symbol '_OBJC_CLASS_$_FIROptions' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GULAppDelegateSwizzler. The symbol '_OBJC_CLASS_$_GULAppDelegateSwizzler' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GULMutableDictionary. The symbol '_OBJC_CLASS_$_GULMutableDictionary' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GULNetwork. The symbol '_OBJC_CLASS_$_GULNetwork' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GULSwizzler. The symbol '_OBJC_CLASS_$_GULSwizzler' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _kFIRLoggerAnalytics. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGULNetworkHTTPStatusCodeCannotAcceptTraffic. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGULNetworkHTTPStatusCodeNotFound. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGULNetworkHTTPStatusCodeNotModified. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGULNetworkHTTPStatusCodeUnavailable. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGULNetworkHTTPStatusNoContent. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGULNetworkHTTPStatusOK. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _pb_decode. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _pb_decode_varint. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _pb_encode. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _pb_encode_string. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _pb_encode_submessage. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _pb_encode_tag_for_field. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _pb_encode_varint. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _pb_istream_from_buffer. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _pb_ostream_from_buffer. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _pb_read. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5201: Native linking failed. Please review the build log and the user flags provided to gcc: -ObjC -lc++ -lsqlite3 -lz -ObjC -lc++ -lsqlite3 -lz
MTOUCH : error MT5202: Native linking failed. Please review the build log.
Done building target "_CompileToNative" in project "test.iOS.csproj" -- FAILED.

Done building project "test.iOS.csproj" -- FAILED.

Build FAILED.

-[APMMeasurement networkUploadCompletionHandlerWithResponse : error : ] in GoogleAppMeasurement(APMMeasurement_0b66c1c0500f6cd21583c995be8b6345.o)
-[APMMeasurement networkUploadCompletionHandlerWithResponse : error : ] in GoogleAppMeasurement(APMMeasurement_0b66c1c0500f6cd21583c995be8b6345.o)
-[APMMeasurement networkUploadCompletionHandlerWithResponse : error : ] in GoogleAppMeasurement(APMMeasurement_0b66c1c0500f6cd21583c995be8b6345.o)
-[APMMeasurement networkUploadCompletionHandlerWithResponse : error : ] in GoogleAppMeasurement(APMMeasurement_0b66c1c0500f6cd21583c995be8b6345.o)
clang : error : linker command failed with exit code 1 (use -v to see invocation)
MTOUCH : error MT5210: Native linking failed, undefined symbol: _GULIsLoggableLevel. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _GULLogBasic. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _GULLogError. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _GULLogInfo. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _GULLogWarning. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _GULSetLoggerLevel. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: FIRApp. The symbol '_OBJC_CLASS_$_FIRApp' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: FIRComponent. The symbol '_OBJC_CLASS_$_FIRComponent' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: FIROptions. The symbol '_OBJC_CLASS_$_FIROptions' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GULAppDelegateSwizzler. The symbol '_OBJC_CLASS_$_GULAppDelegateSwizzler' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GULMutableDictionary. The symbol '_OBJC_CLASS_$_GULMutableDictionary' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GULNetwork. The symbol '_OBJC_CLASS_$_GULNetwork' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GULSwizzler. The symbol '_OBJC_CLASS_$_GULSwizzler' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _kFIRLoggerAnalytics. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGULNetworkHTTPStatusCodeCannotAcceptTraffic. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGULNetworkHTTPStatusCodeNotFound. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGULNetworkHTTPStatusCodeNotModified. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGULNetworkHTTPStatusCodeUnavailable. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGULNetworkHTTPStatusNoContent. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _kGULNetworkHTTPStatusOK. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _pb_decode. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _pb_decode_varint. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _pb_encode. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _pb_encode_string. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _pb_encode_submessage. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _pb_encode_tag_for_field. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _pb_encode_varint. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _pb_istream_from_buffer. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _pb_ostream_from_buffer. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _pb_read. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5201: Native linking failed. Please review the build log and the user flags provided to gcc: -ObjC -lc++ -lsqlite3 -lz -ObjC -lc++ -lsqlite3 -lz
MTOUCH : error MT5202: Native linking failed. Please review the build log.
0 Warning(s)
37 Error(s)`

Also this may be relevant but I am using VisualStudio 2017 as MonoGame lacks 2019 support. 

I will do some more investigating and get back to you when I have more info.

**Comment by Owlzy** [comment]
So I completely removed the project, and copied the files I needed back one by one.  And it now works assuming I use an older version.  Currently I can build with Firebase.Analytics 4.0.5.1

I'm using MonoGame so this may be  depending on an old version of Xamarin or something?   For some reason I can't get any info from VS about the version of xamarin.ios, just says version 0.0.0.0 unfortunately.

**Comment by SotoiGhost** [comment]
@Owlzy Are you up to date with VS updates?

**Comment by Owlzy** [comment]
> @Owlzy Are you up to date with VS updates?

Unfortunately MonoGame (game library we are using) is currently locked to VS 2017 on Mac.  Would this make a difference to the plugin working? I thought the plugin would work independent of the IDE.

**Comment by SotoiGhost** [comment]
The IDE it's not a problem but with X.iOS version. I'm not very familiarized with MonoGame stuff but, does MonoGame is stuck with a X.iOS version? Can you verify if you are up to date with X.iOS version?

**Comment by Owlzy** [comment]
> The IDE it's not a problem but with X.iOS version. I'm not very familiarized with MonoGame stuff but, does MonoGame is stuck with a X.iOS version? Can you verify if you are up to date with X.iOS version? I have seen that error when something new runs against an old X.iOS version.

Apologies for delay @SotoiGhost , I've been doing more investigating on my end.  What I didn't actually realise was that Xamarin is bundled with VS, so in order to get the latest I had to upgrade to VS 2019.  Having done that, it compiles with the latest plugins no problem! 

Thing is MonoGame devs seem to tend to stick with VS 2017, lets just say for reasons...  Which has also been causing issues on Android. So apologies for wasting your time, seems if your using MonoGame you can end up being pretty far out of date on stuff without releasing.  Update your stuff ppl :)
