### ISSUE TITLE
Push notification sometimes not working and sometimes working without code change

### ISSUE THREAD

**Issue by apy534** [xamarin/GoogleApisForiOSComponents#378]
My tools and plugin versions are as follows:

iPad - iOS 13.3

Visual studio - 8.3.11

Xcode - 10.3

Xamarin.Firebase.iOS.CloudMessaging - Version 3.1.2

I had the code working for iOS 12.2. I have my iOS upgraded to 13.3 now. I'm not sure when the notification stopped working for iOS. I doubt the version iOS 13.3. When I start debugging very rarely the notification works.

But most of the time the app doesn't hit RegisteredForRemoteNotifications or FailedToRegisterForRemoteNotifications methods. I'm not sure whats going wrong. I spent around 2 days working on the same :(

I'm not even able to upgrade the plugin. If I upgrade, I'm facing linking error. Please suggest if anyone came across same issue

**Comment by SotoiGhost** [comment]
Hi @apy534! Sorry for the inconveniences that this may cause. We are working right now on an update for Cloud Messaging that fixes the linker issue and also contains some fixes for iOS 13 that Firebase released, maybe this will fix your issue.

**Comment by apy534** [comment]
@SotoiGhost 
Thanks for the response. It is working for me with older version after workaround in AppDelegate. The documentation should be updated accordingly. Closing the issue.
