### ISSUE TITLE
Update Google MobileAds to use googleads-consent-sdk-ios 1.0.5 to remove UIWebView

### ISSUE THREAD

**Issue by brianlenz** [xamarin/GoogleApisForiOSComponents#380]
googleads-consent-sdk-ios has been updated from 1.0.4 to 1.0.5 to remove UIWebView:

https://github.com/googleads/googleads-consent-sdk-ios/releases/tag/v1.0.5
https://github.com/googleads/googleads-consent-sdk-ios/commit/5cc10860a9e3edec73264c5fe8a77759b8d11148
https://github.com/googleads/googleads-consent-sdk-ios/issues/41

The Google MobileAds dependency now needs to be updated to this version to remove support for the deprecated UIWebView.

**Comment by SotoiGhost** [comment]
Hi @brianlenz! We are working right now on an update that fixes this.

**Comment by brianlenz** [comment]
Any updates here?

**Comment by BradKwon** [comment]
Hi @SotoiGhost , 
I am using Xamarin.Google.iOS.MobileAds NuGet and want to update it because of UIWebView. I am not sure the latest version 7.57.0 already removed this. It looks it is by seeing that this ticket is merged to #388 and closed. Additionally, it seems I have to update those Firebase libraries as well to get it work. It would be great if you can correct me if I'm wrong. 
Thanks.

**Comment by ezverev** [comment]
> Hi @SotoiGhost ,
> I am using Xamarin.Google.iOS.MobileAds NuGet and want to update it because of UIWebView. I am not sure the latest version 7.57.0 already removed this. It looks it is by seeing that this ticket is merged to #388 and closed. Additionally, it seems I have to update those Firebase libraries as well to make it work. It would be great if you can correct me if I'm wrong.
> Thanks.

No luck with the 7057.0

There is still 

`/// Presents the full screen consent form over viewController. The form is dismissed and
/// completionHandler is called after the user selects an option. Must be called on the main queue.
- (void)presentFromViewController:(nonnull UIViewController *)viewController
                dismissCompletion:(nullable PACDismissCompletion)completionHandler;`

in place in PACConsentForm.h file which clearly links to the deprecated UIWebView.

**Comment by yuriibabii** [comment]
Version 7.66 resolved the issue for me
