### ISSUE TITLE
MLVison Sample Proj shows " Failed to locate required resources. Please verify the resource bundle is imported.

### ISSUE THREAD

**Issue by lilleydnSub** [xamarin/GoogleApisForiOSComponents#382]
Using the latest packages ML Kit fails to do text recognition.
In the Application output I get

"Failed to locate required resources. Please verify the resource bundle is imported."

Latest Nuggets are 
 <package id="Xamarin.Build.Download" version="0.10.0" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.Core" version="6.6.0" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.MLKit" version="0.13.0.2" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.MLKit.Common" version="0.13.0.1" targetFramework="xamarinios10" />

Looks like another update is required as 
https://github.com/firebase/quickstart-ios/issues/627

Sample Project
[TestMLUpgrade 3.zip](https://github.com/xamarin/GoogleApisForiOSComponents/files/4317229/TestMLUpgrade.3.zip)

**Comment by Waaheeda** [comment]
Facing this issue on iOS 13 device in Xamarin solution
**Failed to locate required resources. Please verify the resource bundle is imported.** 
Packages installed are - 
Xamarin.Firebase.iOS.Core -6.1.0
Xamarin.Firebase.iOS.MLKit.Common-0.13.0.1
Xamarin.Firebase.iOS.MLKit-0.13.0.1

Also, facing native linking failed issue on latest updates of MLKit and Vision package

Please provide quick fix solution or update
