### ISSUE TITLE
Firebase analytics error

### ISSUE THREAD

**Issue by kunaldhande** [xamarin/GoogleApisForiOSComponents#389]
Xamarin forms 4.5 latest
Xamarin.Firebase.iOS.Analytics: 6.2.1

I am getting this error while building iOS app.

error : There was an error unzipping the file bin\iPhone\Release\Dev\iPhone\GTMSessionFetcher.framework.dSYM.zip: Could not find a part of the path '\bin\iPhone\Release\Dev\iPhone\GTMSessionFetcher.framework.dSYM'.

When I checked bin\iPhone\Release\Dev\iPhone\GTMSessionFetcher.framework.dSYM.zip file it exists but its empty.

**Comment by kunaldhande** [comment]
Any update on this?

**Comment by SotoiGhost** [comment]
@kunaldhande Can you provide a test case of this, please? Thanks in advance!
