### ISSUE TITLE
Firebase.iOS.Core 6.6.6 and Google.iOS.MobileAds 7.57.0 Linker Error When Building

### ISSUE THREAD

**Issue by jmichas** [xamarin/GoogleApisForiOSComponents#394]
I had to downgrade to FB 6.6.0 and MobileAds 7.53.1 to get my project to build for distribution.

With 6.6.6 and 7.57 I get this error:
```
Native linking failed, undefined symbol: _GADErrorUserInfoKeyResponseInfo. This symbol was referenced by the managed member Google.MobileAds.ResponseInfo.ErrorUserInfoKey. Please verify that all the necessary frameworks have been referenced and native libraries linked.
```

As soon as I downgraded I was able to build and package the app fine.

Not sure what the cause is, but it appears that the `Google.MobileAds.ResponseInfo.ErrorUserInfoKey` is a new property in 7.57.

I may have been able to build by just downgrading the MobileAds package but I have spent a ton of time on this and I don't feel like testing it as the build is working and I need my CI/CD process to work.

**Comment by SotoiGhost** [comment]
@jmichas Can you update and delete **bin** and **obj** folders and XBD cache, please? Here seems to be working correctly

**Comment by jmichas** [comment]
Yes, that seemed to work. I usually make sure to do that but maybe I didn't when I updated the last time. Sorry for the false alarm.
