### ISSUE TITLE
Cannot build for Armv7 Devices

### ISSUE THREAD

**Issue by lilleydnSub** [xamarin/GoogleApisForiOSComponents#395]
Hi,

I have successfully tested the new Vision Librarys on Arm64 but for ArmV7 it fails to compile.

See Project attached.

Debug builds for Device 
Release builds for Armv7 and Arm64 (Will Fail)
[Armv7Issue.zip]
(https://github.com/xamarin/GoogleApisForiOSComponents/files/4491474/Armv7Issue.zip)

/Users/davidlilley/Downloads/TestMLUpgrade/TestML/clang: Error: linker command failed with exit code 1 (use -v to see invocation) (MLKitSample)
/Users/davidlilley/Downloads/TestMLUpgrade/TestML/error MT5209: Error: warning: ignoring file /Users/davidlilley/Library/Caches/XamarinBuildDownload/FMLVsnO-0.19.0/Frameworks/FirebaseMLVisionObjectDetection.framework/FirebaseMLVisionObjectDetection, missing required architecture armv7 in file /Users/davidlilley/Library/Caches/XamarinBuildDownload/FMLVsnO-0.19.0/Frameworks/FirebaseMLVisionObjectDetection.framework/FirebaseMLVisionObjectDetection (2 slices) (MLKitSample) Native linking
/Users/davidlilley/Downloads/TestMLUpgrade/TestML/MTOUCH: Error MT5211: Native linking failed, undefined Objective-C class: FIRVisionObject. The symbol '_OBJC_CLASS_$_FIRVisionObject' could not be found in any of the libraries or frameworks linked with your application. (MT5211) (MLKitSample)
/Users/davidlilley/Downloads/TestMLUpgrade/TestML/MTOUCH: Error MT5211: Native linking failed, undefined Objective-C class: FIRVisionObjectDetector. The symbol '_OBJC_CLASS_$_FIRVisionObjectDetector' could not be found in any of the libraries or frameworks linked with your application. (MT5211) (MLKitSample)
/Users/davidlilley/Downloads/TestMLUpgrade/TestML/MTOUCH: Error MT5211: Native linking failed, undefined Objective-C class: FIRVisionObjectDetectorOptions. The symbol '_OBJC_CLASS_$_FIRVisionObjectDetectorOptions' could not be found in any of the libraries or frameworks linked with your application. (MT5211) (MLKitSample)
/Users/davidlilley/Downloads/TestMLUpgrade/TestML/MTOUCH: Error MT5201: Native linking failed. Please review the build log and the user flags provided to gcc: -ObjC -lc++ -lsqlite3 -lz -ObjC -lc++ -lsqlite3 -lz -lc++ -ObjC -ObjC -lc++ -ObjC -lc++ -ObjC -lc++ -ObjC -lc++ -ObjC -lc++ -ObjC -lc++ (MT5201) (MLKitSample)

**Comment by SotoiGhost** [comment]
@lilleydnSub Thanks for reporting this issue and an apology for the inconveniences that this could cause.

According to [Firebase MLKit][1] docs, this seems to be by design:

> **Note:** ML Kit's object detection and tracking API only runs on 64-bit devices. If you build your app with 32-bit support, check the device's architecture before using this API.

So there's not too much we can do. What you can do is to file a [feature request][2] to Firebase asking to support 32 devices.

Hope this helps you!

Best!
Israel Soto.

[1]: https://firebase.google.com/docs/ml-kit/ios/detect-objects
[2]: https://github.com/firebase/firebase-ios-sdk/issues/new?labels=type%3A+feature+request&template=feature_request.md
