### ISSUE TITLE
Where should i add FirebaseCrashlyticsUploadSymbolsEnabled?

### ISSUE THREAD

**Issue by samt1925** [xamarin/GoogleApisForiOSComponents#396]
Where should i add this code? In pcl csproj or IOS csproj? In here it say add it before import but i cannot find it on any csproj file.

If you want to upload the dSYM regardless of the configuration,
define the following property anywhere in your .csproj but before of the
Xamarin.Firebase.iOS.Crashlytics.targets import:

```
<PropertyGroup>
	<FirebaseCrashlyticsUploadSymbolsEnabled>True</FirebaseCrashlyticsUploadSymbolsEnabled>
</PropertyGroup>

**Comment by SotoiGhost** [comment]
Hi @samt1925! Please, add it in the first PropertyGroup that you have in your iOS csproj. Hope this helps you.

**Comment by samt1925** [comment]
Thank you @SotoiGhost.
