### ISSUE TITLE
InAppMessaging linking issue

### ISSUE THREAD

**Issue by mayhammf** [xamarin/GoogleApisForiOSComponents#398]
Hi, 
After installing "Xamarin.Firebase.iOS.InAppMessaging (0.19.2)" the following error occurs during build: 
```
error MT5211: Native linking failed, undefined Objective-C class: InAppMessagingDisplayMessage. The symbol '_OBJC_CLASS_$_InAppMessagingDisplayMessage' could not be found in any of the libraries or frameworks linked with your application.
error MT5201: Native linking failed. Please review the build log and the user flags provided to gcc: -ObjC -lc++ -lsqlite3 -lz
error : linker command failed with exit code 1 (use -v to see invocation)
``` 
Tested both an existing and freshly created project (attached). 
[App1.zip](https://github.com/xamarin/GoogleApisForiOSComponents/files/4524896/App1.zip)

Related: #188

**Comment by eshap20** [comment]
facing error on SDK integration

- Native linking failed, undefined Objective-C class: FIRAppEnvironmentUtil. The symbol '_OBJC_CLASS_$_FIRAppEnvironmentUtil' could not be found in any of the libraries or frameworks linked with your application.

- Native linking failed, undefined Objective-C class: FIRAppEnvironmentUtil. The symbol '_OBJC_CLASS_$_FIRAppEnvironmentUtil' could not be found in any of the libraries or frameworks linked with your application.
- Native linking failed, undefined Objective-C class: FIRMutableDictionary. The symbol '_OBJC_CLASS_$_FIRMutableDictionary' could not be found in any of the libraries or frameworks linked with your application.
-Native linking failed, undefined Objective-C class: FIRNetwork. The symbol '_OBJC_CLASS_$_FIRNetwork' could not be found in any of the libraries or frameworks linked with your application.
