### ISSUE TITLE
dSYM is not uploading anymore

### ISSUE THREAD

**Issue by alexshikov** [xamarin/GoogleApisForiOSComponents#407]
We've started to get build failures due to dSYM upload error:

```
(_FirebaseCrashlyticsUploadDSymToFirebaseOnMac target) -> 
  error : Failed uploading cSYMs due to error : Error Domain=com.twitter.FABCompoundOperation.error Code=4294967293 "(null)" UserInfo={com.twitter.FABCompoundOperation.error.user-info-key.underlying-errors=( [/Users/administrator/VSTSAgent2/_work/1/s/iOS/<MyApp>.iOS.csproj]
  /Users/administrator/VSTSAgent2/_work/1/s/packages/Xamarin.Firebase.iOS.Crashlytics.3.14.0.3/build/Xamarin.Firebase.iOS.Crashlytics.targets(59,3): error MSB3073: The command "'/Users/administrator/Library/Caches/XamarinBuildDownload/Fbrc-1.10.2/upload-symbols' -gsp '/Users/administrator/VSTSAgent2/_work/1/s/iOS/GoogleService-Info.plist' -p ios 'bin/iPhone/Dev-Release/<MyApp>.iOS.app.dSYM'" exited with code 8. [/Users/administrator/VSTSAgent2/_work/1/s/iOS/<MyApp>.iOS.csproj]
``` 

Can this be related to the Fabric shutdown?

**Comment by alexshikov** [comment]
Nevermind. That was a temporary issue. Somehow it just disappeared.

**Comment by manjuy124** [comment]
@alexshikov  Do you have any idea about this? I have the same issue.

**Comment by alexshikov** [comment]
@manjuy124 it was a Google server issue. After a few hours the error stopped to happen.

**Comment by glintpursuit** [comment]
We are facing this issue from Last 24 hrs. 

As this is after build script, build is not getting uploaded to app store on failure of upload dysm script.

**Comment by gholias** [comment]
Same thing for us, it stopped working on Friday

**Comment by nnx2202** [comment]
We're the same :)))

**Comment by Kogilan** [comment]
We are having the same issue as well. Any solution or advice is really appreciated.

**Comment by borysf** [comment]
Simply update the `upload-symbols` tool to the latest version. It worked for me.

**Comment by kapiljagtap** [comment]
[FirebaseCrashlytics.zip](https://github.com/xamarin/GoogleApisForiOSComponents/files/5591547/FirebaseCrashlytics.zip)
As mention above by @borysf use the latest version of upload-symbols tool. I have attached here latest one. It is working for me.

**Comment by dimohamdy** [comment]
Hope it work with me

**Comment by dimohamdy** [comment]
Works like magic 😘

**Comment by LGFox** [comment]
I still observe this issue when I upload DSYM's by special directives in my *.csproj file:
`   <FirebaseCrashlyticsUploadSymbolsEnabled>True</FirebaseCrashlyticsUploadSymbolsEnabled>
    <FirebaseCrashlyticsUploadSymbolsContinueOnError>False</FirebaseCrashlyticsUploadSymbolsContinueOnError>`

It was working a few month ago.

**Comment by lin1105** [comment]
https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=ios&authuser=0    From this, I got the answer.
