### ISSUE TITLE
Cant build on OSX

### ISSUE THREAD

**Issue by stoffmasta** [xamarin/GoogleApisForiOSComponents#41]
Having trouble building the libraries on OSX El Capitan 10.11.6

Any help is appreciated.

STEPS
cd Google.Core
sh ../build.sh --target libs

OUTPUT

Analyzing build script...
Processing build script...
Installing tools...
Installing addins...
Compiling build script...
Environment Variables:
	Key: TERM	Value: "xterm-256color"
	Key: NUGET_EXE	Value: "/Users/zz/Downloads/GoogleApisForiOSComponents-firebase 3/tools/nuget.exe"
	Key: SHLVL	Value: "1"
	Key: TERM_SESSION_ID	Value: "1E63D8DF-762C-4535-A18A-488FA4F14D18"
	Key: Apple_PubSub_Socket_Render	Value: "/private/tmp/com.apple.launchd.umAWt57M9b/Render"
	Key: XPC_FLAGS	Value: "0x0"
	Key: PATH	Value: "/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
	Key: TMPDIR	Value: "/var/folders/1l/ng5dzl5n2y93krm9dpwntf380000gn/T/"
	Key: SHELL	Value: "/bin/bash"
	Key: SSH_AUTH_SOCK	Value: "/private/tmp/com.apple.launchd.q1E98HAIx6/Listeners"
	Key: OLDPWD	Value: "/Users/zz/Downloads/GoogleApisForiOSComponents-firebase 3/tools"
	Key: PWD	Value: "/Users/zz/Downloads/GoogleApisForiOSComponents-firebase 3/Google.Core"
	Key: HOME	Value: "/Users/zz"
	Key: USER	Value: "zz"
	Key: TERM_PROGRAM_VERSION	Value: "361.1"
	Key: __CF_USER_TEXT_ENCODING	Value: "0x1F5:0x0:0x0"
	Key: LOGNAME	Value: "zz"
	Key: LC_CTYPE	Value: "UTF-8"
	Key: TERM_PROGRAM	Value: "Apple_Terminal"
	Key: XPC_SERVICE_NAME	Value: "0"

========================================
externals
========================================
Executing task: externals
An error occured when executing task 'externals'.
Error: ApplicationName='/Users/zz/Downloads/GoogleApisForiOSComponents-firebase 3/tools/Cake/Cake.exe', CommandLine='"/Users/zz/Downloads/GoogleApisForiOSComponents-firebase 3/Firebase.Analytics/build.cake" -target="externals"', CurrentDirectory='/Users/zz/Downloads/GoogleApisForiOSComponents-firebase 3/Google.Core', Native error= Access denied

**Comment by bholmes** [comment]
Should be fixed by ac8a3be58851fa17c8806507bb73b349b0190140
