### ISSUE TITLE
Xamarin IOS Native Advanced Admob: Request Error: No ad to show

### ISSUE THREAD

**Issue by csk1nner** [xamarin/GoogleApisForiOSComponents#426]
I'm trying to implement a UnifiedNativeAd in Xamarin.IOS with AdMob. Using test AdUnitId: ca-app-pub-3940256099942544/2521693316 - I've got a helper that requests a batch of ads and loads them into a collection. The renderer then pulls ads from the collection and displays as needed. It also tells the helper to go fetch more ads if the collection gets below a certain threshold. The problem I'm running into is that I very rarely get the DidReceiveUnifiedNativeAd Delegate fired. I either get the DidFailToReceiveAd or nothing. I'm kind of at my wits end here. This looks to be a problem with Admob. If I tell them they will tell me to tell the xamarin ios team about this.

Using Xamarin.Google.IOS.MobileAds: 7.57.0 - I've tried installing older versions but then the code starts refusing to compile as the needed methods aren't in place.

Other packages of note:

- Xamarin.Forms: 4.7.0.1179
- No firebase packages

My AdLoader looks like this:

-----------------------------------------
```
var multipleAdsOptions = new MultipleAdsAdLoaderOptions { NumberOfAds = numberToLoad };
var loader = new AdLoader(
#if DEBUG
    DebugAdUnitId, 
#else
        ReleaseAdUnitId,
#endif
       GetVisibleViewController(),
    new AdLoaderAdType[] { AdLoaderAdType.UnifiedNative },
        new AdLoaderOptions[] { multipleAdsOptions })
        {
            Delegate = this
        };
loader.LoadRequest(Request.GetDefaultRequest());
```
-----------------------------------------
Note the Delegate to this. I'm not using a separate class to handle event notifications.

The AppDelgate initializes AdMob with MobileAds.ShardInstance.Start(); The Handler returns successfully.

I'm not setting MobileAds.Shardinstance.RequestConfigiration.TestDeviceIdIdentifiers as I've read that this can cause a bug.

The info.plist has been properly updated with the needed key/value pair

Any ideas?

**Comment by csk1nner** [comment]
Gang!

This solved itself when I added caching to the application.  So when the application starts up it reaches out to AdMob to request five ads.  If it doesn't get a response back in 2.25 seconds it sends another request.  This process continues until a response from Admob is received.   Not ideal.  But the ads load now.

**Comment by StoatsOnAPlane** [comment]
How did you add caching?
