### ISSUE TITLE
Xamarin.Firebase.iOS.Crashlytics: Update to 4.0.0+ will be required soon.

### ISSUE THREAD

**Issue by Harween64** [xamarin/GoogleApisForiOSComponents#436]
Hi everyone,

I just see this warning on my Firebase crashlytics console:
"Please upgrade to the generally available Firebase Crashlytics SDK to continue getting crash reports in the Firebase console past November 15, 2020. [Learn more](https://firebase.google.com/docs/crashlytics/get-started)"
With this note in the "learn more" link:
"To continue getting crash reports in the Firebase console, make sure you upgrade to the Firebase Crashlytics SDK versions 17.0.0+ for Android, 4.0.0+ for iOS, and 6.15.0+ for Unity."

It is possible to promote the nuget pre-version 4.0.0-beta7 to release ?
Or if there is more tests or work to do, it is possible to have an approximative release date ?
I'd like to be able to update my app with as soon as possible.

Thank you by advance.

**Comment by krishnaxamarin** [comment]
We are also running into the same issue and it would be great if the packages can be upgraded to newest.

**Comment by bash862** [comment]
We have the same problem in our app and we need a stable version for the 4.0.0. thanks.

**Comment by Jagan2412** [comment]
We have the same problem in our app, please let us know how to hondle

**Comment by krishnaxamarin** [comment]
Hi, Is there any update or time line for providing an updated nuget for this issue ?

**Comment by SravanthiKare** [comment]
Hi, We are also facing issue? Are there any plans to release a version with this fix?

**Comment by rickclephas** [comment]
A preview package for `Xamarin.Firebase.Crashlytics` is available: https://github.com/xamarin/XamarinComponents/issues/956#issuecomment-693384789

**Comment by PaulsonMac** [comment]
What will the version of Xamarin.Firebase.iOS.Crashlytics that addresses this update?

**Comment by sasa-bobic** [comment]
Trying to install this package (https://www.nuget.org/packages/Xamarin.Firebase.iOS.Crashlytics/4.0.0-beta.7/) I get this error:

Unpacking failed. Please download 'https://github.com/firebase/firebase-ios-sdk/archive/Crashlytics-4.0.0-beta.6.zip' and extract it to the 'C:\Users\Username\AppData\Local\XamarinBuildDownloadCache\FCrshlytcs-4.0.0.beta.6' directory and create an empty file called 'C:\Users\Username\AppData\Local\XamarinBuildDownloadCache\FCrshlytcs-4.0.0.beta.6.unpacked'.

**Comment by gianlucaparadise** [comment]
The stable Android binding has now been released (https://www.nuget.org/packages/Xamarin.Firebase.Crashlytics/117.0.0).
Are there any news about the stable version for iOS?

Thanks

**Comment by jthegeman** [comment]
The deadline for the old SDK is November 15th. Is there any update when this will be released?

**Comment by wojciech-kulik** [comment]
> The deadline for the old SDK is November 15th. Is there any update when this will be released?

Just use `beta-7` it works fine.

**Comment by rickclephas** [comment]
`beta-7` will stop working on November 15th:
> We are replacing Fabric Crashlytics SDKs and beta versions of the Firebase Crashlytics SDKs with the generally available Firebase Crashlytics SDKs.

**Comment by jthegeman** [comment]
@rickclephas so do not use the beta-7?

I have an app that is releasing Nov 9th.

**Comment by rickclephas** [comment]
> @rickclephas so do not use the beta-7?
> 
> I have an app that is releasing Nov 9th.

We are currently using beta-7 for our apps and just received an email from Google stating that the iOS versions aren't using the new SDK. 
The email also states that beta versions will be deprecated, so I guess using beta-7 won't be any better then using the old Fabric versions...

**Comment by jthegeman** [comment]
@rickclephas I just updated to beta-7 and the Firebase Console says
![image](https://user-images.githubusercontent.com/68656392/97626362-ae7d5d00-19f7-11eb-9569-4a1d564222d7.png)

**Comment by antixaker** [comment]
@jthegeman 

> Also including the latest Android - Xamarin.Firebase.Crashlytics 117.0.0 give these errors
> FirebaseMessageService.cs(9, 6): [CS7069] Reference to type 'Zzb' claims it is defined in 'Xamarin.Firebase.Iid', but it could not be found

I just finished upgrading Android Xamarin.Firebase.Crashlytics to v.117 - I had lots of issues too.
First of all - try to update all Xamarin.Firebase packages to the latest (be careful with Xamarin.Firebase.Perf latest version, it has some changes with Trace class, so I used 118 version instead of 120).
Also, are you migrating to AndroidX with this Xamarin.Firebase.Crashlytics update?

**Comment by krishnaxamarin** [comment]
We are also using beta-7 for our iOS apps and got an email from google saying we need to update sdk's by Nov 15. It will be much appreciated if we can get an stable nugget targeting newest crashlytic sdk's.

**Comment by jthegeman** [comment]
@antixaker Yes when we changed our target to Android 10, it migrated the project to AndroidX.

**Comment by rickclephas** [comment]
@jthegeman we got the same message in the console after updating. 
Unfortunately it seems we still need the stable 4.0.0 instead of the beta-7.

**Comment by antixaker** [comment]
@jthegeman okay, so try to update Analytics and Messaging.
Some tips for future: 
- if you will stuck with some dagger runtime error - add Xamarin.Google.Dagger package
- remove Xamarin.Android.ManifestMerger package if you have one

**Comment by krishnaxamarin** [comment]
Below is part of the email that we have received from google regarding fabric and beta version of crashlytic sdk. 

![image](https://user-images.githubusercontent.com/53803040/97629197-20f43a00-1a04-11eb-95f5-3193bd7641d2.jpeg)

**Comment by wojciech-kulik** [comment]
I think it will be faster to make our own binding to native Crashlytics instead of waiting here for a stable 4.0.0 release. Time is running out. And a binding library should not be a big problem.

**Comment by Harween64** [comment]
I share here a "copy" of this project, but restricted to only firebase analytics and firebase crashlytics. It can be a good start if you want to have updated libraries. 

I focus only on these libraries, because it was my needs, and I don't have time to maintain such a repository. 

You can follow this project instructions to build it, it will product .nupkg files in /output folder, that you can unzip to retrieve dll files, and reference them manually. I think you can use a private NuGet feed, but I don't have tried.
 
You will find the project in attached zip file here : [Firebase.Binding.iOS.zip](https://github.com/xamarin/GoogleApisForiOSComponents/files/5473496/Firebase.Binding.iOS.zip)

**Comment by jthegeman** [comment]
@Harween64 can you post the solution to a Github repo which would be easier.

Thanks!

**Comment by Harween64** [comment]
Hi @jthegeman,

First, I don't want to duplicate this repository. I share this, as a **temporary** solution. The ideal would be to update this repository, but there is a lot of work since there is many different Firebase bindings. 
Then, I'm not really accustomed with GitHub.
And finally as I say, I don't have time to maintain a public repository.

**Comment by padmasrisekar** [comment]
Could anyone please provide the details, which version of Xamarin forms and Xamarin.iOS supports for firebase crashlytics update.

**Comment by Kipotlov** [comment]
The release is now out with the new Firebase Craslytics SDK. 
But when can we expect to have a new nuget package (https://www.nuget.org/packages/Xamarin.Firebase.iOS.Crashlytics/) ?
Thank you!

**Comment by Harween64** [comment]
Ok, seems that nuget 4.6.2 is ,out now.
Thanks you to @dmariogatto and all the reviewers, mergers, publishers, etc....

**Comment by padmasrisekar** [comment]
> Ok, seems that nuget 4.6.2 is ,out now.
> Thanks you to @dmariogatto and all the reviewers, mergers, publishers, etc...

I'm using xamarin.ios13.2 and xcode 11.2 with latest firebase packages but im getting "native linking error". Any help or resolution would be great help!! Thanks in Advance.

**Comment by jthegeman** [comment]
I am getting a

**Comment by jthegeman** [comment]
/Users/joseph.hegeman/CustomerMobileApp/PublicStorageMobile.iOS/MTOUCH: Error MT1303: Could not decompress the native framework 'FirebaseInstallations.framework' from '/Users/{user}/{app}/{app-name}.iOS/obj/iPhoneSimulator/Debug/mtouch-cache/FirebaseInstallations.framework.zip'. Please review the build log for more information from the native 'unzip' command. (MT1303) (PublicStorageMobile.iOS)

 Process exited with code 2, command:
    /usr/bin/unzip System.String[]
    PrivateHeaders/:  mismatching "local" filename (FirebaseInstallations),
             continuing with "central" filename version
    file #2:  bad zipfile offset (local header sig):  73
    file #3:  bad zipfile offset (local header sig):  655
    Archive:  /Users/{user}/{app}/{app-name}.iOS/obj/iPhoneSimulator/Debug/mtouch-cache/FirebaseInstallations.framework.zip

**Comment by artem-metliakov** [comment]
Having the same error after updating the library:
Could not decompress the native framework 'FirebaseInstallations.framework' from '/Users/{user}/{app}/{app-name}.iOS/obj/iPhoneSimulator/Debug/mtouch-cache/FirebaseInstallations.framework.zip'. Please review the build log for more information from the native 'unzip' command. (MT1303)

**Comment by dmariogatto** [comment]
@jthegeman @artem-metliakov  Can you provide an example solution that fails to build?

**Comment by artem-metliakov** [comment]
@dmariogatto I tried to do that in a new solution and it works for me. But it still doesn't work for my project. I get this error even if I update Xamarin.Firebase.iOS.Analytics library. Seems that problem in my project.

**Comment by wojciech-kulik** [comment]
@artem-metliakov 
1. Try to remove all Firebase nugets and add required by your project again. 
2. Remove also nugets `Xamarin.Build.Download` (don't add them manually).
3. Remove bin and obj.
4. Update Visual Studio, Xamarin.Forms and Xamarin.iOS (if applicable).
5. If nothing helps you can also try to downgrade/upgrade to Xcode 12.0.1 (it works for me)

**Comment by jthegeman** [comment]
@wojciech-kulik I have narrowed it down to the  FirebaseInstallations.framework.zip. The zip file is corrupted from the nuget package. 
However when I updated the 

`Xamarin.Firebase.iOS.Analytics` -> 6.9.0
`Xamarin.Firebase.iOS.CloudMessaging` -> 4.7.1

The issue went away.

**Comment by artem-metliakov** [comment]
@wojciech-kulik Thank you, but it didn't work for me.
@jthegeman In my project I have these packages:
```
<PackageReference Include="Xamarin.Firebase.iOS.Analytics" Version="6.9.0" />
<PackageReference Include="Xamarin.Firebase.iOS.Crashlytics" Version="4.6.2" />
<PackageReference Include="Xamarin.Firebase.iOS.DynamicLinks" Version="4.3.1" />
```
and I can't build the project.

But the build passes when I add a reference to 
`<PackageReference Include="Xamarin.Firebase.iOS.CloudMessaging" Version="4.7.1" />`

**Comment by thumpshere** [comment]
Crashlytics.Configure();
it says Crashlytics does not contain any definition for configure().
Does anyone know what we can use instead of this?

**Comment by BradKwon** [comment]
Visual Studio for Mac v8.8.2
Xamarin.iOS v14.6.0.15
Xcode 12.2

I tried to update below packages from own bindings on my project and got many MT1303 decompress. 

```
-  <package id="Xamarin.Build.Download" version="0.4.11" targetFramework="xamarinios10" />
+  <package id="Xamarin.Build.Download" version="0.10.0" targetFramework="xamarinios10" />

  <package id="Xamarin.Firebase.iOS.ABTesting" version="4.2.0" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.Analytics" version="6.9.0" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.CloudMessaging" version="4.7.1" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.Core" version="6.10.4" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.Crashlytics" version="4.6.2" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.Installations" version="1.7.0" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.InstanceID" version="4.8.0" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.PerformanceMonitoring" version="3.3.0" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.RemoteConfig" version="4.9.1" targetFramework="xamarinios10" />
```

```
Error MT1303: Could not decompress the native framework 'GoogleToolboxForMac.framework'
Error MT1303: Could not decompress the native framework 'FirebaseRemoteConfig.framework'
Error MT1303: Could not decompress the native framework 'FirebaseInstallations.framework'
Error MT1303: Could not decompress the native framework 'FirebaseABTesting.framework'
```

I tried above workarounds but for me, all didn't work.

**Comment by SravanthiKare** [comment]
Same here too... After we upgrade the above packages, we got couple of native linking errors for analytics and Firebase Remote config. Any suggestions please.

**Errors**
Native linking failed, undefined Objective-C class: FIRRemoteConfig. The symbol '_OBJC_CLASS_$_FIRRemoteConfig' could not be found in any of the libraries or frameworks linked with your application. (MT5211) (Matchday.iOS)

Error MT5201: Native linking failed. Please review the build log and the user flags provided to gcc: "-L/Users/<>/Documents/Work/Football Association/Code/Matchday/MatchDay/packages/Realm.Database.3.2.0/build/../native/ios/universal" -lrealm-wrappers -lz -framework Security -L/Users/<>/Library/Caches/XamarinBuildDownload/GAnlytcs-3.17/Libraries -lGoogleAnalytics -force_load /Users/147414/Library/Caches/XamarinBuildDownload/GAnlytcs-3.17/Libraries/libGoogleAnalytics.a -ObjC -lz -lsqlite3 -ObjC -lsqlite3 -lz -ObjC -lz -ObjC -ObjC -lc++ -lsqlite3 -lz -ObjC -lc++ -ObjC -lc++ -lsqlite3 -lz -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker

**Comment by BradKwon** [comment]
> Visual Studio for Mac v8.8.2
> Xamarin.iOS v14.6.0.15
> Xcode 12.2
> 
> I tried to update below packages from own bindings on my project and got many MT1303 decompress errors.
> 
> ```
> -  <package id="Xamarin.Build.Download" version="0.4.11" targetFramework="xamarinios10" />
> +  <package id="Xamarin.Build.Download" version="0.10.0" targetFramework="xamarinios10" />
> 
>   <package id="Xamarin.Firebase.iOS.ABTesting" version="4.2.0" targetFramework="xamarinios10" />
>   <package id="Xamarin.Firebase.iOS.Analytics" version="6.9.0" targetFramework="xamarinios10" />
>   <package id="Xamarin.Firebase.iOS.CloudMessaging" version="4.7.1" targetFramework="xamarinios10" />
>   <package id="Xamarin.Firebase.iOS.Core" version="6.10.4" targetFramework="xamarinios10" />
>   <package id="Xamarin.Firebase.iOS.Crashlytics" version="4.6.2" targetFramework="xamarinios10" />
>   <package id="Xamarin.Firebase.iOS.Installations" version="1.7.0" targetFramework="xamarinios10" />
>   <package id="Xamarin.Firebase.iOS.InstanceID" version="4.8.0" targetFramework="xamarinios10" />
>   <package id="Xamarin.Firebase.iOS.PerformanceMonitoring" version="3.3.0" targetFramework="xamarinios10" />
>   <package id="Xamarin.Firebase.iOS.RemoteConfig" version="4.9.1" targetFramework="xamarinios10" />
> ```
> 
> ```
> Error MT1303: Could not decompress the native framework 'GoogleToolboxForMac.framework'
> Error MT1303: Could not decompress the native framework 'FirebaseRemoteConfig.framework'
> Error MT1303: Could not decompress the native framework 'FirebaseInstallations.framework'
> Error MT1303: Could not decompress the native framework 'FirebaseABTesting.framework'
> ```
> 
> I tried above workarounds but for me, all didn't work.

I was able to resolved by updating all Firebase related libraries. In my case, they were Google.SignIn, Google.MobileAds as well as all Firebase libraries. I updated those all in all projects in my solution and worked.
