### ISSUE TITLE
Could not AOT the assembly 

### ISSUE THREAD

**Issue by vcupelloni** [xamarin/GoogleApisForiOSComponents#44]
Adding Firebase.Analytcs, Firebase.InstanceID and Firebase.CloudMessaging from NuGet makes compilation crash with "Could not AOT the assembly '/Users/valeriocupelloni/Library/Caches/Xamarin/mtbs/builds/PlaceViewiOS/10e2454c320b774d349f7c7746b48657/obj/iPhone/Debug/build-ipad4.4-8.4/mtouch-cache/Build/Firebase.Analytics.dll"

[build_log.txt](https://github.com/xamarin/GoogleApisForiOSComponents/files/547948/build_log.txt)

**Comment by SotoiGhost** [comment]
Hi @vcupelloni.

We are aware of this bug, the way to workaround this is by unchecking `Enable incremental builds` in **Project Options** > **iOS Build**.

To know more about this issue, you can follow this [bug](https://bugzilla.xamarin.com/show_bug.cgi?id=43689) posted in Bugzilla.

**Comment by irvinrobles28** [comment]
@SotoiGhost pffff Gracias SOTO!!! también me paso cuando agregue mi proyecto de WatchOS con la librería "xamarin.watchos.dll" no sean manchados, no saquen bugs así :(, Saludos amigo.

**Comment by SotoiGhost** [comment]
@irvinrobles28 De nada Irvin! Estamos trabajando en los Alpha y Beta para ya evitar liberar bugs así en estable. Saludos amigo!
