### ISSUE TITLE
GoogleSignIn missing Info.plist - App Store rejection

### ISSUE THREAD

**Issue by austinf** [xamarin/GoogleApisForiOSComponents#45]
Using version 4.0.0 my app using GoogleSignIn was rejected with message:

This bundle is invalid - The Info.plist file for /Payload/Loki.iOS.app/GoogleAuthUtilities.framework is missing or could not be read.

Invalid Bundle - The bundle at '/Payload/Loki.iOS.app/GoogleAuthUtilities.framework' does not contain a bundle executable.

**Comment by austinf** [comment]
Same issue on previous 3.x version

**Comment by austinf** [comment]
New version of GoogleSignIn (4.0.1) no longer depends on GoogleAuthUtilities so I'm trying to update to test if my issue goes away. I'm having a hard time linking against my build though, having not done any native/xamarin library work before.

If anyone else more setup to do so could build a new version of the component to test, I can test it.

**Comment by SotoiGhost** [comment]
@austinf thanks for letting me know this. We were working on this and working on how to integrate the **.xib** file that comes in GoogleAuthUtilities, because is a not compiled interface so we needed to compile it before we add this to resources. I'll work in the update within the week.

**Comment by Rao27** [comment]
@austinf : Yesterday, I tried to upload the application to itunesconnect, but I got the same error about missing plist. When you say new version of GoogleSignIn(4.0.1) no longer depends on GoogleAuthUtilities, is it like you will not have error? and I tried to search 4.0.1 on nuget package manager but it shows only 4.0.0. How do I get the 4.0.1?

**Comment by austinf** [comment]
The GoogleSignIn SDK from google is at version 4.0.1, but that hasn't been integrated or released for xamarin yet. I also don't know if it will fix the app store rejection issue, but they did remove GoogleAuthUtilities which was mentioned in the rejection message.

**Comment by Rao27** [comment]
So are you still waiting for the release from xamarin to upload the application or do you have any alternative to bypass this problem and submit it to Appstore?

**Comment by austinf** [comment]
Still waiting. I tried to build it myself but I can't get the library to link with my app

**Comment by Rao27** [comment]
So, I tried new version 4.0.1 and I was successfully able to upload it to app store.

**Comment by goldnarms** [comment]
Facing some mtouch issues when building for release using version 4.0.1. Is there an ETA on when the updated package will be released?

**Comment by cnordvik** [comment]
@Rao27 Any chance you can share the 4.0.1 DLL?

**Comment by cnordvik** [comment]
@SotoiGhost This is blocking the AppStore release so any chance of an update here? Would be really appreciated!

**Comment by eduarduamaral** [comment]
@cnordvik I installed via NuGet version 3.0.0.1 and my app came back to be approvade by the apple team. I hope this helps you, sorry for my English.

**Comment by cnordvik** [comment]
@eduarduamaral Thanks, but for various reasons we must use 4.x so hopefully we can get the 4.0.1 update in NuGet as well...

**Comment by SotoiGhost** [comment]
We delayed this release because Google switched to open-source versions of some dependencies of Google Sign-In v4.0.1. Because of this, Sign-In stopped working with other Firebase components. We need to update Firebase.Analytics and release Firebase.Core first to make Sign-In compatible again. This is a high prioritize.

A very big apology for all the inconveniences that this cause.

**Comment by ksloginov** [comment]
@SotoiGhost 
Any rough estimate of how long you think it's gonna take you guys?  I.e. is a question of hours/days/weeks/ :-( ?

**Comment by ksloginov** [comment]
Any updates on this one?

**Comment by ianschmitz** [comment]
We just experienced the same App Store rejection when using Xamarin.Gogle.iOS.SignIn 4.0.0. Unable to publish our app until this is resolved. A rough timeline would be much appreciated!

**Comment by luyzfernando** [comment]
Good morning, I'm having the same problem.

We were going to release an update this weekend.

Any updates on this problem?

Thank you.

**Comment by SotoiGhost** [comment]
We have made a PR (#53) that solve this problem and now is on review, hope by the next week the new version of G.SignIn will be released.

**Comment by SotoiGhost** [comment]
[Google Sign-In for iOS v4.0.1.0](https://components.xamarin.com/view/googleiossignin?version=4.0.1.0) has been released. I'll close the issue but feel free to reopening if something happens.
