### ISSUE TITLE
App.Configure() conflicts with the default name of Xamarin.Forms initialization class.

### ISSUE THREAD

**Issue by GiusepeCasagrande** [xamarin/GoogleApisForiOSComponents#46]
Hello, 

I was trying to use  Firebase Cloud Messaging for iOS with a Xamarin.Forms project, but got stuck at the instructions (https://components.xamarin.com/gettingstarted/firebaseioscloudmessaging) when asked to call App.Configure (); inside my AppDelegate.
After a while I figured out that 
```
	// @interface FIRApp : NSObject
	[DisableDefaultCtor]
	[BaseType (typeof (NSObject), Name = "FIRApp")]
	interface App
```

was conflicting with my Forms 
 ```
   public partial class App : Application
    {
        public App()
        {
```

I suggest to change the Firebase App name back to his original name "FIRApp" and avoid conflicts with the Xamarin.Forms App class.

**Comment by SotoiGhost** [comment]
Leaving the name as `FIRApp` will not satisfy the [.NET class naming convention][1]. It states:

> DO NOT give class names a prefix (e.g., "C").

My suggestion is to use the full namespace of **App** class:

`Firebase.Analytics.App`

Or use [C# using alias][2]:

`using FirebaseApp = Firebase.Analytics.App`

Greetings,
Israel Soto.

[1]: https://msdn.microsoft.com/en-us/library/ms229040(v=vs.110).aspx
[2]: https://msdn.microsoft.com/en-us/library/sf0df423.aspx

**Comment by GiusepeCasagrande** [comment]
That's right, FIRApp was a bad suggestion.

I already renamed my Forms.App.cs to something else and solved my problem.
But it's not intuitive the way it is right now. Especially because Xamarin Studio won't suggest the namespace when trying to "fix..." and is hard to figure out that the configuration class is inside the analytics.

I have talked to more people who gave up on using this because got sucked in the same problem.

Thanks for taking the time to answer my question, appreciate it.

**Comment by softlion** [comment]
I suggest to change the doc on the website and add the full namespace in it

**Comment by ilanolkies** [comment]
Use `Firebas.Core.App`.

**Comment by usmani93** [comment]
When I write Firebase.Core.App.Configure() in app delegate's finishedlaunching method, my app crashes, everything is fine except when this line is executed, any help?

**Comment by usmani93** [comment]
I resolved it by not writing this line, and everything is fine,

**Comment by stewartcrainie** [comment]
Probably fixed now, but for anyone else. Make sure that you have included the 'GoogleService-Info.plist' as part of the 'Bundle Resource'. Right-click -> build action -> bundle resource.
