### ISSUE TITLE
Xamarin.Forms - Crashlytics  is not logging crashes [Crashlytics 4.6.2]

### ISSUE THREAD

**Issue by PaulsonMac** [xamarin/GoogleApisForiOSComponents#463]
Hi! I'm using Crashlytics v4.6.2 for my Xamarin.Forms app. Though the crash count is increasing but still no error message/stack trace is logged in the Firebase Console. I tried in release device build as well.

I get the following logs which makes me think that something else is interfering, but though I tried, I couldn't find what is interfering with Crashlytics (if I've perceived it correctly) :

```
[Crashlytics] The signal SIGABRT has a non-Crashlytics handler (sigabrt_signal_handler).  This will interfere with reporting.

[Crashlytics] The signal SIGBUS has a non-Crashlytics handler (mono_sigsegv_signal_handler).  This will interfere with reporting.

[Crashlytics] The signal SIGFPE has a non-Crashlytics handler (mono_sigfpe_signal_handler).  This will interfere with reporting.

[Crashlytics] The signal SIGILL has a non-Crashlytics handler (<redacted>).  This will interfere with reporting.

[Crashlytics] The signal SIGSEGV has a non-Crashlytics handler (mono_sigsegv_signal_handler).  This will interfere with reporting.

[Crashlytics] The signal SIGSYS has a non-Crashlytics handler (mono_crashing_signal_handler).  This will interfere with reporting.
[Crashlytics] The signal SIGTRAP has a non-Crashlytics handler ((null)).  This will interfere with reporting.
```

I even get symbols uploaded successfully in the logs during build process in Visual Studio.

**What I've tried**

Tried uninstalling App Center Analytics. [I'm not using App Center Crashlytics)

**Other Analytics SDKs I'm using**

Google Analytics
Firebase Analytics

**Comment by PaulsonMac** [comment]
I didn't have this problem before upgrade

Earlier Crashlytics version I was using : 3.14.0

**Comment by sebastiansondergaard** [comment]
I'm experiencing the same problem 😬

**Comment by PaulsonMac** [comment]
@sebastiansondergaard, was this issue fixed for you? I'm trying for a solution still..

**Comment by PaulsonMac** [comment]
Thank you JESUS..!! This issue is resolved.

Don't know why.. After uninstalling CarouselView.FormsPlugin package, the logs went off. Crashes are now reported properly

Maybe some error handling is being done in the CarouselView.FormsPlugin package.

**Comment by PaulsonMac** [comment]
While testing each crash, I only got this CarouselView.FormsPlugin named exception being reported in the Firebase console. In that way, I identified that this package is interfering with the Crashlytics reporting as displayed in the logs

**Comment by Kapusch** [comment]
Hi @PaulsonMac , nice to hear that removing a package has made it work !

However, I don't understand how were you able to see named exceptions in the Firebase Console.
In my case, I still have "missing DSYM files" displayed :/

Did you have this message ?

**Comment by PaulsonMac** [comment]
Hi @Kapusch! I too still have the "missing DSYM files" displayed. But, after everytime I crashed the app, when I checked the console I could see the crash count increasing in my case and the stack trace was always about the same CarouselView exception increasing in count in the **Crashlytics dashboard**.

**Comment by Kapusch** [comment]
Would that mean that even if we have DSYM files are missing, it is not relative to an actual crash ?

**Comment by PaulsonMac** [comment]
I think "No". Even the message says "Upload x missing dSYM required to process n crashes". 

In my case, after I crashed the app, when I checked in the dSYMs tab, there was no new entry in the "Missing dSYMs" section of the dSYMs tab. In this scenario, obviously DSYM files are not related to the actual crash

**Comment by PaulsonMac** [comment]
I have a question : There is not even a single crash logged in your Crashlytics dashboard ?

**Comment by Kapusch** [comment]
From time to time yes, I can see a problem is reported in the Crashlytics dashboard, however, I still have several missing dSYM files; even for my last release :/

**Comment by acuntex** [comment]
@PaulsonMac We also get no crash reports even though we use the current version.
