### ISSUE TITLE
Update to Firebase Crashlytics iOS SDK 4.0.0

### ISSUE THREAD

**Issue by Freezor** [xamarin/GoogleApisForiOSComponents#468]
Any news when Xamarin.Firebase.iOS.Crashlytics will be updated to the Firebase Crashlytics iOS SDK 4.0.0?

We currently use
<PackageReference Include="Xamarin.Firebase.iOS.Crashlytics" Version="4.6.2" />
and the Firebase console will not process any of our crashes.

Thanks in advance

**Comment by tentom** [comment]
Its already out there! 🥳 

https://www.nuget.org/packages/Xamarin.Firebase.iOS.Crashlytics/ 

I'm currently using Version 4.6.2

I had some issues setting it up. But the gist of it was: 

1. Get the GoogleServices-Info.plist file and add it to the iOS project. 
2. Make sure the build action for the file is "BundleResource"
3. Install Xamarin.Firebase.iOS.Crashlytics.
4. Add something similar to this to your FinishedLaunching() function in the AppDelegate.cs file: 
``` C#
var foo = typeof(Analytics) // I have no Idea why this removes some compilation errors 
Firebase.Core.App.Configure(); // not sure if this is needed
// you might also need:
var crashlytics = Crashlytics.SharedInstance;
crashlutics.SendUnsentReports();

``` 
5 . Clean, remove obj, bin folder, restart VS ( Do not know if this is necessary YMMW)
6. Crash the app and see if something is reported, might take some time, I found that the Event and Realtime tabs under Analytics updated faster than the Crashlytics tab under release & monitor.

Hope this helps you. 

PS.  Also look at #443 #436 
PPS you might also need the analytics package firebase/firebase-ios-sdk#3798

**Comment by polianshpatinaaisllc** [comment]
@tentom 
When using var crashlytics = Crashlytics.SharedInstance; 
When I start the app crashlytics instance is null.

**Comment by Freezor** [comment]
@tentom  yes. that this somehow work. Thanks
