### ISSUE TITLE
Google MobileAds / Bad BaseType for the SearchRequest interface

### ISSUE THREAD

**Issue by scordonnier** [xamarin/GoogleApisForiOSComponents#5]
The issue and the solution are described here :

https://forums.xamarin.com/discussion/61831/google-mobile-ads-ios-unable-to-load-searchrequest#latest

**Comment by SotoiGhost** [comment]
Hi @scordonnier.

Thanks for leaving a sample code and the solution too in Xamarin Forums, I'll review the code and, if everything looks ok, I'll apply the solution.

**Comment by SotoiGhost** [comment]
Waiting for approval of Pull request #7 to fix this issue.

**Comment by SotoiGhost** [comment]
Pull request #7 accepted, fix will be available on G.MobileAds v7.7.1.1
