### ISSUE TITLE
Could not decompress the native framework 'GoogleToolboxForMac.framework'

### ISSUE THREAD

**Issue by nromero125** [xamarin/GoogleApisForiOSComponents#503]
I can't get running an app in iOS with Xamarin. I don't know how to get it running, it shows the same error in every phone or simulator. The only thing I know is that is related to firebase. Do someone knows how to solve it?

 Process exited with code 2, command:
    /usr/bin/unzip -u -o -d /Users/nelsonromero/Projects/applab/V2/Universal/Universal.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/GoogleToolboxForMac.framework /Users/nelsonromero/Projects/applab/V2/Universal/Universal.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/GoogleToolboxForMac.framework.zip
    Headers/GTMTypeCasting.h:  mismatching "local" filename (Headers/GTMNSData+zlib.h),
             continuing with "central" filename version
    file #3:  bad zipfile offset (local header sig):  1131
    file #4:  bad zipfile offset (local header sig):  2939
    file #5:  bad zipfile offset (local header sig):  3923
    file #6:  bad zipfile offset (local header sig):  5219
    file #7:  bad zipfile offset (local header sig):  5623
    file #8:  bad zipfile offset (local header sig):  6500
    file #9:  bad zipfile offset (local header sig):  13307
    file #10:  bad zipfile offset (local header sig):  14868
    file #11:  bad zipfile offset (local header sig):  15883
    file #12:  bad zipfile offset (local header sig):  16966
    file #13:  bad zipfile offset (local header sig):  21248
    file #14:  bad zipfile offset (local header sig):  23049
    file #15:  bad zipfile offset (local header sig):  24409
    file #16:  bad zipfile offset (local header sig):  24475
    file #17:  bad zipfile offset (local header sig):  24649
    Archive:  /Users/nelsonromero/Projects/applab/V2/Universal/Universal.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/GoogleToolboxForMac.framework.zip
      inflating: /Users/nelsonromero/Projects/applab/V2/Universal/Universal.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/GoogleToolboxForMac.framework/Headers/GTMTypeCasting.h  
    
    MTOUCH : error MT1303: Could not decompress the native framework 'GoogleToolboxForMac.framework' from '/Users/nelsonromero/Projects/applab/V2/Universal/Universal.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/GoogleToolboxForMac.framework.zip'. Please review the build log for more information from the native 'unzip' command.

**Comment by angelru** [comment]
@nromero125 
Try changing the build path to see if it works for you:
https://developercommunity.visualstudio.com/t/Error-when-trying-to-debug-an-applicatio/1570145

**Comment by nromero125** [comment]
Was an error with the linker and some mtouch arguments.
