### ISSUE TITLE
Can we add Google Map iOS SDK Utility library to map component.

### ISSUE THREAD

**Issue by jessejiang0214** [xamarin/GoogleApisForiOSComponents#51]
Hi Team,

We met some problems with creating a binding library for 'Google-Maps-iOS-Utils’
https://developers.google.com/maps/documentation/ios-sdk/utility/

 Can we put Google-Maps-iOS-Utils library into Google Maps for iOS component? 

I have tried to build the binding library, but failed.
I have tried to use Sharpie with Cocoapod command but failed, cause Google-Maps-iOS-Utils cannot be installed by Cocoapod install command.

Then I have tried in the old way, built the project and using Sharpie to general ApiDefinition file. The Sharpie cannot build that file successful, one error is in GMUMarkerClustering.h , it cannot include other head file, cause it using < not “. Finally, I use a part of Sharpie generated code and other code convert by myself, it can be built. After I included that project to my solution, it get "The native class hasn't been loading” error.

Finally, I still cannot work out with binding that library. Other thing is it include the GoogleMap.h in that library, even though I can link the Google-Maps-iOS-Utils library successfully. How can I pass the MapView as parameter to function in that library. Cause that parameter isn’t Object-C class, it has C# wrapper, so that I guess the code in that function cannot use the MapView Object.

So, What I request is can we put Google-Maps-iOS-Utils library into Google Maps for iOS component? https://components.xamarin.com/view/googleiosmaps, It’s better to do with Android also.

Thanks

**Comment by declandowling** [comment]
I would really like to see this, as I want to use the clustering functionality. I have managed to achieve clustering [on Android using this library](https://github.com/sushihangover/XamarinGoogleMapClustering), but I cannot find an equivalent for iOS.

I have also attempted to implement a bindings library (first attempt), but have been unsuccessful so far.

**Comment by jessejiang0214** [comment]
@declandowling Yes, I did the same thing, but failed. I hope some Xamarin Developer can help us.

**Comment by jessejiang0214** [comment]
@declandowling I found a repo https://github.com/NateRickard/Google-Maps-Utils-Binding , 
after I spent 2 days to convert Object-C source code to C# codes T^T
