### ISSUE TITLE
App freezes on Firebase.Core.App.Configure()

### ISSUE THREAD

**Issue by onetreba** [xamarin/GoogleApisForiOSComponents#511]
XCode Version: 13.2
Xamarin.iOS Version: 15.2.0.17
Xamarin.Firebase.iOS.Analytics version: 6.9.0

After importing Xamarin.Firebase.iOS.Analytics package and adding GoogleService-Info.plist as BundleResource I'm calling Firebase.Core.App.Configure(), but application freezes on this line. In stack trace I see next lines:
```
ApiDefinition.Messaging.void_objc_msgSend()
Firebase.Core.App.Configure()
```

No crashes, nothing found in logs. Tried to call it on both main and BG threads and result is the same.

I tried to do the same in an empty test project and everything works fine, but I can't find any major differences in project settings.

**Comment by ReRodriguez** [comment]
Hi @onetreba, Did you solve this issue ?

**Comment by onetreba** [comment]
Unfortunately, no.

**Comment by onetreba** [comment]
The problem appeared because of conflict with old AdMob library. Solved.
