### ISSUE TITLE
Upgrade Firebase Analytics to 3.4.4 due to crashes

### ISSUE THREAD

**Issue by cnordvik** [xamarin/GoogleApisForiOSComponents#52]
v3.4.2 has a serious crash bug so we need an update to 3.4.4. Can this be done? 
https://groups.google.com/forum/#!topic/firebase-talk/W-gPv4tmXpw

**Comment by SotoiGhost** [comment]
@cnordvik Firebase Analytics version 3.5.1 has been released, please verify that everything is working now. I'll close the issue but feel free to reopening if something happens.
