### ISSUE TITLE
Firebase.CloudMessaging.RemoteMessage - no longer found

### ISSUE THREAD

**Issue by pcaruthers** [xamarin/GoogleApisForiOSComponents#528]
I'm restarting a project that has not been updated in quite some time.  It uses RemoteMessage, which used to be public in Firebase.CloudMessaging but is not there any more.

Has it move to another package that i should be including or do i need to update the code to use something else?  If i can, is there any doc. on migrating?

**Comment by dmariogatto** [comment]
`RemoteMessage` was deprecated for a while & officially removed in Firebase 7.0.0 (https://github.com/firebase/firebase-ios-sdk/pull/6430 & [release notes](https://firebase.google.com/support/release-notes/ios#fcm_10)).

I couldn't find any migration documentation, but it'd probably be best to look at the most current [setup guide](https://firebase.google.com/docs/cloud-messaging/ios/client).

**Comment by pcaruthers** [comment]
In fact, looking at the sample CloudMessaging AppDelegate code is **very** helpful.
That shows that the few lines of code in AppDelegate which used RemoteMessage are no longer needed.  

"migrating" for me amounted to deleting 1 line and a method that used RemoteMessage, update all the packages and recompile.  It seems to be working with that little change.
