### ISSUE TITLE
Azure Pipeline Fail with 8.10 version

### ISSUE THREAD

**Issue by GabrielOcampoLastra** [xamarin/GoogleApisForiOSComponents#547]
Hi,

we uses 8.10 nuget version but the azure devops pipeline fail with this error:

```
(_CompileToNative target) -> 
  MTOUCH : error MT2101: Can't resolve the reference 'System.IntPtr CoreFoundation.CFString::CreateNative(System.String)', referenced from the method 'System.Void Firebase.CloudMessaging.Messaging::DeleteFcmToken(System.String,Firebase.CloudMessaging.MessagingDeleteFcmTokenCompletionHandler)' in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'.
```

Is there any specific configuration or workaround for this?

**Comment by sweekar7** [comment]
Hi @GabrielOcampoLastra [GabrielOcampoLastra](https://github.com/GabrielOcampoLastra) we are also facing a similar issue in our app, can you help us with info on how you were able to resolve this?
