### ISSUE TITLE
Firebase Crash Reporting on iOS

### ISSUE THREAD

**Issue by veryhumble** [xamarin/GoogleApisForiOSComponents#56]
Would be nice to have bindings for the crash reporting feature of Firebase. Seems that Xamarin.Android has support [https://github.com/xamarin/GooglePlayServicesComponents/tree/master/firebase-crash](firebase-crash).

Is it feasible to create such a nuget package for iOS?

**Comment by SotoiGhost** [comment]
@veryhumble I'm working on it right now, the binding is finished but I'm finishing with some last sh files. Hope by this week the component is released.

**Comment by veryhumble** [comment]
Any news on this?

**Comment by SotoiGhost** [comment]
We needed to delay the release and change the structure of the component to avoid some legal stuff. We are still working on this.

**Comment by luigisaggese** [comment]
@SotoiGhost pay attention also on DSYM upload

**Comment by sureshValle** [comment]
Any updates for Firebase Crash Reporting for iOS?

**Comment by sureshValle** [comment]
is it works for iOS10 iMessage extension too?

**Comment by luigisaggese** [comment]
Any news?

**Comment by mgj** [comment]
News? :P

**Comment by luzimar** [comment]
Any update ??

**Comment by SotoiGhost** [comment]
Hi all, after of some time arguing and working on Firebase Crash Reporting for iOS, finally, the component has passed to Review status again. 

This component will be compatible just with Xamarin Studio and Visual Studio for Mac due Firebase scripts contains commands that only work on Mac. If everything goes ok, FCR will be released by next weeks.

Best to all!

**Comment by luigisaggese** [comment]
When i try to add package or component i have this issue:

Executing nuget actions took 479.96 ms
Directory '/Users/luigi.saggese/Library/Caches/XamarinBuildDownload/FCrshR-1.1.4' not found.

**Comment by mgyarmathy** [comment]
reporting the same issue as @luigisaggese.

Executing nuget actions took 290.21 ms
Directory '/Users/mgyarmathy/Library/Caches/XamarinBuildDownload/FCrshR-1.1.4' not found.

The install works just fine on Windows VS 2015. Having install troubles on Mac Xamarin Studio.

**Comment by mgyarmathy** [comment]
Similar error when opening the sample project in Xamarin Studio:

![image](https://cloud.githubusercontent.com/assets/2754894/24638699/458b155e-18b0-11e7-963d-e1e6d36e39fd.png)

**Comment by mgyarmathy** [comment]
Temp workaround on OSX:

1. Download tarball referenced in Firebase.CrashReporting.targets: https://dl.google.com/dl/cpdc/3802e848f39facac/FirebaseCrash-1.1.4.tar.gz
2. Unzip, and move the directory and its contents to ~/Library/Caches/XamarinBuildDownload/FCrshR-1.1.4/

**Comment by yeoupooh** [comment]
Same issue on the v1.1.5.1 with error ".../FCrshR-1.1.6 not found".
Temp workaround on OSX is just creating that folder '~/Library/Caches/XamarinBuildDownload/FCrshR-1.1.6/' and re-install the package.

**Comment by kimdv** [comment]
I think this can be closed, because Firebase will use Crashlytics.

**Comment by SotoiGhost** [comment]
As @kimdv said, Firebase will use Crashlytics instead of Crash Reporting. This is closed now.
