### ISSUE TITLE
NET 7.0 support missing

### ISSUE THREAD

**Issue by iancona** [xamarin/GoogleApisForiOSComponents#608]
Cannot install it from nuget on NET 7.0 MAUI.

Missing support?

**Comment by aritchie** [comment]
Works fine for me.  These native libraries won't work well/at all with hot restart or windows only compiling.  

NET6 libraries almost always work on NET7 without any change

**Comment by iancona** [comment]
I've tested the installation of the library from nuget on Windows and it's not working. I will try the same from mac os and update this issue.

**Comment by iancona** [comment]
Installation completes on mac OS
