### ISSUE TITLE
Google Analytics: Native linking failed

### ISSUE THREAD

**Issue by bezineb5** [xamarin/GoogleApisForiOSComponents#62]
Hello,
Since I updated Xamarin.iOS, I get linking errors when compiling my project with the Google Analytics for iOS component:

```
	MTOUCH: error MT5214: Native linking failed, undefined symbol: _kGAIViewportSize. This symbol was referenced by the managed member Google.Analytics.GaiConstants.ViewportSize. Please verify that all the necessary frameworks have been referenced and native libraries linked.
	MTOUCH: error MT5214: Native linking failed, undefined symbol: _kGAIUseSecure. This symbol was referenced by the managed member Google.Analytics.GaiConstants.UseSecure. Please verify that all the necessary frameworks have been referenced and native libraries linked.
	MTOUCH: error MT5214: Native linking failed, undefined symbol: _kGAIUserId. This symbol was referenced by the managed member Google.Analytics.GaiConstants.UserId. Please verify that all the necessary frameworks have been referenced and native libraries linked.
```
(and many more)

My version of Xamarin.iOS is:
Version: 10.4.0.73 (Xamarin Studio Community)
Hash: a7f1dc3
Branch: master
Build date: 2017-01-08 14:16:01-0500

Any idea?
Thanks!
Benjamin

**Comment by N-Nightingale** [comment]
I have this issue also. Has anyone found a fix or workaround?

**Comment by bezineb5** [comment]
The latest version seems to have fixed the issue:
Xamarin Studio Community
Version 6.2 (build 1778)
Installation UUID: a6600c45-6a5a-41c2-9c6b-d8e12d27d4d0
Runtime:
	Mono 4.8.0 (mono-4.8.0-branch/6f90ed1) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 408000472

NuGet
Version: 3.5.0.0

Xamarin.Profiler
'/Applications/Xamarin Profiler.app' not found

Apple Developer Tools
Xcode 8.2.1 (11766.1)
Build 8C1002

Xamarin.iOS
Version: 10.4.0.96 (Xamarin Studio Community)
Hash: 4e31137
Branch: cycle9
Build date: 2017-01-20 13:08:53-0500

I'm closing it as it's not longer reproducible.
