### ISSUE TITLE
Blazor Hybrid - .Net 8 - iOS - Bitcode_strip: missing argument(s) to: -o option

### ISSUE THREAD

**Issue by omxie** [xamarin/GoogleApisForiOSComponents#634]
Hello there, 

### Description
I'm facing an issue trying to run my application using either of the Debug/Release build onto a physical iPad connected to my mac. This specifically happens on the dotnet 8 rc2 version. While dotnet 7 does not seem to have this issue and the application runs fine on dotnet 7. 
Any help regarding this issue would be appreciated. Thanks!

**The error I get is:** 
`
Error /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip: missing argument(s) to: -o option C:\Users\user_name\.nuget\packages\xamarin.firebase.ios.core\8.10.0.3\buildTransitive\Xamarin.Firebase.iOS.Core.targets 216	
Error MSB3073 The command ""$(xcrun -find bitcode_strip)"  -r -o " exited with code 1. C:\Users\user_name\.nuget\packages\xamarin.firebase.ios.core\8.10.0.3\buildTransitive\Xamarin.Firebase.iOS.Core.targets 216	
`

**The output window shows this:**
`
2>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.8968-net8-rc2\targets\Xamarin.Shared.Sdk.targets(744,3): warning MT7091: The framework C:/Users/user_name/.nuget/packages/xamarin.firebase.ios.core/8.10.0.3/lib/net6.0-ios15.4/Firebase.Core.resources/GoogleUtilitiesComponents.xcframework/ios-arm64/GoogleUtilitiesComponents.framework is a framework of static libraries, and will not be copied to the app.
2>"$(xcrun -find bitcode_strip)"  -r -o
2>C:\Users\user_name\.nuget\packages\xamarin.firebase.ios.core\8.10.0.3\buildTransitive\Xamarin.Firebase.iOS.Core.targets(216,5): error : /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip: missing argument(s) to: -o option
2>Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip input [-r | -m | -l] [-keep_cs] -o output
2>C:\Users\user_name\.nuget\packages\xamarin.firebase.ios.core\8.10.0.3\buildTransitive\Xamarin.Firebase.iOS.Core.targets(216,5): error MSB3073: The command ""$(xcrun -find bitcode_strip)"  -r -o " exited with code 1.
`

### Steps to Reproduce
1) Install VS Version 17.8.0 Preview 5.0
2) install Plugin.Firebase.CloudMessaging Version 2.0.3
3) Run the project (possibly on a physical device as I'm doing the same) and check the build output for error.

### Version with bug
Microsoft Visual Studio Enterprise 2022 (64-bit) - Version 17.8.0 Preview 5.0
DotNet Version - 8.0.100 - rc2
Plugin.Firebase.CloudMessaging Version - 2.0.3 

### Last version that worked well
DotNet Version - 7.0.402
Plugin.Firebase.CloudMessaging Version - 2.0.3

### Affected platforms
iOS

### Affected platform versions
IOS 16.6

### Did you find any workaround?

I tried [this work around](https://github.com/dotnet/maui/issues/10989#issuecomment-1304317816) and it did not work.

**Comment by bangaras** [comment]
Facing same issue. I am trying to archive my .Net MAUI Blazor Application on mac but it failing and giving this on my output window. 

The framework /Users/user245535/.nuget/packages/xamarin.firebase.ios.core/8.10.0.3/lib/net6.0-ios15.4/Firebase.Core.resources/GoogleUtilitiesComponents.xcframework/ios-arm64_x86_64-simulator/GoogleUtilitiesComponents.framework is a framework of static libraries, and will not be copied to the app.

How I get this steps:
1. Open your maui blazor project on mac
2. Set as release mode
3. select device as Generic device
4. Right click on your project and select 'Archive for publishing'
5. It will fail and will show this error on output window. 

If anyone fixed this issue. Please mention.

**Comment by omxie** [comment]
This sample repo by user @coop-tim helped me solve my issue:

https://github.com/coop-tim/maui-sample
