### ISSUE TITLE
DirectoryNotFoundException" with Xamarin.Firebase.iOS.Crashlytics 8.10.0.3 on net7.0-ios Compilation

### ISSUE THREAD

**Issue by takla21** [xamarin/GoogleApisForiOSComponents#636]
# Description

After updating to the latest version of Xamarin.Firebase.iOS.Crashlytics **8.10.0.3**, I encountered a compilation error when trying to build my `net7.0-ios` project. The error message is as follows:

```
4>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7054\targets\Xamarin.Shared.Sdk.targets(2014,3): error : MessagingRemoteException: An error occurred on client Build1647054 while executing a reply for topic xvs/build/16.4.7054/execute-task/{my_project_name}/dd14bb8002fGetFileSystemEntries
4>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7054\targets\Xamarin.Shared.Sdk.targets(2014,3): error : DirectoryNotFoundException: Could not find a part of the path '/Users/{mac_user_name}/Library/Caches/Xamarin/mtbs/builds/{my_project_name}/dd14bb858842a171263b2924953ce8f3babb2e93c6ab9c353b8ccd723dc14284/C:/n/xamarin.firebase.ios.core/8.10.0.3/lib/net6.0-ios15.4/Firebase.Core.resources'.
4>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7054\targets\Xamarin.Shared.Sdk.targets(2014,3): error :
```

This issue might be related to #555 , although I experienced it before encountering this new error message. I have attempted the following solutions without success:
- Setting the 'NUGET_PACKAGES' environment variable with the shortest path possible (e.g., C:/n).
- Enabling the registry key `LongPathsEnabled` and restarting my computer multiple times.

# Additional Information
On my Xamarin project, I'm currently using **8.10.0** and I did not encounter this issue. However, it's important to note that this specific version is only supported on Xamarin.

**Comment by takla21** [comment]
I don't know if it can help, but I tried to go to the mtbs folder on my Mac and it seems that the `xamarin.firebase.ios.core` folder is indeed missing

![image](https://github.com/xamarin/GoogleApisForiOSComponents/assets/17461593/dfe05c1a-a389-483d-8e4a-4a1b8bba67a8)

Comparing to my main windows machine
![image](https://github.com/xamarin/GoogleApisForiOSComponents/assets/17461593/300b49e7-0e86-47de-811d-1cffe9eb621b)

**Comment by Soap-141** [comment]
On my side, trying the same thing, I'm getting the following.

1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7107\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error : C:/Users/thomas.labrecque/AppData/Local/XamarinBuildDownloadCache/GAppM-8.9.1/GoogleAppMeasurement-8.9.1/Frameworks/GoogleAppMeasurement.xcframework has an incorrect or unknown format and cannot be processed.

1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7107\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error :

1>Done building project "CAAMobileApp.Mobile.csproj" -- FAILED.

**Comment by takla21** [comment]
So apparently I had to update my visual studio from 17.6.1 to 17.7.7 which brought me the same problem as @Soap-141 which can be workaround with this solution https://github.com/xamarin/xamarin-macios/issues/19173#issuecomment-1765906924
