### ISSUE TITLE
TagManager 5.x: How can I specify the container ID to use?

### ISSUE THREAD

**Issue by gboudreau** [xamarin/GoogleApisForiOSComponents#64]
I have two containers my app can use: one for PROD, and one for DEV/Sandbox.
In TagManager 3.15.x, I was able to choose the container ID to use with:

    ContainerOpener.OpenContainer (tagManagerContainerId, [...])

But I can't find how to specify the Container ID with TagManager 5.x.

Thanks.

**Comment by SotoiGhost** [comment]
@gboudreau 

Seems that Tag Manager version 5.x doesn't have support for multiple containers. I tried to add two containers to container folder but the app just load one, furthermore, Tag Manager docs don't specify any reference of this.
