### ISSUE TITLE
Can't setup Firebase analytics for iOS to report Install Referrer

### ISSUE THREAD

**Issue by epopov** [xamarin/GoogleApisForiOSComponents#65]
I setup Firebase analytics in my iOS Xamarin project and it reports events, but it does not report correct Install source - always says - direct, but I am sure it should be reporting "google" as a source. Also, AdWords tracking is not seeing conversions via Firebase. What am I missing?

**Comment by SotoiGhost** [comment]
@epopov Why are you sure that it should report "google"? Also, if you can provide a test case, it would be great.

Greetings,
Israel Soto.

**Comment by epopov** [comment]
Does Firebase attribute installs from any campaign or only AdWords campaigns? For instance, if I have an app link on my website and I tagged it with campaign info? Here are links on my website:
iOS: https://itunes.apple.com/app/apple-store/id1021031770?aid=com.hostmeapp.hostmepanel&cs=website-footer&cm=website&cn=website
Android: https://play.google.com/store/apps/details?id=com.hostmeapp.hostmepanel&utm_source=website-promo&utm_medium=website&utm_campaign=website

**Comment by epopov** [comment]
Also, I see that I got many installs from Apple Search ads campaign. And Firebase analytics says nothing about this campaign.

**Comment by JSalazar88** [comment]
We are also trying to track AdWords conversions via Firebase in Xamarin.iOS app. Any update on this?

**Comment by JSalazar88** [comment]
Does this component allow ad-click ==> app-install conversion tracking to work properly???

**Comment by SotoiGhost** [comment]
Is this still an issue?

**Comment by SotoiGhost** [comment]
We have not received the requested information. If you are still experiencing this issue please provide all the requested information and re-open the issue report. Thanks!
