### ISSUE TITLE
Build failure on Adding TagManager(5.0.8) Nuget pack

### ISSUE THREAD

**Issue by tutugeorge** [xamarin/GoogleApisForiOSComponents#66]
When the TagManager package(5.0.8) is added to project via nuget gallery, I am getting build error with the message Error: Error executing task DetectSdkLocations: The type initializer for 'Xamarin.MacDev.AppleSdkSettings' threw an exception.

Whereas when i added Tag Manager(5.0.8) using the Components store , there is no build issues.

**Comment by SotoiGhost** [comment]
@tutugeorge Are you still getting this issue? Also, in which IDE does the error appear?

**Comment by SotoiGhost** [comment]
We have not received the requested information. If you are still experiencing this issue please provide all the requested information and feel free to re-open this issue again. Thanks!

**Comment by tutugeorge** [comment]
Hi Israel Soto,

We are not experiencing this issue now. Thank you for helping us out.

Regards,
Tutu George
