### ISSUE TITLE
I have no events on EVENTS tab in Firebase

### ISSUE THREAD

**Issue by Distro2000** [xamarin/GoogleApisForiOSComponents#68]
1. Project in Xamarin has been created
2. Application in Firebase has been created
3. GoogleService-Info.plist has been added to the project (with BundleContent property)
4. In AppDelegate.cs - App.Configure() has been added
5. In code - Analytics.LogEvent has been added 

Application is launched on iPhone 7 emulator, working properly, I can use app normally but when I navigate to Firebase Dashboard > Events there are no event. What is wrong? BundleId is same in Info.plist and Firebase configuration

**Comment by SotoiGhost** [comment]
Is Firebase still not recording the events from your app?

**Comment by SotoiGhost** [comment]
We have not received the requested information. If you are still experiencing this issue please provide all the requested information and re-open the issue report. Thanks!
