### ISSUE TITLE
Getting a strange value from Firebase.CloudMessaging

### ISSUE THREAD

**Issue by escamoteur** [xamarin/GoogleApisForiOSComponents#70]
Hi,

I'm able to receive Firebase messages which is really great! While exploring the reveived dictionary I get this a bit strange values when printing them like this:

```C#
        private void AppDelegate_NotificationReceived(object sender, UserInfoEventArgs e)
        {
            foreach (KeyValuePair<NSObject, NSObject> valuePair in e.UserInfo)
            {
                Debug.WriteLine("Key: " + valuePair.Key + " - Value: " + valuePair.Value);
            }
        }
```

In the output I get this here

```
[0:] Key: type - Value: dota2
[0:] Key: message - Value: replaydone
[0:] Key: aps - Value: {
    alert =     {
        body = "Your game replay video for dota2 is ready.";
        title = "Replay Video Ready";
    };
}
```

The first two are fine but I don't understand the last one. it almost looks like JSON but it is not. How do I have to deal with it? On Android I receive all values without problems

Thanks
Thomas

**Comment by SotoiGhost** [comment]
@escamoteur Don't think is like a JSON, IIRC, notifications are JSON that can be handled with `KeyValuePair<NSObject, NSObject>` or with `NSDictionary`, but one thing you should know about the **aps** content is that **alert** value is **string** if you just set the **body** value and is `KeyValuePair<NSObject, NSObject>` or `NSDictionary` if you set **body** and **title** values.

Here's an example of how you can handle the **aps** value:

```csharp
void AppDelegate_NotificationReceived (object sender, UserInfoEventArgs e)
{
        // ...
	var apsDictionary = e.UserInfo ["aps"] as NSDictionary;

        string body;
        string title;
	if (apsDictionary ["alert"] is NSDictionary) {
		var alertDictionary = apsDictionary ["alert"] as NSDictionary;

		if (alertDictionary.ContainsKey (new NSString ("title")))
			title = alertDictionary ["title"].ToString ();

		body = alertDictionary ["body"].ToString ();
	} else {
		body = apsDictionary ["alert"].ToString ();
	}

        // ...
}
```

Hope this helps you!

Greetings!
Israel Soto.

**Comment by escamoteur** [comment]
Thanks a lot, will give it a try
