### ISSUE TITLE
PolyLine has no methods to add coordinates for drawing line between two points.

### ISSUE THREAD

**Issue by gsssubramanyam** [xamarin/GoogleApisForiOSComponents#73]
I wanted to draw line between multiple points. Path class is given in framework but it has no methods to add location points. Please advice how to achieve this functionality. I did not see any documentation of Xamarin component, though native ios google maps has documentation all the classes are not exposed in .NET component.

**Comment by SotoiGhost** [comment]
Can you specify which classes, properties or methods are missing in Google Maps? Thanks in advance.

**Comment by SotoiGhost** [comment]
We have not received the requested information. If you are still experiencing this issue please provide all the requested information and re-open the issue report. Thanks!
