### ISSUE TITLE
Could not AOT the assembly '/Users/.../mtouch-cache/Build/Google.Maps.dll'	GoogleMapsSample.iOS

### ISSUE THREAD

**Issue by MTUNNISSEN** [xamarin/GoogleApisForiOSComponents#74]
#Hi,

If i build my xamarin forms app, with a pagerenderer as mapview loader, i get the following error.
`Could not AOT the assembly '/Users/.../mtouch-cache/Build/Google.Maps.dll'`
If i uncheck `Enable incremental builds `
in **Project Options > iOS Build.** as stated in [https://github.com/xamarin/GoogleApisForiOSComponents/issues/44](https://github.com/xamarin/GoogleApisForiOSComponents/issues/44)
I get the "native linking error" on all components in the google.maps.dll.

I am using version Xamarin.Google.iOS.Maps.2.1.0.1.

If i run the sample added with the download of the component it does run.

I loaded my view in the way explained by "geraldVerluis" mentions in the following discussion: https://forums.xamarin.com/discussion/58327/using-google-maps-for-ios-on-xamarin-forms

**Comment by SotoiGhost** [comment]
This was fixed some releases ago, are you still facing this issue?

**Comment by SotoiGhost** [comment]
We have not received the requested information. If you are still experiencing this issue please provide all the requested information and re-open the issue report. Thanks!
