### ISSUE TITLE
DidReceiveNotificationResponse function is not working in ios 10

### ISSUE THREAD

**Issue by Benknightdark** [xamarin/GoogleApisForiOSComponents#75]
HI, DidReceiveNotificationResponse function is not working in ios 10 . How to solve this bug? Thanks

**Comment by SotoiGhost** [comment]
Hi! Sorry for the very late response…

We have updated the documentation of Firebase Cloud Messaging, the workaround provided is no longer for iOS 10 and above. Here's the new way to [handle messages](https://github.com/xamarin/GoogleApisForiOSComponents/blob/master/Firebase.CloudMessaging/component/GettingStarted.md#receive-messages) in your app.
