### ISSUE TITLE
didreceiveremotenotifcation not being called in background

### ISSUE THREAD

**Issue by karlcod531** [xamarin/GoogleApisForiOSComponents#78]
I am testing the firebase cloud messaging for iOS functionality, and I noticed that when my app is in the background and a notification comes in, didreceiveremotenotification is not getting called. 
I have already added remote-notifications capability to the background mode on the app, and I am sending  the notification with "content-available" : 1 in the notification dictionary. 

Is this a known issue?

**Comment by SotoiGhost** [comment]
Hi! Sorry for the very late response…

We have updated the documentation of Firebase Cloud Messaging, the workaround provided is no longer needed for iOS 10 and above. Here's the new way to [handle messages](https://github.com/xamarin/GoogleApisForiOSComponents/blob/master/Firebase.CloudMessaging/component/GettingStarted.md#configure-cloud-messaging-in-your-app) in your app.

Best,
Israel Soto.
