### ISSUE TITLE
The name 'App' does not exist in the current context

### ISSUE THREAD

**Issue by anirusu** [xamarin/GoogleApisForiOSComponents#79]
I'm having trouble building the sample project or the freshly created projects, when adding the line `App.Configure()` in `FinishedLaunching`. Is there an additional step (from the "getting started" steps) that I'm missing?

**Comment by vbisbest** [comment]
The docs are incorrect.  You need to use:
Firebase.Analytics.App.Configure();

**Comment by FernandoMrq** [comment]
In my, firebase.analytics.app.configure() i give error, app nota found in analytics

**Comment by SotoiGhost** [comment]
`App.Configure` method was moved from `Firebase.Analytics` namespace to Firebase.Core namespace in the mayor release from v3.x to v4.x. Please, import Firebase.Core to your libraries to use this method.

**Comment by techview51** [comment]
Add **Firebase.FirebaseApp** to the scope of the app. For example:

`

        Firebase.FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task => {
            var dependencyStatus = task.Result;
            if (dependencyStatus == Firebase.DependencyStatus.Available)
            {
                Firebase.FirebaseApp // I mean here
                // Create and hold a reference to your FirebaseApp,
                // where app is a Firebase.FirebaseApp property of your application class.
                app = Firebase.FirebaseApp.DefaultInstance;

                // Set a flag here to indicate whether Firebase is ready to use by your app.
            }
            else
            {
                UnityEngine.Debug.LogError(System.String.Format(
                  "Could not resolve all Firebase dependencies: {0}", dependencyStatus));
                // Firebase Unity SDK is not safe to use here.
            }
        });
`
