### ISSUE TITLE
Places API: Address type is missing data/properties provided by the API

### ISSUE THREAD

**Issue by hardcodet** [xamarin/GoogleApisForiOSComponents#80]
If you compare the mappings for the Address type here:
https://github.com/xamarin/GoogleApisForiOSComponents/blob/d515cb4e75b89c6a0f7a0fd7710369fd32e12deb/Google.Maps/source/Google.Maps/ApiDefinition.cs#L102

to the Android definition here:
https://developer.android.com/reference/android/location/Address.html

You can see that you don't provide an 1:1 mapping. For example, I'm really missing the _FeatureName_, which would be what I want to present to the user rather than an obscure address when resolving some coordinates:

> getFeatureName
> Returns the feature name of the address, for example, "Golden Gate Bridge", or null if it is unknown.

I assume completing the Address type is a question of a simple mapping since the API will send you the data in question. Would be nice to see that added to the codebase 👍

**Comment by SotoiGhost** [comment]
The Google Maps binding provided in this repository is based on Google Maps for iOS. The [Address][1] class of iOS SDK doesn't contain any method or property named `featureName`. If you think this is a missing feature, you can report it [here][2]

[1]: https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_address
[2]: https://issuetracker.google.com/issues/new?component=188833&template=787421
