### ISSUE TITLE
Ads are not delivered on iPhone 7 (Domain=com.google.ads Code=1 "Request Error: No ad to show.")

### ISSUE THREAD

**Issue by supreettare** [xamarin/GoogleApisForiOSComponents#82]
Hi, 
For some strange reason the Admob ads do not show up only on iPhone 7 & 7 plus using iOS 10.2 the error we get is 

Domain=com.google.ads Code=1 "Request Error: No ad to show."

We have posted this question on SO 

[https://stackoverflow.com/questions/44309438/google-admob-is-not-working-in-xamarin-form-ios-for-larger-screen-devices-like-i?noredirect=1#](url)

& also on Google Groups 

[https://groups.google.com/forum/#!topic/google-admob-ads-sdk/AXqjfNDFm2Q](https://groups.google.com/forum/#!topic/google-admob-ads-sdk/AXqjfNDFm2Q)

but no support from them as Xamarin is not officially supported. 
Can someone please shade some light on what could be wrong? We have been strugglisng to solve this for over 2 weeks now & our app is pending publish just because of this issue. 

We followed James Monetomago's blog to implement Admob in iOS using Xamarin Forms. 
[http://motzcod.es/post/154696375922/xamarinforms-google-admob-ads-in-ios](url)

Any help on this is really appreciated. 

Thanks 
ST

**Comment by SotoiGhost** [comment]
@supreettare are you still having this issue?

**Comment by SotoiGhost** [comment]
We have not received the requested information. If you are still experiencing this issue please provide all the requested information and re-open the issue report. Thanks!
