### ISSUE TITLE
Google Maps Version Update

### ISSUE THREAD

**Issue by muhaym** [xamarin/GoogleApisForiOSComponents#83]
The current binding is for version seems to be 2.1.0 of Google maps.

The latest Google Maps Version is 2.3.0 with lots of deprecations and updates. Will Xamarin team update the bindings soon? The last updates were 3 months before.

Thanks

**Comment by campersau** [comment]
FYI: I updated the google maps bindings to 2.4.0 here https://github.com/xamarin/GoogleApisForiOSComponents/compare/master...campersau:vnext and removed the places APIs but I haven't added any new maps APIs.

**Comment by rayita** [comment]
Any  time estimation?

**Comment by SotoiGhost** [comment]
@rayita Hope by the next week this is released. This update includes the new Google.Places component, so, it takes more time in the review process.
