### ISSUE TITLE
Firebase phone auth

### ISSUE THREAD

**Issue by kimdv** [xamarin/GoogleApisForiOSComponents#84]
Hello, 

Is there any plans to support the Firebase Phone Auth?

https://firebase.google.com/docs/auth/ios/phone-auth

**Comment by SebastianRask** [comment]
I am needing this too. Hopefully it can be implemented before Digits closes.

**Comment by dsb92** [comment]
This is a request from me too, please make it happen soon, before Digits closes.

**Comment by jlovatt121** [comment]
I am hoping that this gets implemented soon as most of the users in my app will no longer be able to log in once Digits becomes deprecated and moves to Firebase.

**Comment by sorotto04** [comment]
I need this. Thank you.

**Comment by Arief-AB** [comment]
I need this. Thank you

**Comment by vissuzya** [comment]
This is an urgent issue for us too.  Is there an update on this?   Please let us know.

**Comment by ugurpelister** [comment]
+1

**Comment by kimdv** [comment]
Can this be closed @SotoiGhost ?

**Comment by SotoiGhost** [comment]
Firebase Auth with Phone Auth support was released some time ago. I'm closing this issue.
