### ISSUE TITLE
DFP native ads doesn't trigger callback

### ISSUE THREAD

**Issue by luigisaggese** [xamarin/GoogleApisForiOSComponents#85]
I'm using Google.MobileAds nuget package 7.16.0, but i have some issue to use NativeContentAd and 
NativeAppInstallAd. Sometimes when i make a request of native ads no methods are triggered of those:

- DidFailToReceiveAd
- DidReceiveNativeContentAd
- DidReceiveNativeAppInstallAd

This is my example code (inside ViewDidLoad):
...
LoadNativeAd("/23154429/AdxNative/app_native_1_serp", this));
...
```

public void LoadNativeAd(string adUnit, AdvertListView rootViewController)
        {

                List<AdLoaderOptions> adLoaderOptions = new List<AdLoaderOptions>();
                adLoaderOptions.Add(new NativeAdViewAdOptions() { PreferredAdChoicesPosition = AdChoicesPosition.TopRightCorner });

                var adsLoader = new AdLoader(adUnit, rootViewController, new NSObject[] { AdLoaderType.NativeContent, AdLoaderType.NativeAppInstall }, adLoaderOptions.ToArray());
                adsLoader.Delegate = rootViewController;
                var requestSim = Google.MobileAds.DoubleClick.Request.GetDefaultRequest();
                requestSim.CustomTargeting = NSDictionary.FromObjectAndKey(
                    (NSString)JR.BL.Core.Settings.CurrentCountry, (NSString)"country");
                var simul = new System.Collections.Generic.List<string>();
                simul.Add("622801a654b4700c0f23d16a55862ab0");
                simul.Add("kGADSimulatorID");
                requestSim.TestDevices = simul.ToArray();
                adsLoader.LoadRequest(requestSim);

        }

public void DidReceiveNativeContentAd(AdLoader adLoader, NativeContentAd nativeContentAd)
        {
           
               Utils.NativeAds.Add(adLoader.AdUnitID, nativeContentAd);
               TableView.ReloadData();

        }

        public void DidFailToReceiveAd(AdLoader adLoader, RequestError error)
        {
        
               Console.WriteLine("AdLoader: " + adLoader.AdUnitID + " | error:" + error.UserInfo.ToString());
          
        }

        public void DidReceiveNativeAppInstallAd(AdLoader adLoader, NativeAppInstallAd nativeAppInstallAd)
        {
            
                Utils.NativeAds.Add(adLoader.AdUnitID, nativeAppInstallAd);
                TableView.ReloadData();
        }
```

We are in touch with google support and this is their answer:

> For iOS specifically, an issue was observed with the callback events not being triggered when an ad is returned, so it's very likely that is causing the relatively lower render rate. I've suggested to Luigi on your team that this issue be reported to the Xamarin team, which provides the SDK wrapper being used by your apps, as we weren't able to replicate the issue with the Google SDK and don't directly control or support the Xamarin product.

**Comment by luigisaggese** [comment]
Any news?

**Comment by asndev** [comment]
*bump*
Any updates on this? We've multiple customers affected by this issue.

**Comment by SotoiGhost** [comment]
Is this still an issue? If yes, can you provide a test case? That will make things faster.

**Comment by SotoiGhost** [comment]
We have not received the requested information. If you are still experiencing this issue please provide all the requested information and re-open the issue report. Thanks!
