### ISSUE TITLE
error MT5209 : Native linking error : file not found: /obj/iPhoneSimulator/Debug/mtouch-cache/GoogleMaps

### ISSUE THREAD

**Issue by jstawski** [xamarin/GoogleApisForiOSComponents#87]
Version 2.1.0.1 throws that error while building. I've added the package through Nuget. Doing so through the Component Store results in the same error.

I'm using Visual Studio for Mac and building with MSBUILD

**Comment by jstawski** [comment]
Here's more info:
 

> MTOUCH : warning MT1302: Could not extract the native library 'GoogleMaps' from '/Path/obj/iPhoneSimulator/Debug/device-builds/iphone9.1-10.3.1/mtouch-cache/GoogleMaps'. Please ensure the native library was properly embedded in the managed assembly (if the assembly was built using a binding project, the native library must be included in the project, and its Build Action must be 'ObjcBindingNativeLibrary').
>     MTOUCH : warning MT1302: Could not extract the native library 'GoogleMapsCore' from '/Path/obj/iPhoneSimulator/Debug/device-builds/iphone9.1-10.3.1/mtouch-cache/GoogleMapsCore'. Please ensure the native library was properly embedded in the managed assembly (if the assembly was built using a binding project, the native library must be included in the project, and its Build Action must be 'ObjcBindingNativeLibrary').
>     MTOUCH : warning MT1302: Could not extract the native library 'GoogleMapsBase' from '/Path/obj/iPhoneSimulator/Debug/device-builds/iphone9.1-10.3.1/mtouch-cache/GoogleMapsBase'. Please ensure the native library was properly embedded in the managed assembly (if the assembly was built using a binding project, the native library must be included in the project, and its Build Action must be 'ObjcBindingNativeLibrary').
>     MTOUCH : warning MT1302: Could not extract the native library 'GooglePlaces' from '/Path/obj/iPhoneSimulator/Debug/device-builds/iphone9.1-10.3.1/mtouch-cache/GooglePlaces'. Please ensure the native library was properly embedded in the managed assembly (if the assembly was built using a binding project, the native library must be included in the project, and its Build Action must be 'ObjcBindingNativeLibrary').
>     MTOUCH : warning MT1302: Could not extract the native library 'GooglePlacePicker' from '/Path/obj/iPhoneSimulator/Debug/device-builds/iphone9.1-10.3.1/mtouch-cache/GooglePlacePicker'. Please ensure the native library was properly embedded in the managed assembly (if the assembly was built using a binding project, the native library must be included in the project, and its Build Action must be 'ObjcBindingNativeLibrary').
>     MTOUCH : warning MT1302: Could not extract the native library 'libGoogleAnalytics.a' from '/Path/obj/iPhoneSimulator/Debug/device-builds/iphone9.1-10.3.1/mtouch-cache/libGoogleAnalytics.a'. Please ensure the native library was properly embedded in the managed assembly (if the assembly was built using a binding project, the native library must be included in the project, and its Build Action must be 'ObjcBindingNativeLibrary').
>     MTOUCH : warning MT0127: Incremental builds have been disabled because this version of Xamarin.iOS does not support incremental builds in projects that include more than one third-party binding libraries.
>     Process exited with code 1, command:
>     ld: file not found: /Path/obj/iPhoneSimulator/Debug/device-builds/iphone9.1-10.3.1/mtouch-cache/GoogleMaps
>     clang : error : linker command failed with exit code 1 (use -v to see invocation)

I looked at /Path/obj/iPhoneSimulator/Debug/device-builds/iphone9.1-10.3.1/mtouch-cache/ and there is no files with those names. The packages folder doesn't have those files either.

**Comment by SotoiGhost** [comment]
@jstawski Try these steps:

1. Close the solution
2. Erase erase bin and obj folders of your app project
3. Open the solution and try again

**Comment by jstawski** [comment]
@SotoiGhost it didn't work

**Comment by cevaris** [comment]
thanks @SotoiGhost 
Those steps seemed to have resolved linker error.

**Comment by cevaris** [comment]
@SotoiGhost actually, it is working only in the simulator. Not when deployed to a device.

**Comment by SotoiGhost** [comment]
Is someone still facing this issue?

**Comment by SotoiGhost** [comment]
We have not received the requested information. If you are still experiencing this issue please provide all the requested information and re-open the issue report. Thanks!

**Comment by mpsarannyaCharu** [comment]
Hi 

I am getting the below error once i have added the freshChat dll on my xamarin.ios project. 

Error: linker command failed with exit code 1 (use -v to see invocation) (FreshChatiOS.iOS)

 Error MT5216: Native linking failed for '/Users/sarannya/Projects/FreshChatiOS/iOS/obj/iPhone/Debug/device-builds/iphone9.2-12.0/mtouch-cache/armv7/libHeltChatLib.dll.dylib'. Please file a bug report at http://bugzilla.xamarin.com (MT5216) (FreshChatiOS.iOS)
