### ISSUE TITLE
First Sign in Blank White Page for a long time

### ISSUE THREAD

**Issue by gcwei** [xamarin/GoogleApisForiOSComponents#88]
After SignIn.SharedInstance.SignInUser(), the app goes to a blank white page for a long time and nothing happens. Am I missing something or is it a bug? 

public override void ViewDidLoad()
	{
             SignIn.SharedInstance.UIDelegate = this;
	     SignIn.SharedInstance.Delegate = this;
             SignIn.SharedInstance.SignInUser();
       }

**Comment by SotoiGhost** [comment]
Are you still facing this issue? If yes, can you provide a test case, please? That would make things faster.

**Comment by SotoiGhost** [comment]
We have not received the requested information. If you are still experiencing this issue please provide all the requested information and re-open the issue report. Thanks!
