### ISSUE TITLE
Impossible to connect when APNs Authentication Key is used

### ISSUE THREAD

**Issue by ugurpelister** [xamarin/GoogleApisForiOSComponents#89]
I decided to switch to APNs Authentication Key instead of the old APNs certificate for my iOS app. I uploaded my key in Firebase console Cloud Messaging settings page. Then I downloaded the up-to-date `GoogleService-Info.plist` and added it to my project.

the result was that whenever my code calls `Messaging.SharedInstance.Connect()` I always get "_The operation couldn’t be completed. (com.google.fcm error 501.)_" error message in the callback. And application output window logs this message:

> FIRMessaging registration is not ready with auth credentials

Even if I repetitiously call `Messaging.SharedInstance.Connect`, the error remains.

**Comment by lassana** [comment]
@ugurpelister have you managed to find what was causing problem?

**Comment by ugurpelister** [comment]
sorry I forgot to close the thread. I renewed my provisioning profile and it's working now with APNs Authentication Key.
