### ISSUE TITLE
Cannot send user proprieties

### ISSUE THREAD

**Issue by carlasampaio01** [xamarin/GoogleApisForiOSComponents#93]
I am trying to use Firebase Analytics to iOS and I cant find a way to make it work. It doesnt send any proprity at all.

**Comment by SotoiGhost** [comment]
Are you still facing this issue?

**Comment by SotoiGhost** [comment]
We have not received the requested information. If you are still experiencing this issue please provide all the requested information and re-open the issue report. Thanks!
