### ISSUE TITLE
keychainError

### ISSUE THREAD

**Issue by argiebacomo** [xamarin/GoogleApisForiOSComponents#95]
auth.defaultinstance.signIn always returns keychainError how do i resolve this?

**Comment by SotoiGhost** [comment]
Are you still facing this issue? If yes, can you provide a test case, please? That would make things faster.

**Comment by argiebacomo** [comment]
i solved it using try catch

**Comment by SotoiGhost** [comment]
Cool! I'm closing this issue now. Feel free to re-open this issue if something else happens related to this.
