### ISSUE TITLE
ApplicationReceivedRemoteMessage never called on iOS 11

### ISSUE THREAD

**Issue by ugurpelister** [xamarin/GoogleApisForiOSComponents#96]
Since the latest release of the FCM iOS package v2.0.0.0, data messages are not received by iOS 11 devices. There are some API changes in v2.0.0.0 that are not reflected in the guideline [here](https://components.xamarin.com/gettingstarted/firebaseioscloudmessaging), but with or without implementing the API changes, the delegate method ApplicationReceivedRemoteMessage is never called.

the issue can be reproduced both on a physical device and on iOS simulator.

**Comment by rdelrosario** [comment]
Could you send you appdelegate.cs? to check how is your current config

**Comment by ugurpelister** [comment]
Hi Rendy,
The actual file is fairly big therefore I just cut out the lines related to FCM. you may see the attached file. I made all the FCM-related changes in the guidance of compiler warnings and errors.

[AppDelegate.txt](https://github.com/xamarin/GoogleApisForiOSComponents/files/1360736/AppDelegate.txt)

**Comment by ugurpelister** [comment]
@rdelrosario I have a new finding: the bug is specifically related to IMessagingDelegate interface, because the problem disappears when I inherit from MessagingDelegate class. since we cannot derive from two classes in C#, I moved cloud messaging logic from my AppDelegate class to a new one.

I guess the bug is a bit more isolated now.

**Comment by rdelrosario** [comment]
I think the main issue is documentation seems to be outdated, a few things changed on version 2.0.0.0. What I did on my implementation was based on the swift samples I saw and google offical docs becase the docs ob the component are outdated.

**Comment by rrispoli** [comment]
@ugurpelister can you please paste here your implementation that was working? I just updated to 2.0.0.0 in a production project, implemented the new DidRefreshRegistrationToken method and made the changes on deprecated warnings, but I can't test on iOS 11 for now, so I don't know if it's 100% working... maybe I should wait for a updated documentation?

**Comment by ugurpelister** [comment]
@rrispoli Actually my source code is really bloated with business logic and it would be cumbersome to tear down things to extract code, but I can explain how to switch to my implementation. really simple: just derive from MessagingDelegate class instead of IMessagingDelegate interface.

and you should inevitably move data message handling logic out from your AppDelegate class to a new one because it can't have two (UIApplicationDelegate and MessagingDelegate) base classes.

**Comment by rrispoli** [comment]
Hi @ugurpelister, thanks! I will check a way to do this.

**Comment by rrispoli** [comment]
I discovered that in version 2.0.0 on iOS 11 we need to implement:

[Export("messaging:didReceiveMessage:")] public void DidReceiveMessage(Messaging messaging, RemoteMessage remoteMessage) { }

**Comment by ashishkumar070** [comment]
Did anyone found a solution for this ?

**Comment by SotoiGhost** [comment]
Hi! Sorry for the very late response…

We have updated the documentation of Firebase Cloud Messaging, the workaround provided is no longer needed for iOS 10 and above. Here's the new way to [handle messages](https://github.com/xamarin/GoogleApisForiOSComponents/blob/master/Firebase.CloudMessaging/component/GettingStarted.md#configure-cloud-messaging-in-your-app) in your app.

Best,
Israel Soto.

**Comment by raquelhortab** [comment]
> Hi! Sorry for the very late response…
> 
> We have updated the documentation of Firebase Cloud Messaging, the workaround provided is no longer needed for iOS 10 and above. Here's the new way to [handle messages](https://github.com/xamarin/GoogleApisForiOSComponents/blob/master/Firebase.CloudMessaging/component/GettingStarted.md#configure-cloud-messaging-in-your-app) in your app.
> 
> Best,
> Israel Soto.

The link seems to be dead.. I am trying to configure push notifications to go through AWS-SNS -> Firebase FCM -> APNs but cannot get it to work. I receive notifications if I send them from the Firebase console but I don't receive them when I sned them using SNS
